Structural deformable models: src/browser.cpp File Reference
browser.cpp File Reference
#include <fx.h>
#include <fx3d.h>
#include <fxkeys.h>
#include <string>
#include <iostream>
#include <sstream>
#include <time.h>
#include "fxconfig.h"
#include <list>
#include "Image.h"
#include "Data.h"
#include "SpeciesDB.h"
#include "Clusterer.h"
#include "SensorSet.h"
Classes
class ImageWindow
Macros
#define SATURATION
Functions
FXDEFMAP (ImageWindow) ImageWindowMap[]
bool setTitle (const char *title)
bool setStatusText (const char *stext)
int main (int argc, char *argv[])
Variables
const FXchar * patterns []
Macro Definition Documentation
#define SATURATION
Function Documentation
FXDEFMAP (ImageWindow)
int main (int argc, char * argv[])
Definition at line 680 of file browser.cpp.
References ImageWindow::cmdline(), and ImageWindow::ImageWindow().
{
   // Make application
   FXApp application("Deformable Model Segmentation","FoxText");
   // Start app
   application.init(argc,argv);
   // Make window
   ImageWindow *iw = new ImageWindow(&application);
   iw->cmdline(argc,argv);
   // Create the application's windows
   application.create();
   // Run the application
   return application.run();
   }
bool setStatusText (const char * stext)
Definition at line 164 of file browser.cpp.
References ImageWindow::setStatusText().
Referenced by ImageWindow::ImageWindow(), Brain::loadSpecies(), and Brain::triggerTest().
{
     return false;
     ImageWindow *mw = dynamic_cast<ImageWindow*>
         (FXApp::instance()->getMainWindow());
     if(mw) {
         mw->setStatusText(stext);
         return true;
     } else return false;
 }
bool setTitle (const char * title)
Definition at line 154 of file browser.cpp.
Referenced by ImageWindow::changeSpecies(), and Brain::loadSpecies().
{
     return false;
     ImageWindow *mw = dynamic_cast<ImageWindow*>
         (FXApp::instance()->getMainWindow());
     if(mw) {
         mw->setTitle(title);
         return true;
     } else return false;
 }
Variable Documentation
const FXchar* patterns[]
Initial value:
={
  "Databases",   "*.dat",
  "All Files",   "*",
  NULL
  }
Definition at line 26 of file browser.cpp.
Referenced by ImageWindow::onLoadImage().