Structural deformable models: MahalSensor Class Reference
MahalSensor Class Reference
#include <SensorSet.h>
Public Member Functions
MahalSensor (const std::string &fname="")
int getNChannels () const
Sensor & assign (const Sensor &rhs)
std::ostream & print (std::ostream &os) const
bool loadConfig (const std::string &fname="")
bool saveConfig (const std::string &fname="") const
void setCovi (const DMatrix< float > &icov)
void setMean (const DMatrix< float > &mean)
const DMatrix< float > & getICov () const
const DMatrix< float > & getMean () const
const std::string & getFilename () const
Public Member Functions inherited from PPSensor
PPSensor ()
virtual float getValue (int x, int y) const
virtual Point getGradient (int x, int y) const
virtual bool performUpdate ()
void togglePP (enum PPState state=PP_DO)
dword getPPState () const
Public Member Functions inherited from Sensor
virtual ~Sensor ()
sensor_cptr getSource ()
virtual void changeSource (sensor_cptr _source)
void replaceBy (sensor_ptr target)
bool assignRef (sensor_cptr rhs)
float getValue (const Point &p) const
get value at position p using nearest neighbour interpolation
virtual std::vector< float > getMValue (int x, int y) const
get multi-channel value
Point2D getGradient (const Point2D &p) const
get gradient at position p using nearest neighbor interpolation
float getMax () const
float getMin () const
float getMinMaxRange () const
float getWeightedValue (int x, int y) const
get max normalized value at discrete position range [0,1]
Point2D getWeightedGradient (int x, int y) const
get range weighted gradient at discrete position
void setCWeights (const std::vector< float > &weights)
const std::vector< float > & getCWeights () const
void setDirection (const Point &dir)
const Point & getDirection () const
void setScale (float _scale)
float getScale () const
bool isModified (dword mask=UPD_ALL) const
void setModified (dword mask=UPD_ALL)
void unsetModified (dword mask=UPD_ALL)
bool isUpdate (dword udMask) const
void enableUpdate (dword udMask)
void disableUpdate (dword udMask)
virtual int getDim1Size () const
virtual int getDim2Size () const
virtual int getDim3Size () const
virtual int getSkip () const
bool isValid (int x, int y) const
virtual Image< float > createSensorImage () const
const std::string & getID () const
void setID (const std::string &id)
virtual std::ostream & hprint (std::ostream &os, SensorCollection *sc) const
void refSuperSensor (sensor_ptr super)
void unrefSuperSensor (sensor_ptr super)
void invalidateSource ()
template<typename Derived >
std::shared_ptr< Derived > shared_from_base ()
Protected Member Functions
float calcValue (int x, int y) const
Computes saturation or some other colour indicator.
Protected Member Functions inherited from PPSensor
void fitSheets ()
virtual void calcAllValues ()
virtual void calcAllGradients ()
Protected Member Functions inherited from Sensor
Sensor (dword updateMask)
Sensor ()
virtual std::vector< float > calcMValue (int x, int y) const
virtual Point calcGradient (int x, int y) const
virtual void calcMinMax ()
Protected Attributes
DMatrix< float > m
DMatrix< float > icov
std::string m_Filename
Protected Attributes inherited from PPSensor
Image< float > values
caching sheet for sensed values
Image< Point > gradients
caching sheet for gradients
dword doPP
do preprocessing?
Protected Attributes inherited from Sensor
sensor_cptr source
float scale
std::vector< float > cweights
multi-channel weights ('color')
Point dir
direction parameter
float maxval
float minval
overall minimum and maximum
float mean
float stdev
overall mean and stdev
dword toupdate
bitflag for updates
dword updateMask
bitflag to mask unimportant updates
std::string m_ID
int m_Skip
int m_AddSkip
Additional Inherited Members
Public Types inherited from PPSensor
enum PPState { PP_DONT =0, PP_DO, PP_FORCE }
Public Types inherited from Sensor
enum UpdateParam {
UPD_NOTHING =0, UPD_DATA =1, UPD_SCALE =2, UPD_CWEIGHTS =4,
UPD_DIR =8, UPD_MINMAX =16, UPD_LAST =32, UPD_ALL =0xffffffff
}
Static Public Member Functions inherited from Sensor
static dword getStringNumber (const char *sid)
static void getNumberString (char sid[5], dword id)
Detailed Description
Mahalanobis distance Sensor
Definition at line 324 of file SensorSet.h.
Constructor & Destructor Documentation
MahalSensor::MahalSensor (const std::string & fname = "") inline
Definition at line 326 of file SensorSet.h.
References Sensor::m_AddSkip.
         {
             m_AddSkip = 1;
             loadConfig(fname);
         }
Member Function Documentation
Sensor & MahalSensor::assign (const Sensor & rhs) virtual
Reimplemented from PPSensor.
Definition at line 236 of file SensorSet.cpp.
References PPSensor::assign(), icov, m, and m_Filename.
 {
     if(&rhs != this) {
         PPSensor::assign(rhs);
         if(typeid(&rhs) == typeid(MahalSensor*)) {
             const MahalSensor& crhs = (const MahalSensor&) rhs;
             m = crhs.m;
             icov = crhs.icov;
             m_Filename = crhs.m_Filename;
         }
     }
     return *this;
 }
float MahalSensor::calcValue (int x, int y) const inline protected virtual
Computes saturation or some other colour indicator.
Implements Sensor.
Definition at line 347 of file SensorSet.h.
References DMatrix< T >::at(), DMatrix< T >::mulRight(), Sensor::source, and DMatrix< T >::transpose().
{
         std::vector<float> mv = source->getMValue(x,y);
         DMatrix<float> v(1,std::min(mv.size(),size_t(3)),&mv.front());
         v -= m;
         DMatrix<float> vt(v); vt.transpose();
         float d = (vt.mulRight(icov.mulRight(v))).at(0,0);
         return exp(-0.5*d);
     }
const std::string& MahalSensor::getFilename () const inline
Definition at line 344 of file SensorSet.h.
 { return m_Filename; }
const DMatrix<float>& MahalSensor::getICov () const inline
Definition at line 342 of file SensorSet.h.
 { return icov; }
const DMatrix<float>& MahalSensor::getMean () const inline
Definition at line 343 of file SensorSet.h.
 { return m; }
int MahalSensor::getNChannels () const inline virtual
Reimplemented from Sensor.
Definition at line 331 of file SensorSet.h.
References Sensor::assign().
 { return 1; }
bool MahalSensor::loadConfig (const std::string & fname = "")
Definition at line 250 of file SensorSet.cpp.
 {
     const string& fn = fname.empty() ? m_Filename : fname;
     ifstream is(fn.c_str());
     if(!is) return false;
     is >> icov;
     is >> m;
     if(icov.sizeX() != 3 || icov.sizeY() != 3) {
         icov = dmutil::makeIdentity<float>(3);
     }
     if(m.sizeX() != 1 || m.sizeY() != 3) {
         m.resize(1,3,0);
     }
     if(!fname.empty()) m_Filename = fname;
     return true;
 }
std::ostream& MahalSensor::print (std::ostream & os) const inline virtual
Reimplemented from Sensor.
Definition at line 333 of file SensorSet.h.
References Sensor::print().
{
         Sensor::print(os)
             << "C " << m_Filename;
         return os;
     }
bool MahalSensor::saveConfig (const std::string & fname = "") const
Definition at line 267 of file SensorSet.cpp.
References Sensor::mean, and MappingSensor::s_MappingNames.
 {
     const string& fn = fname.empty() ? m_Filename : fname;
     ofstream os(fn.c_str());
     if(!os) return false;
     os << icov;
     os << mean;
     if(!fname.empty()) m_Filename = fname;
     return true;
 }
void MahalSensor::setCovi (const DMatrix< float > & icov) inline
Definition at line 340 of file SensorSet.h.
 { this->icov = icov; }
void MahalSensor::setMean (const DMatrix< float > & mean) inline
Definition at line 341 of file SensorSet.h.
References Sensor::mean.
 { this->m = mean; }
Member Data Documentation
DMatrix<float> MahalSensor::icov protected
Definition at line 355 of file SensorSet.h.
Referenced by assign().
DMatrix<float> MahalSensor::m protected
Definition at line 355 of file SensorSet.h.
Referenced by assign().
std::string MahalSensor::m_Filename mutable protected
Definition at line 356 of file SensorSet.h.
Referenced by assign().
The documentation for this class was generated from the following files:
src/SensorSet.h
src/SensorSet.cpp