Structural deformable models: Dataset Class Reference
Dataset Class Reference
#include <Data.h>
Public Member Functions
Dataset ()
Dataset (const char *filename)
~Dataset ()
bool load (const char *filename, dword ppmm=0)
Dataset & copyData (const Dataset &rhs)
void draw (float x=0, float y=0, float sx=1.0f, float sy=1.0f) const
int getDim1Size () const
int getDim2Size () const
int getDim3Size () const
int getNChannels () const
std::ostream & print (std::ostream &os) const
void clear ()
bool initialized () const
operator bool () const
const ByteImage & getImage () const
ByteImage & getImage ()
const ByteImage & getImage (int index) const
ByteImage & getImage (int index)
dword getPPMM () const
void setPPMM (dword ppmm)
const Point2D & getOrigin () const
const Point2D & getOSize () const
const std::string & getFilename () const
PropVec getPropVec () const
PropVec getPropVecMM () const
void setHalveBeyondSize (dword hbs=0xffffffff)
dword getHalveBeyondSize () const
void addNoise (float sigma)
Public Member Functions inherited from Sensor
virtual ~Sensor ()
sensor_cptr getSource ()
virtual void changeSource (sensor_cptr _source)
void replaceBy (sensor_ptr target)
bool assignRef (sensor_cptr rhs)
virtual Sensor & assign (const Sensor &rhs)
virtual float getValue (int x, int y) const
get value at discrete position
float getValue (const Point &p) const
get value at position p using nearest neighbour interpolation
virtual std::vector< float > getMValue (int x, int y) const
get multi-channel value
virtual Point2D getGradient (int x, int y) const
get gradient at discrete position
Point2D getGradient (const Point2D &p) const
get gradient at position p using nearest neighbor interpolation
float getMax () const
float getMin () const
float getMinMaxRange () const
float getWeightedValue (int x, int y) const
get max normalized value at discrete position range [0,1]
Point2D getWeightedGradient (int x, int y) const
get range weighted gradient at discrete position
void setCWeights (const std::vector< float > &weights)
const std::vector< float > & getCWeights () const
void setDirection (const Point &dir)
const Point & getDirection () const
void setScale (float _scale)
float getScale () const
bool isModified (dword mask=UPD_ALL) const
void setModified (dword mask=UPD_ALL)
void unsetModified (dword mask=UPD_ALL)
bool isUpdate (dword udMask) const
void enableUpdate (dword udMask)
void disableUpdate (dword udMask)
virtual bool performUpdate ()
virtual int getSkip () const
bool isValid (int x, int y) const
virtual Image< float > createSensorImage () const
const std::string & getID () const
void setID (const std::string &id)
virtual std::ostream & hprint (std::ostream &os, SensorCollection *sc) const
void refSuperSensor (sensor_ptr super)
void unrefSuperSensor (sensor_ptr super)
void invalidateSource ()
template<typename Derived >
std::shared_ptr< Derived > shared_from_base ()
Static Public Member Functions
static bool loadImage (std::vector< Image< byte > > &image, const char *filename)
static void drawImage (const std::vector< Image< byte > > &image, float x=0, float y=0, float sx=1.0f, float sy=1.0f)
static void drawImage (const Image< byte > &image, float x=0, float y=0, float sx=1.0f, float sy=1.0f)
Static Public Member Functions inherited from Sensor
static dword getStringNumber (const char *sid)
static void getNumberString (char sid[5], dword id)
Public Attributes
vuMutex writeMutex
Protected Member Functions
float calcValue (int x, int y) const
std::vector< float > calcMValue (int x, int y) const
void calcMinMax ()
Protected Member Functions inherited from Sensor
Sensor (dword updateMask)
Sensor ()
virtual Point calcGradient (int x, int y) const
Protected Attributes
std::vector< ByteImage > data
int m_Dim1
int m_Dim2
int m_Dim3
int m_NChannels
int m_CurrImage
current image
dword m_ppmm
std::string m_Filename
Point2D m_Origin
Point2D m_OSize
GLImage m_GLImage
bool m_RefreshImage
dword m_HalveBeyondSize
Protected Attributes inherited from Sensor
sensor_cptr source
float scale
std::vector< float > cweights
multi-channel weights ('color')
Point dir
direction parameter
float maxval
float minval
overall minimum and maximum
float mean
float stdev
overall mean and stdev
dword toupdate
bitflag for updates
dword updateMask
bitflag to mask unimportant updates
std::string m_ID
int m_Skip
int m_AddSkip
Additional Inherited Members
Public Types inherited from Sensor
enum UpdateParam {
UPD_NOTHING =0, UPD_DATA =1, UPD_SCALE =2, UPD_CWEIGHTS =4,
UPD_DIR =8, UPD_MINMAX =16, UPD_LAST =32, UPD_ALL =0xffffffff
}
Detailed Description
Implements data management. Function for loading and querying the dataset. Also a set of data sheets is managed that contains preprocessed results for sensor evaluation.
Definition at line 21 of file Data.h.
Constructor & Destructor Documentation
Dataset::Dataset ()
Default constructor
Definition at line 46 of file Data.cpp.
References Sensor::setID().
                  : data(1),
                      m_Dim1(0), m_Dim2(0), m_Dim3(0), m_NChannels(0),
                      m_CurrImage(0),m_ppmm(DEFAULT_PPMM),m_RefreshImage(false),
                      m_HalveBeyondSize(0xffffffff)
 {
     setID("d0");
 }
Dataset::Dataset (const char * filename)
Constructor
Definition at line 54 of file Data.cpp.
References load().
                                      : m_Dim1(0), m_Dim2(0), m_Dim3(0),
                                          m_NChannels(0), m_CurrImage(0),
                                          m_ppmm(DEFAULT_PPMM),
                                          m_RefreshImage(false)
 {
     load(filename);
 }
Dataset::~Dataset () inline
Destructor
Definition at line 31 of file Data.h.
References copyData(), draw(), and load().
 {};
Member Function Documentation
void Dataset::addNoise (float sigma)
Definition at line 212 of file Data.cpp.
References data, fgauss01(), and m_RefreshImage.
Referenced by getHalveBeyondSize().
 {
     for(vector< ByteImage >::iterator ii=data.begin();
         ii!=data.end();ii++)
     {
         byte* data = ii->getData();
         for(int i=ii->getSize(); i>0; i--, data++)
         {
             int val = int(int(*data) + fgauss01()*sigma);
             if(val<0) *data = 0;
             else if(val>255) *data = 255;
             else *data = byte(val);
         }
     }
     m_RefreshImage = true;
 }
void Dataset::calcMinMax () inline protected virtual
Reimplemented from Sensor.
Definition at line 102 of file Data.h.
References Sensor::maxval, and Sensor::minval.
                       {
         maxval = 255;
         minval = 0;
     }
std::vector<float> Dataset::calcMValue (int x, int y) const inline protected virtual
implementing virtual from class Sensor
Reimplemented from Sensor.
Definition at line 92 of file Data.h.
References data, and m_NChannels.
{
         //vuLock l(*((vuMutex*)&writeMutex));
         std::vector<float> mv(m_NChannels);
         int cc = 0;
         for(std::vector<float>::iterator cv = mv.begin();
             cv != mv.end(); cv++, cc++) {
             *cv = (float)data[cc].getPixel(x,y);
         }
         return mv;
     }
float Dataset::calcValue (int x, int y) const inline protected virtual
implementing virtual from class Sensor
Implements Sensor.
Definition at line 85 of file Data.h.
References data, m_CurrImage, m_Dim1, and m_Dim2.
{
         //vuLock l(*((vuMutex*)&writeMutex));
         if((dword)x < (dword)m_Dim1 && (dword)y < (dword)m_Dim2)
             return data[m_CurrImage].getPixel(x,y);
         else return 0.0f;
     }
void Dataset::clear ()
Definition at line 143 of file Data.cpp.
References data, DEFAULT_PPMM, m_CurrImage, m_Dim1, m_Dim2, m_Dim3, m_Filename, m_NChannels, m_Origin, m_ppmm, Sensor::performUpdate(), Sensor::setModified(), and Sensor::UPD_DATA.
Referenced by print().
 {
     m_Dim1 = m_Dim2 = m_Dim3 = 0;
     m_NChannels = 0; m_CurrImage = 0;
     m_ppmm = DEFAULT_PPMM;
     data.clear();
     data.resize(1);
     m_Filename.clear();
     m_Origin = 0.0f;
     setModified(UPD_DATA);
     performUpdate();
 }
Dataset & Dataset::copyData (const Dataset & rhs)
Definition at line 127 of file Data.cpp.
References data, m_CurrImage, m_Dim1, m_Dim2, m_Dim3, m_Filename, m_HalveBeyondSize, m_NChannels, m_ppmm, Sensor::performUpdate(), Sensor::setModified(), and Sensor::UPD_DATA.
Referenced by ~Dataset().
 {
     data = rhs.data;
     m_CurrImage = 0;
     m_Dim1 = data[0].getSizeX();
     m_Dim2 = data[0].getSizeY();
     m_Dim3 = 1;
     m_NChannels = data.size();
     m_ppmm = rhs.m_ppmm;
     m_Filename = rhs.m_Filename;
     m_HalveBeyondSize = rhs.m_HalveBeyondSize;
     setModified(UPD_DATA);
     performUpdate();
     return *this;
 }
void Dataset::draw (float x = 0, float y = 0, float sx = 1.0f, float sy = 1.0f) const
Draw data set (using OpenGL)
Definition at line 113 of file Data.cpp.
References data, GLImage::draw(), m_GLImage, m_RefreshImage, GLImage::setImage(), and GLImage::unsetImage().
Referenced by ImageWindow::drawScene(), and ~Dataset().
 {
     if(!data.empty())
     {
         if(m_RefreshImage) {
             m_GLImage.unsetImage();
             m_GLImage.setImage(data);
             m_RefreshImage = false;
         }
         m_GLImage.draw(x, y, sx, sy);
         //drawImage(data,x,y,sx,sy);
     }
 }
void Dataset::drawImage (const std::vector< Image< byte > > & image, float x = 0, float y = 0, float sx = 1.0f, float sy = 1.0f) static
Draw Image using glDrawPixels()
Definition at line 263 of file Data.cpp.
References interleave().
Referenced by getImage().
 {
     byte *buf = interleave(image);
     glPixelZoom(sx, sy);
     glRasterPos3f(x,y,0.0f);
     glDrawPixels(image[0].getSizeX(),
                  image[0].getSizeY(),
                  GL_RGB,
                  GL_UNSIGNED_BYTE,
                  buf);
     delete buf;
 }
void Dataset::drawImage (const Image< byte > & image, float x = 0, float y = 0, float sx = 1.0f, float sy = 1.0f) static
Definition at line 229 of file Data.cpp.
References Image< T >::getData(), Image< T >::getSizeX(), and Image< T >::getSizeY().
 {
     glPixelZoom(sx, sy);
     glRasterPos3f(x,y,0.0f);
     glDrawPixels(image.getSizeX(),
                  image.getSizeY(),
                  GL_LUMINANCE,
                  GL_UNSIGNED_BYTE,
                  image.getData());
 }
int Dataset::getDim1Size () const inline virtual
the real dataset will override these
Reimplemented from Sensor.
Definition at line 44 of file Data.h.
References m_Dim1.
Referenced by ImageWindow::drawScene(), main(), ImageWindow::onKeyPress(), ImageWindow::onLeftMouseClick(), and ImageWindow::onRightMouseClick().
 { return m_Dim1; }
int Dataset::getDim2Size () const inline virtual
Reimplemented from Sensor.
Definition at line 45 of file Data.h.
References m_Dim2.
Referenced by ImageWindow::drawScene(), main(), ImageWindow::onKeyPress(), ImageWindow::onLeftMouseClick(), and ImageWindow::onRightMouseClick().
 { return m_Dim2; }
int Dataset::getDim3Size () const inline virtual
Reimplemented from Sensor.
Definition at line 46 of file Data.h.
References m_Dim3.
 { return m_Dim3; }
const std::string& Dataset::getFilename () const inline
Definition at line 75 of file Data.h.
References m_Filename.
 { return m_Filename; }
dword Dataset::getHalveBeyondSize () const inline
Definition at line 81 of file Data.h.
References addNoise(), and m_HalveBeyondSize.
 { return m_HalveBeyondSize; }
const ByteImage& Dataset::getImage () const inline
Definition at line 54 of file Data.h.
References data, and m_CurrImage.
Referenced by ImageWindow::onKeyPress().
 { return data.at(m_CurrImage); }
ByteImage& Dataset::getImage () inline
Definition at line 55 of file Data.h.
References data, and m_CurrImage.
 { return data.at(m_CurrImage); }
const ByteImage& Dataset::getImage (int index) const inline
Definition at line 56 of file Data.h.
References data.
 { return data.at(index); }
ByteImage& Dataset::getImage (int index) inline
Definition at line 57 of file Data.h.
References data, drawImage(), and loadImage().
 { return data.at(index); }
int Dataset::getNChannels () const inline virtual
Reimplemented from Sensor.
Definition at line 47 of file Data.h.
References m_NChannels.
 { return m_NChannels; }
const Point2D& Dataset::getOrigin () const inline
Definition at line 72 of file Data.h.
References m_Origin.
 { return m_Origin; }
const Point2D& Dataset::getOSize () const inline
Definition at line 73 of file Data.h.
References m_OSize.
 { return m_OSize; }
dword Dataset::getPPMM () const inline
Definition at line 70 of file Data.h.
References m_ppmm.
 { return m_ppmm; }
PropVec Dataset::getPropVec () const inline
Definition at line 76 of file Data.h.
References m_Dim1, and setPropScale().
Referenced by getPropVecMM().
         { PropVec pv(0.f); return setPropScale(pv, (float)m_Dim1); }
PropVec Dataset::getPropVecMM () const inline
Definition at line 78 of file Data.h.
References getPropVec(), m_ppmm, and scalePropVec().
         { PropVec pv(getPropVec()); return scalePropVec(pv, 1.f/m_ppmm); }
bool Dataset::initialized () const inline
Definition at line 52 of file Data.h.
References m_Dim1, and m_Dim2.
Referenced by ImageWindow::drawScene(), and operator bool().
 { return m_Dim1 && m_Dim2; }
bool Dataset::load (const char * filename, dword ppmm = 0)
Load data set from file
Definition at line 62 of file Data.cpp.
References data, Image< T >::getSizeX(), Image< T >::getSizeY(), Image< T >::insert(), loadImage(), m_CurrImage, m_Dim1, m_Dim2, m_Dim3, m_Filename, m_HalveBeyondSize, m_NChannels, m_Origin, m_OSize, m_RefreshImage, Sensor::performUpdate(), Sensor::setModified(), setPPMM(), Image< T >::sum(), Sensor::UPD_DATA, writeMutex, Point2D::x, and Point2D::y.
Referenced by ImageWindow::changeSpecies(), Dataset(), and ~Dataset().
 {
     if(data.empty()) data.push_back(*(new ByteImage()));
     vuLock l(writeMutex);
     bool loaded = loadImage(data, filename);
     if(loaded) {
         m_Filename = filename;
         m_Origin = 0.0f;
         if(data[0].getSizeY()>3 && data[0].getSizeX()>3) {
             ByteImage zimg(data[0].getSizeX()-2, data[0].getSizeY()-2,0);
             int brd = (1<<6);
             m_Origin = (float)brd;
             for(vector< ByteImage >::iterator ii=data.begin();
                 ii!=data.end();ii++)
             {
                 if((dword)ii->getSize() > m_HalveBeyondSize) {
                     *ii = ii->scaleBy(0.5);
                     ppmm /= 2;
                     cout << "reducing image" << endl;
                 }
                 ByteImage copimg(*ii);
                 copimg.insert(zimg, 1, 1);
                 double avgcol = copimg.sum()/
                     ((copimg.getSizeX()+copimg.getSizeY())*2-4);
                 ii->zeroPad(brd, byte(avgcol));
                 // make edge length even
                 dword nx = (ii->getSizeX()/2+1)*2;
                 dword ny = (ii->getSizeY()/2+1)*2;
                 ByteImage ni(nx, ny, byte(avgcol));
                 ni.insert(*ii);
                 *ii = ni;
 //                 stringstream fname;
 //                 fname << "bimage" << ii-data.begin() << ".ppm";
 //                 if(ii->writePPM(fname.str())) cout << "ok." << endl;
             }
         }
         m_OSize.x = (float)data[0].getSizeX();
         m_OSize.y = (float)data[0].getSizeY();
         m_CurrImage = 0;
         m_Dim1 = data[0].getSizeX();
         m_Dim2 = data[0].getSizeY();
         m_Dim3 = 1;
         m_RefreshImage = true;
         m_NChannels = data.size();
         setPPMM(ppmm);
         setModified(UPD_DATA);
         performUpdate();
         return true;
     } else return false;
 }
bool Dataset::loadImage (std::vector< Image< byte > > & image, const char * filename) static
Load an Image<byte>
Definition at line 159 of file Data.cpp.
References copyFXImage2Image(), and NULL.
Referenced by getImage(), and load().
{
     FXString ext=FXPath::extension(file);
     FXImage *img=NULL;
     FXApp *app = FXApp::instance(); //getApp()
     if(comparecase(ext,"bmp")==0){
         img=new FXBMPImage(app,NULL,IMAGE_KEEP|IMAGE_SHMI|IMAGE_SHMP);
     }
     else if(comparecase(ext,"gif")==0){
         img=new FXGIFImage(app,NULL,IMAGE_KEEP|IMAGE_SHMI|IMAGE_SHMP);
     }
     else if(comparecase(ext,"tga")==0){
         img=new FXTGAImage(app,NULL,IMAGE_KEEP|IMAGE_SHMI|IMAGE_SHMP);
     }
 #ifdef HAVE_PNG_H
     else if(comparecase(ext,"png")==0){
         img=new FXPNGImage(app,NULL,IMAGE_KEEP|IMAGE_SHMI|IMAGE_SHMP);
     }
 #endif
 #ifdef HAVE_JPEG_H
     else if(comparecase(ext,"jpg")==0){
         img=new FXJPGImage(app,NULL,IMAGE_KEEP|IMAGE_SHMI|IMAGE_SHMP);
     }
 #endif
 #ifdef HAVE_TIFF_H
     else if(comparecase(ext,"tif")==0 || comparecase(ext,"tiff")==0){
         img=new FXTIFImage(app,NULL,IMAGE_KEEP|IMAGE_SHMI|IMAGE_SHMP);
     }
 #endif
     bool load_ok = false;
     if(img!=NULL) {
         // Load it
         FXFileStream stream;
         if(stream.open(file,FXStreamLoad)){
             //app->beginWaitCursor();
             load_ok = img->loadPixels(stream);
             if(load_ok) {
                 img->create();
                 //app->endWaitCursor();
                 //img->mirror(false, true);
                 copyFXImage2Image(image, *img);
             }
             stream.close();
         }
         delete img;
     }
     //note: modal error message causes deadlock on Brain::m_DataMutex
     //between Brain::loadData and Brain::drawAllModels
     //if(!load_ok)
     //    FXMessageBox::error(/*this app->getRootWindow()*/ app,MBOX_OK,"Error Loading Image","Unsupported type: %s",ext.text());
     return load_ok;
 }
Dataset::operator bool () const inline
Definition at line 53 of file Data.h.
References initialized().
 { return initialized(); }
std::ostream& Dataset::print (std::ostream & os) const inline virtual
Reimplemented from Sensor.
Definition at line 48 of file Data.h.
References clear().
         { return os; } //don't print to model file
void Dataset::setHalveBeyondSize (dword hbs = 0xffffffff) inline
Definition at line 80 of file Data.h.
References m_HalveBeyondSize.
 { m_HalveBeyondSize = hbs; }
void Dataset::setPPMM (dword ppmm) inline
Definition at line 71 of file Data.h.
References DEFAULT_PPMM, and m_ppmm.
Referenced by load().
 { m_ppmm = ppmm ? ppmm : DEFAULT_PPMM; }
Member Data Documentation
std::vector<ByteImage> Dataset::data protected
The data as one dimensional array. If more than one channel is used data will be organized as vector<ByteImage>.
Definition at line 108 of file Data.h.
Referenced by addNoise(), calcMValue(), calcValue(), clear(), copyData(), draw(), getImage(), load(), and makeNoiseImage().
int Dataset::m_CurrImage protected
current image
Definition at line 112 of file Data.h.
Referenced by calcValue(), clear(), copyData(), getImage(), and load().
int Dataset::m_Dim1 protected
Dimensions in X, Y, and Z direction + number of channels
Definition at line 111 of file Data.h.
Referenced by calcValue(), clear(), copyData(), getDim1Size(), getPropVec(), initialized(), and load().
int Dataset::m_Dim2 protected
Definition at line 111 of file Data.h.
Referenced by calcValue(), clear(), copyData(), getDim2Size(), initialized(), and load().
int Dataset::m_Dim3 protected
Definition at line 111 of file Data.h.
Referenced by clear(), copyData(), getDim3Size(), and load().
std::string Dataset::m_Filename protected
Definition at line 114 of file Data.h.
Referenced by clear(), copyData(), getFilename(), and load().
GLImage Dataset::m_GLImage mutable protected
Definition at line 116 of file Data.h.
Referenced by draw().
dword Dataset::m_HalveBeyondSize protected
Definition at line 118 of file Data.h.
Referenced by copyData(), getHalveBeyondSize(), load(), and setHalveBeyondSize().
int Dataset::m_NChannels protected
Definition at line 111 of file Data.h.
Referenced by calcMValue(), clear(), copyData(), getNChannels(), and load().
Point2D Dataset::m_Origin protected
Definition at line 115 of file Data.h.
Referenced by clear(), getOrigin(), and load().
Point2D Dataset::m_OSize protected
Definition at line 115 of file Data.h.
Referenced by getOSize(), and load().
dword Dataset::m_ppmm protected
Definition at line 113 of file Data.h.
Referenced by clear(), copyData(), getPPMM(), getPropVecMM(), and setPPMM().
bool Dataset::m_RefreshImage mutable protected
Definition at line 117 of file Data.h.
Referenced by addNoise(), draw(), and load().
vuMutex Dataset::writeMutex
Definition at line 68 of file Data.h.
Referenced by load().
The documentation for this class was generated from the following files:
src/Data.h
src/Data.cpp