Structural deformable models: Sensor Class Reference
Sensor Class Reference abstract
#include <Sensor.h>
Public Types
enum UpdateParam {
UPD_NOTHING =0, UPD_DATA =1, UPD_SCALE =2, UPD_CWEIGHTS =4,
UPD_DIR =8, UPD_MINMAX =16, UPD_LAST =32, UPD_ALL =0xffffffff
}
Public Member Functions
virtual ~Sensor ()
sensor_cptr getSource ()
virtual void changeSource (sensor_cptr _source)
void replaceBy (sensor_ptr target)
bool assignRef (sensor_cptr rhs)
virtual Sensor & assign (const Sensor &rhs)
virtual float getValue (int x, int y) const
get value at discrete position
float getValue (const Point &p) const
get value at position p using nearest neighbour interpolation
virtual std::vector< float > getMValue (int x, int y) const
get multi-channel value
virtual Point2D getGradient (int x, int y) const
get gradient at discrete position
Point2D getGradient (const Point2D &p) const
get gradient at position p using nearest neighbor interpolation
float getMax () const
float getMin () const
float getMinMaxRange () const
float getWeightedValue (int x, int y) const
get max normalized value at discrete position range [0,1]
Point2D getWeightedGradient (int x, int y) const
get range weighted gradient at discrete position
void setCWeights (const std::vector< float > &weights)
const std::vector< float > & getCWeights () const
void setDirection (const Point &dir)
const Point & getDirection () const
void setScale (float _scale)
float getScale () const
bool isModified (dword mask=UPD_ALL) const
void setModified (dword mask=UPD_ALL)
void unsetModified (dword mask=UPD_ALL)
bool isUpdate (dword udMask) const
void enableUpdate (dword udMask)
void disableUpdate (dword udMask)
virtual bool performUpdate ()
virtual int getDim1Size () const
virtual int getDim2Size () const
virtual int getDim3Size () const
virtual int getNChannels () const
virtual int getSkip () const
bool isValid (int x, int y) const
virtual Image< float > createSensorImage () const
const std::string & getID () const
void setID (const std::string &id)
virtual std::ostream & hprint (std::ostream &os, SensorCollection *sc) const
virtual std::ostream & print (std::ostream &os) const
void refSuperSensor (sensor_ptr super)
void unrefSuperSensor (sensor_ptr super)
void invalidateSource ()
template<typename Derived >
std::shared_ptr< Derived > shared_from_base ()
Static Public Member Functions
static dword getStringNumber (const char *sid)
static void getNumberString (char sid[5], dword id)
Protected Member Functions
Sensor (dword updateMask)
Sensor ()
virtual float calcValue (int x, int y) const =0
virtual std::vector< float > calcMValue (int x, int y) const
virtual Point calcGradient (int x, int y) const
virtual void calcMinMax ()
Protected Attributes
sensor_cptr source
float scale
std::vector< float > cweights
multi-channel weights ('color')
Point dir
direction parameter
float maxval
float minval
overall minimum and maximum
float mean
float stdev
overall mean and stdev
dword toupdate
bitflag for updates
dword updateMask
bitflag to mask unimportant updates
std::string m_ID
int m_Skip
int m_AddSkip
Detailed Description
Sensor calculates filter values from the source.
Definition at line 21 of file Sensor.h.
Member Enumeration Documentation
enum Sensor::UpdateParam
Enumerator
UPD_NOTHING
UPD_DATA
UPD_SCALE
UPD_CWEIGHTS
UPD_DIR
UPD_MINMAX
UPD_LAST
UPD_ALL
Definition at line 26 of file Sensor.h.
                       {UPD_NOTHING=0, UPD_DATA=1,
                        UPD_SCALE=2, UPD_CWEIGHTS=4, UPD_DIR=8,
                        UPD_MINMAX=16,
                        UPD_LAST=32, UPD_ALL=0xffffffff
     };
Constructor & Destructor Documentation
Sensor::Sensor (dword updateMask) protected
Definition at line 13 of file Sensor.cpp.
References cweights.
     : source(),
       scale(0.f),
       maxval(), minval(), mean(), stdev(),
       toupdate(), updateMask(_updateMask),
       m_ID(""), m_Skip(0), m_AddSkip(0)
 {
     cweights.resize(1, 1.f);
 }
Sensor::Sensor () protected
Definition at line 23 of file Sensor.cpp.
References cweights, and setModified().
     : source(getZeroSensor()),
       scale(0.f),
       maxval(), minval(), mean(), stdev(),
       toupdate(), updateMask((dword)UPD_DATA),
       m_ID(""), m_Skip(0), m_AddSkip(0)
 {
     cweights.resize(1, 1.f);
     setModified();
 }
Sensor::~Sensor () virtual
Destructor
Definition at line 34 of file Sensor.cpp.
References getZeroSensor(), source, and unrefSuperSensor().
 {
     if(source && source != getZeroSensor())
         std::const_pointer_cast<Sensor>(source)->unrefSuperSensor( shared_from_this() );
     for(set<sensor_ptr>::iterator ss = superSensors.begin();
         ss != superSensors.end();
         ss++)
         (*ss)->invalidateSource();
 }
Member Function Documentation
Sensor & Sensor::assign (const Sensor & rhs) virtual
Reimplemented in MappingSensor, MahalSensor, CombiSensor, and PPSensor.
Definition at line 54 of file Sensor.cpp.
References changeSource(), cweights, dir, m_AddSkip, m_ID, m_Skip, scale, setCWeights(), setDirection(), setScale(), and source.
Referenced by PPSensor::assign(), assignRef(), MahalSensor::getNChannels(), MappingSensor::getNChannels(), getSource(), and CombiSensor::setSource().
 {
     if(&rhs != this) {
         if(source != rhs.source) changeSource(rhs.source);
         if(scale != rhs.scale) setScale(rhs.scale);
         if(dir != rhs.dir) setDirection(rhs.dir);
         if(cweights != rhs.cweights) setCWeights(rhs.cweights);
         m_ID = rhs.m_ID;
         m_Skip = rhs.m_Skip;
         m_AddSkip = rhs.m_AddSkip;
         //superSensors are not changed here (no sensor fusion)
     }
     return *this;
 }
bool Sensor::assignRef (sensor_cptr rhs)
Definition at line 69 of file Sensor.cpp.
References assign().
Referenced by getSource().
{
     if(typeid(*this) != typeid(*rhs)) return false;
     assign(*rhs);
     return true;
 }
virtual Point Sensor::calcGradient (int x, int y) const inline protected virtual
Calculates the gradient using central differencing.
Reimplemented in ZeroSensor, and MCGSensor.
Definition at line 149 of file Sensor.h.
References calcMinMax(), getValue(), invalidateSource(), refSuperSensor(), and unrefSuperSensor().
Referenced by PPSensor::calcAllGradients(), getGradient(), and PPSensor::getGradient().
{
         float v = getValue(x,y);
         return Point2D(getValue(x+1,y)-v,
                        getValue(x,y+1)-v);
     }
void Sensor::calcMinMax () protected virtual
Reimplemented in Dataset.
Definition at line 152 of file Sensor.cpp.
References dmutil::avg(), getValue(), maxval, mean, minval, source, dmutil::sqrt(), and stdev.
Referenced by calcGradient(), and performUpdate().
{
     if(!source) {
         minval = maxval = 0;
         mean = stdev = 0;
         return;
     }
     int i,j;
     minval=numeric_limits<float>::max();
     maxval=numeric_limits<float>::min();
     double avg=0, avg2=0;
     double size = double(source->getDim1Size()*source->getDim2Size());
     if(size > 0.) {
         for(j=0; j<source->getDim2Size(); j++) {
             for(i=0; i<source->getDim1Size(); i++) {
                 float val = getValue(i,j);
                 if(val>maxval) maxval = val;
                 if(val<minval) minval = val;
                 avg+=double(val);
                 avg2+=double(val*val);
             }
         }
         avg  /= size;
         avg2 /= size;
     } else {
         minval = maxval = 0;
     }
     mean = float(avg);
     stdev = float(sqrt(avg2-avg*avg))*1.5;
 }
virtual std::vector<float> Sensor::calcMValue (int x, int y) const inline protected virtual
Calculate a multi-valued sensor result. The size of the returned vector is the same as getNChannels().
Reimplemented in CombiSensor, and Dataset.
Definition at line 145 of file Sensor.h.
References calcValue(), and getNChannels().
Referenced by getMValue().
{
         return std::vector<float>(getNChannels(), calcValue(x,y));
     }
virtual float Sensor::calcValue (int x, int y) const protected pure virtual
Compute a sensed value at position x,y. This function is essential for all derived sensors.
Implemented in MappingSensor, MahalSensor, CombiSensor, CornerSensor, ZeroSensor, GradMagSensor, SmoothIntensitySensor, CRSensor, Dataset, MCGSensor, MCIntensitySensor, PPIntensitySensor, and IntensitySensor.
Referenced by PPSensor::calcAllValues(), calcMValue(), getValue(), PPSensor::getValue(), and setID().
void Sensor::changeSource (sensor_cptr _source) virtual
Reimplemented in CombiSensor, and ZeroSensor.
Definition at line 96 of file Sensor.cpp.
References cweights, getZeroSensor(), refSuperSensor(), setModified(), source, unrefSuperSensor(), and UPD_DATA.
Referenced by assign(), CombiSensor::changeSource(), CombiSensor::getSkip(), and getSource().
{
     assert(source);
     std::const_pointer_cast<Sensor>(source)->unrefSuperSensor( shared_from_this() );
     if(!_source)
         source = getZeroSensor();
     else
         source = _source;
     if(cweights.size() != size_t(source->getNChannels()))
         cweights.resize(source->getNChannels(), 1.f);
     std::const_pointer_cast<Sensor>(source)->refSuperSensor( shared_from_this() );
     setModified(UPD_DATA);
 }
Image< float > Sensor::createSensorImage () const virtual
Definition at line 203 of file Sensor.cpp.
References getDim1Size(), getDim2Size(), getWeightedValue(), and Image< T >::setPixel().
Referenced by getSkip().
{
     Image<float> img(getDim1Size(), getDim2Size());
     int i,j;
     for(j=0;j<getDim2Size();j++)
         for(i=0;i<getDim1Size();i++) {
             img.setPixel(i,j, getWeightedValue(i,j));
         }
     return img;
 }
void Sensor::disableUpdate (dword udMask) inline
Definition at line 114 of file Sensor.h.
References performUpdate().
 { updateMask &= ~udMask; }
void Sensor::enableUpdate (dword udMask) inline
Definition at line 113 of file Sensor.h.
Referenced by CombiSensor::changeSource(), CombiSensor::CombiSensor(), CornerSensor::CornerSensor(), GradMagSensor::GradMagSensor(), and CombiSensor::setSource().
 { updateMask |= udMask; }
const std::vector<float>& Sensor::getCWeights () const inline
Definition at line 97 of file Sensor.h.
References cweights, dir, and setDirection().
Referenced by CombiSensor::assign().
 { return cweights; }
virtual int Sensor::getDim1Size () const inline virtual
the real dataset will override these
Reimplemented in ZeroSensor, and Dataset.
Definition at line 120 of file Sensor.h.
References source.
Referenced by createSensorImage(), and isValid().
 { return source->getDim1Size(); }
virtual int Sensor::getDim2Size () const inline virtual
Reimplemented in ZeroSensor, and Dataset.
Definition at line 121 of file Sensor.h.
References source.
Referenced by createSensorImage(), and isValid().
 { return source->getDim2Size(); }
virtual int Sensor::getDim3Size () const inline virtual
Reimplemented in ZeroSensor, and Dataset.
Definition at line 122 of file Sensor.h.
References source.
 { return source->getDim3Size(); }
const Point& Sensor::getDirection () const inline
Definition at line 99 of file Sensor.h.
References dir, and setScale().
 { return dir; }
virtual Point2D Sensor::getGradient (int x, int y) const inline virtual
get gradient at discrete position
Reimplemented in PPSensor.
Definition at line 53 of file Sensor.h.
References calcGradient().
Referenced by getGradient(), and getWeightedGradient().
{
         return calcGradient(x,y);
     }
Point2D Sensor::getGradient (const Point2D & p) const inline
get gradient at position p using nearest neighbor interpolation
Definition at line 57 of file Sensor.h.
References getGradient(), Point2D::x, and Point2D::y.
{
 //  float v = getValue(p);
 //  return Point2D(getValue(p+Point2D(1,0))-v,
 //             getValue(p+Point2D(0,1))-v);
         return getGradient((int)p.x, (int)p.y);
     };
const std::string& Sensor::getID () const inline
Definition at line 128 of file Sensor.h.
References m_ID.
Referenced by CombiSensor::print().
 { return m_ID; }
float Sensor::getMax () const inline
Definition at line 63 of file Sensor.h.
References isModified(), and maxval.
{
         if(isModified()) ((Sensor*)this)->performUpdate();
         return maxval;
     }
float Sensor::getMin () const inline
Definition at line 67 of file Sensor.h.
References isModified(), and minval.
{
         if(isModified()) ((Sensor*)this)->performUpdate();
         return minval;
     }
float Sensor::getMinMaxRange () const inline
Definition at line 71 of file Sensor.h.
References isModified(), maxval, and minval.
Referenced by getWeightedGradient(), and getWeightedValue().
{
         if(isModified()) ((Sensor*)this)->performUpdate();
         return maxval-minval;
     }
virtual std::vector<float> Sensor::getMValue (int x, int y) const inline virtual
get multi-channel value
Definition at line 49 of file Sensor.h.
References calcMValue().
Referenced by ImageWindow::onKeyPress().
{
         return calcMValue(x,y);
     }
virtual int Sensor::getNChannels () const inline virtual
Reimplemented in MappingSensor, MahalSensor, CombiSensor, ZeroSensor, CRSensor, MCGSensor, Dataset, and MCIntensitySensor.
Definition at line 123 of file Sensor.h.
References source.
Referenced by calcMValue(), and CombiSensor::calcMValue().
 { return source->getNChannels(); }
void Sensor::getNumberString (char sid[5], dword id) static
Definition at line 88 of file Sensor.cpp.
Referenced by setID().
 {
     int i;
     for(i=0;i<4 && id!=0;i++,id=id>>8)
         sid[i] = char(id);
     sid[i] = 0;
 }
float Sensor::getScale () const inline
Definition at line 101 of file Sensor.h.
References scale.
Referenced by SmoothIntensitySensor::print().
 { return scale; }
virtual int Sensor::getSkip () const inline virtual
Reimplemented in CombiSensor.
Definition at line 124 of file Sensor.h.
References createSensorImage(), isValid(), and m_Skip.
 { return m_Skip; }
sensor_cptr Sensor::getSource () inline
Definition at line 34 of file Sensor.h.
References assign(), assignRef(), changeSource(), replaceBy(), and source.
 {return source;}
dword Sensor::getStringNumber (const char * sid) static
Definition at line 75 of file Sensor.cpp.
Referenced by setID().
{
     if(!sid) return 0;
     else {
         dword val;
         int i;
         for(i=0, val=0; i<4 && sid[i]!=0; i++) {
             if(sid[i]>32)
                 val |= ((dword)(sid[i]))<<(8*i);
         }
         return val;
     }
 }
virtual float Sensor::getValue (int x, int y) const inline virtual
get value at discrete position
Reimplemented in PPSensor.
Definition at line 41 of file Sensor.h.
References calcValue().
Referenced by calcGradient(), calcMinMax(), getValue(), and getWeightedValue().
{
         return calcValue( x, y);
     }
float Sensor::getValue (const Point & p) const inline
get value at position p using nearest neighbour interpolation
Definition at line 45 of file Sensor.h.
References getValue(), Point2D::x, and Point2D::y.
{
         return getValue((int)p.x, (int)p.y);
     }
Point2D Sensor::getWeightedGradient (int x, int y) const inline
get range weighted gradient at discrete position
Definition at line 90 of file Sensor.h.
References getGradient(), getMinMaxRange(), and setCWeights().
{
         float range = getMinMaxRange();
         if(range==0) range = 1;
         return getGradient(x,y)/range;
     }
float Sensor::getWeightedValue (int x, int y) const inline
get max normalized value at discrete position range [0,1]
Definition at line 76 of file Sensor.h.
References getMinMaxRange(), getValue(), minval, SENSOR_GAUSS_NORMALIZATION_RANGE, and stdev.
Referenced by createSensorImage().
{
 #define _USE_MINMAX_NORMALIZATION_
 #ifdef _USE_MINMAX_NORMALIZATION_
         float range = getMinMaxRange();
         if(range==0) return 0.f;
         return (getValue(x,y)-minval)/range;
 #else
         float range = stdev*SENSOR_GAUSS_NORMALIZATION_RANGE;
         if(range==0) range = 1;
         float value = (getValue(x,y)-minval)/range;
         return value > 1.f ? 1.f : value; //(value < 0.f ? 0.f : value);
 #endif
     }
ostream & Sensor::hprint (std::ostream & os, SensorCollection * sc) const virtual
Reimplemented in CombiSensor.
Definition at line 222 of file Sensor.cpp.
References getZeroSensor(), SensorCollection::isPrinted(), m_ID, print(), SensorCollection::setPrinted(), and source.
Referenced by CombiSensor::getSkip(), and setID().
 {
     if(sc->isPrinted(m_ID)) return os;
     if(source && source != getZeroSensor()) source->hprint(os, sc);
     if(sc->isPrinted(m_ID)) return os;
     sc->setPrinted(m_ID);
     return (print(os) << endl);
 }
void Sensor::invalidateSource ()
Definition at line 190 of file Sensor.cpp.
References getZeroSensor(), source, and unrefSuperSensor().
Referenced by calcGradient().
{
     if(source && source != getZeroSensor()) {
         std::const_pointer_cast<Sensor>(source)->unrefSuperSensor( shared_from_this() );
         source = getZeroSensor();
     }
 }
bool Sensor::isModified (dword mask = UPD_ALL) const inline
Check whether something is marked as modified. enum Sensor::UpdateParam is used. Also, mask is filtered through internal updateMask. So only the properties that matter to the current sensor will take effect.
Definition at line 108 of file Sensor.h.
References toupdate.
Referenced by PPSensor::calcAllGradients(), PPSensor::getGradient(), getMax(), getMin(), getMinMaxRange(), PPSensor::getValue(), performUpdate(), GradMagSensor::performUpdate(), CornerSensor::performUpdate(), PPSensor::performUpdate(), and MappingSensor::performUpdate().
         { return (toupdate & (mask & updateMask)) != 0; }
bool Sensor::isUpdate (dword udMask) const inline
Definition at line 112 of file Sensor.h.
Referenced by CombiSensor::setSource().
 { return updateMask & udMask; }
bool Sensor::isValid (int x, int y) const
Definition at line 197 of file Sensor.cpp.
References getDim1Size(), getDim2Size(), and m_Skip.
Referenced by GradMagSensor::calcValue(), CornerSensor::calcValue(), and getSkip().
 {
     return x>=m_Skip && x<getDim1Size()-m_Skip
                           && y>=m_Skip && y<getDim2Size()-m_Skip;
 }
bool Sensor::performUpdate () virtual
Perform an update if isModified()
Reimplemented in MappingSensor, PPSensor, CornerSensor, GradMagSensor, and SmoothIntensitySensor.
Definition at line 123 of file Sensor.cpp.
References calcMinMax(), isModified(), m_AddSkip, m_Skip, source, unsetModified(), UPD_DATA, UPD_MINMAX, and updateMask.
Referenced by PPSensor::calcAllGradients(), Dataset::clear(), Dataset::copyData(), disableUpdate(), PPSensor::getGradient(), MappingSensor::getMappingID(), PPSensor::getValue(), GradMagSensor::GradMagSensor(), Dataset::load(), and PPSensor::performUpdate().
{
     bool modified = false;
     if(isModified()) {
         if(isModified(UPD_DATA)) {
             m_Skip = source->getSkip()+m_AddSkip;
             //if(cweights.size() != source->getNChannels()) {
             //  cweights.resize(source->getNChannels(),1.f);
             //modified = true;
             //}
         }
         unsetModified();
         if(updateMask&UPD_MINMAX) {
             calcMinMax();
         }
         // do nothing for this sensor, but for the others...
         for(set<sensor_ptr>::iterator ss = superSensors.begin();
             ss != superSensors.end(); ss++)
         {
             (*ss)->setModified(Sensor::UPD_DATA);
         }
         for(set<sensor_ptr>::iterator ss = superSensors.begin();
             ss != superSensors.end(); ss++)
         {
             (*ss)->performUpdate();
         }
     }
     return modified;  // no modification to *this
 }
ostream & Sensor::print (std::ostream & os) const virtual
Reimplemented in MappingSensor, MahalSensor, CombiSensor, ZeroSensor, CornerSensor, GradMagSensor, SmoothIntensitySensor, CRSensor, MCGSensor, Dataset, MCIntensitySensor, and IntensitySensor.
Definition at line 213 of file Sensor.cpp.
References getZeroSensor(), m_ID, and source.
Referenced by hprint(), IntensitySensor::print(), MCIntensitySensor::print(), MCGSensor::print(), CRSensor::print(), SmoothIntensitySensor::print(), GradMagSensor::print(), CornerSensor::print(), ZeroSensor::print(), MahalSensor::print(), MappingSensor::print(), and setID().
 {
     os << "s " << m_ID << " ";
     if(source && source->getID() != "d0" && source != getZeroSensor()) {
         os << "source " << source->getID() << " ";
     }
     return os;
 }
void Sensor::refSuperSensor (sensor_ptr super)
Definition at line 182 of file Sensor.cpp.
References getZeroSensor().
Referenced by calcGradient(), and changeSource().
{
     if(super != getZeroSensor())
         superSensors.insert(super);
 }
void Sensor::replaceBy (sensor_ptr target)
Definition at line 44 of file Sensor.cpp.
Referenced by getSource(), and SensorCollection::merge().
{
     for(set<sensor_ptr>::iterator ss = superSensors.begin();
         ss != superSensors.end();)
     {
         set<sensor_ptr>::iterator last = ss;
         ss++;
         (*last)->changeSource(target);
     }
 }
void Sensor::setCWeights (const std::vector< float > & weights)
Definition at line 109 of file Sensor.cpp.
References cweights, setModified(), and UPD_CWEIGHTS.
Referenced by assign(), and getWeightedGradient().
{
     //if((int)weights.size() == source->getNChannels()) {
     cweights = weights;
     setModified(UPD_CWEIGHTS);
     //}
 }
void Sensor::setDirection (const Point & dir)
Definition at line 115 of file Sensor.cpp.
References dir, setModified(), and UPD_DIR.
Referenced by assign(), and getCWeights().
{
     this->dir = dir;
     setModified(UPD_DIR);
 }
void Sensor::setID (const std::string & id) inline
Definition at line 129 of file Sensor.h.
References calcValue(), getNumberString(), getStringNumber(), hprint(), m_ID, and print().
Referenced by Dataset::Dataset(), and ZeroSensor::ZeroSensor().
 { m_ID = id; }
void Sensor::setModified (dword mask = UPD_ALL) inline
Definition at line 110 of file Sensor.h.
References toupdate.
Referenced by PPSensor::calcAllGradients(), changeSource(), CombiSensor::changeSource(), Dataset::clear(), CombiSensor::clearSources(), Dataset::copyData(), Dataset::load(), Sensor(), setCWeights(), setDirection(), CombiSensor::setNSources(), setScale(), and CombiSensor::setSource().
 { toupdate |= mask; }
void Sensor::setScale (float _scale)
Definition at line 119 of file Sensor.cpp.
References scale, setModified(), and UPD_SCALE.
Referenced by assign(), and getDirection().
{
     scale = _scale;
     setModified(UPD_SCALE);
 }
template<typename Derived > std::shared_ptr<Derived> Sensor::shared_from_base () inline
Definition at line 162 of file Sensor.h.
         {
             return std::static_pointer_cast<Derived>(shared_from_this());
         }
void Sensor::unrefSuperSensor (sensor_ptr super)
Definition at line 186 of file Sensor.cpp.
References getZeroSensor().
Referenced by calcGradient(), changeSource(), invalidateSource(), and ~Sensor().
{
     if(super != getZeroSensor())
         superSensors.erase(super);
 }
void Sensor::unsetModified (dword mask = UPD_ALL) inline
Definition at line 111 of file Sensor.h.
References toupdate.
Referenced by PPSensor::calcAllGradients(), performUpdate(), and ZeroSensor::ZeroSensor().
 { toupdate &= ~mask; }
Member Data Documentation
std::vector<float> Sensor::cweights protected
multi-channel weights ('color')
Definition at line 174 of file Sensor.h.
Referenced by assign(), CombiSensor::calcMValue(), MCIntensitySensor::calcValue(), CombiSensor::calcValue(), changeSource(), CombiSensor::clearSources(), getCWeights(), MCIntensitySensor::print(), CombiSensor::print(), Sensor(), setCWeights(), CombiSensor::setNSources(), and CombiSensor::setSource().
Point Sensor::dir protected
direction parameter
Definition at line 175 of file Sensor.h.
Referenced by assign(), getCWeights(), getDirection(), and setDirection().
int Sensor::m_AddSkip protected
Definition at line 183 of file Sensor.h.
Referenced by assign(), CornerSensor::CornerSensor(), CRSensor::CRSensor(), GradMagSensor::GradMagSensor(), MahalSensor::MahalSensor(), MappingSensor::MappingSensor(), MCGSensor::MCGSensor(), performUpdate(), GradMagSensor::performUpdate(), and CornerSensor::performUpdate().
std::string Sensor::m_ID protected
Definition at line 181 of file Sensor.h.
Referenced by assign(), getID(), hprint(), CombiSensor::hprint(), print(), and setID().
int Sensor::m_Skip protected
Definition at line 182 of file Sensor.h.
Referenced by assign(), getSkip(), CombiSensor::getSkip(), isValid(), performUpdate(), GradMagSensor::performUpdate(), and CornerSensor::performUpdate().
float Sensor::maxval protected
Definition at line 176 of file Sensor.h.
Referenced by Dataset::calcMinMax(), calcMinMax(), getMax(), and getMinMaxRange().
float Sensor::mean protected
Definition at line 177 of file Sensor.h.
Referenced by calcMinMax(), makeNoiseImage(), MahalSensor::saveConfig(), and MahalSensor::setMean().
float Sensor::minval protected
overall minimum and maximum
Definition at line 176 of file Sensor.h.
Referenced by Dataset::calcMinMax(), calcMinMax(), getMin(), getMinMaxRange(), and getWeightedValue().
float Sensor::scale protected
Scale of filter (log2 scale –> 0 means 'full' resolution)
Definition at line 173 of file Sensor.h.
Referenced by assign(), getScale(), and setScale().
sensor_cptr Sensor::source protected
Handle of the source
Definition at line 170 of file Sensor.h.
Referenced by assign(), PPSensor::calcAllGradients(), PPSensor::calcAllValues(), MCGSensor::calcGradient(), calcMinMax(), IntensitySensor::calcValue(), PPIntensitySensor::calcValue(), MCIntensitySensor::calcValue(), MCGSensor::calcValue(), CRSensor::calcValue(), SmoothIntensitySensor::calcValue(), GradMagSensor::calcValue(), CornerSensor::calcValue(), MahalSensor::calcValue(), MappingSensor::calcValue(), changeSource(), CombiSensor::changeSource(), PPSensor::fitSheets(), getDim1Size(), getDim2Size(), getDim3Size(), getNChannels(), getSource(), hprint(), invalidateSource(), performUpdate(), GradMagSensor::performUpdate(), CornerSensor::performUpdate(), MappingSensor::performUpdate(), print(), CombiSensor::setSource(), and ~Sensor().
float Sensor::stdev protected
overall mean and stdev
Definition at line 177 of file Sensor.h.
Referenced by calcMinMax(), and getWeightedValue().
dword Sensor::toupdate protected
bitflag for updates
Definition at line 179 of file Sensor.h.
Referenced by PPSensor::calcAllGradients(), isModified(), setModified(), and unsetModified().
dword Sensor::updateMask protected
bitflag to mask unimportant updates
Definition at line 180 of file Sensor.h.
Referenced by performUpdate(), and ZeroSensor::ZeroSensor().
The documentation for this class was generated from the following files:
src/Sensor.h
src/Sensor.cpp