Structural deformable models: IntensitySensor Class Reference
IntensitySensor Class Reference
#include <SensorSet.h>
Public Member Functions
IntensitySensor (const Sensor *_source=NULL)
std::ostream & print (std::ostream &os) const
Public Member Functions inherited from Sensor
Sensor (const Sensor *_source=NULL)
virtual ~Sensor ()
const Sensor * getSource ()
virtual void changeSource (const Sensor *_source)
void replaceBy (Sensor *target)
bool assignRef (const Sensor *rhs)
virtual Sensor & assign (const Sensor &rhs)
virtual float getValue (int x, int y) const
get value at discrete position
float getValue (const Point &p) const
get value at position p using nearest neighbour interpolation
virtual std::vector< float > getMValue (int x, int y) const
get multi-channel value
virtual Point2D getGradient (int x, int y) const
get gradient at discrete position
Point2D getGradient (const Point2D &p) const
get gradient at position p using nearest neighbor interpolation
float getMax () const
float getMin () const
float getMinMaxRange () const
float getWeightedValue (int x, int y) const
get max normalized value at discrete position range [0,1]
Point2D getWeightedGradient (int x, int y) const
get range weighted gradient at discrete position
void setCWeights (const std::vector< float > &weights)
const std::vector< float > & getCWeights () const
void setDirection (const Point &dir)
const Point & getDirection () const
void setScale (float _scale)
float getScale () const
bool isModified (dword mask=UPD_ALL) const
void setModified (dword mask=UPD_ALL)
void unsetModified (dword mask=UPD_ALL)
bool isUpdate (dword udMask) const
void enableUpdate (dword udMask)
void disableUpdate (dword udMask)
virtual bool performUpdate ()
virtual int getDim1Size () const
virtual int getDim2Size () const
virtual int getDim3Size () const
virtual int getNChannels () const
virtual int getSkip () const
bool isValid (int x, int y) const
virtual Image< float > createSensorImage () const
const std::string & getID () const
void setID (const std::string &id)
virtual std::ostream & hprint (std::ostream &os, SensorCollection *sc) const
void refSuperSensor (Sensor *super)
void unrefSuperSensor (Sensor *super)
void invalidateSource ()
Protected Member Functions
float calcValue (int x, int y) const
Protected Member Functions inherited from Sensor
virtual std::vector< float > calcMValue (int x, int y) const
virtual Point calcGradient (int x, int y) const
virtual void calcMinMax ()
Additional Inherited Members
Public Types inherited from Sensor
enum UpdateParam {
UPD_NOTHING =0, UPD_DATA =1, UPD_SCALE =2, UPD_CWEIGHTS =4,
UPD_DIR =8, UPD_MINMAX =16, UPD_LAST =32, UPD_ALL =0xffffffff
}
Static Public Member Functions inherited from Sensor
static dword getStringNumber (const char *sid)
static void getNumberString (char sid[5], dword id)
Protected Attributes inherited from Sensor
const Sensor * source
float scale
std::vector< float > cweights
multi-channel weights ('color')
Point dir
direction parameter
float maxval
float minval
overall minimum and maximum
float mean
float stdev
overall mean and stdev
dword toupdate
bitflag for updates
dword updateMask
bitflag to mask unimportant updates
std::string m_ID
int m_Skip
int m_AddSkip
Detailed Description
Intensity sensor (identity operator)
Definition at line 14 of file SensorSet.h.
Constructor & Destructor Documentation
IntensitySensor::IntensitySensor (const Sensor * _source = NULL) inline
Definition at line 16 of file SensorSet.h.
 : Sensor(_source) {};
Member Function Documentation
float IntensitySensor::calcValue (int x, int y) const inline protected virtual
Returns the Intensity
Implements Sensor.
Definition at line 23 of file SensorSet.h.
References Sensor::getValue(), and Sensor::source.
{
     return source->getValue(x,y);
     }
std::ostream& IntensitySensor::print (std::ostream & os) const inline virtual
Reimplemented from Sensor.
Definition at line 17 of file SensorSet.h.
References Sensor::print().
Referenced by MappingSensor::getNChannels(), and CombiSensor::getSkip().
{
         Sensor::print(os) << "i";
         return os;
     }
The documentation for this class was generated from the following file:
src/SensorSet.h