Structural deformable models: Fourier2D Class Reference
Fourier2D Class Reference
#include <Fourier.h>
Public Member Functions
Fourier2D ()
~Fourier2D ()
void initTransform (int xsize, int ysize, double *f, double *F)
void destroyTransform ()
void transform ()
void transformInv ()
int complexX () const
int complexY () const
int realX () const
int realY () const
Static Public Member Functions
static int complexX (int sizex)
Protected Member Functions
void loadWisdom ()
void saveWisdom ()
Protected Attributes
fftw_plan m_Plan2D
fftw_plan m_Plan2Dinv
bool m_PlansCreated
int m_SizeX
int m_SizeY
Static Protected Attributes
static bool s_WisdomLoaded = false
static bool s_WisdomModified = false
Detailed Description
Definition at line 6 of file Fourier.h.
Constructor & Destructor Documentation
Fourier2D::Fourier2D ()
Definition at line 16 of file Fourier.cpp.
References loadWisdom().
                      : m_PlansCreated(false) {
     loadWisdom();
 }
Fourier2D::~Fourier2D ()
Definition at line 19 of file Fourier.cpp.
References destroyTransform(), and saveWisdom().
                       {
     destroyTransform();
     saveWisdom();
 }
Member Function Documentation
static int Fourier2D::complexX (int sizex) inline static
Definition at line 14 of file Fourier.h.
 { return (sizex/2+1)*2; }
int Fourier2D::complexX () const inline
Definition at line 15 of file Fourier.h.
References complexX(), and m_SizeX.
Referenced by complexX(), SmoothIntensitySensor::performUpdate(), and SmoothIntensitySensor::updateScale().
 { return complexX(m_SizeX); }
int Fourier2D::complexY () const inline
Definition at line 16 of file Fourier.h.
References m_SizeY.
 { return m_SizeY; }
void Fourier2D::destroyTransform ()
Definition at line 73 of file Fourier.cpp.
References m_Plan2D, m_Plan2Dinv, m_PlansCreated, m_SizeX, and m_SizeY.
Referenced by initTransform(), and ~Fourier2D().
{
     if(m_PlansCreated) {
         fftw_destroy_plan(m_Plan2D);
         fftw_destroy_plan(m_Plan2Dinv);
         m_SizeX = m_SizeY = 0;
         m_PlansCreated = false;
     }
 }
void Fourier2D::initTransform (int xsize, int ysize, double * f, double * F)
Definition at line 53 of file Fourier.cpp.
References destroyTransform(), F2D_PLANQUAL, m_Plan2D, m_Plan2Dinv, m_PlansCreated, m_SizeX, m_SizeY, and s_WisdomModified.
{
     if(m_PlansCreated) destroyTransform();
 #ifdef F2D_REAL_TRANSFORM
     m_Plan2D    = fftw_plan_dft_r2c_2d(ysize, xsize, f, (fftw_complex*)F,
                                        F2D_PLANQUAL);
     m_Plan2Dinv = fftw_plan_dft_c2r_2d(ysize, xsize, (fftw_complex*)F, f,
                                        FFTW_ESTIMATE);
 #else
     m_Plan2D    = fftw_plan_dft_2d(ysize, xsize,
                                    (fftw_complex*)f, (fftw_complex*)F,
                                    FFTW_FORWARD, FFTW_ESTIMATE);
     m_Plan2Dinv = fftw_plan_dft_2d(ysize, xsize,
                                    (fftw_complex*)f, (fftw_complex*)F,
                                    FFTW_BACKWARD, FFTW_ESTIMATE);
 #endif
     m_SizeX = xsize; m_SizeY = ysize;
     m_PlansCreated = true;
     s_WisdomModified = true;
 }
void Fourier2D::loadWisdom () protected
Definition at line 33 of file Fourier.cpp.
References s_WisdomLoaded, and WISDOM.
Referenced by Fourier2D(), and realY().
{
     if(!s_WisdomLoaded) {
         FILE* wisdom_file = fopen(WISDOM, "a+");
         rewind(wisdom_file);
         fftw_import_wisdom_from_file(wisdom_file);
         fclose(wisdom_file);
         s_WisdomLoaded = true;
     }
 }
int Fourier2D::realX () const inline
Definition at line 17 of file Fourier.h.
References m_SizeX.
 { return m_SizeX; }
int Fourier2D::realY () const inline
Definition at line 18 of file Fourier.h.
References loadWisdom(), m_SizeY, and saveWisdom().
 { return m_SizeY; }
void Fourier2D::saveWisdom () protected
Definition at line 43 of file Fourier.cpp.
References s_WisdomLoaded, s_WisdomModified, and WISDOM.
Referenced by realY(), and ~Fourier2D().
{
     if(s_WisdomLoaded && s_WisdomModified) {
         FILE* wisdom_file = fopen(WISDOM, "w");
         fftw_export_wisdom_to_file(wisdom_file);
         fclose(wisdom_file);
         std::cout << "fftw plan written to file " << WISDOM << "."<<std::endl;
         s_WisdomModified = false;
     }
 }
void Fourier2D::transform ()
Definition at line 23 of file Fourier.cpp.
References m_Plan2D, and m_PlansCreated.
{
     assert(m_PlansCreated);
     fftw_execute(m_Plan2D);
 }
void Fourier2D::transformInv ()
Definition at line 28 of file Fourier.cpp.
References m_Plan2Dinv, and m_PlansCreated.
{
     assert(m_PlansCreated);
     fftw_execute(m_Plan2Dinv);
 }
Member Data Documentation
fftw_plan Fourier2D::m_Plan2D protected
Definition at line 25 of file Fourier.h.
Referenced by destroyTransform(), initTransform(), and transform().
fftw_plan Fourier2D::m_Plan2Dinv protected
Definition at line 25 of file Fourier.h.
Referenced by destroyTransform(), initTransform(), and transformInv().
bool Fourier2D::m_PlansCreated protected
Definition at line 26 of file Fourier.h.
Referenced by destroyTransform(), initTransform(), transform(), and transformInv().
int Fourier2D::m_SizeX protected
Definition at line 27 of file Fourier.h.
Referenced by complexX(), destroyTransform(), initTransform(), and realX().
int Fourier2D::m_SizeY protected
Definition at line 27 of file Fourier.h.
Referenced by complexY(), destroyTransform(), initTransform(), and realY().
bool Fourier2D::s_WisdomLoaded = false static protected
Definition at line 28 of file Fourier.h.
Referenced by loadWisdom(), and saveWisdom().
bool Fourier2D::s_WisdomModified = false static protected
Definition at line 28 of file Fourier.h.
Referenced by initTransform(), and saveWisdom().
The documentation for this class was generated from the following files:
src/Fourier.h
src/Fourier.cpp