Structural deformable models: Node Class Reference
Node Class Reference
Implements a Node used by Model and Edge.
#include <Node.h>
Public Types
enum NodeState { ST_NONE =0, ST_HIGHLIGHT =1, ST_SELECT =2 }
Public Member Functions
Node (const ParticleParam *phys=&ParticleParam::global)
Default constructor.
Node (const Node &rhs)
Assignment constructor.
Node (float _x, float _y, const ParticleParam *phys=&ParticleParam::global)
Constructor.
virtual ~Node ()
Destructor.
Node & operator= (const Node &rhs)
Assignment operator.
Node & setPos (const Point &p)
int getIndex () const
void attachSensor (const Sensor *_sensor)
void addSensorForce ()
void enableState (dword nstate)
void disableState (dword nstate=0xffffffff)
void toggleState (dword nstate)
bool hasState (dword nstate=0xffffffff) const
void draw () const
Public Member Functions inherited from Point2D
Point2D ()
Point2D (const Point2D &rhs)
Point2D (float _x, float _y)
Point2D (const float *val)
virtual ~Point2D ()
Point2D & operator= (const Point2D &rhs)
Point2D & operator= (float rhs)
Point2D & operator= (const float *rhs)
Point2D & operator+= (const Point2D &rhs)
Point2D & operator-= (const Point2D &rhs)
Point2D & operator*= (const Point2D &rhs)
Point2D & operator*= (const float f)
Point2D & operator/= (const Point2D &rhs)
Point2D & operator/= (const float f)
float operator* (const Point2D &rhs) const
const Point2D & const_times (const Point2D &rhs) const
Point2D & times (const Point2D &rhs)
float dot (const Point2D &rhs) const
float crossZ (const Point2D &rhs) const
float sinAngle (const Point2D &rhs) const
float angle (const Point2D &rhs=Point2D(1, 0)) const
float sinAngleX () const
float angleX () const
Point2D operator* (float rhs) const
Point2D operator+ (const Point2D &rhs) const
Point2D operator- (const Point2D &rhs) const
Point2D operator/ (const Point2D &rhs) const
Point2D operator/ (float rhs) const
float sum () const
returns 1-norm
float norm2 () const
returns squared 2-norm
float norm () const
returns 2-norm aka length or absolute
float normalize ()
normalizes the vector; returns old norm
bool clamp (float x0, float y0, float x1, float y1)
void glVertex () const
Issue a glVertex2f call.
const Point2D flipOrtho () const
const Point2D copyNormalized () const
const Point2D rotate (float angle) const
Public Attributes
Sensor const * sensor
std::string sensorID
float mass
Mass.
Public Attributes inherited from Point2D
float x
float y
Protected Attributes
Point v
Velocity and Force.
Point f
Point ef
extern force
int index
Index in the list (Model.nodes)
float oangle
float cangle
float nedges
std::vector< int > edges
dword state
Friends
class Model
std::ostream & operator<< (std::ostream &os, const Node &n)
output operator
Detailed Description
Implements a Node used by Model and Edge.
Definition at line 14 of file Node.h.
Member Enumeration Documentation
enum Node::NodeState
Enumerator
ST_NONE
ST_HIGHLIGHT
ST_SELECT
Definition at line 17 of file Node.h.
 { ST_NONE=0, ST_HIGHLIGHT=1, ST_SELECT=2 };
Constructor & Destructor Documentation
Node::Node (const ParticleParam * phys = &ParticleParam::global)
Default constructor.
Definition at line 7 of file Node.cpp.
Referenced by Node().
     : Point(0,0), sensor(getZeroSensor()),
       mass(phys->mass), index(-1), state(ST_NONE)
 {
 }
Node::Node (const Node & rhs) inline
Assignment constructor.
Definition at line 22 of file Node.h.
References ParticleParam::global, Node(), operator=(), and Model::phys.
 { operator=(rhs); }
Node::Node (float _x, float _y, const ParticleParam * phys = &ParticleParam::global)
Constructor.
Definition at line 14 of file Node.cpp.
     : Point(_x, _y), sensor(getZeroSensor()), mass(phys->mass),
       index(-1), state(ST_NONE)
 {
 }
virtual Node::~Node () inline virtual
Destructor.
Definition at line 26 of file Node.h.
References operator=().
 {};
Member Function Documentation
void Node::addSensorForce ()
Definition at line 62 of file Node.cpp.
References f, Sensor::getWeightedGradient(), sensor, Point2D::x, and Point2D::y.
Referenced by getIndex().
{
     if(sensor) {
         Point sf = sensor->getWeightedGradient((int)x,(int)y);
         f += sf;
     }
 }
void Node::attachSensor (const Sensor * _sensor)
Definition at line 50 of file Node.cpp.
References Sensor::getID(), PPSensor::getPPState(), PPSensor::PP_DO, PPSensor::PP_DONT, sensor, sensorID, and Sensor::UPD_MINMAX.
Referenced by getIndex(), Model::readNode(), and Brain::triggerTest().
{
     sensor = _sensor;
     sensorID = sensor->getID();
     if(!((Sensor*)sensor)->isUpdate(Sensor::UPD_MINMAX)) {
         ((Sensor*)sensor)->enableUpdate(Sensor::UPD_MINMAX);
         ((Sensor*)sensor)->setModified(Sensor::UPD_MINMAX);
     }
     const PPSensor *pps = dynamic_cast<const PPSensor*>(_sensor);
     if(pps && pps->getPPState()==PPSensor::PP_DONT)
         ((PPSensor*)pps)->togglePP(PPSensor::PP_DO);
 }
void Node::disableState (dword nstate = 0xffffffff) inline
Definition at line 40 of file Node.h.
References state.
Referenced by Model::setHLNode(), and Brain::triggerTest().
 { state &= ~nstate; }
void Node::draw () const
Definition at line 69 of file Node.cpp.
References hasState(), sensorID, sglBitmapStringOutlined(), ST_HIGHLIGHT, ST_SELECT, state, Point2D::x, and Point2D::y.
Referenced by hasState().
                       {
     if(state) {
         const int HLSIZE = 5;
         if(hasState(ST_HIGHLIGHT)) {
             glBegin(GL_QUADS); {
                 glColor4f(1,1,0,0.5);
                 glVertex2f(x-HLSIZE, y-HLSIZE);
                 glVertex2f(x-HLSIZE, y+HLSIZE);
                 glVertex2f(x+HLSIZE, y+HLSIZE);
                 glVertex2f(x+HLSIZE, y-HLSIZE);
             } glEnd();
             sglBitmapStringOutlined(sensorID.c_str(), (int)x, (int)y);
         }
         if(hasState(ST_SELECT)) {
             glBegin(GL_LINE_STRIP); {
                 glColor4f(1,0,1,1);
                 glVertex2f(x-HLSIZE, y-HLSIZE);
                 glVertex2f(x-HLSIZE, y+HLSIZE);
                 glVertex2f(x+HLSIZE, y+HLSIZE);
                 glVertex2f(x+HLSIZE, y-HLSIZE);
                 glVertex2f(x-HLSIZE, y-HLSIZE);
             } glEnd();
         }
     }
 }
void Node::enableState (dword nstate) inline
Definition at line 39 of file Node.h.
References state.
Referenced by Model::setHLNode(), and Brain::triggerTest().
 { state |= nstate; }
int Node::getIndex () const inline
Returns
the index in Model.nodes array
Definition at line 34 of file Node.h.
References addSensorForce(), attachSensor(), index, and operator<<.
Referenced by Brain::doCommand().
 { return index; }
bool Node::hasState (dword nstate = 0xffffffff) const inline
Definition at line 42 of file Node.h.
References draw(), and state.
Referenced by draw().
 { return state & nstate; }
Node & Node::operator= (const Node & rhs)
Assignment operator.
Definition at line 21 of file Node.cpp.
References edges, ef, f, index, mass, oangle, Point2D::operator=(), sensor, sensorID, state, and v.
Referenced by Node(), and ~Node().
{
     if(&rhs == this) return *this;
     Point::operator=(rhs);
     mass = rhs.mass;
     f = rhs.f;
     v = rhs.v;
     index = rhs.index;
     sensor = rhs.sensor;
     edges = rhs.edges;
     oangle = rhs.oangle;
     sensorID = rhs.sensorID;
     ef = 0.f;
     state = rhs.state;
     return *this;
 }
Node& Node::setPos (const Point & p) inline
Definition at line 29 of file Node.h.
References Point2D::operator=().
Referenced by Brain::triggerTest().
{
         Point::operator=(p);
         return *this;
     }
void Node::toggleState (dword nstate) inline
Definition at line 41 of file Node.h.
References state.
 { state ^= nstate; }
Friends And Related Function Documentation
friend class Model friend
Definition at line 15 of file Node.h.
std::ostream& operator<< (std::ostream & os, const Node & n) friend
output operator
Definition at line 38 of file Node.cpp.
Referenced by getIndex(), and operator<<().
{
     os << "v ";
     operator<<(os, Point(n));
     if(n.sensor) {
         os << " s " << n.sensor->getID();
     }
     if(n.mass != ParticleParam::global.mass)
         os << " m " << n.mass;
     os << endl;
     return os;
 }
Member Data Documentation
float Node::cangle protected
Definition at line 59 of file Node.h.
std::vector<int> Node::edges protected
Definition at line 61 of file Node.h.
Referenced by Model::getNodeAngle(), and operator=().
Point Node::ef protected
extern force
Definition at line 55 of file Node.h.
Referenced by operator=().
Point Node::f protected
Definition at line 53 of file Node.h.
Referenced by addSensorForce(), Model::addTorque(), and operator=().
int Node::index protected
Index in the list (Model.nodes)
Definition at line 57 of file Node.h.
Referenced by Model::addNode(), getIndex(), and operator=().
float Node::mass
Mass.
Definition at line 49 of file Node.h.
Referenced by operator<<(), operator=(), and Model::readNode().
float Node::nedges protected
Definition at line 60 of file Node.h.
float Node::oangle protected
Definition at line 58 of file Node.h.
Referenced by operator=().
Sensor const* Node::sensor
Definition at line 44 of file Node.h.
Referenced by addSensorForce(), attachSensor(), Edge::getSensorValue(), operator<<(), and operator=().
std::string Node::sensorID
Definition at line 45 of file Node.h.
Referenced by attachSensor(), draw(), and operator=().
dword Node::state protected
Definition at line 62 of file Node.h.
Referenced by disableState(), draw(), enableState(), hasState(), operator=(), and toggleState().
Point Node::v protected
Velocity and Force.
Definition at line 53 of file Node.h.
Referenced by operator=().
The documentation for this class was generated from the following files:
src/Node.h
src/Node.cpp