Structural deformable models: CornerSensor Class Reference
CornerSensor Class Reference
#include <SensorSet.h>
Public Member Functions
CornerSensor ()
bool performUpdate ()
std::ostream & print (std::ostream &os) const
Public Member Functions inherited from PPSensor
PPSensor ()
virtual float getValue (int x, int y) const
virtual Point getGradient (int x, int y) const
Sensor & assign (const Sensor &rhs)
void togglePP (enum PPState state=PP_DO)
dword getPPState () const
Public Member Functions inherited from Sensor
virtual ~Sensor ()
sensor_cptr getSource ()
virtual void changeSource (sensor_cptr _source)
void replaceBy (sensor_ptr target)
bool assignRef (sensor_cptr rhs)
float getValue (const Point &p) const
get value at position p using nearest neighbour interpolation
virtual std::vector< float > getMValue (int x, int y) const
get multi-channel value
Point2D getGradient (const Point2D &p) const
get gradient at position p using nearest neighbor interpolation
float getMax () const
float getMin () const
float getMinMaxRange () const
float getWeightedValue (int x, int y) const
get max normalized value at discrete position range [0,1]
Point2D getWeightedGradient (int x, int y) const
get range weighted gradient at discrete position
void setCWeights (const std::vector< float > &weights)
const std::vector< float > & getCWeights () const
void setDirection (const Point &dir)
const Point & getDirection () const
void setScale (float _scale)
float getScale () const
bool isModified (dword mask=UPD_ALL) const
void setModified (dword mask=UPD_ALL)
void unsetModified (dword mask=UPD_ALL)
bool isUpdate (dword udMask) const
void enableUpdate (dword udMask)
void disableUpdate (dword udMask)
virtual int getDim1Size () const
virtual int getDim2Size () const
virtual int getDim3Size () const
virtual int getNChannels () const
virtual int getSkip () const
bool isValid (int x, int y) const
virtual Image< float > createSensorImage () const
const std::string & getID () const
void setID (const std::string &id)
virtual std::ostream & hprint (std::ostream &os, SensorCollection *sc) const
void refSuperSensor (sensor_ptr super)
void unrefSuperSensor (sensor_ptr super)
void invalidateSource ()
template<typename Derived >
std::shared_ptr< Derived > shared_from_base ()
Protected Member Functions
float calcValue (int x, int y) const
Protected Member Functions inherited from PPSensor
void fitSheets ()
virtual void calcAllValues ()
virtual void calcAllGradients ()
Protected Member Functions inherited from Sensor
Sensor (dword updateMask)
Sensor ()
virtual std::vector< float > calcMValue (int x, int y) const
virtual Point calcGradient (int x, int y) const
virtual void calcMinMax ()
Additional Inherited Members
Public Types inherited from PPSensor
enum PPState { PP_DONT =0, PP_DO, PP_FORCE }
Public Types inherited from Sensor
enum UpdateParam {
UPD_NOTHING =0, UPD_DATA =1, UPD_SCALE =2, UPD_CWEIGHTS =4,
UPD_DIR =8, UPD_MINMAX =16, UPD_LAST =32, UPD_ALL =0xffffffff
}
Static Public Member Functions inherited from Sensor
static dword getStringNumber (const char *sid)
static void getNumberString (char sid[5], dword id)
Protected Attributes inherited from PPSensor
Image< float > values
caching sheet for sensed values
Image< Point > gradients
caching sheet for gradients
dword doPP
do preprocessing?
Protected Attributes inherited from Sensor
sensor_cptr source
float scale
std::vector< float > cweights
multi-channel weights ('color')
Point dir
direction parameter
float maxval
float minval
overall minimum and maximum
float mean
float stdev
overall mean and stdev
dword toupdate
bitflag for updates
dword updateMask
bitflag to mask unimportant updates
std::string m_ID
int m_Skip
int m_AddSkip
Detailed Description
curvature Sensor
Definition at line 202 of file SensorSet.h.
Constructor & Destructor Documentation
CornerSensor::CornerSensor () inline
Definition at line 204 of file SensorSet.h.
References Sensor::enableUpdate(), Sensor::m_AddSkip, PPSensor::PP_FORCE, and Sensor::UPD_DATA.
         {
             enableUpdate(UPD_DATA);
             togglePP(PPSensor::PP_FORCE);
             m_AddSkip = 3;
         };
Member Function Documentation
float CornerSensor::calcValue (int x, int y) const inline protected virtual
Compute cornerness
Implements Sensor.
Definition at line 224 of file SensorSet.h.
References Sensor::isValid(), Point2D::normalize(), Sensor::source, Point2D::x, and Point2D::y.
{
         if(!isValid(x,y)) return 0;
         float value = source->getValue(x,y);
         if(value==0) return 0;
         Point c=source->getGradient(x,y);
         Point ddx = source->getGradient(x+1,y)-c;
         Point ddy = source->getGradient(x,y+1)-c;
 //#define SS_GRADIENT_WEIGHTED_DETERMINANT
 #ifdef SS_GRADIENT_WEIGHTED_DETERMINANT
         float n1 = ddx.normalize();
         float n2 = ddy.normalize();
         float det = ddx.x*ddy.y-ddx.y*ddy.x;
         det *= min(n1,n2);
 #else
         float det = ddx.x*ddy.y-ddx.y*ddy.x;
 #endif
         if(det<0) return 0; // repelling regions are no good
         float ret=det*value;
         return ret;
 /* using eigenvalues
 //cout << det;
 //cout << ddx << endl << ddy << endl;
 float p = (ddx.x+ddy.y)/2;
 float d = sqrt(p*p-ddx.x*ddy.y+ddx.y*ddy.x);
 //cout << "p=" << p << " d=" << d<<endl;
 float e1 = p+d;
 float e2 = p-d;
 //cout << "e1="<<e1<<" e2="<<e2<<endl;
 //cout << "---------------------" << endl;
 return e1*e2;
 */
     }
bool CornerSensor::performUpdate () inline virtual
clear all data sheets
Reimplemented from PPSensor.
Definition at line 211 of file SensorSet.h.
References Sensor::isModified(), Sensor::m_AddSkip, Sensor::m_Skip, PPSensor::performUpdate(), Sensor::source, and Sensor::UPD_DATA.
{
         if(isModified(UPD_DATA)) {
             m_Skip = source->getSkip()+m_AddSkip;
         }
         return PPSensor::performUpdate();
     }
std::ostream& CornerSensor::print (std::ostream & os) const inline virtual
Reimplemented from Sensor.
Definition at line 217 of file SensorSet.h.
References Sensor::print().
{
         Sensor::print(os)
             << "c";
         return os;
     }
The documentation for this class was generated from the following file:
src/SensorSet.h