Structural deformable models: VVector< T, D > Class Template Reference
VVector< T, D > Class Template Reference
#include <VVector.h>
Public Types
typedef VVector< T, D > VT
typedef T * TPtr
typedef const T * CTPtr
typedef Traits< T > TTrait
Public Member Functions
VVector ()
VVector (const T &sval)
VVector (CTPtr pval)
VVector (const VT &rhs)
~VVector ()
TPtr begin ()
CTPtr begin () const
TPtr end ()
CTPtr end () const
const T & operator[] (unsigned int i) const
T & operator[] (unsigned int i)
bool operator== (const VT &rhs) const
bool operator< (const VT &rhs) const
bool operator> (const VT &rhs) const
bool operator<= (const VT &rhs) const
bool operator>= (const VT &rhs) const
VT & operator= (const T &rhs)
VT & operator= (CTPtr rhs)
VT & operator= (const VT &rhs)
VT & operator+= (const VT &rhs)
VT & operator-= (const VT &rhs)
VT & operator*= (const VT &rhs)
VT & operator/= (const VT &rhs)
VT & operator+= (const T &rhs)
VT & operator-= (const T &rhs)
VT & operator*= (const T &rhs)
VT & operator/= (const T &rhs)
VT operator+ (const VT &rhs) const
VT operator- (const VT &rhs) const
VT operator* (const VT &rhs) const
VT operator/ (const VT &rhs) const
VT operator+ (const T &rhs) const
VT operator- (const T &rhs) const
VT operator* (const T &rhs) const
VT operator/ (const T &rhs) const
VT & times (const VT &rhs)
T dot (const VT &rhs) const
VVector< T, 3 > cross (const VVector< T, 3 > &rhs) const
T sum () const
T prod () const
T norm2 () const
T norm () const
T normalize ()
T avg () const
T var () const
T stdev () const
VT & sqrtEach ()
T maxVal () const
T minVal () const
unsigned int majorComponent () const
VT & clampLB (const VT &lb)
VT & clampUB (const VT &ub)
VT & clamp (const VT &lb, const VT &ub)
float angle (const VT &rhs) const
Static Public Member Functions
static VT zero ()
static VT one ()
static unsigned int size ()
Public Attributes
T val [D]
Friends
std::ostream & operator<< (std::ostream &os, const VT &rhs)
std::istream & operator>> (std::istream &is, VT &rhs)
Detailed Description
template<class T, unsigned int D>
class VVector< T, D >
a small numerical vector class
Definition at line 14 of file VVector.h.
Member Typedef Documentation
template<class T, unsigned int D> typedef const T* VVector< T, D >::CTPtr
Definition at line 19 of file VVector.h.
template<class T, unsigned int D> typedef T* VVector< T, D >::TPtr
Definition at line 18 of file VVector.h.
template<class T, unsigned int D> typedef Traits<T> VVector< T, D >::TTrait
Definition at line 20 of file VVector.h.
template<class T, unsigned int D> typedef VVector<T, D> VVector< T, D >::VT
Definition at line 17 of file VVector.h.
Constructor & Destructor Documentation
template<class T, unsigned int D> VVector< T, D >::VVector () inline
Definition at line 22 of file VVector.h.
 {};
template<class T, unsigned int D> VVector< T, D >::VVector (const T & sval) inline
Definition at line 23 of file VVector.h.
{
         operator=(sval);
     }
template<class T, unsigned int D> VVector< T, D >::VVector (CTPtr pval) inline
Definition at line 26 of file VVector.h.
{
         operator=(pval);
     }
template<class T, unsigned int D> VVector< T, D >::VVector (const VT & rhs) inline
Definition at line 29 of file VVector.h.
{
         operator=(rhs);
     }
template<class T, unsigned int D> VVector< T, D >::~VVector () inline
Definition at line 32 of file VVector.h.
 {};
Member Function Documentation
template<class T, unsigned int D> float VVector< T, D >::angle (const VT & rhs) const inline
Definition at line 262 of file VVector.h.
{
         float dv = cross(rhs).norm(); //sin(a)
         float dh = dot(rhs); //cos(a)
 #ifndef _THERE_IS_NO_ATAN2_
         return atan2(dv,dh);
 #else
         float dvp,dvn;
         if(dv > 0.0) {
             dvp = 1.0;
             dvn = 0.0;
         } else {
             dvp = 0.0;
             dvn = 1.0;
         }
         float dhn = (dh < 0) ? 1.0 : 0.0;
         float psi;
         if (dh == 0.0)
             psi = M_PI_2 * (dvp + 3.0 * dvn);
         else if (dv == 0.0)
             psi = M_PI * dhn;
         else
             psi = atan(dv/dh) + M_PI * dhn * dvp
                 + (M_PI + M_PI * (dh > 0.0)) * dvn;
         return psi * (180.0*M_1_PI);
 #endif
     }
template<class T, unsigned int D> T VVector< T, D >::avg () const inline
Definition at line 212 of file VVector.h.
 { return sum()/D; }
template<class T, unsigned int D> TPtr VVector< T, D >::begin () inline
Definition at line 37 of file VVector.h.
Referenced by MStructure::buildAllStats(), VVector< float, 4 >::clamp(), VVector< float, 4 >::clampLB(), VVector< float, 4 >::clampUB(), VVector< float, 4 >::dot(), hgPropTF(), VVector< float, 4 >::operator*=(), VVector< float, 4 >::operator+=(), VVector< float, 4 >::operator-=(), VVector< float, 4 >::operator/=(), VVector< float, 4 >::operator<(), VVector< float, 4 >::operator<=(), VVector< float, 4 >::operator=(), VVector< float, 4 >::operator==(), VVector< float, 4 >::operator>(), VVector< float, 4 >::operator>=(), MStructure::showStats(), and VVector< float, 4 >::times().
 { return val; }
template<class T, unsigned int D> CTPtr VVector< T, D >::begin () const inline
Definition at line 38 of file VVector.h.
 { return val; }
template<class T, unsigned int D> VT& VVector< T, D >::clamp (const VT & lb, const VT & ub) inline
Definition at line 253 of file VVector.h.
Referenced by EMDRect::clamp(), ExpectationMap::getPropVec(), and EMDRect::ratePropVec().
{
         CTPtr sv=lb.begin();
         CTPtr uv=ub.begin();
         for(TPtr pv=begin(); pv!=end(); pv++, sv++, uv++) {
             if(*pv > *uv) *pv = *uv;
             else if(*pv < *sv) *pv = *sv;
         }
         return *this;
     }
template<class T, unsigned int D> VT& VVector< T, D >::clampLB (const VT & lb) inline
Definition at line 241 of file VVector.h.
Referenced by Searcher::cleanFlags(), and ExpectationMap::correctLBUB().
{
         CTPtr sv=lb.begin();
         for(TPtr pv=begin(); pv!=end(); pv++, sv++)
             if(*pv < *sv) *pv = *sv;
         return *this;
     }
template<class T, unsigned int D> VT& VVector< T, D >::clampUB (const VT & ub) inline
Definition at line 247 of file VVector.h.
Referenced by Searcher::cleanFlags(), and ExpectationMap::correctLBUB().
{
         CTPtr sv=ub.begin();
         for(TPtr pv=begin(); pv!=end(); pv++, sv++)
             if(*pv > *sv) *pv = *sv;
         return *this;
     }
template<class T, unsigned int D> VVector<T, 3> VVector< T, D >::cross (const VVector< T, 3 > & rhs) const inline
Definition at line 181 of file VVector.h.
{
         VVector<T, 3> r;
         r.val[0]= val[1]*rhs.val[2] - val[2]*rhs.val[1];
         r.val[1]= val[2]*rhs.val[0] - val[0]*rhs.val[2];
         r.val[2]= r.val[2] = val[0]*rhs.val[1] - val[1]*rhs.val[0];
         return r;
     }
template<class T, unsigned int D> T VVector< T, D >::dot (const VT & rhs) const inline
Definition at line 174 of file VVector.h.
{
         T r= TTrait::zero();
         for(CTPtr pv=begin(), *sv=rhs.begin(); pv!=end(); pv++, sv++)
             r += *pv * *sv;
         return r;
     }
template<class T, unsigned int D> TPtr VVector< T, D >::end () inline
Definition at line 39 of file VVector.h.
 { return &val[D]; }
template<class T, unsigned int D> CTPtr VVector< T, D >::end () const inline
Definition at line 40 of file VVector.h.
 { return &val[D]; }
template<class T, unsigned int D> unsigned int VVector< T, D >::majorComponent () const inline
Definition at line 232 of file VVector.h.
{
         T mv=TTrait::zero();
         unsigned int mc=0,cc=0;
         for(CTPtr pv=begin(); pv!=end(); pv++, cc++) {
             T apv = abs(*pv);
             if(mv < apv) { mv = apv; mc = cc; }
         }
         return mc;
     }
template<class T, unsigned int D> T VVector< T, D >::maxVal () const inline
Definition at line 220 of file VVector.h.
                      {
         T mv=val[0];
         for(CTPtr pv=begin(); pv!=end(); pv++)
             if(mv < *pv) mv = *pv;
         return mv;
     }
template<class T, unsigned int D> T VVector< T, D >::minVal () const inline
Definition at line 226 of file VVector.h.
                      {
         T mv=val[0];
         for(CTPtr pv=begin(); pv!=end(); pv++)
             if(mv > *pv) mv = *pv;
         return mv;
     }
template<class T, unsigned int D> T VVector< T, D >::norm () const inline
Definition at line 206 of file VVector.h.
 { return sqrt(norm2()); }
template<class T, unsigned int D> T VVector< T, D >::norm2 () const inline
Definition at line 200 of file VVector.h.
                     {
         T n= TTrait::zero();
         for(CTPtr pv=begin(); pv!=end(); pv++)
             n += *pv * *pv;
         return n;
     }
template<class T, unsigned int D> T VVector< T, D >::normalize () inline
Definition at line 207 of file VVector.h.
                   {
         T n = norm();
         operator*=(TTrait::one()/n);
         return n;
     }
template<class T, unsigned int D> static VT VVector< T, D >::one () inline static
Definition at line 35 of file VVector.h.
 { return VT(TTrait::one()); }
template<class T, unsigned int D> VT VVector< T, D >::operator* (const VT & rhs) const inline
Definition at line 146 of file VVector.h.
{
         VT r(*this);
         return r*=rhs;
     }
template<class T, unsigned int D> VT VVector< T, D >::operator* (const T & rhs) const inline
Definition at line 160 of file VVector.h.
{
         return (VT(*this) *= rhs);
     }
template<class T, unsigned int D> VT& VVector< T, D >::operator*= (const VT & rhs) inline
Definition at line 105 of file VVector.h.
{
         CTPtr sv=rhs.begin();
         for(TPtr pv=begin(); pv!=end(); pv++, sv++)
             *pv *= *sv;
         return *this;
     }
template<class T, unsigned int D> VT& VVector< T, D >::operator*= (const T & rhs) inline
Definition at line 127 of file VVector.h.
{
         for(TPtr pv=begin(); pv!=end(); pv++)
             *pv *= rhs;
         return *this;
     }
template<class T, unsigned int D> VT VVector< T, D >::operator+ (const VT & rhs) const inline
Definition at line 138 of file VVector.h.
{
         VT r(*this);
         return r+=rhs;
     }
template<class T, unsigned int D> VT VVector< T, D >::operator+ (const T & rhs) const inline
Definition at line 154 of file VVector.h.
{
         return (VT(*this) += rhs);
     }
template<class T, unsigned int D> VT& VVector< T, D >::operator+= (const VT & rhs) inline
Definition at line 93 of file VVector.h.
{
         CTPtr sv=rhs.begin();
         for(TPtr pv=begin(); pv!=end(); pv++, sv++)
             *pv += *sv;
         return *this;
     }
template<class T, unsigned int D> VT& VVector< T, D >::operator+= (const T & rhs) inline
Definition at line 117 of file VVector.h.
{
         for(TPtr pv=begin(); pv!=end(); pv++)
             *pv += rhs;
         return *this;
     }
template<class T, unsigned int D> VT VVector< T, D >::operator- (const VT & rhs) const inline
Definition at line 142 of file VVector.h.
{
         VT r(*this);
         return r-=rhs;
     }
template<class T, unsigned int D> VT VVector< T, D >::operator- (const T & rhs) const inline
Definition at line 157 of file VVector.h.
{
         return (VT(*this) -= rhs);
     }
template<class T, unsigned int D> VT& VVector< T, D >::operator-= (const VT & rhs) inline
Definition at line 99 of file VVector.h.
{
         CTPtr sv=rhs.begin();
         for(TPtr pv=begin(); pv!=end(); pv++, sv++)
             *pv -= *sv;
         return *this;
     }
template<class T, unsigned int D> VT& VVector< T, D >::operator-= (const T & rhs) inline
Definition at line 122 of file VVector.h.
{
         for(TPtr pv=begin(); pv!=end(); pv++)
             *pv -= rhs;
         return *this;
     }
template<class T, unsigned int D> VT VVector< T, D >::operator/ (const VT & rhs) const inline
Definition at line 150 of file VVector.h.
{
         VT r(*this);
         return r/=rhs;
     }
template<class T, unsigned int D> VT VVector< T, D >::operator/ (const T & rhs) const inline
Definition at line 163 of file VVector.h.
{
         return (VT(*this) /= rhs);
     }
template<class T, unsigned int D> VT& VVector< T, D >::operator/= (const VT & rhs) inline
Definition at line 111 of file VVector.h.
{
         CTPtr sv=rhs.begin();
         for(TPtr pv=begin(); pv!=end(); pv++, sv++)
             *pv /= *sv;
         return *this;
     }
template<class T, unsigned int D> VT& VVector< T, D >::operator/= (const T & rhs) inline
Definition at line 132 of file VVector.h.
{
         for(TPtr pv=begin(); pv!=end(); pv++)
             *pv /= rhs;
         return *this;
     }
template<class T, unsigned int D> bool VVector< T, D >::operator< (const VT & rhs) const inline
Definition at line 51 of file VVector.h.
{
         CTPtr sv=rhs.begin();
         for(CTPtr pv=begin(); pv!=end(); pv++, sv++)
             if(*pv >= *sv) return false;
         return true;
     }
template<class T, unsigned int D> bool VVector< T, D >::operator<= (const VT & rhs) const inline
Definition at line 63 of file VVector.h.
{
         CTPtr sv=rhs.begin();
         for(CTPtr pv=begin(); pv!=end(); pv++, sv++)
             if(*pv > *sv) return false;
         return true;
     }
template<class T, unsigned int D> VT& VVector< T, D >::operator= (const T & rhs) inline
Definition at line 76 of file VVector.h.
{
         for(TPtr pv=begin(); pv!=end(); pv++)
             *pv = rhs;
         return *this;
     }
template<class T, unsigned int D> VT& VVector< T, D >::operator= (CTPtr rhs) inline
Definition at line 81 of file VVector.h.
{
         for(TPtr pv=begin(); pv!=end(); pv++, rhs++)
             *pv = *rhs;
         return *this;
     }
template<class T, unsigned int D> VT& VVector< T, D >::operator= (const VT & rhs) inline
Definition at line 86 of file VVector.h.
{
         CTPtr sv=rhs.begin();
         for(TPtr pv=begin(); pv!=end(); pv++, sv++)
             *pv = *sv;
         return *this;
     }
template<class T, unsigned int D> bool VVector< T, D >::operator== (const VT & rhs) const inline
Definition at line 45 of file VVector.h.
{
         CTPtr sv=rhs.begin();
         for(CTPtr pv=begin(); pv!=end(); pv++, sv++)
             if(*pv != *sv) return false;
         return true;
     }
template<class T, unsigned int D> bool VVector< T, D >::operator> (const VT & rhs) const inline
Definition at line 57 of file VVector.h.
{
         CTPtr sv=rhs.begin();
         for(CTPtr pv=begin(); pv!=end(); pv++, sv++)
             if(*pv <= *sv) return false;
         return true;
     }
template<class T, unsigned int D> bool VVector< T, D >::operator>= (const VT & rhs) const inline
Definition at line 69 of file VVector.h.
{
         CTPtr sv=rhs.begin();
         for(CTPtr pv=begin(); pv!=end(); pv++, sv++)
             if(*pv < *sv) return false;
         return true;
     }
template<class T, unsigned int D> const T& VVector< T, D >::operator[] (unsigned int i) const inline
Definition at line 42 of file VVector.h.
 { return val[i]; }
template<class T, unsigned int D> T& VVector< T, D >::operator[] (unsigned int i) inline
Definition at line 43 of file VVector.h.
 { return val[i]; }
template<class T, unsigned int D> T VVector< T, D >::prod () const inline
Definition at line 194 of file VVector.h.
                    {
         T n= TTrait::one();
         for(CTPtr pv=begin(); pv!=end(); pv++)
             n *= *pv;
         return n;
     }
template<class T, unsigned int D> static unsigned int VVector< T, D >::size () inline static
Definition at line 41 of file VVector.h.
Referenced by SubStructure::analyseTF(), MStructure::buildAllStats(), EMDRect::getPropVec(), EMDGauss::getPropVec(), hgPropTF(), EMDGauss::setStdev(), EMDXformer::setTFMat(), and MStructure::showStats().
 { return D; }
template<class T, unsigned int D> VT& VVector< T, D >::sqrtEach () inline
Definition at line 215 of file VVector.h.
Referenced by Searcher::cleanFlags().
                    {
         for(TPtr pv=begin(); pv!=end(); pv++)
             *pv = sqrt(*pv);
         return *this;
     }
template<class T, unsigned int D> T VVector< T, D >::stdev () const inline
Definition at line 214 of file VVector.h.
 { return sqrt(var()); }
template<class T, unsigned int D> T VVector< T, D >::sum () const inline
Definition at line 188 of file VVector.h.
                   { //norm1
         T n= TTrait::zero();
         for(CTPtr pv=begin(); pv!=end(); pv++)
             n += *pv;
         return n;
     }
template<class T, unsigned int D> VT& VVector< T, D >::times (const VT & rhs) inline
Definition at line 167 of file VVector.h.
{
         CTPtr sv=rhs.begin();
         for(TPtr pv=begin(); pv!=end(); pv++, sv++)
             *pv *= *sv;
         return *this;
     }
template<class T, unsigned int D> T VVector< T, D >::var () const inline
Definition at line 213 of file VVector.h.
 { return (*this-avg()).norm2(); }
template<class T, unsigned int D> static VT VVector< T, D >::zero () inline static
Definition at line 34 of file VVector.h.
 { return VT(TTrait::zero()); }
Friends And Related Function Documentation
template<class T, unsigned int D> std::ostream& operator<< (std::ostream & os, const VT & rhs) friend
Definition at line 289 of file VVector.h.
{
         for(CTPtr pv= rhs.begin(); pv != rhs.end(); pv++) {
             //if(pv != rhs.begin()) os << " ";
             os << *pv << " ";
         }
         return os;
     }
template<class T, unsigned int D> std::istream& operator>> (std::istream & is, VT & rhs) friend
Definition at line 296 of file VVector.h.
{
         for(TPtr pv=rhs.begin(); pv!=rhs.end(); pv++) {
             is >> *pv;
         }
         return is;
     }
Member Data Documentation
template<class T, unsigned int D> T VVector< T, D >::val[D]
Definition at line 304 of file VVector.h.
Referenced by VVector< float, 4 >::cross().
The documentation for this class was generated from the following file:
src/VVector.h