Structural deformable models: Edge Class Reference
Edge Class Reference
Implements an Edge with spring functionality.
#include <Edge.h>
Public Member Functions
Edge (const Edge &rhs)
Edge (int _from, int _to, std::vector< Node > &_nodes, const ParticleParam *phys=&ParticleParam::global, int _index=-1)
Edge (int _from, int _to, std::vector< Node > &_nodes, float restlength, float spring_k=1, int _index=-1)
virtual ~Edge ()
void setNodesList (std::vector< Node > &nodes)
Edge & operator= (const Edge &rhs)
const Point dir () const
const Point idir () const
float length2 () const
float length () const
float lengthRatio () const
float adaptRestLength ()
float adaptRestLength (float ratio)
float getAngle () const
float adaptAngle ()
Node & fromNode ()
Node & toNode ()
const Node & fromNode () const
const Node & toNode () const
dword getSensorValue (float &sum, dword &nsamples) const
Public Attributes
int from
int to
float xangle
float cxangle
std::vector< Node > * nodes
float restlength
float springconstant
spring constant
float dampingconstant
damping constant
int edgesensor
0-none, >0-use from sensor n times, <0 use to sensor
Protected Attributes
int index
index in the model (Model.edges)
Friends
class Model
std::ostream & operator<< (std::ostream &os, const Edge &p)
Detailed Description
Implements an Edge with spring functionality.
Definition at line 14 of file Edge.h.
Constructor & Destructor Documentation
Edge::Edge (const Edge & rhs) inline
Definition at line 25 of file Edge.h.
References operator=().
     {
         operator=(rhs);
     }
Edge::Edge (int _from, int _to, std::vector< Node > & _nodes, const ParticleParam * phys = &ParticleParam::global, int _index = -1) inline
Definition at line 29 of file Edge.h.
References adaptRestLength(), ParticleParam::damping, dampingconstant, edgesensor, from, index, nodes, Model::phys, ParticleParam::springconst, springconstant, and to.
     {
         from = _from;
         to = _to;
         nodes = &_nodes;
         adaptRestLength();
         springconstant = phys->springconst;
         dampingconstant = phys->damping;
         edgesensor = 0;
         index = _index;
     }
Edge::Edge (int _from, int _to, std::vector< Node > & _nodes, float restlength, float spring_k = 1, int _index = -1) inline
Definition at line 42 of file Edge.h.
References edgesensor, from, index, nodes, restlength, springconstant, and to.
     {
         from = _from;
         to = _to;
         nodes = &_nodes;
         this->restlength = restlength;
         this->springconstant = spring_k;
         edgesensor = 0;
         this->index = _index;
     }
virtual Edge::~Edge () inline virtual
Definition at line 54 of file Edge.h.
 {}
Member Function Documentation
float Edge::adaptAngle () inline
Definition at line 105 of file Edge.h.
References getAngle(), and xangle.
{
         return xangle = getAngle();
     }
float Edge::adaptRestLength () inline
Definition at line 95 of file Edge.h.
References length(), and restlength.
Referenced by Edge(), and Brain::triggerTest().
{
         return restlength = length();
     }
float Edge::adaptRestLength (float ratio) inline
Definition at line 99 of file Edge.h.
References length(), and restlength.
{
         return restlength -= (restlength-length())*ratio;
     }
const Point Edge::dir () const inline
Definition at line 73 of file Edge.h.
References from, fromNode(), to, and toNode().
Referenced by getAngle(), and length2().
{
         if(from==-1 || to==-1) return Point();
         return toNode()-fromNode();
     }
Node& Edge::fromNode () inline
Definition at line 121 of file Edge.h.
References from, and nodes.
Referenced by Model::addTorque(), dir(), getSensorValue(), and idir().
 { return (*nodes)[from]; }
const Node& Edge::fromNode () const inline
Definition at line 123 of file Edge.h.
References from, and nodes.
 { return (*nodes)[from]; }
float Edge::getAngle () const inline
Definition at line 102 of file Edge.h.
References Point2D::angleX(), and dir().
Referenced by adaptAngle().
{
         return dir().angleX();
     }
dword Edge::getSensorValue (float & sum, dword & nsamples) const inline
Definition at line 144 of file Edge.h.
References edgesensor, from, fromNode(), Node::sensor, to, and toNode().
Referenced by toNode().
 {
     if(!edgesensor) return 0;
     const Node& from = fromNode();
     const Node& to = toNode();
     sensor_cptr sensor = (edgesensor > 0) ? from.sensor : to.sensor;
     if(!sensor) return 0;
     dword ntimes = edgesensor > 0 ? dword(edgesensor) : dword(-edgesensor);
     Point x(from);
     Point xinc(to); xinc -= from; xinc /= float(ntimes+1);
     x += xinc;
     for(dword i=0; i<ntimes; i++, x+=xinc) {
         sum += sensor->getWeightedValue((int)x.x, (int)x.y);
     }
     nsamples += ntimes;
     return ntimes;
 }
const Point Edge::idir () const inline
Definition at line 77 of file Edge.h.
References from, fromNode(), to, and toNode().
{
         if(from==-1 || to==-1) return Point();
         return fromNode()-toNode();
     }
float Edge::length () const inline
Definition at line 87 of file Edge.h.
References length2(), and dmutil::sqrt().
Referenced by adaptRestLength(), and lengthRatio().
{
         return (float)sqrt(length2());
     }
float Edge::length2 () const inline
Definition at line 82 of file Edge.h.
References dir(), from, Point2D::norm2(), and to.
Referenced by length().
{
         if(from==-1 || to==-1) return 0;
         return dir().norm2();
     }
float Edge::lengthRatio () const inline
Definition at line 91 of file Edge.h.
References length(), and restlength.
Referenced by MStructure::buildMasterModel().
{
         return length()/restlength;
     }
Edge& Edge::operator= (const Edge & rhs) inline
Definition at line 60 of file Edge.h.
References dampingconstant, edgesensor, from, index, nodes, restlength, springconstant, and to.
Referenced by Edge().
{
         if(&rhs == this) return *this;
         from = rhs.from;
         to = rhs.to;
         nodes = rhs.nodes;
         restlength = rhs.restlength;
         springconstant = rhs.springconstant;
         dampingconstant = rhs.dampingconstant;
         edgesensor = rhs.edgesensor;
         index = rhs.index;
         return *this;
     }
void Edge::setNodesList (std::vector< Node > & nodes) inline
Definition at line 56 of file Edge.h.
References nodes.
{
         this->nodes = &nodes;
     }
Node& Edge::toNode () inline
Definition at line 122 of file Edge.h.
References nodes, and to.
Referenced by Model::addTorque(), dir(), getSensorValue(), and idir().
 { return (*nodes)[to]; }
const Node& Edge::toNode () const inline
Definition at line 124 of file Edge.h.
References getSensorValue(), nodes, dmutil::sum(), and to.
 { return (*nodes)[to]; }
Friends And Related Function Documentation
friend class Model friend
Definition at line 15 of file Edge.h.
std::ostream& operator<< (std::ostream & os, const Edge & p) friend
Definition at line 108 of file Edge.h.
{
         os << "e " << p.from+1 << " " << p.to+1;
         if(p.springconstant != ParticleParam::global.springconst)
             os << " sc " << p.springconstant;
         if(p.dampingconstant != ParticleParam::global.damping)
             os << " dc " << p.dampingconstant;
         if(p.length() != p.restlength) os << " rl " << p.restlength;
         if(p.edgesensor>0) os << " es f " << p.edgesensor;
         if(p.edgesensor<0) os << " es t " << -p.edgesensor;
         os << std::endl;
         return os;
     }
Member Data Documentation
float Edge::cxangle
Definition at line 130 of file Edge.h.
float Edge::dampingconstant
damping constant
Definition at line 136 of file Edge.h.
Referenced by Edge(), operator=(), and Model::readEdge().
int Edge::edgesensor
0-none, >0-use from sensor n times, <0 use to sensor
Definition at line 137 of file Edge.h.
Referenced by Edge(), getSensorValue(), operator=(), and Model::readEdge().
int Edge::from
Definition at line 128 of file Edge.h.
Referenced by dir(), Edge(), fromNode(), getSensorValue(), idir(), length2(), operator=(), and Brain::triggerTest().
int Edge::index protected
index in the model (Model.edges)
Definition at line 141 of file Edge.h.
Referenced by Edge(), and operator=().
std::vector<Node>* Edge::nodes
Definition at line 131 of file Edge.h.
Referenced by Edge(), fromNode(), operator=(), setNodesList(), and toNode().
float Edge::restlength
Definition at line 132 of file Edge.h.
Referenced by adaptRestLength(), MStructure::buildMasterModel(), Edge(), lengthRatio(), operator=(), Model::readEdge(), and Brain::triggerTest().
float Edge::springconstant
spring constant
Definition at line 134 of file Edge.h.
Referenced by MStructure::buildMasterModel(), Edge(), operator=(), Model::readEdge(), and Brain::triggerTest().
int Edge::to
Definition at line 128 of file Edge.h.
Referenced by dir(), Edge(), getSensorValue(), idir(), length2(), operator=(), toNode(), and Brain::triggerTest().
float Edge::xangle
Definition at line 129 of file Edge.h.
Referenced by adaptAngle().
The documentation for this class was generated from the following file:
src/Edge.h