Structural deformable models: EMDistribution Class Reference
EMDistribution Class Reference
#include <ExpMap.h>
Public Types
enum EDFlags { ED_NONE =0, ED_OLD =1 }
Public Member Functions
EMDistribution ()
virtual ~EMDistribution ()
virtual PropVec getPropVec () const
virtual void setIntegral (float integral)
virtual EMDistribution * copy () const
virtual float ratePropVec (const PropVec &prop, Winner *winner=NULL) const
void setCreator (const Winner &creator)
void setShootCount (dword scount)
dword getShootCount () const
bool hasFlags (dword flags) const
void setFlags (dword flags)
void unsetFlags (dword flags=0xffffffff)
Public Attributes
float m_Integral
Winner m_Creator
dword m_ShootCount
dword m_Flags
Detailed Description
Definition at line 44 of file ExpMap.h.
Member Enumeration Documentation
enum EMDistribution::EDFlags
Enumerator
ED_NONE
ED_OLD
Definition at line 46 of file ExpMap.h.
 { ED_NONE=0, ED_OLD=1 };
Constructor & Destructor Documentation
EMDistribution::EMDistribution () inline
Definition at line 47 of file ExpMap.h.
 : m_Integral(1.f), m_ShootCount(0), m_Flags(ED_NONE) {};
virtual EMDistribution::~EMDistribution () inline virtual
Definition at line 48 of file ExpMap.h.
 {}
Member Function Documentation
virtual EMDistribution* EMDistribution::copy () const inline virtual
Reimplemented in ExpectationMap, EMDXformer, EMDGauss, and EMDRect.
Definition at line 53 of file ExpMap.h.
Referenced by EMDXformer::copy().
{
         return new EMDistribution(*this);
     }
virtual PropVec EMDistribution::getPropVec () const inline virtual
Reimplemented in ExpectationMap, EMDXformer, EMDGauss, and EMDRect.
Definition at line 49 of file ExpMap.h.
         { return PropVec(0.); }
dword EMDistribution::getShootCount () const inline
Definition at line 62 of file ExpMap.h.
Referenced by MStructure::addExpectation(), and ExpectationMap::getShootCount().
 { return m_ShootCount; }
bool EMDistribution::hasFlags (dword flags) const inline
Definition at line 63 of file ExpMap.h.
 { return m_Flags&flags; }
virtual float EMDistribution::ratePropVec (const PropVec & prop, Winner * winner = NULL) const inline virtual
Reimplemented in ExpectationMap, EMDXformer, EMDGauss, and EMDRect.
Definition at line 56 of file ExpMap.h.
Referenced by MStructure::showStats().
         { return 0; }
void EMDistribution::setCreator (const Winner & creator) inline
Definition at line 58 of file ExpMap.h.
Referenced by MStructure::addExpectation().
{
         m_Creator = creator;
     }
void EMDistribution::setFlags (dword flags) inline
Definition at line 64 of file ExpMap.h.
 { m_Flags |= flags; }
virtual void EMDistribution::setIntegral (float integral) inline virtual
Definition at line 51 of file ExpMap.h.
Referenced by MStructure::addExpectation().
         { m_Integral = integral; }
void EMDistribution::setShootCount (dword scount) inline
Definition at line 61 of file ExpMap.h.
Referenced by MStructure::addExpectation().
 { m_ShootCount = scount; }
void EMDistribution::unsetFlags (dword flags = 0xffffffff) inline
Definition at line 65 of file ExpMap.h.
 { m_Flags &= ~flags; }
Member Data Documentation
Winner EMDistribution::m_Creator
Definition at line 68 of file ExpMap.h.
Referenced by ExpectationMap::add().
dword EMDistribution::m_Flags
Definition at line 70 of file ExpMap.h.
float EMDistribution::m_Integral
Definition at line 67 of file ExpMap.h.
Referenced by Searcher::evolve(), ExpectationMap::getPropVec(), MStructure::rebuildExpMap(), Searcher::triggerTest(), and ExpectationMap::updateIntegral().
dword EMDistribution::m_ShootCount
Definition at line 69 of file ExpMap.h.
The documentation for this class was generated from the following file:
src/ExpMap.h