Structural deformable models: EMDXformer Class Reference
EMDXformer Class Reference
#include <ExpMap.h>
Public Member Functions
EMDXformer (EMDistribution *input, const PropVec &origin=getIdentityPropTF(), const DMatrixf &tfmat=DMatrixf())
virtual ~EMDXformer ()
virtual EMDistribution * copy () const
PropVec getPropVec () const
float ratePropVec (const PropVec &prop, Winner *winner=NULL) const
void setTFMat (const DMatrixf &mat)
void setMean (const PropVec &mean)
void setStdev (const PropVec &stdev)
Public Member Functions inherited from EMDistribution
EMDistribution ()
virtual ~EMDistribution ()
virtual void setIntegral (float integral)
void setCreator (const Winner &creator)
void setShootCount (dword scount)
dword getShootCount () const
bool hasFlags (dword flags) const
void setFlags (dword flags)
void unsetFlags (dword flags=0xffffffff)
Protected Attributes
EMDistribution * m_InputEMD
DMatrixf m_TFMat
DMatrixf m_ITFMat
PropVec m_Origin
PropVec m_Mean
PropVec m_Stdev
Additional Inherited Members
Public Types inherited from EMDistribution
enum EDFlags { ED_NONE =0, ED_OLD =1 }
Public Attributes inherited from EMDistribution
float m_Integral
Winner m_Creator
dword m_ShootCount
dword m_Flags
Detailed Description
Definition at line 109 of file ExpMap.h.
Constructor & Destructor Documentation
EMDXformer::EMDXformer (EMDistribution * input, const PropVec & origin = getIdentityPropTF(), const DMatrixf & tfmat = DMatrixf()) inline
Definition at line 111 of file ExpMap.h.
References NULL.
         : m_InputEMD(input), m_Origin(origin), m_Mean(0.f), m_Stdev(1.f) {
         assert(input != NULL);
         setTFMat(tfmat);
     }
virtual EMDXformer::~EMDXformer () inline virtual
Definition at line 123 of file ExpMap.h.
References NULL.
{
         delete m_InputEMD; m_InputEMD = NULL;
     }
Member Function Documentation
virtual EMDistribution* EMDXformer::copy () const inline virtual
Reimplemented from EMDistribution.
Definition at line 126 of file ExpMap.h.
References EMDistribution::copy(), m_InputEMD, and NULL.
{
         EMDXformer* cpy = new EMDXformer(*this);
         cpy->m_InputEMD = m_InputEMD->copy();
         return (EMDistribution*) cpy;
     }
PropVec EMDXformer::getPropVec () const virtual
Reimplemented from EMDistribution.
Definition at line 245 of file ExpMap.cpp.
References fwdPropTF(), and hgPropTF().
 {
     PropVec propPV = m_InputEMD->getPropVec();
     hgPropTF(m_TFMat, propPV);
     propPV *= m_Stdev;
     propPV += m_Mean;
     PropVec pv(m_Origin);
     fwdPropTF(pv, propPV);
     return pv;
 }
float EMDXformer::ratePropVec (const PropVec & prop, Winner * winner = NULL) const virtual
Reimplemented from EMDistribution.
Definition at line 256 of file ExpMap.cpp.
References getPropDir(), getPropTF(), hgPropTF(), mapAnglePI(), and setPropDir().
 {
 //inverse transform
     PropVec tfprop(getPropTF(m_Origin, prop));
     tfprop -= m_Mean;
     setPropDir(tfprop, mapAnglePI(getPropDir(tfprop)));
     tfprop /= m_Stdev;
     hgPropTF(m_ITFMat, tfprop);
     return m_InputEMD->ratePropVec(tfprop);
 }
void EMDXformer::setMean (const PropVec & mean) inline
Definition at line 134 of file ExpMap.h.
Referenced by SubStructure::generateEMDist().
 { m_Mean = mean; }
void EMDXformer::setStdev (const PropVec & stdev) inline
Definition at line 135 of file ExpMap.h.
References dmutil::stdev().
 { m_Stdev = stdev; }
void EMDXformer::setTFMat (const DMatrixf & mat)
Definition at line 267 of file ExpMap.cpp.
References dmutil::inverse(), VVector< T, D >::size(), DMatrix< T >::sizeX(), and DMatrix< T >::sizeY().
 {
     if(mat.sizeX() == mat.sizeY() &&
        (mat.sizeX() == PropVec::size() ||
         mat.sizeX() == PropVec::size()+1)) {
         m_TFMat = mat;
         m_ITFMat = dmutil::inverse(m_TFMat);
     } else {
         m_TFMat.clear();
         m_ITFMat.clear();
     }
 }
Member Data Documentation
EMDistribution* EMDXformer::m_InputEMD protected
Definition at line 137 of file ExpMap.h.
Referenced by copy().
DMatrixf EMDXformer::m_ITFMat protected
Definition at line 138 of file ExpMap.h.
PropVec EMDXformer::m_Mean protected
Definition at line 139 of file ExpMap.h.
PropVec EMDXformer::m_Origin protected
Definition at line 139 of file ExpMap.h.
PropVec EMDXformer::m_Stdev protected
Definition at line 139 of file ExpMap.h.
DMatrixf EMDXformer::m_TFMat protected
Definition at line 138 of file ExpMap.h.
The documentation for this class was generated from the following files:
src/ExpMap.h
src/ExpMap.cpp