Structural deformable models: vuThread Class Reference
vuThread Class Reference abstract
#include <vuThread.h>
Public Member Functions
virtual ~vuThread ()
Virtual destructor (doing nothing)
bool startThread (int whatsup, void *data=NULL)
virtual void run (int whatsup, void *data)=0
void stopThread ()
Static Public Member Functions
static void usleep (unsigned long ms)
sleep for n microseconds (!!not yet implemented for win32)
Friends
void * _kickoff (void *ptr)
Detailed Description
class providing basic multithreading functions
NB - These threads are created as detached threads so that they will deallocate properely as the vuThread class is currently used.
Definition at line 79 of file vuThread.h.
Constructor & Destructor Documentation
virtual vuThread::~vuThread () inline virtual
Virtual destructor (doing nothing)
Definition at line 83 of file vuThread.h.
References _kickoff(), and NULL.
 {};
Member Function Documentation
virtual void vuThread::run (int whatsup, void * data) pure virtual
This function is called when a new thread is started by startThread. The function is virtual. Override it to run your own code. The whatsup argument is for free use to customize behaviour of different threads.
Implemented in Brain.
Referenced by _kickoff(), and vuMutex::unlock().
bool vuThread::startThread (int whatsup, void * data = NULL)
This function is called by the user to start a new thread. It calls the virtual run() with parameter whatsup to allow different behaviour of the threads.
Definition at line 45 of file vuThread.cpp.
References _kickoff(), and NULL.
Referenced by Brain::Brain(), Brain::doCommand(), and vuMutex::unlock().
 {
   pthread_t *thread = new pthread_t;
   m_WhatsupMutex.lock();
   m_Whatsup        = whatsup;
   m_AdditionalData = data;
   pthread_attr_t tattr;
 //  cout << "here" << endl;
   pthread_attr_setdetachstate (&tattr, PTHREAD_CREATE_DETACHED);
 //  cout << "s1" << endl;
   int t = pthread_create(thread, NULL, &_kickoff, (void*) this);
   if (t != 0)
   {
 //      cout << "s2.5" << endl;
     cout << strerror (errno) << endl;
     if (t == EAGAIN)
         cout << "eagain" << endl;
     return false;
   }
   pthread_detach (*thread);
 //  cout << "s3" << endl;
   return true;
 }
void vuThread::stopThread ()
Definition at line 107 of file vuThread.cpp.
References NULL.
Referenced by _kickoff(), and vuMutex::unlock().
 {
     pthread_exit(NULL);
 }
void vuThread::usleep (unsigned long ms) static
sleep for n microseconds (!!not yet implemented for win32)
Definition at line 112 of file vuThread.cpp.
Referenced by Brain::run(), and vuMutex::unlock().
 {
     ::usleep(ms);
 }
Friends And Related Function Documentation
void* _kickoff (void * ptr) friend
Definition at line 20 of file vuThread.cpp.
 {
   vuThread *th = (vuThread*)ptr;
   int   whatsup = th->m_Whatsup;
   void* data    = th->m_AdditionalData;
   th->m_WhatsupMutex.unlock();
   th->run(whatsup, data);
   th->stopThread();
   return NULL;
 }
The documentation for this class was generated from the following files:
src/vuThread.h
src/vuThread.cpp