Structural deformable models: Species Class Reference
Species Class Reference
#include <SpeciesDB.h>
Public Types
enum SpFlags {
FLIPPED =0x01, QUALITY =0x02, SCALE =0x04, SEL1 =0x08,
DEL =0x10, SEL2 =0x20, SEL3 =0x04, SEL4 =0x80,
SEL5 =0x100
}
enum SpCompare { CMP_EQUALS, CMP_CONTAINS, CMP_LESSER, CMP_GREATER }
Public Member Functions
Species (dword _id=0, dword _flags=0)
Species & operator= (const Species &rhs)
void reset ()
bool hasFlag (dword flag) const
dword setFlag (dword flag)
dword unsetFlag (dword flag)
dword readFlagString (const std::string &flags)
std::string getFlagString () const
bool select (const Species &sp, enum SpCompare how=Species::CMP_CONTAINS) const
dword getScale () const
Public Attributes
dword id
dword m_Flags
Static Public Attributes
static const char * SFIELDS []
static const char s_SPFLAGS []
Friends
ParseFile & operator>> (ParseFile &is, Species &sp)
std::ostream & operator<< (std::ostream &os, const Species &sp)
Detailed Description
Definition at line 12 of file SpeciesDB.h.
Member Enumeration Documentation
enum Species::SpCompare
Enumerator
CMP_EQUALS
CMP_CONTAINS
CMP_LESSER
CMP_GREATER
Definition at line 20 of file SpeciesDB.h.
 { CMP_EQUALS, CMP_CONTAINS, CMP_LESSER, CMP_GREATER };
enum Species::SpFlags
Enumerator
FLIPPED
QUALITY
SCALE
SEL1
DEL
SEL2
SEL3
SEL4
SEL5
Definition at line 16 of file SpeciesDB.h.
                  {
         FLIPPED=0x01, QUALITY=0x02, SCALE=0x04, SEL1=0x08, DEL=0x10,
         SEL2=0x20, SEL3=0x04, SEL4=0x80, SEL5=0x100
     };
Constructor & Destructor Documentation
Species::Species (dword _id = 0, dword _flags = 0) inline
Definition at line 21 of file SpeciesDB.h.
 : id(_id), m_Flags(_flags) {}
Member Function Documentation
string Species::getFlagString () const
Definition at line 181 of file SpeciesDB.cpp.
Referenced by ImageWindow::changeSpecies(), Brain::doCommand(), Brain::loadSpecies(), operator<<(), operator=(), and Brain::triggerTest().
{
     dword bv=1;
     string fs;
     for(int b=0; b<32 && s_SPFLAGS[b]; b++,bv=bv<<1)
         if(m_Flags&bv) fs += s_SPFLAGS[b];
     return fs;
 }
dword Species::getScale () const
Definition at line 229 of file SpeciesDB.cpp.
Referenced by ImageWindow::changeSpecies(), Brain::doCommand(), Brain::loadData(), Brain::loadSpecies(), and operator=().
 {
     dword scale=0;
     const_iterator s=find("scale");
     if(s!=end()) {
         istringstream(s->second)>>scale;
     }
     return scale;
 }
bool Species::hasFlag (dword flag) const
Definition at line 169 of file SpeciesDB.cpp.
Referenced by operator=(), and Brain::run().
{
     return m_Flags & flag;
 }
Species& Species::operator= (const Species & rhs) inline
Definition at line 22 of file SpeciesDB.h.
References CMP_CONTAINS, getFlagString(), getScale(), hasFlag(), id, m_Flags, operator<<, operator>>, readFlagString(), reset(), select(), setFlag(), and unsetFlag().
{
         if(&rhs == this) return *this;
         std::map<std::string, std::string>::operator=(rhs);
         id = rhs.id;
         m_Flags = rhs.m_Flags;
         return *this;
     }
dword Species::readFlagString (const std::string & flags)
Definition at line 189 of file SpeciesDB.cpp.
Referenced by Brain::doCommand(), operator=(), and operator>>().
{
     m_Flags = 0;
     dword bv=1;
     for(int b=0; b<32 && s_SPFLAGS[b]; b++,bv=(bv<<1))
         if(flags.find(s_SPFLAGS[b]) != flags.npos) m_Flags |= bv;
     return m_Flags;
 }
void Species::reset ()
Definition at line 163 of file SpeciesDB.cpp.
Referenced by Brain::load(), and operator=().
                     {
     clear();
     m_Flags = 0;
     id = 0;
 }
bool Species::select (const Species & sp, enum SpCompare how = Species::CMP_CONTAINS) const
Definition at line 197 of file SpeciesDB.cpp.
Referenced by SpeciesDB::getFilename(), and operator=().
 {
     for(map<string,string>::const_iterator rs=sp.begin();
         rs != sp.end(); rs++)
     {
         map<string,string>::const_iterator s=find(rs->first);
         if(s == end()) return false;
         const string &lv = s->second;
         const string &rv = rs->second;
         if(s->first == "flags") {
             for(string::const_iterator f=rv.begin(); f!=rv.end(); f++)
                 if(lv.find(*f)==lv.npos) return false;
         } else {
             switch(how) {
             case CMP_EQUALS:
                 if(lv != rv) return false;
                 break;
             case CMP_CONTAINS:
                 if(lv.find(rv) == lv.npos) return false;
                 break;
             case CMP_LESSER:
                 if(lv > rv) return false;
                 break;
             case CMP_GREATER:
                 if(lv < rv) return false;
                 break;
             }
         }
     }
     return true;
 }
dword Species::setFlag (dword flag)
Definition at line 173 of file SpeciesDB.cpp.
Referenced by operator=(), and Brain::triggerTest().
{
     return m_Flags |= flag;
 }
dword Species::unsetFlag (dword flag)
Definition at line 177 of file SpeciesDB.cpp.
Referenced by operator=(), and Brain::triggerTest().
{
     return m_Flags &= ~flag;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Species & sp) friend
Definition at line 149 of file SpeciesDB.cpp.
Referenced by operator=(), and SpeciesDB::SpeciesDB().
 {
     int entry=0;
     while(Species::SFIELDS[entry] != NULL) {
         const string fields(Species::SFIELDS[entry]);
         map<string,string>::const_iterator s=sp.find(fields);
         if(sp.m_Flags && fields == "flags")
             os << fields << " " << sp.getFlagString() << endl;
         else if(s != sp.end()) os << s->first << " " << s->second << endl;
         entry++;
     }
     return os;
 }
ParseFile& operator>> (ParseFile & is, Species & sp) friend
Definition at line 128 of file SpeciesDB.cpp.
Referenced by operator=(), and SpeciesDB::SpeciesDB().
 {
     sp.clear();
     sp.id = 0;
     sp.m_Flags = 0;
     while(is.getNextLine()) {
         const string& token = is.getKey();
         const string& value = is.getValue();
         //cout << "token: " << token << " value: " << value << endl;
         if(token == "species_id") {
             if(sp.id != 0) { is.pushLine(); return is; }
             istringstream(value) >> sp.id;
         } else if(sp.id == 0) {
             throw new IOException("record didn't start with 'species_id'");
         } else if(token == "flags")
             sp.readFlagString(value);
         sp[token] = value;
     }
     return is;
 }
Member Data Documentation
dword Species::id
Definition at line 41 of file SpeciesDB.h.
Referenced by Brain::doCommand(), Brain::load(), ImageWindow::onKeyPress(), ImageWindow::onRightMouseClick(), operator=(), operator>>(), Brain::run(), and Brain::triggerTest().
dword Species::m_Flags
Definition at line 42 of file SpeciesDB.h.
Referenced by operator<<(), operator=(), and operator>>().
const char Species::s_SPFLAGS[] static
Definition at line 15 of file SpeciesDB.h.
const char* Species::SFIELDS[] static
Definition at line 14 of file SpeciesDB.h.
Referenced by operator<<().
The documentation for this class was generated from the following files:
src/SpeciesDB.h
src/SpeciesDB.cpp