Structural deformable models: ParseFile Class Reference
ParseFile Class Reference
#include <ParseFile.h>
Public Types
enum ErrorID { ERR_OK =0, ERR_FILE, ERR_PARSE, ERR_EOF }
Public Member Functions
ParseFile (const std::string &filename)
ParseFile (std::istream &is)
bool open (const std::string &filename)
void attach (std::istream &is)
void close ()
bool good () const
bool eof () const
bool error () const
const std::string & getPath () const
const std::string & getFilename () const
const std::string & getLine () const
const std::string & getKey () const
const std::string & getValue () const
const int getLineNumber () const
const bool getNextLine ()
void pushLine (const std::string &line)
void pushLine ()
void setParseError (const std::string &msg="")
char getCommentChar () const
void setCommentChar (char cchar)
std::string getErrorMsg () const
void appendErrMsg (const std::string &msg)
operator bool () const
operator std::istream & ()
Static Public Member Functions
static std::string getPath (const std::string &sfilename)
Protected Member Functions
void resetStrings ()
void parseLine ()
Protected Attributes
std::ifstream m_IF
std::istream m_IS
std::string m_Filename
std::string m_Path
enum ErrorID m_Error
std::list< std::string > m_PushedLines
std::string m_Line
std::string m_LastLine
int m_LineN
std::string m_Key
std::string m_Value
std::string m_ErrMsg
const char c_CommentChar
Detailed Description
Definition at line 15 of file ParseFile.h.
Member Enumeration Documentation
enum ParseFile::ErrorID
Enumerator
ERR_OK
ERR_FILE
ERR_PARSE
ERR_EOF
Definition at line 17 of file ParseFile.h.
 {ERR_OK=0, ERR_FILE, ERR_PARSE, ERR_EOF };
Constructor & Destructor Documentation
ParseFile::ParseFile (const std::string & filename) inline
Definition at line 19 of file ParseFile.h.
References open().
         : m_IS(m_IF.rdbuf()), m_Error(ERR_OK), c_CommentChar('#') {
         open(filename);
     }
ParseFile::ParseFile (std::istream & is) inline
Definition at line 24 of file ParseFile.h.
         : m_IS(is.rdbuf()), m_Error(ERR_OK), c_CommentChar('#') {}
Member Function Documentation
void ParseFile::appendErrMsg (const std::string & msg) inline
Definition at line 98 of file ParseFile.h.
References m_ErrMsg.
 { m_ErrMsg = msg; }
void ParseFile::attach (std::istream & is) inline
Definition at line 37 of file ParseFile.h.
References m_IS, and resetStrings().
Referenced by open().
{
         resetStrings();
         m_IS.rdbuf(is.rdbuf());
     }
void ParseFile::close () inline
Definition at line 41 of file ParseFile.h.
References ERR_OK, m_Error, m_Filename, m_IF, m_Key, m_Line, m_LineN, m_Path, and m_Value.
                  {
         m_Error = ERR_OK;
         m_LineN = 0;
         m_Line.clear(); m_Key.clear(); m_Value.clear();
         m_Filename.clear(); m_Path.clear();
         m_IF.close();
     }
bool ParseFile::eof () const inline
Definition at line 49 of file ParseFile.h.
References ERR_EOF, and m_Error.
Referenced by operator>>().
 { return m_Error == ERR_EOF; }
bool ParseFile::error () const inline
Definition at line 50 of file ParseFile.h.
References ERR_EOF, ERR_OK, and m_Error.
Referenced by SubStructure::read(), StructTable::read(), and MStructure::read().
 { return m_Error!=ERR_OK && m_Error!=ERR_EOF; }
char ParseFile::getCommentChar () const inline
Definition at line 82 of file ParseFile.h.
References c_CommentChar.
 { return c_CommentChar; }
std::string ParseFile::getErrorMsg () const inline
Definition at line 85 of file ParseFile.h.
References ERR_FILE, ERR_OK, ERR_PARSE, m_ErrMsg, m_Error, m_Filename, and m_LineN.
Referenced by Brain::load(), and StructTable::read().
{
         std::ostringstream msg;
         msg << "[file " << m_Filename << "] ";
         switch(m_Error) {
             case ERR_OK: msg << "none"; break;
             case ERR_FILE: msg << "error opening file"; break;
             case ERR_PARSE: msg << "parse error in line " << m_LineN;
                 break;
             case ERR_EOF: msg << "end of file"; break;
         }
         if(!m_ErrMsg.empty()) msg << ": " << m_ErrMsg;
         return msg.str();
     }
const std::string& ParseFile::getFilename () const inline
Definition at line 53 of file ParseFile.h.
References m_Filename.
Referenced by SpeciesDB::load(), and operator>>().
 { return m_Filename; }
const std::string& ParseFile::getKey () const inline
Definition at line 56 of file ParseFile.h.
References m_Key.
Referenced by Brain::load(), MStructure::loadRefProp(), operator>>(), SubStructure::read(), MStructure::read(), SearcherParams::read(), Model::readEdge(), StructTable::readInterpreations(), Model::readNode(), Model::readParameter(), SensorCollection::readSensor(), and Model::readSensor().
 { return m_Key; }
const std::string& ParseFile::getLine () const inline
Definition at line 55 of file ParseFile.h.
References m_Line.
 { return m_Line; }
const int ParseFile::getLineNumber () const inline
Definition at line 58 of file ParseFile.h.
References m_LineN.
Referenced by operator>>().
 { return m_LineN; }
const bool ParseFile::getNextLine () inline
Definition at line 59 of file ParseFile.h.
References ERR_EOF, ERR_OK, m_Error, m_IS, m_Key, m_LastLine, m_Line, m_LineN, m_PushedLines, m_Value, and parseLine().
Referenced by Brain::load(), MStructure::loadRefProp(), operator>>(), SubStructure::read(), MStructure::read(), SearcherParams::read(), Model::readEdge(), StructTable::readInterpreations(), Model::readNode(), Model::readParameter(), SensorCollection::readSensor(), and Model::readSensor().
{
         if(m_Error != ERR_OK) return false;
         m_LastLine = m_Line;
         m_Line.clear(); m_Key.clear(); m_Value.clear();
         while(m_Key.empty() &&
               (!m_PushedLines.empty() ? true : (bool)std::getline(m_IS, m_Line))) {
             if(!m_PushedLines.empty()) {
                 m_Line = m_PushedLines.back();
                 m_PushedLines.pop_back();
             } else m_LineN++;
             parseLine();
         }
         if(m_Key.empty()) { m_Error = ERR_EOF; return false; }
         return true;
     }
const std::string& ParseFile::getPath () const inline
Definition at line 52 of file ParseFile.h.
References m_Path.
Referenced by Brain::load(), SpeciesDB::load(), open(), operator<<(), StructTable::read(), MStructure::read(), and Model::readSensor().
 { return m_Path; }
static std::string ParseFile::getPath (const std::string & sfilename) inline static
Definition at line 106 of file ParseFile.h.
{
         dword slashpos = sfilename.rfind('/');
         if(slashpos == sfilename.npos) slashpos = sfilename.rfind('\\');
         if(slashpos != sfilename.npos) return sfilename.substr(0,slashpos+1);
         else return std::string("./");
     }
const std::string& ParseFile::getValue () const inline
Definition at line 57 of file ParseFile.h.
References m_Value.
Referenced by Brain::load(), MStructure::loadRefProp(), operator>>(), SubStructure::read(), MStructure::read(), SearcherParams::read(), Model::readEdge(), StructTable::readInterpreations(), Model::readNode(), Model::readParameter(), SensorCollection::readSensor(), and Model::readSensor().
 { return m_Value; }
bool ParseFile::good () const inline
Definition at line 48 of file ParseFile.h.
References ERR_OK, and m_Error.
Referenced by operator bool().
 { return m_Error == ERR_OK; }
bool ParseFile::open (const std::string & filename) inline
Definition at line 27 of file ParseFile.h.
References attach(), ERR_FILE, getPath(), m_Error, m_Filename, m_IF, m_Path, and resetStrings().
Referenced by ParseFile().
{
         resetStrings();
         m_IF.open(filename.c_str());
         if(m_IF) {
             attach(m_IF);
             m_Filename = filename;
             m_Path = getPath(filename);
             return true;
         } else { m_Error = ERR_FILE; return false; }
     }
ParseFile::operator bool () const inline
Definition at line 100 of file ParseFile.h.
References good().
 { return good(); }
ParseFile::operator std::istream & () inline
Definition at line 102 of file ParseFile.h.
References m_IS.
 { return m_IS; }
void ParseFile::parseLine () inline protected
Definition at line 121 of file ParseFile.h.
References c_CommentChar, m_Key, m_Line, and m_Value.
Referenced by getNextLine(), and pushLine().
                      {
         m_Line = m_Line.substr(0,m_Line.find(c_CommentChar));
         std::string::reverse_iterator ch = m_Line.rbegin();
         while(ch!=m_Line.rend() && *ch<=32) ch++; //moves backwards
         m_Line = m_Line.substr(0,m_Line.size()-(ch-m_Line.rbegin()));
         std::istringstream lines(m_Line);
         std::string token, value;
         if(lines >> m_Key) {
             lines >> std::ws;
             std::getline(lines, m_Value);
         }
     }
void ParseFile::pushLine (const std::string & line) inline
Definition at line 74 of file ParseFile.h.
References m_PushedLines.
Referenced by operator>>(), MStructure::read(), SearcherParams::read(), Model::readEdge(), StructTable::readInterpreations(), Model::readNode(), Model::readParameter(), SensorCollection::readSensor(), and Model::readSensor().
 { m_PushedLines.push_back(line); }
void ParseFile::pushLine () inline
Definition at line 75 of file ParseFile.h.
References m_LastLine, m_Line, and parseLine().
                     {
         pushLine(m_Line);
         if(!m_LastLine.empty())
         { m_Line = m_LastLine; m_LastLine.clear(); parseLine(); }
     }
void ParseFile::resetStrings () inline protected
Definition at line 113 of file ParseFile.h.
References ERR_OK, m_ErrMsg, m_Error, m_Filename, m_Key, m_LastLine, m_Line, m_LineN, m_Path, m_PushedLines, and m_Value.
Referenced by attach(), and open().
{
         m_Error = ERR_OK;
         m_LineN = 0;
         m_Line.clear(); m_Key.clear(); m_Value.clear(); m_LastLine.clear();
         m_PushedLines.clear();
         m_ErrMsg.clear();
         m_Filename.clear(); m_Path.clear();
     }
void ParseFile::setCommentChar (char cchar) inline
Definition at line 83 of file ParseFile.h.
References c_CommentChar.
 { ((char&)c_CommentChar) = cchar; }
void ParseFile::setParseError (const std::string & msg = "") inline
Definition at line 80 of file ParseFile.h.
References ERR_OK, ERR_PARSE, m_ErrMsg, and m_Error.
Referenced by Brain::load(), SubStructure::read(), StructTable::read(), MStructure::read(), Model::readEdge(), StructTable::readInterpreations(), Model::readNode(), and SensorCollection::readSensor().
         { if(m_Error == ERR_OK) { m_Error = ERR_PARSE; m_ErrMsg = msg; } }
Member Data Documentation
const char ParseFile::c_CommentChar protected
Definition at line 143 of file ParseFile.h.
Referenced by getCommentChar(), parseLine(), and setCommentChar().
std::string ParseFile::m_ErrMsg protected
Definition at line 142 of file ParseFile.h.
Referenced by appendErrMsg(), getErrorMsg(), resetStrings(), and setParseError().
enum ErrorID ParseFile::m_Error protected
Definition at line 137 of file ParseFile.h.
Referenced by close(), eof(), error(), getErrorMsg(), getNextLine(), good(), open(), resetStrings(), and setParseError().
std::string ParseFile::m_Filename protected
Definition at line 136 of file ParseFile.h.
Referenced by close(), getErrorMsg(), getFilename(), open(), and resetStrings().
std::ifstream ParseFile::m_IF protected
Definition at line 134 of file ParseFile.h.
Referenced by close(), and open().
std::istream ParseFile::m_IS protected
Definition at line 135 of file ParseFile.h.
Referenced by attach(), getNextLine(), and operator std::istream &().
std::string ParseFile::m_Key protected
Definition at line 141 of file ParseFile.h.
Referenced by close(), getKey(), getNextLine(), parseLine(), and resetStrings().
std::string ParseFile::m_LastLine protected
Definition at line 139 of file ParseFile.h.
Referenced by getNextLine(), pushLine(), and resetStrings().
std::string ParseFile::m_Line protected
Definition at line 139 of file ParseFile.h.
Referenced by close(), getLine(), getNextLine(), parseLine(), pushLine(), and resetStrings().
int ParseFile::m_LineN protected
Definition at line 140 of file ParseFile.h.
Referenced by close(), getErrorMsg(), getLineNumber(), getNextLine(), and resetStrings().
std::string ParseFile::m_Path protected
Definition at line 136 of file ParseFile.h.
Referenced by close(), getPath(), open(), and resetStrings().
std::list<std::string> ParseFile::m_PushedLines protected
Definition at line 138 of file ParseFile.h.
Referenced by getNextLine(), pushLine(), and resetStrings().
std::string ParseFile::m_Value protected
Definition at line 141 of file ParseFile.h.
Referenced by close(), getNextLine(), getValue(), parseLine(), and resetStrings().
The documentation for this class was generated from the following file:
src/ParseFile.h