Structural deformable models: SubStructure Class Reference
SubStructure Class Reference
#include <MStruct.h>
Public Types
enum DistrType { EMD_PCA =0, EMD_GAUSS, EMD_RECT, EMD_RECTTF }
enum Modes { MODE_NONE =0, MODE_NOSPAWN =2, MODE_SHOWSTATS =4 }
Public Member Functions
SubStructure (const std::string &subStructName="", const std::string &supStructName="", const PropTF &transform=PropTF(0.f), int pivot=-1)
void clear ()
void analyseTF (const DMatrixf &tfmat)
EMDistribution * generateEMDist (const PropVec &wprop, float ppmm, bool inverse=false, dword dtype=EMD_RECT) const
void getLBUB (PropVec &lb, PropVec &ub, const PropVec &wprop, float ppmm, float radius=3) const
bool read (ParseFile &is)
Public Attributes
std::string m_SubStructName
std::string m_SupStructName
PropTF m_Transform
int m_Pivot
bool m_Polar
PropVec m_Mean
PropVec m_Stdev
DMatrixf m_PC
DMatrixf m_Sigma
DMatrixf m_IPC
float m_RateWeight
float m_RateTH
dword m_Mode
Friends
std::ostream & operator<< (std::ostream &os, const SubStructure &ss)
Detailed Description
Definition at line 21 of file MStruct.h.
Member Enumeration Documentation
enum SubStructure::DistrType
Enumerator
EMD_PCA
EMD_GAUSS
EMD_RECT
EMD_RECTTF
Definition at line 24 of file MStruct.h.
 {EMD_PCA=0, EMD_GAUSS, EMD_RECT, EMD_RECTTF};
enum SubStructure::Modes
Enumerator
MODE_NONE
MODE_NOSPAWN
MODE_SHOWSTATS
Definition at line 25 of file MStruct.h.
 {MODE_NONE=0, MODE_NOSPAWN=2, MODE_SHOWSTATS=4 };
Constructor & Destructor Documentation
SubStructure::SubStructure (const std::string & subStructName = "", const std::string & supStructName = "", const PropTF & transform = PropTF(0.f), int pivot = -1)
Definition at line 636 of file MStruct.cpp.
     : m_SubStructName(subStructName),m_SupStructName(subStructName),
       m_Transform(transform), m_Pivot(pivot),
       m_Polar(false), m_RateWeight(SUBSTRUCT_RATEWEIGHT),
       m_RateTH(SUBSTRUCT_RATETH), m_Mode(MODE_NONE)
 {
 }
Member Function Documentation
void SubStructure::analyseTF (const DMatrixf & tfmat)
Definition at line 646 of file MStruct.cpp.
References StructTable::adjustByAvgDir(), DMatrix< T >::at(), dmutil::avg(), DUMP, DMatrix< T >::empty(), dmutil::expand(), DMatrix< T >::getDiag(), DMatrix< T >::getRange(), getSearchPara(), dmutil::inverse(), m_IPC, m_Mean, m_Mode, m_PC, SearcherParams::m_PCTH, m_Sigma, m_Stdev, MODE_SHOWSTATS, DMatrix< T >::mulRight(), PVEC_DIR, DMatrix< T >::resize(), DMatrix< T >::setRange(), VVector< T, D >::size(), DMatrix< T >::sizeX(), DMatrix< T >::sizeY(), dmutil::sqrt(), dmutil::stdev(), and DMatrix< T >::transpose().
Referenced by MStructure::buildAllStats().
 {
     using namespace dmutil;
     if(tfmat.empty() ||tfmat.sizeX()!=PropVec::size()) {
         m_PC = m_IPC = makeIdentity<float>(PropVec::size()+1);
         m_Sigma.resize(1,4); m_Sigma = 0.f;
         m_Mean = m_Stdev = 0.f;
         return;
     }
     bool show = false && (m_Mode&MODE_SHOWSTATS);
     if(show) DUMP(tfmat);
     DMatrixf ntfmat(tfmat);
     DMatrixf angles(1,ntfmat.sizeY());
     ntfmat.getRange(PVEC_DIR, 0, angles);
     StructTable::adjustByAvgDir(angles);
     ntfmat.setRange(PVEC_DIR, 0, angles);
     //todo: switch to polar position (translation)
 //         ofstream f1("tfmat.dat");
 //         f1 << tfmat;
 //         ofstream f2("ids.dat");
 //         copy(comod.begin(), comod.end(), ostream_iterator<dword>(f2, "\n"));
     //build a (0,1) standardized matrix of the distribution
     DMatrixf avghg(avg(ntfmat));
     DMatrixf stdevhg(stdev(ntfmat));
     DMatrixf mavg(expand(avghg, 1,ntfmat.sizeY()));
     DMatrixf mstdev(expand(stdevhg, 1,ntfmat.sizeY()));
     ntfmat -= mavg; ntfmat /= mstdev;
     //build a normalized covariance matrix
     DMatrixf tfcov(ntfmat);
     tfcov.transpose();
     tfcov = tfcov.mulRight(ntfmat);
     tfcov *= (1.f/(ntfmat.sizeY())); //normalize by number of samples
     if(show) DUMP(tfcov);
     DMatrixf mU, mS, mV;
     // dmutil::SVD(tfcov, mU, mS, mV); // TODO
     m_Sigma = mS.getDiag();
     float relvar = 1.f/4; //1.f/dmutil::sum(m_Sigma).at(0,0); // has to be 1/4
     for(dword i=0;i<m_Sigma.sizeY(); i++)
         if(m_Sigma.at(0,i)*relvar < getSearchPara().m_PCTH)
             m_Sigma.at(0,i) = 0.f;
     dmutil::sqrt(m_Sigma);
     m_Mean = &avghg.at(0,0);
     m_Stdev = &stdevhg.at(0,0);
     if(show) DUMP(mU << mS << mV);
 //make a homogeneous matrix to integrate de-standardization
     //m_Sigma.resize(1,m_Sigma.sizeY()+1,1.f);
     //mS = makeDiag(m_Sigma);
 //     avghg.transpose();
 //     avghg.resize(1,avghg.sizeY()+1,1.f);
 //     stdevhg.transpose();
 //     stdevhg.resize(1,stdevhg.sizeY()+1,1.f);
 //     DMatrixf mVhg(makeIdentity<float>(mV.sizeX()+1));
 //     mVhg.setRange(0,0,mV);
 //     //mVhg.transpose(); //no transposed, or not?
 //     //m_PC = makeDiag(stdevhg).mulRight(mVhg.mulRight(mS));
 //     m_PC = makeDiag(stdevhg).mulRight(mVhg);
 //     m_PC.setRange(m_PC.sizeX()-1,0,avghg);
     m_PC = mV;
     m_IPC = inverse(m_PC);
     //cout << m_Sigma << m_Mean << endl << m_Stdev << endl;
 //     DUMP(m_SubStructName);
 //     DUMP(m_Mean);
 //     DUMP(m_Stdev);
 }
void SubStructure::clear ()
Definition at line 822 of file MStruct.cpp.
References m_Mode, m_Pivot, m_Polar, m_RateTH, m_RateWeight, m_SubStructName, m_SupStructName, m_Transform, MODE_NONE, SUBSTRUCT_RATETH, and SUBSTRUCT_RATEWEIGHT.
Referenced by read().
 {
     m_SubStructName.clear();
     m_SupStructName.clear();
     m_Transform = 0.f;
     m_Pivot = -1;
     m_Polar = false;
     m_Mode = MODE_NONE;
     m_RateWeight = SUBSTRUCT_RATEWEIGHT;
     m_RateTH = SUBSTRUCT_RATETH;
 }
EMDistribution * SubStructure::generateEMDist (const PropVec & wprop, float ppmm, bool inverse = false, dword dtype = EMD_RECT) const
Definition at line 711 of file MStruct.cpp.
References DMatrix< T >::at(), ExpectationMap::correctLBUB(), EMD_GAUSS, EMD_PCA, EMD_RECT, EMD_RECTTF, DMatrix< T >::empty(), fwdPropTF(), getIdentityPropTF(), getPropPos(), getSearchPara(), invPropTF(), m_IPC, m_Mean, m_PC, SearcherParams::m_ScaleStd, m_Sigma, m_Stdev, DMatrix< T >::mulLeft(), NULL, PVEC_POSX, PVEC_POSY, EMDXformer::setMean(), setPropPos(), DMatrix< T >::sizeX(), and dmutil::sqrt().
Referenced by MStructure::addExpectation(), and MStructure::showStats().
 {
     //ATTENTION: backward transform isn't working the way I'm doing it here
     // so, only use forward transform
     EMDistribution* emdist = NULL;
     switch(DistrType(dtype)) {
         case EMD_PCA:
         {
             if(m_Sigma.empty()) break;
             //generate a transformed gaussian distribution (using PCA xform)
             DMatrixf stddm(m_Sigma);
             stddm *= getSearchPara().m_ScaleStd;
             PropVec stdtf(&stddm.at(0,0));
             EMDGauss* eminput = new EMDGauss(PropVec(0.f), stdtf);
             //EMDRect* eminput = new EMDRect(stdtf*-1.f, stdtf);
             DMatrixf tfmat = backwards ? m_IPC : m_PC;
 #ifndef _PROPTF_NORMALIZE_SCALE_
             DMatrixf mmmat = dmutil::makeIdentity<float>(tfmat.sizeX());
             mmmat.at(PVEC_POSX,PVEC_POSX) = ppmm;
             mmmat.at(PVEC_POSY,PVEC_POSY) = ppmm;
             tfmat = tfmat.mulLeft(mmmat);
 #endif
             emdist = (EMDistribution*) new EMDXformer(eminput, wprop, tfmat);
             ((EMDXformer*)emdist)->setMean(m_Mean);
             ((EMDXformer*)emdist)->setStdev(m_Stdev);
         }
         break;
         case EMD_RECT:
         {
             //generate a rectangular uniform distribution
             PropVec propsd(m_Stdev);
             //propsd*=sqrt(3.f);
             PropVec lb(m_Mean-propsd);
             PropVec ub(m_Mean+propsd);
 #ifndef _PROPTF_NORMALIZE_SCALE_
             setPropPos(lb, getPropPos(lb)*ppmm);
             setPropPos(ub, getPropPos(ub)*ppmm);
 #endif
             PropVec olb(wprop), oub(wprop);
             if(backwards) { invPropTF(olb, ub); invPropTF(oub, lb); }
             else { fwdPropTF(olb, lb); fwdPropTF(oub, ub); }
             PropVec mean(m_Mean);
             setPropPos(mean, getPropPos(mean)*ppmm);
             PropVec a(wprop);
             ExpectationMap::correctLBUB(olb, oub);
             emdist = (EMDistribution*) new EMDRect(olb,oub);
         }
         break;
         case EMD_RECTTF:
         {
             //generate a rectangular uniform distribution
             PropVec propsd(m_Stdev);
             propsd*=sqrt(3.f);
             PropVec lb(m_Mean-propsd);
             PropVec ub(m_Mean+propsd);
 #ifndef _PROPTF_NORMALIZE_SCALE_
             setPropPos(lb, getPropPos(lb)*ppmm);
             setPropPos(ub, getPropPos(ub)*ppmm);
 #endif
             PropVec olb(getIdentityPropTF()), oub(getIdentityPropTF());
             if(backwards) { invPropTF(olb, lb); invPropTF(oub, ub); }
             else { fwdPropTF(olb, lb); fwdPropTF(oub, ub); }
             ExpectationMap::correctLBUB(olb, oub);
             EMDistribution* inpdist = (EMDistribution*) new EMDRect(olb,oub);
             emdist = (EMDistribution*) new EMDXformer(inpdist, wprop);
         }
         break;
         case EMD_GAUSS:
         {
             //generate a multidimensional axis-aligned gaussian distribution
             PropVec sdevpv(m_Stdev);
             sdevpv *= getSearchPara().m_ScaleStd;
             PropVec meanpv(m_Mean);
 #ifndef _PROPTF_NORMALIZE_SCALE_
             setPropPos(sdevpv, getPropPos(sdevpv)*ppmm);
             setPropPos(meanpv, getPropPos(meanpv)*ppmm);
 #endif
             PropVec cprop(getIdentityPropTF());
             if(backwards) invPropTF(cprop, meanpv);
             else fwdPropTF(cprop, meanpv); //cool form of: cprop = meanpv
             EMDistribution* inpdist =
                 (EMDistribution*) new EMDGauss(PropVec(0.f), sdevpv);
             emdist = (EMDistribution*) new EMDXformer(inpdist, wprop);
             ((EMDXformer*)emdist)->setMean(cprop);
         }
         break;
     }
     return emdist;
 }
void SubStructure::getLBUB (PropVec & lb, PropVec & ub, const PropVec & wprop, float ppmm, float radius = 3) const
Definition at line 803 of file MStruct.cpp.
References fwdPropTF(), getPropPos(), getPropScale(), m_Mean, M_PI, m_Stdev, setPropDir(), setPropPos(), and setPropScale().
Referenced by MStructure::addExpectation().
 {
     lb = ub = wprop;
     PropVec tflb(m_Mean);
     tflb -= (m_Stdev*radius);
     PropVec tfub(m_Mean);
     tfub += (m_Stdev*radius);
 #ifndef _PROPTF_NORMALIZE_SCALE_
     setPropPos(tflb, getPropPos(tflb)*ppmm);
     setPropPos(tfub, getPropPos(tfub)*ppmm);
 #endif
     fwdPropTF(lb, tflb);
     fwdPropTF(ub, tfub);
     if(getPropScale(lb)<0.001) setPropScale(lb, 0.001);
     setPropDir(lb, 0);
     setPropDir(ub, 2*M_PI);
 }
bool SubStructure::read (ParseFile & is)
Definition at line 834 of file MStruct.cpp.
References clear(), ParseFile::error(), fromString(), ParseFile::getKey(), ParseFile::getNextLine(), ParseFile::getValue(), m_Mode, m_Pivot, m_RateTH, m_RateWeight, m_SubStructName, m_Transform, MODE_NOSPAWN, MODE_SHOWSTATS, and ParseFile::setParseError().
Referenced by MStructure::hasSupStruct(), and MStructure::read().
 {
     if(is.getKey() != "substruct") return false;
     clear();
     m_SubStructName = is.getValue();
     bool readon = true;
     while(readon && is.getNextLine()) {
         const string& key = is.getKey();
         const string& value = is.getValue();
         if(key == "transform") {
             fromString(value, m_Transform);
         } else if(key == "pivot") {
             fromString(value, m_Pivot);
             m_Pivot--;
         } else if(key == "rateweight") {
             fromString(value, m_RateWeight);
         } else if(key == "rateth") {
             fromString(value, m_RateTH);
         } else if(key == "mode") {
             if(value.find("nospawn") != value.npos)
                 m_Mode |= MODE_NOSPAWN;
             if(value.find("showstats") != value.npos)
                 m_Mode |= MODE_SHOWSTATS;
         } else if (key == "end") readon = false;
         else { is.setParseError("error parsing substructure"); return false; }
     }
     if(is.error()) return false;
     return true;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const SubStructure & ss) friend
Definition at line 864 of file MStruct.cpp.
 {
     os << "  substruct " << ss.m_SubStructName << endl;
     os << "    transform " << ss.m_Transform << endl;
     if(ss.m_Pivot>=0)
         os << "    pivot " << ss.m_Pivot+1 << endl;
     if(ss.m_Polar) os << "    polar" << endl;
     if(ss.m_RateWeight != SUBSTRUCT_RATEWEIGHT)
         os << "    rateweight " << ss.m_RateWeight << endl;
     if(ss.m_Mode != SubStructure::MODE_NONE) {
         os << "    mode"
            << (ss.m_Mode&SubStructure::MODE_NOSPAWN ? " nospawn" : "")
            << (ss.m_Mode&SubStructure::MODE_SHOWSTATS ? " showstats" : "")
            << endl;
     }
     os << "  end    # of substruct" << endl;
     return os;
 }
Member Data Documentation
DMatrixf SubStructure::m_IPC
Definition at line 46 of file MStruct.h.
Referenced by analyseTF(), and generateEMDist().
PropVec SubStructure::m_Mean
Definition at line 45 of file MStruct.h.
Referenced by analyseTF(), generateEMDist(), getLBUB(), and MStructure::showStats().
dword SubStructure::m_Mode
Definition at line 48 of file MStruct.h.
Referenced by MStructure::addExpectation(), analyseTF(), MStructure::buildAllStats(), clear(), operator<<(), and read().
DMatrixf SubStructure::m_PC
Definition at line 46 of file MStruct.h.
Referenced by analyseTF(), and generateEMDist().
int SubStructure::m_Pivot
Definition at line 43 of file MStruct.h.
Referenced by MStructure::addExpectation(), MStructure::buildAllStats(), clear(), operator<<(), read(), and MStructure::showStats().
bool SubStructure::m_Polar
Definition at line 44 of file MStruct.h.
Referenced by clear(), and operator<<().
float SubStructure::m_RateTH
Definition at line 47 of file MStruct.h.
Referenced by clear(), StructTable::findBestConnection(), and read().
float SubStructure::m_RateWeight
Definition at line 47 of file MStruct.h.
Referenced by MStructure::addExpectation(), clear(), StructTable::findBestConnection(), operator<<(), StructPath::print(), and read().
DMatrixf SubStructure::m_Sigma
Definition at line 46 of file MStruct.h.
Referenced by analyseTF(), generateEMDist(), and MStructure::showStats().
PropVec SubStructure::m_Stdev
Definition at line 45 of file MStruct.h.
Referenced by analyseTF(), generateEMDist(), getLBUB(), and MStructure::showStats().
std::string SubStructure::m_SubStructName
Definition at line 41 of file MStruct.h.
Referenced by MStructure::addSubStruct(), MStructure::buildAllStats(), clear(), operator<<(), read(), and MStructure::showStats().
std::string SubStructure::m_SupStructName
Definition at line 41 of file MStruct.h.
Referenced by clear(), and MStructure::showStats().
PropTF SubStructure::m_Transform
Definition at line 42 of file MStruct.h.
Referenced by clear(), operator<<(), and read().
The documentation for this class was generated from the following files:
src/MStruct.h
src/MStruct.cpp