Structural deformable models: CombiSensor Class Reference
CombiSensor Class Reference
#include <SensorSet.h>
Public Member Functions
CombiSensor (int nchannels=0)
virtual ~CombiSensor ()
int getNChannels () const
int getSkip () const
void changeSource (const Sensor *_source)
std::ostream & print (std::ostream &os) const
std::ostream & hprint (std::ostream &os, SensorCollection *sc) const
void clearSources ()
void setNSources (int n)
void setSource (Sensor *_source, float weight, int id)
void setSource (Sensor *_source, float weight)
Sensor & assign (const Sensor &rhs)
void normalizeInput (bool doit=true)
bool isInputNormalized () const
Public Member Functions inherited from PPSensor
PPSensor (const Sensor *_source)
virtual float getValue (int x, int y) const
virtual Point getGradient (int x, int y) const
virtual bool performUpdate ()
void togglePP (enum PPState state=PP_DO)
dword getPPState () const
Public Member Functions inherited from Sensor
Sensor (const Sensor *_source=NULL)
virtual ~Sensor ()
const Sensor * getSource ()
void replaceBy (Sensor *target)
bool assignRef (const Sensor *rhs)
float getValue (const Point &p) const
get value at position p using nearest neighbour interpolation
virtual std::vector< float > getMValue (int x, int y) const
get multi-channel value
Point2D getGradient (const Point2D &p) const
get gradient at position p using nearest neighbor interpolation
float getMax () const
float getMin () const
float getMinMaxRange () const
float getWeightedValue (int x, int y) const
get max normalized value at discrete position range [0,1]
Point2D getWeightedGradient (int x, int y) const
get range weighted gradient at discrete position
void setCWeights (const std::vector< float > &weights)
const std::vector< float > & getCWeights () const
void setDirection (const Point &dir)
const Point & getDirection () const
void setScale (float _scale)
float getScale () const
bool isModified (dword mask=UPD_ALL) const
void setModified (dword mask=UPD_ALL)
void unsetModified (dword mask=UPD_ALL)
bool isUpdate (dword udMask) const
void enableUpdate (dword udMask)
void disableUpdate (dword udMask)
virtual int getDim1Size () const
virtual int getDim2Size () const
virtual int getDim3Size () const
bool isValid (int x, int y) const
virtual Image< float > createSensorImage () const
const std::string & getID () const
void setID (const std::string &id)
void refSuperSensor (Sensor *super)
void unrefSuperSensor (Sensor *super)
void invalidateSource ()
Protected Member Functions
float calcValue (int x, int y) const
Computes a scalar product between the multi-channel intensities and the cweights vector.
std::vector< float > calcMValue (int x, int y) const
Protected Member Functions inherited from PPSensor
void fitSheets ()
virtual void calcAllValues ()
virtual void calcAllGradients ()
Protected Member Functions inherited from Sensor
virtual Point calcGradient (int x, int y) const
virtual void calcMinMax ()
Protected Attributes
std::vector< Sensor * > sources
bool m_NormalizeInput
Protected Attributes inherited from PPSensor
Image< float > values
caching sheet for sensed values
Image< Point > gradients
caching sheet for gradients
dword doPP
do preprocessing?
Protected Attributes inherited from Sensor
const Sensor * source
float scale
std::vector< float > cweights
multi-channel weights ('color')
Point dir
direction parameter
float maxval
float minval
overall minimum and maximum
float mean
float stdev
overall mean and stdev
dword toupdate
bitflag for updates
dword updateMask
bitflag to mask unimportant updates
std::string m_ID
int m_Skip
int m_AddSkip
Additional Inherited Members
Public Types inherited from PPSensor
enum PPState { PP_DONT =0, PP_DO, PP_FORCE }
Public Types inherited from Sensor
enum UpdateParam {
UPD_NOTHING =0, UPD_DATA =1, UPD_SCALE =2, UPD_CWEIGHTS =4,
UPD_DIR =8, UPD_MINMAX =16, UPD_LAST =32, UPD_ALL =0xffffffff
}
Static Public Member Functions inherited from Sensor
static dword getStringNumber (const char *sid)
static void getNumberString (char sid[5], dword id)
Detailed Description
Multi-Sensor
Definition at line 265 of file SensorSet.h.
Constructor & Destructor Documentation
CombiSensor::CombiSensor (int nchannels = 0)
Definition at line 96 of file SensorSet.cpp.
References Sensor::enableUpdate(), setNSources(), Sensor::UPD_CWEIGHTS, and Sensor::UPD_DATA.
     : PPSensor(NULL), m_NormalizeInput(true)
 {
     setNSources(nchannels);
     enableUpdate(UPD_DATA|UPD_CWEIGHTS);
     //togglePP(PP_FORCE);
 }
CombiSensor::~CombiSensor () virtual
Definition at line 104 of file SensorSet.cpp.
References sources.
 {
     for(vector<Sensor*>::iterator s=sources.begin();
         s!=sources.end(); s++)
     {
         (*s)->unrefSuperSensor(this);
     }
 }
Member Function Documentation
Sensor & CombiSensor::assign (const Sensor & rhs) virtual
Reimplemented from PPSensor.
Definition at line 189 of file SensorSet.cpp.
References PPSensor::assign(), Sensor::getCWeights(), setNSources(), setSource(), and sources.
 {
     if(&rhs != this) {
         PPSensor::assign(rhs);
         if(typeid(&rhs) == typeid(CombiSensor*)) {
             const CombiSensor& crhs = (const CombiSensor&) rhs;
             if(sources != crhs.sources) {
                 setNSources(crhs.sources.size());
                 int sid = 0;
                 const vector<float>& weights = crhs.getCWeights();
                 for(vector<Sensor*>::const_iterator s = crhs.sources.begin();
                     s != crhs.sources.end(); s++, sid++)
                     setSource((Sensor*)*s, weights[sid], sid);
             }
         }
     }
     return *this;
 }
std::vector<float> CombiSensor::calcMValue (int x, int y) const inline protected virtual
Calculate a multi-valued sensor result. The size of the returned vector is the same as getNChannels().
Reimplemented from Sensor.
Definition at line 312 of file SensorSet.h.
References Sensor::cweights, and Sensor::getNChannels().
{
     std::vector<float> vv(getNChannels());
         std::vector<float>::iterator v = vv.begin();
         std::vector<Sensor*>::const_iterator s = sources.begin();
         std::vector<float>::const_iterator w = cweights.begin();
         if(m_NormalizeInput)
             for(; v != vv.end(); v++, s++,w++)
                 *v = (*s)->getWeightedValue(x,y)*(*w);
         else
             for(; v != vv.end(); v++, s++,w++)
                 *v = (*s)->getValue(x,y)*(*w);
         return vv;
     }
float CombiSensor::calcValue (int x, int y) const inline protected virtual
Computes a scalar product between the multi-channel intensities and the cweights vector.
Implements Sensor.
Definition at line 297 of file SensorSet.h.
References Sensor::cweights.
{
     float result = 0.0f;
         std::vector<Sensor*>::const_iterator s = sources.begin();
         std::vector<float>::const_iterator w = cweights.begin();
         if(m_NormalizeInput)
             for(; s != sources.end(); s++,w++) {
                 result += (*s)->getWeightedValue(x,y)*(*w);
             }
         else
             for(; s != sources.end(); s++,w++) {
                 result += (*s)->getValue(x,y)*(*w);
             }
     return result;
     }
void CombiSensor::changeSource (const Sensor * _source) virtual
Reimplemented from Sensor.
Definition at line 156 of file SensorSet.cpp.
References Sensor::changeSource(), Sensor::enableUpdate(), Sensor::getID(), print(), setSource(), Sensor::source, sources, TRACE, and Sensor::UPD_MINMAX.
 {
     if(!_source) return;
     const string& sid = _source->getID();
     vector<Sensor*>::iterator s=sources.begin();
     while(s!=sources.end() && (*s)->getID()!=sid) s++;
     if(s!=sources.end()) {      // && sid == (*s)->getID()) { // use assert?
         source = *s;
         PPSensor::changeSource(_source);
         *s = (Sensor*)source;
     if(!((Sensor*)source)->isUpdate(UPD_MINMAX)) {
         ((Sensor*)source)->enableUpdate(UPD_MINMAX);
         ((Sensor*)source)->setModified(UPD_MINMAX);
     }
     } else {
         TRACE("error replacing element <"<<sid<<"> in combi sensor - appending instead.");
         print(cout) << endl;
         setSource((Sensor*)_source,1.f);
     }
 }
void CombiSensor::clearSources ()
Definition at line 113 of file SensorSet.cpp.
References Sensor::cweights, Sensor::setModified(), sources, Sensor::UPD_CWEIGHTS, and Sensor::UPD_DATA.
 {
     vector<Sensor*>::iterator s=sources.begin();
     while(s!=sources.end()) {
         (*s)->unrefSuperSensor(this);
         s++;
     }
     sources.clear();
     cweights.clear();
     setModified(UPD_CWEIGHTS|UPD_DATA);
 }
int CombiSensor::getNChannels () const inline virtual
Reimplemented from Sensor.
Definition at line 271 of file SensorSet.h.
 { return sources.size(); }
int CombiSensor::getSkip () const inline virtual
Reimplemented from Sensor.
Definition at line 272 of file SensorSet.h.
References Sensor::changeSource(), Sensor::hprint(), Sensor::m_Skip, and IntensitySensor::print().
{
         int m_Skip = 0;
         for(std::vector<Sensor*>::const_iterator s = sources.begin();
             s!=sources.end(); s++)
             if((*s)->getSkip() > m_Skip) m_Skip = (*s)->getSkip();
         return m_Skip;
     }
ostream & CombiSensor::hprint (std::ostream & os, SensorCollection * sc) const virtual
Reimplemented from Sensor.
Definition at line 223 of file SensorSet.cpp.
References SensorCollection::isPrinted(), Sensor::m_ID, print(), SensorCollection::setPrinted(), and sources.
 {
     if(sc->isPrinted(m_ID)) return os;
     for(vector<Sensor*>::const_iterator s=sources.begin();
         s!=sources.end(); s++)
     {
         (*s)->hprint(os, sc);
     }
     if(sc->isPrinted(m_ID)) return os;
     sc->setPrinted(m_ID);
     return (print(os) << endl);
 }
bool CombiSensor::isInputNormalized () const inline
Definition at line 291 of file SensorSet.h.
 { return m_NormalizeInput; }
void CombiSensor::normalizeInput (bool doit = true) inline
Definition at line 290 of file SensorSet.h.
 { m_NormalizeInput = doit; }
ostream & CombiSensor::print (std::ostream & os) const virtual
Reimplemented from Sensor.
Definition at line 208 of file SensorSet.cpp.
References Sensor::cweights, Sensor::getID(), m_NormalizeInput, and sources.
Referenced by changeSource(), and hprint().
 {
     os << "s " << getID() << " ";
     //Sensor::print(os); would print modified source
     if(m_NormalizeInput) os << "k";
     else os << "K";
     vector<float>::const_iterator w = cweights.begin();
     for(vector<Sensor*>::const_iterator s=sources.begin();
         s!=sources.end(); s++, w++)
     {
         os << " " << (*s)->getID() << " " << *w;
     }
     return os;
 }
void CombiSensor::setNSources (int n)
Definition at line 125 of file SensorSet.cpp.
References Sensor::cweights, getZeroSensor(), Sensor::setModified(), sources, Sensor::UPD_CWEIGHTS, and Sensor::UPD_DATA.
Referenced by assign(), CombiSensor(), and setSource().
 {
     if(n != (int)sources.size()) {
         //clearSources();
         sources.resize(n,(Sensor*)getZeroSensor());
         cweights.resize(n, 1);
     setModified(UPD_CWEIGHTS|UPD_DATA);
     }
 }
void CombiSensor::setSource (Sensor * _source, float weight, int id)
Definition at line 135 of file SensorSet.cpp.
References Sensor::cweights, Sensor::enableUpdate(), getZeroSensor(), Sensor::isUpdate(), Sensor::refSuperSensor(), Sensor::setModified(), setNSources(), Sensor::source, sources, Sensor::UPD_CWEIGHTS, Sensor::UPD_DATA, and Sensor::UPD_MINMAX.
Referenced by assign(), and changeSource().
 {
     assert(id>=0);
     if(id>=(int)sources.size()) {
         setNSources(id+1);
     }
     else if (sources[id] != 0 && sources[id] != getZeroSensor())
     {
         sources[id]->unrefSuperSensor(this);
     }
     sources[id] = _source;
     cweights[id] = weight;
     _source->refSuperSensor(this);
     source = _source;
     if(!((Sensor*)source)->isUpdate(UPD_MINMAX)) {
     ((Sensor*)source)->enableUpdate(UPD_MINMAX);
     ((Sensor*)source)->setModified(UPD_MINMAX);
     }
     setModified(UPD_CWEIGHTS|UPD_DATA);
 }
void CombiSensor::setSource (Sensor * _source, float weight) inline
Definition at line 287 of file SensorSet.h.
References Sensor::assign().
         { setSource(_source, weight, sources.size()); }
Member Data Documentation
bool CombiSensor::m_NormalizeInput protected
Definition at line 294 of file SensorSet.h.
Referenced by print().
std::vector<Sensor*> CombiSensor::sources protected
Definition at line 293 of file SensorSet.h.
Referenced by assign(), changeSource(), clearSources(), hprint(), print(), setNSources(), setSource(), and ~CombiSensor().
The documentation for this class was generated from the following files:
src/SensorSet.h
src/SensorSet.cpp