Structural deformable models: IPoint2D Class Reference
IPoint2D Class Reference
#include <Point.h>
Public Member Functions
IPoint2D ()
IPoint2D (int _i, float _x, float _y)
IPoint2D (int _i, const Point2D &p)
IPoint2D & operator= (const IPoint2D &rhs)
IPoint2D & operator= (const Point2D &rhs)
Public Member Functions inherited from Point2D
Point2D ()
Point2D (const Point2D &rhs)
Point2D (float _x, float _y)
Point2D (const float *val)
virtual ~Point2D ()
Point2D & operator= (const Point2D &rhs)
Point2D & operator= (float rhs)
Point2D & operator= (const float *rhs)
Point2D & operator+= (const Point2D &rhs)
Point2D & operator-= (const Point2D &rhs)
Point2D & operator*= (const Point2D &rhs)
Point2D & operator*= (const float f)
Point2D & operator/= (const Point2D &rhs)
Point2D & operator/= (const float f)
float operator* (const Point2D &rhs) const
const Point2D & const_times (const Point2D &rhs) const
Point2D & times (const Point2D &rhs)
float dot (const Point2D &rhs) const
float crossZ (const Point2D &rhs) const
float sinAngle (const Point2D &rhs) const
float angle (const Point2D &rhs=Point2D(1, 0)) const
float sinAngleX () const
float angleX () const
Point2D operator* (float rhs) const
Point2D operator+ (const Point2D &rhs) const
Point2D operator- (const Point2D &rhs) const
Point2D operator/ (const Point2D &rhs) const
Point2D operator/ (float rhs) const
float sum () const
returns 1-norm
float norm2 () const
returns squared 2-norm
float norm () const
returns 2-norm aka length or absolute
float normalize ()
normalizes the vector; returns old norm
bool clamp (float x0, float y0, float x1, float y1)
void glVertex () const
Issue a glVertex2f call.
const Point2D flipOrtho () const
const Point2D copyNormalized () const
const Point2D rotate (float angle) const
Public Attributes
int index
Public Attributes inherited from Point2D
float x
float y
Detailed Description
Definition at line 228 of file Point.h.
Constructor & Destructor Documentation
IPoint2D::IPoint2D () inline
Definition at line 231 of file Point.h.
 : Point2D() {};
IPoint2D::IPoint2D (int _i, float _x, float _y) inline
Definition at line 232 of file Point.h.
 : Point2D(_x, _y), index(_i) {}
IPoint2D::IPoint2D (int _i, const Point2D & p) inline
Definition at line 233 of file Point.h.
References Point2D::operator=().
{
         operator=(p);
         index = _i;
     }
Member Function Documentation
IPoint2D& IPoint2D::operator= (const IPoint2D & rhs) inline
Definition at line 237 of file Point.h.
References index, and Point2D::operator=().
{
         Point2D::operator=(rhs);
         index = rhs.index;
         return *this;
     }
IPoint2D& IPoint2D::operator= (const Point2D & rhs) inline
Definition at line 242 of file Point.h.
References Point2D::operator=().
{
         Point2D::operator=(rhs);
         index = -1;
         return *this;
     }
Member Data Documentation
int IPoint2D::index
Definition at line 248 of file Point.h.
Referenced by operator=().
The documentation for this class was generated from the following file:
src/Point.h