Structural deformable models: IOException Class Reference
IOException Class Reference
#include <Errors.h>
Public Member Functions
IOException (const char *msg=NULL)
~IOException ()
void setMessage (const char *msg=NULL)
const char * getMessage () const
Protected Attributes
char * message
Detailed Description
Definition at line 11 of file Errors.h.
Constructor & Destructor Documentation
IOException::IOException (const char * msg = NULL) inline
Definition at line 13 of file Errors.h.
                                         : message(NULL) {
     setMessage(msg);
     }
IOException::~IOException () inline
Definition at line 16 of file Errors.h.
References NULL.
                    {
     if(message) {
         delete message;
         message = NULL;
     }
     }
Member Function Documentation
const char* IOException::getMessage () const inline
Definition at line 41 of file Errors.h.
Referenced by SpeciesDB::load(), operator>>(), Model::readFile(), and Model::writeFile().
 { return message; }
void IOException::setMessage (const char * msg = NULL) inline
Definition at line 22 of file Errors.h.
References NULL.
{
     if(!msg) {
         if(message) {
         if(message[0] != 0) {
             delete message;
             message = new char[1];
             message[0] = 0;
         }
         } else {
         message = new char[1];
         message[0] = 0;
         }
         return;
     }
     int len = strlen(msg);
     if(!len) setMessage(NULL);
     message = new char[len+1];
     strcpy(message, msg);
     }
Member Data Documentation
char* IOException::message protected
Definition at line 43 of file Errors.h.
The documentation for this class was generated from the following file:
src/Errors.h