Structural deformable models: Winner Class Reference
Winner Class Reference
#include <ExpMap.h>
Public Types
enum ReservedID {
WID_EMPTY = 0, WID_FIRST, WID_LAST = 0xfffffdff, WID_FRAME,
WID_BLOCKED, WID_FIRSTFREE
}
typedef std::map< std::string, dword > BestRatings
typedef const std::map< std::string, dword > CBestRatings
typedef std::map< std::string, std::map< dword, float > > Ratings
typedef const std::map< std::string, std::map< dword, float > > CRatings
Public Member Functions
Winner (Model *m=NULL)
void setModel (Model *m)
void setStructName (const std::string &sname)
void clearRatings ()
float rateBy (const std::string &creatorname, dword creatorid, float rating)
float updateBestRating ()
const BestRatings::mapped_type & getBestRatingID (const std::string &sname) const
const Ratings::mapped_type & getRatingList (const std::string &sname) const
const std::pair< dword, float > getBest (const std::string &sname) const
bool hasConnection (const std::string &sname) const
float getConnection (const std::string &sname, dword wid) const
Public Attributes
Model * m_Model
dword m_WinnerID
std::string m_StructName
float m_BestRating
Ratings m_Ratings
BestRatings m_BestRatings
Detailed Description
Definition at line 10 of file ExpMap.h.
Member Typedef Documentation
typedef std::map<std::string,dword> Winner::BestRatings
Definition at line 14 of file ExpMap.h.
typedef const std::map<std::string,dword> Winner::CBestRatings
Definition at line 15 of file ExpMap.h.
typedef const std::map<std::string, std::map<dword,float> > Winner::CRatings
Definition at line 17 of file ExpMap.h.
typedef std::map<std::string, std::map<dword,float> > Winner::Ratings
Definition at line 16 of file ExpMap.h.
Member Enumeration Documentation
enum Winner::ReservedID
Enumerator
WID_EMPTY
WID_FIRST
WID_LAST
WID_FRAME
WID_BLOCKED
WID_FIRSTFREE
Definition at line 12 of file ExpMap.h.
                     { WID_EMPTY = 0, WID_FIRST, WID_LAST = 0xfffffdff,
                       WID_FRAME, WID_BLOCKED, WID_FIRSTFREE};
Constructor & Destructor Documentation
Winner::Winner (Model * m = NULL) inline
Definition at line 19 of file ExpMap.h.
References setModel().
                           : m_WinnerID(WID_EMPTY), m_BestRating(0.f)
         { setModel(m); }
Member Function Documentation
void Winner::clearRatings ()
Definition at line 288 of file ExpMap.cpp.
Referenced by ExpectationMap::ratePropVec(), and setStructName().
 {
     m_BestRating = 0.0f;
     m_BestRatings.clear();
     m_Ratings.clear();
 }
const std::pair< dword, float > Winner::getBest (const std::string & sname) const
Definition at line 306 of file ExpMap.cpp.
Referenced by getRatingList().
 {
     const std::map<dword,float>& rl = getRatingList(sname);
     dword bid = getBestRatingID(sname);
     return *rl.find(bid);
 }
const BestRatings::mapped_type& Winner::getBestRatingID (const std::string & sname) const inline
Definition at line 27 of file ExpMap.h.
References m_BestRatings.
         { return m_BestRatings.find(sname)->second; }
float Winner::getConnection (const std::string & sname, dword wid) const
Definition at line 313 of file ExpMap.cpp.
Referenced by hasConnection(), and StructPath::print().
 {
     if(!hasConnection(sname)) return -1.f;
     const std::map<dword,float>& rl = getRatingList(sname);
     std::map<dword,float>::const_iterator rt = rl.find(wid);
     if(rt != rl.end()) return rt->second;
     else return -1.f;
 }
const Ratings::mapped_type& Winner::getRatingList (const std::string & sname) const inline
Definition at line 29 of file ExpMap.h.
References getBest(), and m_Ratings.
         { return m_Ratings.find(sname)->second; }
bool Winner::hasConnection (const std::string & sname) const inline
Definition at line 32 of file ExpMap.h.
References getConnection(), and m_Ratings.
         { return m_Ratings.find(sname) != m_Ratings.end(); }
float Winner::rateBy (const std::string & creatorname, dword creatorid, float rating)
Definition at line 295 of file ExpMap.cpp.
Referenced by ExpectationMap::ratePropVec(), and setStructName().
 {
     m_Ratings[creatorname][creatorid] = rating;
     dword& brid = m_BestRatings[creatorname];
     if(!brid || m_Ratings[creatorname][brid] < rating) {
         brid = creatorid;
         if(m_BestRating < rating) m_BestRating = rating;
     }
     return m_BestRating;
 }
void Winner::setModel (Model * m)
Definition at line 281 of file ExpMap.cpp.
References Model::getID(), Model::getName(), and WID_EMPTY.
Referenced by Winner().
 {
     m_Model = m;
     m_WinnerID = m ? m->getID() : Winner::WID_EMPTY;
     m_StructName = m ? m->getName() : "";
 }
void Winner::setStructName (const std::string & sname) inline
Definition at line 22 of file ExpMap.h.
References clearRatings(), m_StructName, rateBy(), and updateBestRating().
 { m_StructName = sname; }
float Winner::updateBestRating ()
Definition at line 322 of file ExpMap.cpp.
Referenced by setStructName().
 {
     m_BestRating = 0.f;
     m_BestRatings.clear();
     for(Ratings::const_iterator refstruct = m_Ratings.begin();
         refstruct != m_Ratings.end(); refstruct++)
     {
         dword& brid = m_BestRatings[refstruct->first];
         float bestrating = 0.f; //m_Ratings[refstruct->first][brid];
         for(std::map<dword,float>::const_iterator wr= refstruct->second.begin();
             wr != refstruct->second.end(); wr++)
         { // for each rating wr
             if(wr->second > bestrating) {
                 bestrating = wr->second;
                 brid = wr->first;
             }
         }
         if(m_BestRating < bestrating) m_BestRating = bestrating;
     }
     return m_BestRating;
 }
Member Data Documentation
float Winner::m_BestRating
Definition at line 39 of file ExpMap.h.
Referenced by MStructure::addExpectation(), StructPath::print(), and ExpectationMap::ratePropVec().
BestRatings Winner::m_BestRatings
Definition at line 41 of file ExpMap.h.
Referenced by getBestRatingID().
Model* Winner::m_Model
Definition at line 36 of file ExpMap.h.
Referenced by MStructure::addExpectation(), StructTable::draw(), StructTable::findBestConnection(), StructPath::print(), StructPath::protectWinners(), and StructPath::unprotectWinners().
Ratings Winner::m_Ratings
Definition at line 40 of file ExpMap.h.
Referenced by StructTable::findBestConnection(), getRatingList(), and hasConnection().
std::string Winner::m_StructName
Definition at line 38 of file ExpMap.h.
Referenced by MStructure::clear(), StructTable::findBestConnection(), MStructure::setName(), and setStructName().
dword Winner::m_WinnerID
Definition at line 37 of file ExpMap.h.
Referenced by ExpectationMap::add(), MStructure::addExpectation(), Searcher::evolve(), StructTable::findBestConnection(), and MStructure::setName().
The documentation for this class was generated from the following files:
src/ExpMap.h
src/ExpMap.cpp