Structural deformable models: EMDGauss Class Reference
EMDGauss Class Reference
#include <ExpMap.h>
Public Member Functions
EMDGauss (const PropVec &avg=PropVec(0.f), const PropVec &stdev=PropVec(1.f))
virtual ~EMDGauss ()
virtual EMDistribution * copy () const
PropVec getPropVec () const
float ratePropVec (const PropVec &prop, Winner *winner=NULL) const
void setAvg (const PropVec &avg)
void setStdev (const PropVec &stdev)
Public Member Functions inherited from EMDistribution
EMDistribution ()
virtual ~EMDistribution ()
virtual void setIntegral (float integral)
void setCreator (const Winner &creator)
void setShootCount (dword scount)
dword getShootCount () const
bool hasFlags (dword flags) const
void setFlags (dword flags)
void unsetFlags (dword flags=0xffffffff)
Protected Attributes
PropVec m_Avg
PropVec m_Stdev
PropVec m_StdevRate
Additional Inherited Members
Public Types inherited from EMDistribution
enum EDFlags { ED_NONE =0, ED_OLD =1 }
Public Attributes inherited from EMDistribution
float m_Integral
Winner m_Creator
dword m_ShootCount
dword m_Flags
Detailed Description
Definition at line 93 of file ExpMap.h.
Constructor & Destructor Documentation
EMDGauss::EMDGauss (const PropVec & avg = PropVec(0.f), const PropVec & stdev = PropVec(1.f)) inline
Definition at line 95 of file ExpMap.h.
References dmutil::stdev().
     : m_Avg(avg) { setStdev(stdev); }
virtual EMDGauss::~EMDGauss () inline virtual
Definition at line 98 of file ExpMap.h.
 {};
Member Function Documentation
virtual EMDistribution* EMDGauss::copy () const inline virtual
Reimplemented from EMDistribution.
Definition at line 99 of file ExpMap.h.
References NULL.
     { return (EMDistribution*) (new EMDGauss(*this)); }
PropVec EMDGauss::getPropVec () const virtual
Reimplemented from EMDistribution.
Definition at line 222 of file ExpMap.cpp.
References fgauss01(), and VVector< T, D >::size().
 {
     PropVec pv;
     for(unsigned int i=0; i<PropVec::size(); i++)
         pv[i] = fgauss01()*m_Stdev[i] + m_Avg[i];
     return pv;
 }
float EMDGauss::ratePropVec (const PropVec & prop, Winner * winner = NULL) const virtual
Reimplemented from EMDistribution.
Definition at line 230 of file ExpMap.cpp.
References gauss2(), and M_SQRT2PI.
Referenced by main().
 {
     return gauss2(((prop-m_Avg)/=m_StdevRate).norm2(),1)*M_SQRT2PI;
 }
void EMDGauss::setAvg (const PropVec & avg) inline
Definition at line 103 of file ExpMap.h.
References dmutil::avg(), and dmutil::stdev().
 { m_Avg = avg; }
void EMDGauss::setStdev (const PropVec & stdev)
Definition at line 235 of file ExpMap.cpp.
References VVector< T, D >::size(), and dmutil::stdev().
 {
     m_Stdev = stdev;
     for(dword i = 0; i<stdev.size(); i++) {
         if(stdev[i]>0.0001) m_StdevRate[i] = stdev[i];
         else m_StdevRate[i] = std::numeric_limits<float>::max();
     }
 }
Member Data Documentation
PropVec EMDGauss::m_Avg protected
Definition at line 106 of file ExpMap.h.
PropVec EMDGauss::m_Stdev protected
Definition at line 106 of file ExpMap.h.
PropVec EMDGauss::m_StdevRate protected
Definition at line 106 of file ExpMap.h.
The documentation for this class was generated from the following files:
src/ExpMap.h
src/ExpMap.cpp