Structural deformable models: Point2D Class Reference
Point2D Class Reference
#include <Point.h>
Public Member Functions
Point2D ()
Point2D (const Point2D &rhs)
Point2D (float _x, float _y)
Point2D (const float *val)
virtual ~Point2D ()
Point2D & operator= (const Point2D &rhs)
Point2D & operator= (float rhs)
Point2D & operator= (const float *rhs)
Point2D & operator+= (const Point2D &rhs)
Point2D & operator-= (const Point2D &rhs)
Point2D & operator*= (const Point2D &rhs)
Point2D & operator*= (const float f)
Point2D & operator/= (const Point2D &rhs)
Point2D & operator/= (const float f)
float operator* (const Point2D &rhs) const
const Point2D & const_times (const Point2D &rhs) const
Point2D & times (const Point2D &rhs)
float dot (const Point2D &rhs) const
float crossZ (const Point2D &rhs) const
float sinAngle (const Point2D &rhs) const
float angle (const Point2D &rhs=Point2D(1, 0)) const
float sinAngleX () const
float angleX () const
Point2D operator* (float rhs) const
Point2D operator+ (const Point2D &rhs) const
Point2D operator- (const Point2D &rhs) const
Point2D operator/ (const Point2D &rhs) const
Point2D operator/ (float rhs) const
float sum () const
returns 1-norm
float norm2 () const
returns squared 2-norm
float norm () const
returns 2-norm aka length or absolute
float normalize ()
normalizes the vector; returns old norm
bool clamp (float x0, float y0, float x1, float y1)
void glVertex () const
Issue a glVertex2f call.
const Point2D flipOrtho () const
const Point2D copyNormalized () const
const Point2D rotate (float angle) const
Public Attributes
float x
float y
Friends
std::ostream & operator<< (std::ostream &os, const Point2D &p)
std::istream & operator>> (std::istream &is, Point2D &p)
bool operator== (const Point2D &lhs, const Point2D &rhs)
bool operator!= (const Point2D &lhs, const Point2D &rhs)
Detailed Description
Definition at line 16 of file Point.h.
Constructor & Destructor Documentation
Point2D::Point2D () inline
Definition at line 18 of file Point.h.
Referenced by angleX(), flipOrtho(), and rotate().
 : x(0), y(0) {};
Point2D::Point2D (const Point2D & rhs) inline
Definition at line 19 of file Point.h.
References operator=().
{
         operator=(rhs); }
Point2D::Point2D (float _x, float _y) inline
Definition at line 21 of file Point.h.
 : x(_x), y(_y) {}
Point2D::Point2D (const float * val) inline
Definition at line 22 of file Point.h.
References operator=().
{
         operator=(val); }
virtual Point2D::~Point2D () inline virtual
Definition at line 25 of file Point.h.
 {};
Member Function Documentation
float Point2D::angle (const Point2D & rhs = Point2D(1,0)) const inline
Definition at line 93 of file Point.h.
References crossZ(), dot(), M_1_PI, and M_PI.
Referenced by StructTable::adjustByAvgDir(), angleX(), Model::getNodeAngle(), and setPropSDir().
{
         float dv = crossZ(rhs);
         float dh = dot(rhs);
         return atan2(dv,dh);
 #ifdef _THERE_IS_NO_ATAN2_
         float dvp,dvn;
         if(dv > 0.0) {
             dvp = 1.0;
             dvn = 0.0;
         } else {
             dvp = 0.0;
             dvn = 1.0;
         }
         float dhn = (dh < 0) ? 1.0 : 0.0;
         float psi;
         if (dh == 0.0)
             psi = M_PI_2 * (dvp + 3.0 * dvn);
         else if (dv == 0.0)
             psi = M_PI * dhn;
         else
             psi = atan(dv/dh) + M_PI * dhn * dvp
                 + (M_PI + M_PI * (dh > 0.0)) * dvn;
         return psi * (180.0*M_1_PI);
 #endif
     }
float Point2D::angleX () const inline
Definition at line 123 of file Point.h.
References angle(), and Point2D().
Referenced by Edge::getAngle().
{
         //return asin(sinAngleX());
         return angle(Point2D(1,0));
     }
bool Point2D::clamp (float x0, float y0, float x1, float y1) inline
Definition at line 181 of file Point.h.
References clamp(), x, and y.
         {
             return ::clamp(x,y,x0,y0,x1,y1);
         }
const Point2D& Point2D::const_times (const Point2D & rhs) const inline
Definition at line 73 of file Point.h.
References times().
{
         Point2D p(*this);
         return p.times(rhs);
     }
const Point2D Point2D::copyNormalized () const inline
Definition at line 206 of file Point.h.
References normalize().
{
         Point2D p(*this);
         p.normalize();
         return p;
     }
float Point2D::crossZ (const Point2D & rhs) const inline
Definition at line 85 of file Point.h.
References x, and y.
Referenced by angle().
{
         return y*rhs.x-x*rhs.y;
     }
float Point2D::dot (const Point2D & rhs) const inline
Definition at line 82 of file Point.h.
References x, and y.
Referenced by angle(), and Model::calculateForces().
{
         return x*rhs.x+y*rhs.y;
     }
const Point2D Point2D::flipOrtho () const inline
Definition at line 202 of file Point.h.
References Point2D(), x, and y.
Referenced by Model::addTorque().
{
         return Point2D(-y,x);
     }
void Point2D::glVertex () const inline
Issue a glVertex2f call.
Definition at line 198 of file Point.h.
References x, and y.
{
         glVertex2f(x, y);
     }
float Point2D::norm () const inline
returns 2-norm aka length or absolute
Definition at line 170 of file Point.h.
References dmutil::sqrt(), x, and y.
Referenced by Model::calculateForces(), normalize(), setPropSDir(), and sinAngleX().
{
         return (float)sqrt(x*x+y*y);
     }
float Point2D::norm2 () const inline
returns squared 2-norm
Definition at line 165 of file Point.h.
References x, and y.
Referenced by Edge::length2(), and sinAngle().
{
         return x*x+y*y;
     }
float Point2D::normalize () inline
normalizes the vector; returns old norm
Definition at line 175 of file Point.h.
References norm(), and operator*=().
Referenced by Model::addTorque(), CornerSensor::calcValue(), and copyNormalized().
                       {
         float n = norm();
         if (n>0.0f) operator*=(1/n);
         return n;
     }
float Point2D::operator* (const Point2D & rhs) const inline
Definition at line 69 of file Point.h.
References x, and y.
{
         return x*rhs.x + y*rhs.y;
     }
Point2D Point2D::operator* (float rhs) const inline
Definition at line 129 of file Point.h.
{
         Point2D p(*this);
         p *= rhs;
         return p;
     }
Point2D& Point2D::operator*= (const Point2D & rhs) inline
Definition at line 50 of file Point.h.
References x, and y.
Referenced by normalize().
{
         x*=rhs.x; y*=rhs.y;
         return *this;
     }
Point2D& Point2D::operator*= (const float f) inline
Definition at line 55 of file Point.h.
References x, and y.
{
         x*=f; y*=f;
         return *this;
     }
Point2D Point2D::operator+ (const Point2D & rhs) const inline
Definition at line 135 of file Point.h.
{
         Point2D p(*this);
         p += rhs;
         return p;
     }
Point2D& Point2D::operator+= (const Point2D & rhs) inline
Definition at line 41 of file Point.h.
References x, and y.
{
         x+=rhs.x; y+=rhs.y;
         return *this;
     }
Point2D Point2D::operator- (const Point2D & rhs) const inline
Definition at line 141 of file Point.h.
{
         Point2D p(*this);
         p -= rhs;
         return p;
     }
Point2D& Point2D::operator-= (const Point2D & rhs) inline
Definition at line 45 of file Point.h.
References x, and y.
{
         x-=rhs.x; y-=rhs.y;
         return *this;
     }
Point2D Point2D::operator/ (const Point2D & rhs) const inline
Definition at line 147 of file Point.h.
{
         Point2D p(*this);
         p /= rhs;
         return p;
     }
Point2D Point2D::operator/ (float rhs) const inline
Definition at line 153 of file Point.h.
{
         Point2D p(*this);
         p *= 1/rhs;
         return p;
     }
Point2D& Point2D::operator/= (const Point2D & rhs) inline
Definition at line 60 of file Point.h.
References x, and y.
{
         x/=rhs.x; y/=rhs.y;
         return *this;
     }
Point2D& Point2D::operator/= (const float f) inline
Definition at line 64 of file Point.h.
References x, and y.
{
         x/=f; y/=f;
         return *this;
     }
Point2D& Point2D::operator= (const Point2D & rhs) inline
Definition at line 27 of file Point.h.
References x, and y.
Referenced by IPoint2D::IPoint2D(), Node::operator=(), IPoint2D::operator=(), Point2D(), and Node::setPos().
{
         x=rhs.x; y=rhs.y;
         return *this;
     }
Point2D& Point2D::operator= (float rhs) inline
Definition at line 32 of file Point.h.
References x, and y.
{
         x = y = rhs;
         return *this;
     }
Point2D& Point2D::operator= (const float * rhs) inline
Definition at line 37 of file Point.h.
References x, and y.
{
         this->x = rhs[0]; this->y = rhs[1];
         return *this;
     }
const Point2D Point2D::rotate (float angle) const inline
Definition at line 211 of file Point.h.
References Point2D(), x, and y.
Referenced by StructTable::adjustByAvgDir(), getPropSDir(), and Model::rotate().
{
         float ca = cos(angle);
         float sa = sin(angle);
         return Point2D(x*ca-y*sa,x*sa+y*ca);
     }
float Point2D::sinAngle (const Point2D & rhs) const inline
Definition at line 88 of file Point.h.
References norm2(), dmutil::sqrt(), x, and y.
{
         // z-component of the cross product
         return (x*rhs.y-y*rhs.x)/sqrt(norm2()*rhs.norm2());
     }
float Point2D::sinAngleX () const inline
Definition at line 119 of file Point.h.
References norm(), and y.
{
         return -y/norm();
     }
float Point2D::sum () const inline
returns 1-norm
Definition at line 160 of file Point.h.
References x, and y.
Referenced by Searcher::buildBins().
                       {
         return x+y;
     }
Point2D& Point2D::times (const Point2D & rhs) inline
Definition at line 78 of file Point.h.
Referenced by const_times().
{
         return *this *= rhs;
     }
Friends And Related Function Documentation
bool operator!= (const Point2D & lhs, const Point2D & rhs) friend
Definition at line 219 of file Point.h.
{
         return !operator==(lhs, rhs);
     }
std::ostream& operator<< (std::ostream & os, const Point2D & p) friend
Definition at line 186 of file Point.h.
{
         os << p.x << " " << p.y;
         return os;
     }
bool operator== (const Point2D & lhs, const Point2D & rhs) friend
Definition at line 216 of file Point.h.
{
         return lhs.x == rhs.x && lhs.y == rhs.y;
     }
std::istream& operator>> (std::istream & is, Point2D & p) friend
Definition at line 191 of file Point.h.
{
         is >> p.x;
         is >> p.y;
         return is;
     }
Member Data Documentation
float Point2D::x
Definition at line 224 of file Point.h.
Referenced by Node::addSensorForce(), Searcher::buildBins(), Searcher::buildClusters(), MCGSensor::calcGradient(), CornerSensor::calcValue(), clamp(), crossZ(), Model::distance(), dot(), Node::draw(), Brain::drawAllModels(), flipOrtho(), Sensor::getGradient(), Sensor::getValue(), glVertex(), Dataset::load(), norm(), norm2(), operator*(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), Model::readNode(), rotate(), setPropPos(), sinAngle(), and sum().
float Point2D::y
Definition at line 224 of file Point.h.
Referenced by Node::addSensorForce(), Searcher::buildBins(), Searcher::buildClusters(), MCGSensor::calcGradient(), CornerSensor::calcValue(), clamp(), crossZ(), Model::distance(), dot(), Node::draw(), Brain::drawAllModels(), flipOrtho(), Sensor::getGradient(), Sensor::getValue(), glVertex(), Dataset::load(), norm(), norm2(), operator*(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), Model::readNode(), rotate(), setPropPos(), sinAngle(), sinAngleX(), and sum().
The documentation for this class was generated from the following file:
src/Point.h