Structural deformable models: StructPath Class Reference
StructPath Class Reference
#include <StructTable.h>
Public Member Functions
StructPath ()
StructPath (const StructPath &rhs)
~StructPath ()
StructPath & operator= (const StructPath &rhs)
void clear ()
Winner * getWinner (MStructure &struc)
const Winner * getWinner (const MStructure &struc) const
float getGoodness () const
void protectWinners (StructTable &structs)
void unprotectWinners (StructTable &structs)
void blockOtherPaths (const std::set< std::string > &freepath, const StructTable &structs)
std::ostream & print (std::ostream &os, const StructTable &structs) const
float getRelGoodness () const
StructPath branch () const
void merge (const StructPath &mp)
Public Attributes
float m_Goodness
goodness of path
float m_Maxness
maximum goodness
Protected Attributes
bool m_WinnersProtected
Detailed Description
Definition at line 21 of file StructTable.h.
Constructor & Destructor Documentation
StructPath::StructPath ()
Definition at line 523 of file StructTable.cpp.
                        : m_Goodness(0.f), m_Maxness(0.f),
                            m_WinnersProtected(false)
 {}
StructPath::StructPath (const StructPath & rhs)
Definition at line 527 of file StructTable.cpp.
References operator=().
 {
     operator=(rhs);
 }
StructPath::~StructPath ()
Definition at line 532 of file StructTable.cpp.
 {
     //unprotectWinners();
 }
Member Function Documentation
void StructPath::blockOtherPaths (const std::set< std::string > & freepath, const StructTable & structs)
Definition at line 611 of file StructTable.cpp.
References StructTable::getStructs(), m_WinnersProtected, and Winner::WID_BLOCKED.
Referenced by StructTable::findBestConnection(), and getGoodness().
 {
     for(map<string,MStructure>::const_iterator
             st = structs.getStructs().begin();
         st != structs.getStructs().end(); st++)
     {
         if(freepath.find(st->second.getName()) == freepath.end())
             operator[](st->second.getName()) = Winner::WID_BLOCKED;
     }
     m_WinnersProtected = false;
 }
StructPath StructPath::branch () const
Definition at line 664 of file StructTable.cpp.
References m_Goodness, m_Maxness, Winner::WID_BLOCKED, and Winner::WID_EMPTY.
Referenced by StructTable::findBestConnection(), and getRelGoodness().
 {
     StructPath bp(*this);
     for(iterator wi = bp.begin(); wi != bp.end(); wi++)
         if(wi->second != Winner::WID_EMPTY) wi->second = Winner::WID_BLOCKED;
     bp.m_Goodness = 0.f; bp.m_Maxness = 0.f;
     return bp;
 }
void StructPath::clear ()
Definition at line 548 of file StructTable.cpp.
References m_Goodness, m_Maxness, and m_WinnersProtected.
 {
     map<string,dword>::clear();
     m_Goodness = 0.0f;
     m_Maxness = 0.f;
     m_WinnersProtected = false;
 }
float StructPath::getGoodness () const inline
Definition at line 31 of file StructTable.h.
References blockOtherPaths(), m_Goodness, print(), protectWinners(), and unprotectWinners().
 { return m_Goodness; }
float StructPath::getRelGoodness () const inline
Definition at line 37 of file StructTable.h.
References branch(), m_Goodness, m_Maxness, and merge().
Referenced by StructTable::findBestConnection(), and print().
     { return m_Maxness != 0.f ? m_Goodness/m_Maxness : 0.f; }
Winner * StructPath::getWinner (MStructure & struc)
Definition at line 556 of file StructTable.cpp.
References MStructure::getName(), MStructure::getWinner(), and NULL.
 {
     iterator wi = find(struc.getName());
     if(wi != end() && wi->second) {
         Winner* winner = (Winner*)struc.getWinner(wi->second);
         if(!winner) wi->second = 0;
         return winner;
     } else return NULL;
 }
const Winner * StructPath::getWinner (const MStructure & struc) const
Definition at line 566 of file StructTable.cpp.
References MStructure::getName(), MStructure::getWinner(), and NULL.
 {
     const_iterator wi = find(struc.getName());
     if(wi != end() && wi->second)
     {
         const Winner* winner = struc.getWinner(wi->second);
         if(!winner) (dword&)(wi->second) = 0;
         return winner;
     } else return NULL;
 }
void StructPath::merge (const StructPath & mp)
Definition at line 673 of file StructTable.cpp.
References m_Goodness, m_Maxness, Winner::WID_BLOCKED, and Winner::WID_EMPTY.
Referenced by StructTable::findBestConnection(), and getRelGoodness().
 {
     for(const_iterator wi = mp.begin(); wi != mp.end(); wi++)
         if(wi->second != Winner::WID_EMPTY &&
            wi->second != Winner::WID_BLOCKED)
             operator[](wi->first) = wi->second;
     m_Goodness += mp.m_Goodness; m_Maxness += mp.m_Maxness;
 }
StructPath & StructPath::operator= (const StructPath & rhs)
Definition at line 537 of file StructTable.cpp.
References m_Goodness, m_Maxness, and m_WinnersProtected.
Referenced by StructPath().
 {
     if(this != &rhs) {
         map<string,dword>::operator=(rhs);
         m_Goodness = rhs.m_Goodness;
         m_WinnersProtected = rhs.m_WinnersProtected;
         m_Maxness = rhs.m_Maxness;
     }
     return *this;
 }
ostream & StructPath::print (std::ostream & os, const StructTable & structs) const
Definition at line 624 of file StructTable.cpp.
References Winner::getConnection(), Model::getQualityOfFit(), getRelGoodness(), StructTable::getStructure(), MStructure::getSupStruct(), MStructure::getWeight(), MStructure::getWinner(), MStructure::hasSupStruct(), Winner::m_BestRating, m_Goodness, Winner::m_Model, SubStructure::m_RateWeight, Winner::WID_BLOCKED, and Winner::WID_EMPTY.
Referenced by getGoodness().
 {
     os << setw(10);
     os << "path goodness: " << m_Goodness << " ("
        << getRelGoodness() << ")" << endl;
     for(const_iterator wi = begin(); wi != end(); wi++)
     {
         if(wi->second != Winner::WID_EMPTY &&
            wi->second != Winner::WID_BLOCKED)
         {
             os << "  " << wi->first;
             const MStructure& st = structs.getStructure(wi->first);
             const Winner* winner = st.getWinner(wi->second);
             if(winner) {
                 if(winner->m_Model)
                     os << "\t ("<< st.getWeight() <<") * "
                        << winner->m_Model->getQualityOfFit() << endl;
                 else os << "\t (no model)"<<endl;
                 for(const_iterator ri = begin(); ri != end(); ri++)
                 {
                     float rating = winner->getConnection(ri->first,
                                                          ri->second);
                     if(rating>=0.f) {
                         if(st.hasSupStruct(ri->first)) {
                             const SubStructure& subs =
                                 st.getSupStruct(ri->first);
                             os << "    <--[" << ri->first
                                << "\t] = ("<<subs.m_RateWeight<<") * "
                                << rating << endl;
                         }
                     }
                 }
                 os << "       (best: " << winner->m_BestRating << ")" << endl;
             } else os << " (deleted)"<< endl;
         }
     }
     os << setw(0) << flush;
     return os;
 }
void StructPath::protectWinners (StructTable & structs)
Definition at line 577 of file StructTable.cpp.
References StructTable::getStructs(), Winner::m_Model, m_WinnersProtected, Model::setFlags(), Model::ST_NODEL, Winner::WID_FIRST, and Winner::WID_LAST.
Referenced by getGoodness().
 {
     if(m_WinnersProtected) return;
     for(iterator wi = begin(); wi != end(); wi++)
     {
         if(wi->second>=Winner::WID_FIRST &&
            wi->second<=Winner::WID_LAST) {
             Winner* winner = (Winner*)structs.getStructs()[wi->first]
                 .getWinner(wi->second);
             if(winner && winner->m_Model) {
                 winner->m_Model->setFlags(Model::ST_NODEL);
             } else wi->second = 0;
         }
     }
     m_WinnersProtected = true;
 }
void StructPath::unprotectWinners (StructTable & structs)
Definition at line 594 of file StructTable.cpp.
References StructTable::getStructs(), Winner::m_Model, m_WinnersProtected, Model::ST_NODEL, Model::unsetFlags(), Winner::WID_FIRST, and Winner::WID_LAST.
Referenced by getGoodness().
 {
     if(!m_WinnersProtected) return;
     for(iterator wi = begin(); wi != end(); wi++)
     {
         if(wi->second>=Winner::WID_FIRST &&
            wi->second<=Winner::WID_LAST) {
             Winner* winner = (Winner*)structs.getStructs()[wi->first]
                 .getWinner(wi->second);
             if(winner && winner->m_Model) {
                 winner->m_Model->unsetFlags(Model::ST_NODEL);
             } else wi->second = 0;
         }
     }
     m_WinnersProtected = false;
 }
Member Data Documentation
float StructPath::m_Goodness
goodness of path
Definition at line 42 of file StructTable.h.
Referenced by branch(), clear(), StructTable::findBestConnection(), getGoodness(), getRelGoodness(), merge(), operator=(), and print().
float StructPath::m_Maxness
maximum goodness
Definition at line 43 of file StructTable.h.
Referenced by branch(), clear(), StructTable::findBestConnection(), getRelGoodness(), merge(), and operator=().
bool StructPath::m_WinnersProtected protected
Definition at line 45 of file StructTable.h.
Referenced by blockOtherPaths(), clear(), operator=(), protectWinners(), and unprotectWinners().
The documentation for this class was generated from the following files:
src/StructTable.h
src/StructTable.cpp