Structural deformable models: DMatrix< T > Class Template Reference
DMatrix< T > Class Template Reference
#include <DMatrix.h>
Public Types
typedef std::vector< T >::const_iterator const_iterator
typedef std::vector< T >::iterator iterator
typedef T * TPtr
typedef const T * CTPtr
typedef DMatrix< T > MT
Public Member Functions
DMatrix (dword _sx=0, dword _sy=0, const T &inival=T())
DMatrix (dword _sx, dword _sy, const T *data)
~DMatrix ()
MT & resize (dword _sx, dword _sy, const T &inival=T())
MT & reshape (dword _sx, dword _sy)
void clear ()
dword sizeX () const
dword sizeY () const
dword size () const
dword index (dword x, dword y) const
T & at (dword x, dword y)
const T & at (dword x, dword y) const
std::vector< T > & getData ()
const std::vector< T > & getData () const
bool empty () const
MT & operator= (const T &rhs)
MT & operator= (const T *rhs)
MT & operator+= (const MT &rhs)
MT & operator-= (const MT &rhs)
MT & operator*= (const MT &rhs)
MT & operator/= (const MT &rhs)
MT & operator+= (const T &rhs)
MT & operator-= (const T &rhs)
MT & operator*= (const T &rhs)
MT & operator/= (const T &rhs)
MT & max (const MT &rhs)
MT & max (const T &rhs)
T max () const
MT & min (const MT &rhs)
MT & min (const T &rhs)
T min () const
MT mulRight (const MT &rhs) const
MT mulLeft (const MT &rhs) const
MT & setCol (dword col, MT &vec)
MT & setCol (dword col, const T &val=1)
MT & setRow (dword row, MT &vec)
MT & setRange (dword ox, dword oy, const MT &mat)
MT & getRange (dword ox, dword oy, MT &mat) const
MT & setRow (dword row, const T &val=1)
MT & setDiag (MT &vec, int offset=0)
MT & setDiag (const T &val=1, int offset=0)
MT getDiag (int offset=0)
MT & setUpper (const T &val=1, int offset=0)
MT & setLower (const T &val=1, int offset=0)
MT & transpose ()
Protected Attributes
dword sx
dword sy
std::vector< T > values
Friends
std::ostream & operator<< (std::ostream &os, const DMatrix< T > &rhs)
std::istream & operator>> (std::istream &is, DMatrix< T > &rhs)
Detailed Description
template<class T>
class DMatrix< T >
Small matrix class. First index is colum number. Memory arrangement is row-wise.
Definition at line 12 of file DMatrix.h.
Member Typedef Documentation
template<class T> typedef std::vector<T>::const_iterator DMatrix< T >::const_iterator
Definition at line 14 of file DMatrix.h.
template<class T> typedef const T* DMatrix< T >::CTPtr
Definition at line 17 of file DMatrix.h.
template<class T> typedef std::vector<T>::iterator DMatrix< T >::iterator
Definition at line 15 of file DMatrix.h.
template<class T> typedef DMatrix<T> DMatrix< T >::MT
Definition at line 18 of file DMatrix.h.
template<class T> typedef T* DMatrix< T >::TPtr
Definition at line 16 of file DMatrix.h.
Constructor & Destructor Documentation
template<class T> DMatrix< T >::DMatrix (dword _sx = 0, dword _sy = 0, const T & inival = T()) inline
Definition at line 20 of file DMatrix.h.
         : sx(_sx), sy(_sy), values(_sx*_sy, inival) {}
template<class T> DMatrix< T >::DMatrix (dword _sx, dword _sy, const T * data) inline
Definition at line 22 of file DMatrix.h.
         : sx(_sx), sy(_sy), values(_sx*_sy) {
         operator=(data);
     }
template<class T> DMatrix< T >::~DMatrix () inline
Definition at line 26 of file DMatrix.h.
 {}
Member Function Documentation
template<class T> T& DMatrix< T >::at (dword x, dword y) inline
Definition at line 44 of file DMatrix.h.
Referenced by MStructure::addExpectation(), Model::adjMat(), SubStructure::analyseTF(), MahalSensor::calcValue(), Model::createByAdjMat(), SubStructure::generateEMDist(), dmutil::makeDiag(), dmutil::makeRotMat2D(), DMatrix< float >::mulRight(), dmutil::pseudoInv(), Model::removeByAdjMat(), Model::scaleSel(), MStructure::showStats(), dmutil::SVD(), and DMatrix< float >::transpose().
 { return values[index(x,y)]; }
template<class T> const T& DMatrix< T >::at (dword x, dword y) const inline
Definition at line 45 of file DMatrix.h.
 { return values[index(x,y)]; }
template<class T> void DMatrix< T >::clear () inline
Definition at line 38 of file DMatrix.h.
 { values.clear(); sx = sy = 0; }
template<class T> bool DMatrix< T >::empty () const inline
Definition at line 48 of file DMatrix.h.
Referenced by SubStructure::analyseTF(), SubStructure::generateEMDist(), and hgPropTF().
 { return values.empty(); }
template<class T> std::vector<T>& DMatrix< T >::getData () inline
Definition at line 46 of file DMatrix.h.
Referenced by dmutil::abs(), StructTable::adjustByAvgDir(), DMatrix< float >::getDiag(), dmutil::makeDiag(), DMatrix< float >::setCol(), DMatrix< float >::setDiag(), DMatrix< float >::setRow(), dmutil::sqr(), dmutil::sqrt(), dmutil::sum(), and dmutil::threshold().
 { return values; }
template<class T> const std::vector<T>& DMatrix< T >::getData () const inline
Definition at line 47 of file DMatrix.h.
 { return values; }
template<class T> MT DMatrix< T >::getDiag (int offset = 0) inline
Definition at line 229 of file DMatrix.h.
Referenced by SubStructure::analyseTF().
{
         int count = offset>=0 ? sx-offset : sy+offset;
         MT res(1,count);
         const_iterator vi = values.begin()+( offset>=0 ? offset : -offset*sx);
         for(iterator ri = res.getData().begin(); count>0;
             count--, ri++, vi+=sx+1)
             *ri = *vi;
         return res;
     }
template<class T> MT& DMatrix< T >::getRange (dword ox, dword oy, MT & mat) const inline
Definition at line 195 of file DMatrix.h.
Referenced by SubStructure::analyseTF(), and dmutil::SVD().
{
         assert(ox<sx && oy<sy);
         dword width = mat.sx <= sx-ox ? mat.sx : sx-ox;
         dword height = mat.sy <= sy-oy ? mat.sy : sy-oy;
         for(dword y = 0; y<height; y++) {
             const_iterator src = values.begin()+index(ox,oy+y);
             iterator dst = mat.values.begin() + mat.index(0,y);
             for(dword x=0; x<width; x++, src++, dst++)
                 *dst = *src;
         }
         return mat;
     }
template<class T> dword DMatrix< T >::index (dword x, dword y) const inline
Definition at line 43 of file DMatrix.h.
Referenced by DMatrix< float >::at(), DMatrix< float >::getRange(), and DMatrix< float >::setRange().
 { return y*sx+x; }
template<class T> MT& DMatrix< T >::max (const MT & rhs) inline
Definition at line 108 of file DMatrix.h.
Referenced by MStructure::addExpectation(), and MStructure::showStats().
{
         const_iterator ri = rhs.values.begin();
         for(iterator vi = values.begin(); vi != values.end(); vi++, ri++)
             if(*vi < *ri) *vi = *ri;
         return *this;
     }
template<class T> MT& DMatrix< T >::max (const T & rhs) inline
Definition at line 114 of file DMatrix.h.
{
         for(iterator vi = values.begin(); vi != values.end(); vi++)
             if(*vi < rhs) *vi = rhs;
         return *this;
     }
template<class T> T DMatrix< T >::max () const inline
Definition at line 119 of file DMatrix.h.
                   {
         assert(sx>0 && sy>0);
         //T val = std::numeric_limits<T>::min();
         T val(values[0]);
         for(const_iterator vi = values.begin(); vi != values.end(); vi++)
             if(*vi > val) val = *vi;
         return val;
     }
template<class T> MT& DMatrix< T >::min (const MT & rhs) inline
Definition at line 127 of file DMatrix.h.
Referenced by MStructure::addExpectation(), Model::connectNodes(), Model::selMaskMat(), and MStructure::showStats().
{
         const_iterator ri = rhs.values.begin();
         for(iterator vi = values.begin(); vi != values.end(); vi++, ri++)
             if(*vi > *ri) *vi = *ri;
         return *this;
     }
template<class T> MT& DMatrix< T >::min (const T & rhs) inline
Definition at line 133 of file DMatrix.h.
{
         for(iterator vi = values.begin(); vi != values.end(); vi++)
             if(*vi > rhs) *vi = rhs;
         return *this;
     }
template<class T> T DMatrix< T >::min () const inline
Definition at line 138 of file DMatrix.h.
                   {
         assert(sx>0 && sy>0);
         //T val = std::numeric_limits<T>::max();
         T val(values[0]);
         for(const_iterator vi = values.begin(); vi != values.end(); vi++)
             if(*vi < val) val = *vi;
         return val;
     }
template<class T> MT DMatrix< T >::mulLeft (const MT & rhs) const inline
Definition at line 157 of file DMatrix.h.
Referenced by SubStructure::generateEMDist(), and hgPropTF().
{
         return rhs.mulRight(*this);
     }
template<class T> MT DMatrix< T >::mulRight (const MT & rhs) const inline
Definition at line 147 of file DMatrix.h.
Referenced by SubStructure::analyseTF(), MahalSensor::calcValue(), DMatrix< float >::mulLeft(), and dmutil::pseudoInv().
{
         assert(rhs.sy == sx);
         MT res(rhs.sx, sy, T(0));
         for(dword rx=0; rx<rhs.sx; rx++)
             for( dword ly=0; ly<sy; ly++)
                 for(dword ry=0; ry<rhs.sy; ry++)
                     res.at(rx, ly) += at(ry, ly)*rhs.at(rx, ry);
         return res;
     }
template<class T> MT& DMatrix< T >::operator*= (const MT & rhs) inline
Definition at line 74 of file DMatrix.h.
{
         const_iterator ri = rhs.values.begin();
         for(iterator vi = values.begin(); vi != values.end(); vi++, ri++)
             *vi *= *ri;
         return *this;
     }
template<class T> MT& DMatrix< T >::operator*= (const T & rhs) inline
Definition at line 97 of file DMatrix.h.
{
         for(iterator vi = values.begin(); vi != values.end(); vi++)
             *vi *= rhs;
         return *this;
     }
template<class T> MT& DMatrix< T >::operator+= (const MT & rhs) inline
Definition at line 62 of file DMatrix.h.
{
         const_iterator ri = rhs.values.begin();
         for(iterator vi = values.begin(); vi != values.end(); vi++, ri++)
             *vi += *ri;
         return *this;
     }
template<class T> MT& DMatrix< T >::operator+= (const T & rhs) inline
Definition at line 87 of file DMatrix.h.
{
         for(iterator vi = values.begin(); vi != values.end(); vi++)
             *vi += rhs;
         return *this;
     }
template<class T> MT& DMatrix< T >::operator-= (const MT & rhs) inline
Definition at line 68 of file DMatrix.h.
{
         const_iterator ri = rhs.values.begin();
         for(iterator vi = values.begin(); vi != values.end(); vi++, ri++)
             *vi -= *ri;
         return *this;
     }
template<class T> MT& DMatrix< T >::operator-= (const T & rhs) inline
Definition at line 92 of file DMatrix.h.
{
         for(iterator vi = values.begin(); vi != values.end(); vi++)
             *vi -= rhs;
         return *this;
     }
template<class T> MT& DMatrix< T >::operator/= (const MT & rhs) inline
Definition at line 80 of file DMatrix.h.
{
         const_iterator ri = rhs.values.begin();
         for(iterator vi = values.begin(); vi != values.end(); vi++, ri++)
             *vi /= *ri;
         return *this;
     }
template<class T> MT& DMatrix< T >::operator/= (const T & rhs) inline
Definition at line 102 of file DMatrix.h.
{
         for(iterator vi = values.begin(); vi != values.end(); vi++)
             *vi /= rhs;
         return *this;
     }
template<class T> MT& DMatrix< T >::operator= (const T & rhs) inline
Definition at line 50 of file DMatrix.h.
Referenced by DMatrix< float >::DMatrix().
{
         for(iterator vi = values.begin(); vi != values.end(); vi++)
             *vi += rhs;
         return *this;
     }
template<class T> MT& DMatrix< T >::operator= (const T * rhs) inline
Definition at line 56 of file DMatrix.h.
{
         for(iterator vi = values.begin(); vi != values.end(); vi++, rhs++)
             *vi += *rhs;
         return *this;
     }
template<class T> MT& DMatrix< T >::reshape (dword _sx, dword _sy) inline
Definition at line 33 of file DMatrix.h.
Referenced by DMatrix< float >::transpose().
{
         assert(sx*sy == _sx*_sy);
         sx = _sx; sy = _sy;
         return *this;
     }
template<class T> MT& DMatrix< T >::resize (dword _sx, dword _sy, const T & inival = T()) inline
Definition at line 28 of file DMatrix.h.
Referenced by SubStructure::analyseTF(), and dmutil::SVD().
{
         sx = _sx; sy = _sy;
         values.resize(sx*sy, inival);
         return *this;
     }
template<class T> MT& DMatrix< T >::setCol (dword col, MT & vec) inline
Definition at line 161 of file DMatrix.h.
Referenced by Model::selMaskMat(), and dmutil::SVD().
{
         assert(sy == vec.getData().size());
         iterator vi = values.begin()+col;
         for(const_iterator ri = vec.getData().begin();
             ri != vec.getData().end(); ri++, vi+=sx)
             *vi = *ri;
         return *this;
     }
template<class T> MT& DMatrix< T >::setCol (dword col, const T & val = 1) inline
Definition at line 169 of file DMatrix.h.
{
         iterator vi = values.begin()+col;
         for(dword i=0; i<sy; i++, vi+=sx)
             *vi = val;
         return *this;
     }
template<class T> MT& DMatrix< T >::setDiag (MT & vec, int offset = 0) inline
Definition at line 213 of file DMatrix.h.
{
         int count = offset>=0 ? sx-offset : sy+offset;
         assert( count <= vec.getData().size() );
         iterator vi = values.begin() + ( offset>=0 ? offset : -offset*sx);
         for(const_iterator ri = vec.getData().begin(); count>0;
             count--, ri++, vi+=sx+1)
             *vi = *ri;
         return *this;
     }
template<class T> MT& DMatrix< T >::setDiag (const T & val = 1, int offset = 0) inline
Definition at line 222 of file DMatrix.h.
{
         int count = offset>=0 ? sx-offset : sy+offset;
         iterator vi = values.begin() + ( offset>=0 ? offset : -offset*sx);
         for(; count>0; count--, vi+=(sx+1))
             *vi = val;
         return *this;
     }
template<class T> MT& DMatrix< T >::setLower (const T & val = 1, int offset = 0) inline
Definition at line 248 of file DMatrix.h.
Referenced by Model::adjMat(), and Model::connectNodes().
{
         int i=0,j=0;
         for(iterator mi = values.begin();
             mi != values.end(); mi++, i++) {
             if(i==(int)sx) { j++; i=0; }
             if(i-j<=offset) *mi = val;
         }
         return *this;
     }
template<class T> MT& DMatrix< T >::setRange (dword ox, dword oy, const MT & mat) inline
Definition at line 183 of file DMatrix.h.
Referenced by SubStructure::analyseTF(), MStructure::buildAllStats(), dmutil::expand(), hgPropTF(), dmutil::horizCat(), MStructure::showStats(), and dmutil::vertCat().
{
         assert(ox<sx && oy<sy);
         dword width = mat.sx <= sx-ox ? mat.sx : sx-ox;
         dword height = mat.sy <= sy-oy ? mat.sy : sy-oy;
         for(dword y = 0; y<height; y++) {
             iterator dst = values.begin()+index(ox,oy+y);
             const_iterator src = mat.values.begin() + mat.index(0,y);
             for(dword x=0; x<width; x++, src++, dst++)
                 *dst = *src;
         }
         return *this;
     }
template<class T> MT& DMatrix< T >::setRow (dword row, MT & vec) inline
Definition at line 175 of file DMatrix.h.
Referenced by Model::selMaskMat().
{
         assert(sx == vec.getData().size());
         iterator vi = values.begin()+(row*sx);
         for(const_iterator ri = vec.getData().begin();
             ri != vec.getData().end(); ri++, vi++)
             *vi = *ri;
         return *this;
     }
template<class T> MT& DMatrix< T >::setRow (dword row, const T & val = 1) inline
Definition at line 207 of file DMatrix.h.
{
         iterator vi = values.begin()+(row*sx);
         for(dword i=0; i<sx; i++, vi++)
             *vi = val;
         return *this;
     }
template<class T> MT& DMatrix< T >::setUpper (const T & val = 1, int offset = 0) inline
Definition at line 239 of file DMatrix.h.
{
         int i=0,j=0;
         for(iterator mi = values.begin();
             mi != values.end(); mi++, i++) {
             if(i==sx) { j++; i=0; }
             if(i-j>=offset) *mi = val;
         }
         return *this;
     }
template<class T> dword DMatrix< T >::size () const inline
Definition at line 42 of file DMatrix.h.
Referenced by StructTable::adjustByAvgDir(), and dmutil::makeDiag().
 { return values.size(); }
template<class T> dword DMatrix< T >::sizeX () const inline
Definition at line 40 of file DMatrix.h.
Referenced by SubStructure::analyseTF(), dmutil::convert(), Model::createByAdjMat(), dmutil::expand(), SubStructure::generateEMDist(), hgPropTF(), dmutil::horizCat(), dmutil::pseudoInv(), Model::removeByAdjMat(), EMDXformer::setTFMat(), dmutil::sum(), dmutil::SVD(), and dmutil::vertCat().
 { return sx; }
template<class T> dword DMatrix< T >::sizeY () const inline
Definition at line 41 of file DMatrix.h.
Referenced by SubStructure::analyseTF(), dmutil::avg(), dmutil::convert(), Model::createByAdjMat(), dmutil::expand(), hgPropTF(), dmutil::horizCat(), dmutil::pseudoInv(), Model::removeByAdjMat(), EMDXformer::setTFMat(), dmutil::sum(), dmutil::SVD(), and dmutil::vertCat().
 { return sy; }
template<class T> MT& DMatrix< T >::transpose () inline
Definition at line 258 of file DMatrix.h.
Referenced by Model::adjMat(), SubStructure::analyseTF(), MahalSensor::calcValue(), and dmutil::pseudoInv().
                     {
         if(sx*sy>1) {
             if(sx==sy)
                 for(dword j=0; j<sy-1; j++)
                     for(dword i = j+1; i<sx; i++)
                     {
                         T& a = at(i,j);
                         T& b = at(j,i);
                         T dummy = a; a = b; b = dummy;
                     }
             else if(sx == 1 || sy == 1) reshape(sy, sx);
             else {
                 MT tmp(*this);
                 reshape(sy,sx);
                 for(dword j=0; j<sy; j++)
                     for(dword i = 0; i<sx; i++)
                     {
                         at(i,j) = tmp.at(j,i);
                     }
             }
         }
         return *this;
     }
Friends And Related Function Documentation
template<class T> std::ostream& operator<< (std::ostream & os, const DMatrix< T > & rhs) friend
Definition at line 282 of file DMatrix.h.
{
         os << rhs.sx << " " << rhs.sy;
         dword cc=0;
         for(const_iterator vi = rhs.values.begin();
             vi != rhs.values.end(); vi++, cc--) {
             if(!cc) { cc = rhs.sx; os << std::endl; }
             else os << " ";
             os << *vi;
         }
         os << std::endl;
         return os;
     }
template<class T> std::istream& operator>> (std::istream & is, DMatrix< T > & rhs) friend
Definition at line 294 of file DMatrix.h.
{
         is >> rhs.sx; is >> rhs.sy;
         rhs.resize(rhs.sx, rhs.sy);
         for(iterator vi = rhs.values.begin();
             vi != rhs.values.end(); vi++)
             is >> *vi;
         return is;
     }
Member Data Documentation
template<class T> dword DMatrix< T >::sx protected
Definition at line 304 of file DMatrix.h.
Referenced by DMatrix< float >::clear(), DMatrix< float >::getDiag(), DMatrix< float >::getRange(), DMatrix< float >::index(), DMatrix< float >::max(), DMatrix< float >::min(), DMatrix< float >::mulRight(), DMatrix< float >::reshape(), DMatrix< float >::resize(), DMatrix< float >::setCol(), DMatrix< float >::setDiag(), DMatrix< float >::setLower(), DMatrix< float >::setRange(), DMatrix< float >::setRow(), DMatrix< float >::setUpper(), DMatrix< float >::sizeX(), and DMatrix< float >::transpose().
template<class T> dword DMatrix< T >::sy protected
Definition at line 304 of file DMatrix.h.
Referenced by DMatrix< float >::clear(), DMatrix< float >::getDiag(), DMatrix< float >::getRange(), DMatrix< float >::max(), DMatrix< float >::min(), DMatrix< float >::mulRight(), DMatrix< float >::reshape(), DMatrix< float >::resize(), DMatrix< float >::setCol(), DMatrix< float >::setDiag(), DMatrix< float >::setRange(), DMatrix< float >::sizeY(), and DMatrix< float >::transpose().
template<class T> std::vector<T> DMatrix< T >::values protected
Definition at line 305 of file DMatrix.h.
Referenced by DMatrix< float >::at(), DMatrix< float >::clear(), DMatrix< float >::empty(), DMatrix< float >::getData(), DMatrix< float >::getDiag(), DMatrix< float >::getRange(), DMatrix< float >::max(), DMatrix< float >::min(), DMatrix< float >::operator*=(), DMatrix< float >::operator+=(), DMatrix< float >::operator-=(), DMatrix< float >::operator/=(), DMatrix< float >::operator=(), DMatrix< float >::resize(), DMatrix< float >::setCol(), DMatrix< float >::setDiag(), DMatrix< float >::setLower(), DMatrix< float >::setRange(), DMatrix< float >::setRow(), DMatrix< float >::setUpper(), and DMatrix< float >::size().
The documentation for this class was generated from the following file:
src/DMatrix.h