Structural deformable models: MappingSensor Class Reference
MappingSensor Class Reference
#include <SensorSet.h>
Public Types
enum MappingTypes {
MS_IDENTITY, MS_CLAMPLU, MS_CLAMPL, MS_CLAMPU,
MS_GAUSSNORM, MS_MGAUSSNORM, MS_MCLAMPU, MS_BIAS,
MS_LAST
}
Public Types inherited from PPSensor
enum PPState { PP_DONT =0, PP_DO, PP_FORCE }
Public Types inherited from Sensor
enum UpdateParam {
UPD_NOTHING =0, UPD_DATA =1, UPD_SCALE =2, UPD_CWEIGHTS =4,
UPD_DIR =8, UPD_MINMAX =16, UPD_LAST =32, UPD_ALL =0xffffffff
}
Public Member Functions
MappingSensor (const Sensor *_source=NULL, const std::string &mapn="")
int getNChannels () const
Sensor & assign (const Sensor &rhs)
std::ostream & print (std::ostream &os) const
const char * getMappingName () const
dword getMappingID () const
dword setMappingID (dword id)
dword setMapping (const std::string &mname)
bool readParams (std::istream &is)
bool performUpdate ()
Public Member Functions inherited from PPSensor
PPSensor (const Sensor *_source)
virtual float getValue (int x, int y) const
virtual Point getGradient (int x, int y) const
void togglePP (enum PPState state=PP_DO)
dword getPPState () const
Public Member Functions inherited from Sensor
Sensor (const Sensor *_source=NULL)
virtual ~Sensor ()
const Sensor * getSource ()
virtual void changeSource (const Sensor *_source)
void replaceBy (Sensor *target)
bool assignRef (const Sensor *rhs)
float getValue (const Point &p) const
get value at position p using nearest neighbour interpolation
virtual std::vector< float > getMValue (int x, int y) const
get multi-channel value
Point2D getGradient (const Point2D &p) const
get gradient at position p using nearest neighbor interpolation
float getMax () const
float getMin () const
float getMinMaxRange () const
float getWeightedValue (int x, int y) const
get max normalized value at discrete position range [0,1]
Point2D getWeightedGradient (int x, int y) const
get range weighted gradient at discrete position
void setCWeights (const std::vector< float > &weights)
const std::vector< float > & getCWeights () const
void setDirection (const Point &dir)
const Point & getDirection () const
void setScale (float _scale)
float getScale () const
bool isModified (dword mask=UPD_ALL) const
void setModified (dword mask=UPD_ALL)
void unsetModified (dword mask=UPD_ALL)
bool isUpdate (dword udMask) const
void enableUpdate (dword udMask)
void disableUpdate (dword udMask)
virtual int getDim1Size () const
virtual int getDim2Size () const
virtual int getDim3Size () const
virtual int getSkip () const
bool isValid (int x, int y) const
virtual Image< float > createSensorImage () const
const std::string & getID () const
void setID (const std::string &id)
virtual std::ostream & hprint (std::ostream &os, SensorCollection *sc) const
void refSuperSensor (Sensor *super)
void unrefSuperSensor (Sensor *super)
void invalidateSource ()
Protected Member Functions
virtual float calcValue (int x, int y) const
Computes saturation or some other colour indicator.
Protected Member Functions inherited from PPSensor
void fitSheets ()
virtual void calcAllValues ()
virtual void calcAllGradients ()
Protected Member Functions inherited from Sensor
virtual std::vector< float > calcMValue (int x, int y) const
virtual Point calcGradient (int x, int y) const
virtual void calcMinMax ()
Protected Attributes
dword m_MappingID
std::vector< float > m_Param
Protected Attributes inherited from PPSensor
Image< float > values
caching sheet for sensed values
Image< Point > gradients
caching sheet for gradients
dword doPP
do preprocessing?
Protected Attributes inherited from Sensor
const Sensor * source
float scale
std::vector< float > cweights
multi-channel weights ('color')
Point dir
direction parameter
float maxval
float minval
overall minimum and maximum
float mean
float stdev
overall mean and stdev
dword toupdate
bitflag for updates
dword updateMask
bitflag to mask unimportant updates
std::string m_ID
int m_Skip
int m_AddSkip
Static Protected Attributes
static const char * s_MappingNames []
Additional Inherited Members
Static Public Member Functions inherited from Sensor
static dword getStringNumber (const char *sid)
static void getNumberString (char sid[5], dword id)
Detailed Description
Sensor performing various mappings
Definition at line 367 of file SensorSet.h.
Member Enumeration Documentation
enum MappingSensor::MappingTypes
Enumerator
MS_IDENTITY
MS_CLAMPLU
MS_CLAMPL
MS_CLAMPU
MS_GAUSSNORM
MS_MGAUSSNORM
MS_MCLAMPU
MS_BIAS
MS_LAST
Definition at line 369 of file SensorSet.h.
                       {MS_IDENTITY, MS_CLAMPLU, MS_CLAMPL, MS_CLAMPU,
                        MS_GAUSSNORM, MS_MGAUSSNORM, MS_MCLAMPU, MS_BIAS,
                        MS_LAST};
Constructor & Destructor Documentation
MappingSensor::MappingSensor (const Sensor * _source = NULL, const std::string & mapn = "") inline
Definition at line 373 of file SensorSet.h.
References Sensor::m_AddSkip.
         : PPSensor(_source)
         {
             m_AddSkip = 1;
             setMapping(mapn);
         }
Member Function Documentation
Sensor & MappingSensor::assign (const Sensor & rhs) virtual
Reimplemented from PPSensor.
Definition at line 285 of file SensorSet.cpp.
References PPSensor::assign(), m_MappingID, and m_Param.
 {
     if(&rhs != this) {
         PPSensor::assign(rhs);
         if(typeid(&rhs) == typeid(MappingSensor*)) {
             const MappingSensor& crhs = (const MappingSensor&) rhs;
             m_MappingID = crhs.m_MappingID;
             m_Param = crhs.m_Param;
         }
     }
     return *this;
 }
virtual float MappingSensor::calcValue (int x, int y) const inline protected virtual
Computes saturation or some other colour indicator.
Implements Sensor.
Definition at line 392 of file SensorSet.h.
References Sensor::getValue(), and Sensor::source.
{
         float v = source->getValue(x,y);
         switch(m_MappingID) {
 //             case MS_IDENTITY:
 //                 break;
             case MS_CLAMPL:
                 if(v < m_Param[0]) v = m_Param[0];
                 break;
             case MS_CLAMPU:
                 if(v > m_Param[0]) v = m_Param[0];
                 break;
             case MS_CLAMPLU:
                 if(v < m_Param[0]) v = m_Param[0];
                 else if(v > m_Param[1]) v = m_Param[1];
                 break;
             case MS_MCLAMPU:
                 if(v > m_Param[1]) v = m_Param[1];
                 break;
             case MS_GAUSSNORM:
                 v = (v-m_Param[1])*m_Param[2]+0.5;
                 break;
             case MS_MGAUSSNORM:
                 if(v>0.f) v = (v-m_Param[1])*m_Param[2];
                 break;
             case MS_BIAS:
                 //if(v>0.f) {
                 v = (v-m_Param[1])*m_Param[2];
                 v = erf(v)*0.5+0.5;
                 //} else v = 0.f;
                 break;
         }
         return v;
     }
dword MappingSensor::getMappingID () const inline
Definition at line 384 of file SensorSet.h.
References Sensor::performUpdate().
 { return m_MappingID; }
const char* MappingSensor::getMappingName () const inline
Definition at line 382 of file SensorSet.h.
         { return s_MappingNames[m_MappingID]; }
int MappingSensor::getNChannels () const inline virtual
Reimplemented from Sensor.
Definition at line 379 of file SensorSet.h.
References Sensor::assign(), and IntensitySensor::print().
 { return 1; }
bool MappingSensor::performUpdate () virtual
clear all data sheets
Reimplemented from PPSensor.
Definition at line 351 of file SensorSet.cpp.
References Sensor::getDim1Size(), Sensor::getDim2Size(), Sensor::getValue(), Sensor::isModified(), PPSensor::performUpdate(), Sensor::source, and dmutil::sqrt().
{
     if(!isModified()) return false;
     if(source->getDim1Size()>0) {
         bool doanalysis = true;
         switch(m_MappingID) {
             case MS_MCLAMPU:
             case MS_GAUSSNORM:
             case MS_MGAUSSNORM:
             case MS_BIAS:
                 if(m_Param.size() < 4) m_Param.resize(4);
                 m_Param[1] = m_Param[2] = m_Param[3] = 0.f;
                 break;
             default:
                 doanalysis = false;
         }
         if(doanalysis) {
             int i,j;
             for(j=0; j<source->getDim2Size(); j++) {
                 for(i=0; i<source->getDim1Size(); i++)
                 {
                     float v = source->getValue(i,j);
                     switch(m_MappingID) {
                         case MS_BIAS:
                         case MS_GAUSSNORM:
                             m_Param[1] += v;
                             m_Param[2] += v*v;
                             m_Param[3]++;
                             break;
                         case MS_MCLAMPU:
                         case MS_MGAUSSNORM:
                             if(v>0) {
                                 m_Param[1] += v;
                                 m_Param[2] += v*v;
                                 m_Param[3]++;
                             }
                             break;
                     }
                 }
             }
             switch(m_MappingID) {
                 case MS_MCLAMPU:
                     m_Param[1] /= m_Param[3];
                     m_Param[2] /= m_Param[3];
                     m_Param[2] = sqrt(m_Param[2]-m_Param[1]*m_Param[1]);
                     m_Param[1] = m_Param[1]+m_Param[2]*m_Param[0];
                     break;
                 case MS_BIAS:
                 case MS_GAUSSNORM:
                     m_Param[1] /= m_Param[3];
                     m_Param[2] /= m_Param[3];
                     m_Param[2] = sqrt(m_Param[2]-m_Param[1]*m_Param[1]);
                     m_Param[2] = 1/(m_Param[2]*m_Param[0]);
                     break;
                 case MS_MGAUSSNORM:
                     m_Param[1] /= m_Param[3];
                     m_Param[2] /= m_Param[3];
                     m_Param[2] = sqrt(m_Param[2]-m_Param[1]*m_Param[1]);
                     m_Param[2] = 1/(m_Param[2]*m_Param[0]);
                     m_Param[1] = m_Param[1] - (m_Param[1]/m_Param[2]);
                     break;
             }
         }
     }
     return PPSensor::performUpdate();
 }
std::ostream & MappingSensor::print (std::ostream & os) const virtual
Reimplemented from Sensor.
Definition at line 298 of file SensorSet.cpp.
References Sensor::print().
 {
     Sensor::print(os)
         << "f " << getMappingName();
     for(vector<float>::const_iterator p=m_Param.begin(); p!=m_Param.end(); p++)
     {
         os << " " << *p;
     }
     return os;
 }
bool MappingSensor::readParams (std::istream & is)
Definition at line 322 of file SensorSet.cpp.
 {
     m_Param.clear();
     is >> ws;
     while(is) {
         float para= -0.12347891f;
         is >> para;
         if(para != -0.12347891f) m_Param.push_back(para);
         is >> ws;
     }
     dword psize = m_Param.size();
     if((m_MappingID == MS_CLAMPL ||
         m_MappingID == MS_CLAMPU ||
         m_MappingID == MS_GAUSSNORM ||
         m_MappingID == MS_MGAUSSNORM ||
         m_MappingID == MS_MCLAMPU ||
         m_MappingID == MS_BIAS)
        && psize<1)
     {
         m_MappingID = MS_IDENTITY;
         return false;
     }
     if(m_MappingID == MS_CLAMPLU && psize<2)
     {
         m_MappingID = MS_IDENTITY; return false;
     }
     return true;
 }
dword MappingSensor::setMapping (const std::string & mname)
Definition at line 315 of file SensorSet.cpp.
 {
     dword mid = 0;
     while(mid < MS_LAST && mname != s_MappingNames[mid]) mid++;
     return setMappingID(mid);
 }
dword MappingSensor::setMappingID (dword id)
Definition at line 309 of file SensorSet.cpp.
 {
     if(id>=MS_LAST) m_MappingID = 0; else m_MappingID = id;
     return m_MappingID;
 }
Member Data Documentation
dword MappingSensor::m_MappingID protected
Definition at line 427 of file SensorSet.h.
Referenced by assign().
std::vector<float> MappingSensor::m_Param protected
Definition at line 428 of file SensorSet.h.
Referenced by assign().
const char * MappingSensor::s_MappingNames static protected
Initial value:
=
{"identity","clamplu","clampl","clampu","gaussnorm","mgaussnorm",
 "mclampu", "bias", 0}
Definition at line 390 of file SensorSet.h.
Referenced by MahalSensor::saveConfig().
The documentation for this class was generated from the following files:
src/SensorSet.h
src/SensorSet.cpp