Structural deformable models: FFind Class Reference
FFind Class Reference
#include <FFind.h>
Public Member Functions
FFind (const string &pattern)
void setPattern (const string &pattern)
template<class T >
int findFiles (const std::string &fmask, T iter)
FFind ()
FFind (const std::string &pattern)
void setPattern (const std::string &pattern)
template<class T >
int find (const std::string &fmask, T iter)
Static Public Member Functions
template<class T >
static int findFiles (const std::string &fmask, T iter)
Protected Attributes
string m_Pattern
string m_Dir
std::string m_Pattern
std::string m_Dir
Detailed Description
Definition at line 16 of file ffind.cpp.
Constructor & Destructor Documentation
FFind::FFind (const string & pattern) inline
Definition at line 19 of file ffind.cpp.
 { setPattern(pattern); }
FFind::FFind () inline
Definition at line 18 of file FFind.h.
 {}
FFind::FFind (const std::string & pattern) inline
Definition at line 19 of file FFind.h.
References setPattern().
 { setPattern(pattern); }
Member Function Documentation
template<class T > int FFind::find (const std::string & fmask, T iter) inline
Definition at line 35 of file FFind.h.
References __fixed_fnmatch(), __set_fnmatchpattern(), findFiles(), m_Dir, m_Pattern, and setPattern().
Referenced by findFiles().
{
         setPattern(fmask);
         int n,nn;
 #ifdef LINUX
         struct dirent **namelist;
         // THIS IS NOT THREADSAFE :-(
         __set_fnmatchpattern(m_Pattern);
         nn = n = scandir(m_Dir.c_str(), &namelist, __fixed_fnmatch, alphasort);
         if (n < 0)
             return 0;
         else {
             while(n--) {
                 *iter++ = namelist[n]->d_name;
                 free(namelist[n]);
             }
             free(namelist);
         }
 #else
         nn = n = ::findFiles(fmask, iter);
 #endif
         return nn;
     }
template<class T > int FFind::findFiles (const std::string & fmask, T iter) inline
Definition at line 33 of file ffind.cpp.
References __fixed_fnmatch(), __fnmatchpattern, and perror().
Referenced by find(), and MStructure::getRefModelIDs().
{
         setPattern(fmask);
         struct dirent **namelist;
         int n;
         // THIS IS NOT THREADSAFE :-(
         strncpy(__fnmatchpattern, m_Pattern.c_str(), 2047);
         n = scandir(m_Dir.c_str(), &namelist, __fixed_fnmatch, alphasort);
         if (n < 0)
             perror("scandir");
         else {
             while(n--) {
                 *iter++ = namelist[n]->d_name;
                 free(namelist[n]);
             }
             free(namelist);
         }
     }
template<class T > static int FFind::findFiles (const std::string & fmask, T iter) inline static
Definition at line 59 of file FFind.h.
References find().
{
         FFind ff;
         return ff.find(fmask, iter);
     }
void FFind::setPattern (const std::string & pattern) inline
Definition at line 20 of file FFind.h.
References m_Dir, m_Pattern, and NULL.
{
         char *dname=NULL,*bname=NULL;
 #ifdef LINUX
         char *p1 = strdup(pattern.c_str());
         char *p2 = strdup(pattern.c_str());
         dname = dirname(p1);
         bname = basename(p2);
         m_Pattern = bname;
         m_Dir = dname;
         if(p1) free(p1);
         if(p2) free(p2);
 #endif
     }
void FFind::setPattern (const string & pattern) inline
Definition at line 20 of file ffind.cpp.
References NULL.
Referenced by FFind(), and find().
{
         char *dname=NULL,*bname=NULL;
         char *p1 = strdup(pattern.c_str());
         char *p2 = strdup(pattern.c_str());
         dname = dirname(p1);
         bname = basename(p2);
         m_Pattern = bname;
         m_Dir = dname;
         if(p1) free(p1);
         if(p2) free(p2);
     }
Member Data Documentation
string FFind::m_Dir protected
Definition at line 54 of file ffind.cpp.
Referenced by find(), and setPattern().
std::string FFind::m_Dir protected
Definition at line 66 of file FFind.h.
string FFind::m_Pattern protected
Definition at line 53 of file ffind.cpp.
Referenced by find(), and setPattern().
std::string FFind::m_Pattern protected
Definition at line 65 of file FFind.h.
The documentation for this class was generated from the following files:
src/ffind.cpp
src/FFind.h