Structural deformable models: ExpectationMap Class Reference
ExpectationMap Class Reference
#include <ExpMap.h>
Public Types
typedef std::map< dword, EMDistribution * > EDistributions
Public Types inherited from EMDistribution
enum EDFlags { ED_NONE =0, ED_OLD =1 }
Public Member Functions
ExpectationMap ()
ExpectationMap (const Model &model)
ExpectationMap (const ExpectationMap &rhs)
virtual ~ExpectationMap ()
ExpectationMap & operator= (const ExpectationMap &rhs)
virtual EMDistribution * copy () const
float ratePropVec (const PropVec &prop, Winner *winner=NULL) const
void setRepresentative (const Model &model)
Model & getRepresentative ()
void add (EMDistribution *ed)
void add (EMDistribution *ed, dword wid)
void add (const EDistributions &distlist)
bool erase (dword wid)
bool hasDist (dword wid) const
EMDistribution * getEDist (dword wid)
const EMDistribution * getEDist (dword wid) const
EDistributions & getDistList ()
virtual PropVec getPropVec () const
Model * generateInstance () const
float updateIntegral ()
void clear (bool oldonly=false)
void markAllOld ()
dword getShootCount (dword wid) const
operator bool () const
Public Member Functions inherited from EMDRect
EMDRect (const PropVec &lb=PropVec(0.f), const PropVec &ub=PropVec(1.f))
virtual ~EMDRect ()
PropVec & clamp (PropVec &v)
const PropVec & getUB () const
const PropVec & getLB () const
void setUB (const PropVec &ub)
void setLB (const PropVec &lb)
Public Member Functions inherited from EMDistribution
EMDistribution ()
virtual ~EMDistribution ()
virtual void setIntegral (float integral)
void setCreator (const Winner &creator)
void setShootCount (dword scount)
dword getShootCount () const
bool hasFlags (dword flags) const
void setFlags (dword flags)
void unsetFlags (dword flags=0xffffffff)
Static Public Member Functions
static void correctLBUB (PropVec &lb, PropVec &ub)
Protected Attributes
Model m_Representative
EDistributions m_Distributions
std::map< float, EMDistribution * > m_SortDist
Additional Inherited Members
Public Attributes inherited from EMDRect
PropVec m_LB
PropVec m_UB
Public Attributes inherited from EMDistribution
float m_Integral
Winner m_Creator
dword m_ShootCount
dword m_Flags
Detailed Description
Definition at line 142 of file ExpMap.h.
Member Typedef Documentation
typedef std::map<dword,EMDistribution*> ExpectationMap::EDistributions
Definition at line 144 of file ExpMap.h.
Constructor & Destructor Documentation
ExpectationMap::ExpectationMap () inline
Definition at line 146 of file ExpMap.h.
Referenced by copy().
 {}
ExpectationMap::ExpectationMap (const Model & model) inline
Definition at line 147 of file ExpMap.h.
         { setRepresentative(model); }
ExpectationMap::ExpectationMap (const ExpectationMap & rhs) inline
Definition at line 149 of file ExpMap.h.
{
         operator=(rhs); }
virtual ExpectationMap::~ExpectationMap () inline virtual
Definition at line 151 of file ExpMap.h.
References NULL.
 { clear(); }
Member Function Documentation
void ExpectationMap::add (EMDistribution * ed)
Definition at line 23 of file ExpMap.cpp.
References EMDistribution::m_Creator, m_Distributions, Winner::m_WinnerID, Winner::WID_EMPTY, and Winner::WID_FIRSTFREE.
Referenced by add(), MStructure::addExpectation(), main(), operator=(), MStructure::rebuildExpMap(), and Brain::setupSearch().
 {
     if(!ed) return;
     dword wid = ed->m_Creator.m_WinnerID;
     if(wid == Winner::WID_EMPTY) {
         if(!m_Distributions.empty()) wid = m_Distributions.rbegin()->first+1;
         if(wid < Winner::WID_FIRSTFREE) wid = Winner::WID_FIRSTFREE;
     }
     add(ed,wid);
 }
void ExpectationMap::add (EMDistribution * ed, dword wid)
Definition at line 34 of file ExpMap.cpp.
References erase(), m_Distributions, and updateIntegral().
 {
     if(!ed) return;
     erase(wid);
     m_Distributions[wid] = ed;
     updateIntegral();
 }
void ExpectationMap::add (const EDistributions & distlist)
Definition at line 42 of file ExpMap.cpp.
References add().
 {
     for(EDistributions::const_iterator dl=distlist.begin();
         dl != distlist.end(); dl++)
     {
         add(dl->second->copy());
     }
 }
void ExpectationMap::clear (bool oldonly = false)
Definition at line 141 of file ExpMap.cpp.
References EMDistribution::ED_OLD, m_Distributions, and updateIntegral().
Referenced by Searcher::clear(), operator=(), and MStructure::rebuildExpMap().
 {
     EDistributions::iterator dl=m_Distributions.begin();
     while(dl != m_Distributions.end())
     {
         EDistributions::iterator cd = dl++;
         if(cd->second)
         {
             if(!oldonly || cd->second->hasFlags(EMDistribution::ED_OLD)) {
                 delete cd->second;
                 if(oldonly) m_Distributions.erase(cd);
             }
         } else if(oldonly) m_Distributions.erase(cd);
     }
     if(!oldonly) m_Distributions.clear();
     if(oldonly) updateIntegral();
 }
EMDistribution * ExpectationMap::copy () const virtual
Reimplemented from EMDRect.
Definition at line 13 of file ExpMap.cpp.
References ExpectationMap().
 {
     return (EMDistribution*) new ExpectationMap(*this);
 }
void ExpectationMap::correctLBUB (PropVec & lb, PropVec & ub) static
Definition at line 193 of file ExpMap.cpp.
References VVector< T, D >::clampLB(), VVector< T, D >::clampUB(), getPropDir(), getPropScale(), M_PI, mapAngle2PI(), MIN_SCALE, setPropDir(), and setPropScale().
Referenced by MStructure::addExpectation(), SubStructure::generateEMDist(), MStructure::rebuildExpMap(), Searcher::setExpectationMap(), and Brain::setupSearch().
 {
     float la = mapAngle2PI(getPropDir(lb));
     float ua = mapAngle2PI(getPropDir(ub), la);
     if(ua-la < 0.00001) ua += 2*M_PI;
     setPropDir(lb, la); setPropDir(ub, ua);
     PropVec cub(ub); ub.clampLB(lb); lb.clampUB(cub); //conditional swap
     float ls = getPropScale(lb);
     if(ls < MIN_SCALE) setPropScale(lb, MIN_SCALE);
 }
bool ExpectationMap::erase (dword wid)
Definition at line 51 of file ExpMap.cpp.
References m_Distributions.
Referenced by add().
 {
     EDistributions::iterator ed = m_Distributions.find(wid);
     if(ed == m_Distributions.end()) return false;
     if(ed->second) delete ed->second;
     m_Distributions.erase(ed);
     return true;
 }
Model * ExpectationMap::generateInstance () const
Definition at line 184 of file ExpMap.cpp.
References Model::adaptProperties(), getPropVec(), and m_Representative.
Referenced by Searcher::distribute(), Searcher::evolve(), and main().
 {
     Model *model = new Model(m_Representative);
     PropVec v = getPropVec();
     model->adaptProperties(v);
     return model;
 }
EDistributions& ExpectationMap::getDistList () inline
Definition at line 164 of file ExpMap.h.
 { return m_Distributions; }
EMDistribution * ExpectationMap::getEDist (dword wid)
Definition at line 65 of file ExpMap.cpp.
References m_Distributions, and NULL.
Referenced by MStructure::addExpectation(), and getShootCount().
 {
     EDistributions::iterator ed = m_Distributions.find(wid);
     if(ed == m_Distributions.end()) return NULL;
     else return ed->second;
 }
const EMDistribution * ExpectationMap::getEDist (dword wid) const
Definition at line 72 of file ExpMap.cpp.
References m_Distributions, and NULL.
 {
     EDistributions::const_iterator ed = m_Distributions.find(wid);
     if(ed == m_Distributions.end()) return NULL;
     else return ed->second;
 }
PropVec ExpectationMap::getPropVec () const virtual
Reimplemented from EMDRect.
Definition at line 86 of file ExpMap.cpp.
References VVector< T, D >::clamp(), frand, getIdentityPropTF(), getPropDir(), m_Distributions, EMDistribution::m_Integral, EMDRect::m_LB, m_SortDist, EMDRect::m_UB, mapAngle2PI(), and setPropDir().
Referenced by generateInstance(), and main().
 {
     if(m_SortDist.empty() || m_Integral==0.0) {
         if(!m_Distributions.empty()) {
             ((ExpectationMap*)this)->updateIntegral();
             if(m_SortDist.empty() || m_Integral==0.0)
                 return getIdentityPropTF();
         } else return getIdentityPropTF();
     }
     float rint = frand(m_Integral);
     std::map<float, EMDistribution*>::const_iterator
         ed = m_SortDist.lower_bound(rint);
     if(ed == m_SortDist.end()) ed = m_SortDist.begin();
     ed->second->m_ShootCount++;
     PropVec prop = ed->second->getPropVec();
     setPropDir(prop, mapAngle2PI(getPropDir(prop),
                                  getPropDir(m_LB)));
     return prop.clamp(m_LB,m_UB);
     //return m_Distributions.begin()->getPropVec(); // is this fair?
 }
Model& ExpectationMap::getRepresentative () inline
Definition at line 156 of file ExpMap.h.
Referenced by Searcher::buildBins(), Searcher::distribute(), Searcher::reattachSensors(), and MStructure::rebuildExpMap().
 { return m_Representative; }
dword ExpectationMap::getShootCount (dword wid) const
Definition at line 79 of file ExpMap.cpp.
References getEDist(), and EMDistribution::getShootCount().
 {
     const EMDistribution* ed = getEDist(wid);
     if(!ed) return 0;
     else return ed->getShootCount();
 }
bool ExpectationMap::hasDist (dword wid) const
Definition at line 60 of file ExpMap.cpp.
References m_Distributions.
 {
     return m_Distributions.find(wid) != m_Distributions.end();
 }
void ExpectationMap::markAllOld ()
Definition at line 159 of file ExpMap.cpp.
References EMDistribution::ED_OLD, and m_Distributions.
Referenced by MStructure::rebuildExpMap().
{
     for(EDistributions::iterator dl=m_Distributions.begin();
         dl != m_Distributions.end(); dl++)
     {
         if(dl->second) dl->second->setFlags(EMDistribution::ED_OLD);
     }
 }
ExpectationMap::operator bool () const inline
Definition at line 171 of file ExpMap.h.
 { return !m_Distributions.empty(); }
ExpectationMap & ExpectationMap::operator= (const ExpectationMap & rhs)
Definition at line 4 of file ExpMap.cpp.
References add(), clear(), m_Distributions, and m_Representative.
{
     if(&rhs == this) return *this;
     EMDRect::operator=(rhs);
     m_Representative = rhs.m_Representative;
     clear();
     add(rhs.m_Distributions);
     return *this;
 }
float ExpectationMap::ratePropVec (const PropVec & prop, Winner * winner = NULL) const virtual
Reimplemented from EMDRect.
Definition at line 107 of file ExpMap.cpp.
References Winner::clearRatings(), getPropDir(), Winner::m_BestRating, m_Distributions, EMDRect::m_LB, mapAngle2PI(), Winner::rateBy(), EMDRect::ratePropVec(), and setPropDir().
Referenced by Searcher::evolve().
 {
     if(m_Distributions.empty()) return 0;
     PropVec pv(prop);
     setPropDir(pv, mapAngle2PI(getPropDir(prop), getPropDir(m_LB)));
     if(EMDRect::ratePropVec(pv) == 0.0) {
         return 0; //clamped?
     }
     float rate = 0.f;
     if(winner) {
         winner->clearRatings();
         for(EDistributions::const_iterator dl=m_Distributions.begin();
             dl != m_Distributions.end(); dl++)
         {
             float tr = dl->second->ratePropVec(prop);
             if(dl->second->m_Creator.m_WinnerID) {
                 const std::string& creatorname = dl->second->m_Creator.m_StructName;
                 dword creatorid = dl->second->m_Creator.m_WinnerID;
                 winner->rateBy(creatorname, creatorid, tr);
             } else if(winner->m_BestRating < tr) winner->m_BestRating = tr;
         }
         rate = winner->m_BestRating;
     } else {
         for(EDistributions::const_iterator dl=m_Distributions.begin();
             dl != m_Distributions.end(); dl++)
         {
             float tr = dl->second->ratePropVec(prop);
             if(rate<tr) rate = tr;
         }
     }
     return rate;
 }
void ExpectationMap::setRepresentative (const Model & model)
Definition at line 18 of file ExpMap.cpp.
References m_Representative.
Referenced by MStructure::rebuildExpMap(), and Brain::setupSearch().
 {
     m_Representative = model;
 }
float ExpectationMap::updateIntegral ()
Definition at line 167 of file ExpMap.cpp.
References m_Distributions, EMDistribution::m_Integral, and m_SortDist.
Referenced by add(), clear(), main(), and Searcher::setExpectationMap().
 {
     m_Integral = 0.f;
     m_SortDist.clear();
     for(EDistributions::const_iterator dl=m_Distributions.begin();
         dl != m_Distributions.end(); dl++)
     {
         if(dl->second) {
             if(dl->second->m_Integral > 0.00001) {
                 m_Integral += dl->second->m_Integral;
                 m_SortDist[m_Integral] = dl->second;
             }
         }
     }
     return m_Integral;
 }
Member Data Documentation
EDistributions ExpectationMap::m_Distributions protected
Definition at line 176 of file ExpMap.h.
Referenced by add(), clear(), erase(), getEDist(), getPropVec(), hasDist(), markAllOld(), operator=(), ratePropVec(), and updateIntegral().
Model ExpectationMap::m_Representative protected
Definition at line 175 of file ExpMap.h.
Referenced by generateInstance(), operator=(), and setRepresentative().
std::map<float, EMDistribution*> ExpectationMap::m_SortDist protected
Definition at line 177 of file ExpMap.h.
Referenced by getPropVec(), and updateIntegral().
The documentation for this class was generated from the following files:
src/ExpMap.h
src/ExpMap.cpp