Structural deformable models: EMDRect Class Reference
EMDRect Class Reference
#include <ExpMap.h>
Public Member Functions
EMDRect (const PropVec &lb=PropVec(0.f), const PropVec &ub=PropVec(1.f))
virtual ~EMDRect ()
virtual EMDistribution * copy () const
PropVec getPropVec () const
float ratePropVec (const PropVec &prop, Winner *winner=NULL) const
PropVec & clamp (PropVec &v)
const PropVec & getUB () const
const PropVec & getLB () const
void setUB (const PropVec &ub)
void setLB (const PropVec &lb)
Public Member Functions inherited from EMDistribution
EMDistribution ()
virtual ~EMDistribution ()
virtual void setIntegral (float integral)
void setCreator (const Winner &creator)
void setShootCount (dword scount)
dword getShootCount () const
bool hasFlags (dword flags) const
void setFlags (dword flags)
void unsetFlags (dword flags=0xffffffff)
Public Attributes
PropVec m_LB
PropVec m_UB
Public Attributes inherited from EMDistribution
float m_Integral
Winner m_Creator
dword m_ShootCount
dword m_Flags
Additional Inherited Members
Public Types inherited from EMDistribution
enum EDFlags { ED_NONE =0, ED_OLD =1 }
Detailed Description
Definition at line 73 of file ExpMap.h.
Constructor & Destructor Documentation
EMDRect::EMDRect (const PropVec & lb = PropVec(0.f), const PropVec & ub = PropVec(1.f)) inline
Definition at line 75 of file ExpMap.h.
         : m_LB(lb), m_UB(ub)
         {}
virtual EMDRect::~EMDRect () inline virtual
Definition at line 79 of file ExpMap.h.
 {}
Member Function Documentation
PropVec& EMDRect::clamp (PropVec & v) inline
Definition at line 84 of file ExpMap.h.
References VVector< T, D >::clamp().
 { return v.clamp(m_LB, m_UB); }
virtual EMDistribution* EMDRect::copy () const inline virtual
Reimplemented from EMDistribution.
Reimplemented in ExpectationMap.
Definition at line 80 of file ExpMap.h.
References NULL.
         { return (EMDistribution*) (new EMDRect(*this)); }
const PropVec& EMDRect::getLB () const inline
Definition at line 86 of file ExpMap.h.
Referenced by MStructure::addExpectation(), Searcher::setExpectationMap(), and Brain::setupSearch().
 { return m_LB; }
PropVec EMDRect::getPropVec () const virtual
Reimplemented from EMDistribution.
Reimplemented in ExpectationMap.
Definition at line 205 of file ExpMap.cpp.
References frand, m_LB, m_UB, and VVector< T, D >::size().
 {
     PropVec pv;
     for(unsigned int i=0; i<PropVec::size(); i++)
         pv[i] = frand(m_UB[i]-m_LB[i])+m_LB[i];
     return pv;
 }
const PropVec& EMDRect::getUB () const inline
Definition at line 85 of file ExpMap.h.
Referenced by MStructure::addExpectation(), Searcher::setExpectationMap(), and Brain::setupSearch().
 { return m_UB; }
float EMDRect::ratePropVec (const PropVec & prop, Winner * winner = NULL) const virtual
Reimplemented from EMDistribution.
Reimplemented in ExpectationMap.
Definition at line 213 of file ExpMap.cpp.
References VVector< T, D >::clamp(), m_LB, and m_UB.
Referenced by main(), and ExpectationMap::ratePropVec().
 {
     PropVec clampvec(prop);
     clampvec.clamp(m_LB, m_UB);
     if((clampvec-prop).norm2() < 0.0001) return 1;
     else return 0;
 }
void EMDRect::setLB (const PropVec & lb) inline
Definition at line 88 of file ExpMap.h.
Referenced by MStructure::addExpectation(), main(), MStructure::rebuildExpMap(), Searcher::setExpectationMap(), and Brain::setupSearch().
 { m_LB = lb; }
void EMDRect::setUB (const PropVec & ub) inline
Definition at line 87 of file ExpMap.h.
Referenced by MStructure::addExpectation(), main(), MStructure::rebuildExpMap(), Searcher::setExpectationMap(), and Brain::setupSearch().
 { m_UB = ub; }
Member Data Documentation
PropVec EMDRect::m_LB
Definition at line 90 of file ExpMap.h.
Referenced by getPropVec(), ExpectationMap::getPropVec(), ratePropVec(), and ExpectationMap::ratePropVec().
PropVec EMDRect::m_UB
Definition at line 90 of file ExpMap.h.
Referenced by getPropVec(), ExpectationMap::getPropVec(), and ratePropVec().
The documentation for this class was generated from the following files:
src/ExpMap.h
src/ExpMap.cpp