Structural deformable models: DBSelector Class Reference
DBSelector Class Reference
#include <SpeciesDB.h>
Public Member Functions
DBSelector (SpeciesDB &db)
DBSelector (SpeciesDB &db, const char *filename)
bool load (const char *filename)
void update ()
should be called when data base has changed
Species & getCurSpecies ()
Returns a handle to the currently selected species in the data base.
bool nextSelection (int dir=1, bool wrap=true)
bool nextSelector (int walkdir=1, bool wrap=true, dword mincount=1)
Public Attributes
SpeciesDB & m_DB
std::list< Species > m_Selectors
std::list< Species >::iterator m_CSel
Species m_CSpecies
Detailed Description
This class helps to select subsets of a data base. As well it assists in navigation through the selectors and the resulting selections.
Definition at line 78 of file SpeciesDB.h.
Constructor & Destructor Documentation
DBSelector::DBSelector (SpeciesDB & db) inline
Definition at line 80 of file SpeciesDB.h.
 : m_DB(db), m_CSel(m_Selectors.begin()) {};
DBSelector::DBSelector (SpeciesDB & db, const char * filename) inline
Definition at line 81 of file SpeciesDB.h.
         : m_DB(db), m_CSel(m_Selectors.begin())
         { load(filename); }
Member Function Documentation
Species& DBSelector::getCurSpecies () inline
Returns a handle to the currently selected species in the data base.
Definition at line 90 of file SpeciesDB.h.
Referenced by Brain::doCommand(), Brain::loadDB(), Brain::loadDBSelector(), ImageWindow::onKeyPress(), Brain::run(), and Brain::triggerTest().
         {
             std::map<dword,Species>::iterator n = m_DB.find(
                 m_DB.getSelectionID());
             if(n != m_DB.end()) return n->second;
             else return m_CSpecies;
         }
bool DBSelector::load (const char * filename)
Load a set of species used as selectors for filtering the data base. Calls update() afterwards.
Definition at line 241 of file SpeciesDB.cpp.
Referenced by ImageWindow::create(), and Brain::loadDBSelector().
 {
     ParseFile rf(filename);
     while(rf) {
         Species sp;
         rf >> sp;
         sp.erase("species_id");
         m_Selectors.push_back(sp);
     }
     cout << m_Selectors.size() << " records read from " << filename << endl;
     update();
     return true;
 }
bool DBSelector::nextSelection (int dir = 1, bool wrap = true)
Move on to next selection.
Parameters
dir -1 move backwards, 1 move forwards, 0 just refresh
wrap if false then return false if end of selection list has been reached. Otherwise just wrap around.
Definition at line 261 of file SpeciesDB.cpp.
Referenced by Brain::doCommand(), ImageWindow::onKeyPress(), Brain::run(), and Brain::triggerTest().
 {
     if(m_DB.empty()) return false;
     if(!m_DB.getSelectionID()) {
         map<dword,Species>::iterator n = m_DB.find(m_CSpecies.id);
         if(n != m_DB.end()) {
             if(dir>0) {
                 n++;
                 if(n == m_DB.end()) {
                     n = m_DB.begin();
                     if(!wrap) return false;
                 }
             } else if(dir<0) {
                 if(n == m_DB.begin()) {
                     n = m_DB.end();
                     n--;
                     if(!wrap) return false;
                 } else n--;
             }
             m_CSpecies = n->second;
         } else return false;
     } else {
         map<dword,Species>::iterator n = m_DB.find(
             m_DB.getSelectionID(dir,wrap));
         if(n != m_DB.end()) m_CSpecies = n->second;
         else return false;
     }
     return true;
 }
bool DBSelector::nextSelector (int walkdir = 1, bool wrap = true, dword mincount = 1)
Move on to next selector.
Parameters
walkdir -1=move backwards, 1=move forwards (default), 0=just refresh
wrap if false then return false if end of selector list has been reached. Otherwise just wrap around.
Definition at line 291 of file SpeciesDB.cpp.
Referenced by ImageWindow::onKeyPress(), and Brain::triggerTest().
{
     bool ret = true;
     list<Species>::iterator osel = m_Selectors.end();
     while(m_CSel != osel)
     {
         if(osel == m_Selectors.end()) osel = m_CSel;
         if(walkdir<0) {
             if(m_CSel == m_Selectors.begin()) {
                 m_CSel = m_Selectors.end();
                 ret = wrap;
             }
             m_CSel--;
         } else if(walkdir>0) {
             m_CSel++;
             if(m_CSel == m_Selectors.end()) {
                 m_CSel = m_Selectors.begin();
                 ret = wrap;
             }
         }
         dword nsel = m_DB.select(*m_CSel);
         if(nsel >= mincount) {
             cout << nsel << " records found using selector:" << endl
                  << *m_CSel;
             nextSelection(0);
             osel = m_CSel;
         } else {
             cout << " no records found using selector:" <<endl<<*m_CSel;
         }
     }
     if(m_CSel == m_Selectors.end()) {
         m_CSel = m_Selectors.begin();
         return false;
     }
     return ret;
 }
void DBSelector::update ()
should be called when data base has changed
Definition at line 255 of file SpeciesDB.cpp.
Referenced by Brain::loadDB().
 {
     m_CSel = m_Selectors.begin();
     nextSelector(0);
 }
Member Data Documentation
std::list<Species>::iterator DBSelector::m_CSel
Definition at line 111 of file SpeciesDB.h.
Species DBSelector::m_CSpecies
Definition at line 112 of file SpeciesDB.h.
SpeciesDB& DBSelector::m_DB
Definition at line 109 of file SpeciesDB.h.
std::list<Species> DBSelector::m_Selectors
Definition at line 110 of file SpeciesDB.h.
The documentation for this class was generated from the following files:
src/SpeciesDB.h
src/SpeciesDB.cpp