Structural deformable models: GLImage Class Reference
GLImage Class Reference
#include <glImage.h>
Public Member Functions
GLImage ()
GLImage (const std::vector< Image< byte > > &image)
GLImage (const Image< byte > &image)
~GLImage ()
void setImage (const Image< byte > &image)
void setImage (const std::vector< Image< byte > > &image)
void unsetImage ()
bool bindTexture () const
void draw (float x, float y, float sx=1.f, float sy=1.f) const
operator bool () const
float getSizeX () const
float getSizeY () const
Protected Attributes
GLuint m_gltexture
int m_sx
int m_sy
float m_tx
float m_ty
bool m_Initialized
Detailed Description
Definition at line 9 of file glImage.h.
Constructor & Destructor Documentation
GLImage::GLImage () inline
Definition at line 11 of file glImage.h.
 : m_Initialized(false) {}
GLImage::GLImage (const std::vector< Image< byte > > & image) inline
Definition at line 12 of file glImage.h.
References setImage().
                                                    : m_Initialized(false)
         {
             setImage(image);
         }
GLImage::GLImage (const Image< byte > & image) inline
Definition at line 17 of file glImage.h.
References setImage().
                                       : m_Initialized(false)
         {
             setImage(image);
         }
GLImage::~GLImage () inline
Definition at line 22 of file glImage.h.
References unsetImage().
         {
             unsetImage();
         }
Member Function Documentation
bool GLImage::bindTexture () const inline
Definition at line 79 of file glImage.h.
References m_gltexture, and m_Initialized.
Referenced by draw().
         {
             if(m_Initialized) glBindTexture(GL_TEXTURE_2D, m_gltexture);
             return m_Initialized;
         }
void GLImage::draw (float x, float y, float sx = 1.f, float sy = 1.f) const inline
Definition at line 85 of file glImage.h.
References bindTexture(), m_sx, m_sy, m_tx, and m_ty.
Referenced by Dataset::draw().
         {
             if(!bindTexture()) return;
             float bx = x + sx*m_sx;
             float by = y + sy*m_sy;
             glBegin(GL_QUADS);// Begin Drawing The Textured Quad
             glTexCoord2f(0.0f, 0.0f); glVertex2f(  x,  y);
             glTexCoord2f(m_tx, 0.0f); glVertex2f( bx,  y);
             glTexCoord2f(m_tx, m_ty); glVertex2f( bx, by);
             glTexCoord2f(0.0f, m_ty); glVertex2f(  x, by);
             glEnd();
         }
float GLImage::getSizeX () const inline
Definition at line 99 of file glImage.h.
References m_sx.
 { return m_sx; }
float GLImage::getSizeY () const inline
Definition at line 100 of file glImage.h.
References m_sy.
 { return m_sy; }
GLImage::operator bool () const inline
Definition at line 98 of file glImage.h.
References m_Initialized.
 { return m_Initialized; }
void GLImage::setImage (const Image< byte > & image) inline
Definition at line 27 of file glImage.h.
References Image< T >::getData(), Image< T >::getSizeX(), Image< T >::getSizeY(), Image< T >::insert(), m_gltexture, m_Initialized, m_sx, m_sy, m_tx, m_ty, power2(), and unsetImage().
Referenced by Dataset::draw(), and GLImage().
         {
             unsetImage();
             m_sx = image.getSizeX();
             m_sy = image.getSizeY();
             dword p2x = power2(m_sx);
             dword p2y = power2(m_sy);
             m_tx = float(m_sx)/p2x;
             m_ty = float(m_sy)/p2y;
             Image<byte> p2i(p2x, p2y);
             p2i.insert(image);
             glGenTextures(1, &m_gltexture);// Create One Texture
 // Create Linear Filtered Texture
             glBindTexture(GL_TEXTURE_2D, m_gltexture);
             glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_LINEAR);
             glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_LINEAR);
             glTexImage2D(GL_TEXTURE_2D, 0, 3, p2x, p2y, 0,
                          GL_LUMINANCE, GL_UNSIGNED_BYTE, p2i.getData());
             m_Initialized = true;
         }
void GLImage::setImage (const std::vector< Image< byte > > & image) inline
Definition at line 48 of file glImage.h.
References Image< T >::getData(), Image< T >::getSizeX(), Image< T >::getSizeY(), Image< T >::insert(), Image< T >::interleave(), m_gltexture, m_Initialized, m_sx, m_sy, m_tx, m_ty, power2(), and unsetImage().
         {
             unsetImage();
             if(image.empty()) return;
             Image<byte> combimg;
             combimg.interleave(image, 3);
             m_sx = combimg.getSizeX()/3; //image[0].getSizeX();
             m_sy = combimg.getSizeY(); //image[0].getSizeY();
             dword p2x = power2(m_sx);
             dword p2y = power2(m_sy);
             m_tx = float(m_sx)/float(p2x);
             m_ty = float(m_sy)/float(p2y);
             Image<byte> p2i(p2x*3, p2y);
             p2i.insert(combimg);
             glGenTextures(1, &m_gltexture);// Create One Texture
 // Create Linear Filtered Texture
             glBindTexture(GL_TEXTURE_2D, m_gltexture);
             glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_LINEAR);
             glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_LINEAR);
             glTexImage2D(GL_TEXTURE_2D, 0, 3, p2x, p2y, 0, GL_RGB,
                          GL_UNSIGNED_BYTE, p2i.getData());
             m_Initialized = true;
         }
void GLImage::unsetImage () inline
Definition at line 72 of file glImage.h.
References m_gltexture, and m_Initialized.
Referenced by Dataset::draw(), setImage(), and ~GLImage().
         {
             if(!m_Initialized) return;
             glDeleteTextures(1, &m_gltexture);
             m_Initialized = false;
         }
Member Data Documentation
GLuint GLImage::m_gltexture protected
Definition at line 103 of file glImage.h.
Referenced by bindTexture(), setImage(), and unsetImage().
bool GLImage::m_Initialized protected
Definition at line 106 of file glImage.h.
Referenced by bindTexture(), operator bool(), setImage(), and unsetImage().
int GLImage::m_sx protected
Definition at line 104 of file glImage.h.
Referenced by draw(), getSizeX(), and setImage().
int GLImage::m_sy protected
Definition at line 104 of file glImage.h.
Referenced by draw(), getSizeY(), and setImage().
float GLImage::m_tx protected
Definition at line 105 of file glImage.h.
Referenced by draw(), and setImage().
float GLImage::m_ty protected
Definition at line 105 of file glImage.h.
Referenced by draw(), and setImage().
The documentation for this class was generated from the following file:
src/glImage.h