Structural deformable models: SpeciesDB Class Reference
SpeciesDB Class Reference
#include <SpeciesDB.h>
Public Member Functions
SpeciesDB ()
SpeciesDB (const char *filename)
bool load (const char *filename)
const std::string & getDirectory () const
const std::string & getFilename () const
dword select (const Species &rhs, enum Species::SpCompare how=Species::CMP_CONTAINS)
dword select (const std::list< dword > &idlist)
dword getSelectionID (int dir=0, bool wrap=true)
dword loadSelection (const std::string &fname)
dword writeSelection (const std::string &fname) const
Static Public Member Functions
static dword loadSelection (const std::string &fname, std::list< dword > &sel)
static dword writeSelection (const std::string &fname, const std::list< dword > &sel)
Protected Attributes
std::string m_Directory
std::string m_Filename
std::list< dword > m_Selection
std::list< dword >::iterator m_CSel
Friends
ParseFile & operator>> (ParseFile &is, SpeciesDB &sp)
std::ostream & operator<< (std::ostream &os, const SpeciesDB &sp)
Detailed Description
Definition at line 45 of file SpeciesDB.h.
Constructor & Destructor Documentation
SpeciesDB::SpeciesDB () inline
Definition at line 47 of file SpeciesDB.h.
 {}
SpeciesDB::SpeciesDB (const char * filename) inline
Definition at line 48 of file SpeciesDB.h.
References Species::operator<<, and Species::operator>>.
{
         load(filename);
     }
Member Function Documentation
const std::string& SpeciesDB::getDirectory () const inline
Definition at line 55 of file SpeciesDB.h.
Referenced by ImageWindow::changeSpecies(), Brain::loadSpecies(), and ImageWindow::onKeyPress().
 { return m_Directory; }
const std::string& SpeciesDB::getFilename () const inline
Definition at line 56 of file SpeciesDB.h.
References Species::CMP_CONTAINS, and Species::select().
Referenced by Brain::doCommand().
 { return m_Filename; }
dword SpeciesDB::getSelectionID (int dir = 0, bool wrap = true)
Definition at line 54 of file SpeciesDB.cpp.
 {
     if(m_Selection.empty()) return 0;
     if(dir==1) { // dir>0
         m_CSel++;
         if(m_CSel==m_Selection.end()) {
             m_CSel = m_Selection.begin();
             if(!wrap) return 0;
         }
     } else if(dir>1) {
         m_CSel = m_Selection.end();
         m_CSel--;
     } else if(dir==-1) { // dir<0
         if(m_CSel==m_Selection.begin()) {
             m_CSel = m_Selection.end();
             m_CSel--;
             if(!wrap) return 0;
         } else m_CSel--;
     } else if(dir < -1) {
         m_CSel = m_Selection.begin();
     }
     return *m_CSel;
 }
bool SpeciesDB::load (const char * filename)
Definition at line 13 of file SpeciesDB.cpp.
References ParseFile::getFilename(), IOException::getMessage(), ParseFile::getPath(), and operator>>().
Referenced by ImageWindow::create(), Brain::loadDB(), and ImageWindow::onLoadImage().
 {
     clear();
     ifstream ifs(filename);
     ifs.close();
     ParseFile pf(filename);
     if(pf) {
         try {
             operator>>(pf, *this);
         } catch (const IOException *e) {
             cout << "Error loading " << filename << " message: "
                  << e->getMessage() << endl;
             return false;
         }
         cout << "read " << size() << " entries from " << filename << endl;
         m_Directory = pf.getPath();
         m_Filename = pf.getFilename();
         return true;
     } else {
         cout << "Error loading " << filename << endl;
         return false;
     }
 }
dword SpeciesDB::loadSelection (const std::string & fname) inline
Definition at line 61 of file SpeciesDB.h.
         { return loadSelection(fname, m_Selection); }
dword SpeciesDB::loadSelection (const std::string & fname, std::list< dword > & sel) static
Definition at line 78 of file SpeciesDB.cpp.
 {
     ifstream is(fname.c_str());
     if(is) {
         sel.clear();
         is >> ws;
         while(is) {
             dword selid=0;
             is >> selid;
             if(selid) sel.push_back(selid);
         }
     } else return 0;
     return sel.size();
 }
dword SpeciesDB::select (const Species & rhs, enum Species::SpCompare how = Species::CMP_CONTAINS)
Definition at line 37 of file SpeciesDB.cpp.
Referenced by Brain::doCommand().
 {
     m_Selection.clear();
     for(map<dword,Species>::const_iterator s=begin(); s!=end(); s++)
         if(s->second.select(sp, how))
             m_Selection.push_back(s->second.id);
     m_CSel = m_Selection.begin();
     return m_Selection.size();
 }
dword SpeciesDB::select (const std::list< dword > & idlist)
Definition at line 47 of file SpeciesDB.cpp.
 {
     m_Selection = idlist;
     m_CSel = m_Selection.begin();
     return m_Selection.size();
 }
dword SpeciesDB::writeSelection (const std::string & fname) const inline
Definition at line 63 of file SpeciesDB.h.
         { return writeSelection(fname, m_Selection); }
dword SpeciesDB::writeSelection (const std::string & fname, const std::list< dword > & sel) static
Definition at line 94 of file SpeciesDB.cpp.
 {
     ofstream os(fname.c_str());
     if(os) {
         for(list<dword>::const_iterator csel = sel.begin();
             csel != sel.end(); csel++)
         {
             os << *csel << endl;
         }
     } else return 0;
     return sel.size();
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const SpeciesDB & sp) friend
Definition at line 118 of file SpeciesDB.cpp.
 {
     for(map<dword,Species>::const_iterator s=sp.begin(); s!=sp.end(); s++)
         os << s->second << endl;
     return os;
 }
ParseFile& operator>> (ParseFile & is, SpeciesDB & sp) friend
Definition at line 108 of file SpeciesDB.cpp.
 {
     Species s;
     while(is) {
         is >> s;
         if(s.id) sp[s.id] = s;
     }
     return is;
 }
Member Data Documentation
std::list<dword>::iterator SpeciesDB::m_CSel protected
Definition at line 72 of file SpeciesDB.h.
std::string SpeciesDB::m_Directory protected
Definition at line 69 of file SpeciesDB.h.
std::string SpeciesDB::m_Filename protected
Definition at line 70 of file SpeciesDB.h.
std::list<dword> SpeciesDB::m_Selection protected
Definition at line 71 of file SpeciesDB.h.
The documentation for this class was generated from the following files:
src/SpeciesDB.h
src/SpeciesDB.cpp