Structural deformable models: CElement< D > Class Template Reference
CElement< D > Class Template Reference
#include <Clusterer.h>
Public Member Functions
CElement ()
CElement (float v)
CElement (const vector< float > &rhs)
CElement< D > & operator= (const vector< float > &rhs)
CElement< D > & operator= (const CElement &rhs)
CElement< D > & operator= (float v)
CElement< D > & operator+= (const CElement< D > &rhs)
CElement< D > & operator*= (const CElement< D > &rhs)
CElement< D > & operator*= (float v)
CElement< D > & operator/= (float v)
CElement< D > & randomize (float min=0, float max=1)
float dist2 (const CElement< D > &rhs) const
float dist (const CElement< D > &rhs) const
dword getNMembers () const
dword & getNMembers ()
dword getClassID () const
void setClassID (dword cid)
Public Attributes
float val [D]
dword id
dword multiv
Friends
ostream & operator<< (ostream &os, const CElement< D > &rhs)
Detailed Description
template<int D>
class CElement< D >
Definition at line 9 of file Clusterer.h.
Constructor & Destructor Documentation
template<int D> CElement< D >::CElement () inline
Definition at line 11 of file Clusterer.h.
 : id(0), multiv(0) {}
template<int D> CElement< D >::CElement (float v) inline
Definition at line 12 of file Clusterer.h.
References CElement< D >::operator=().
                       : id(0), multiv(0) {
         operator=(v);
     }
template<int D> CElement< D >::CElement (const vector< float > & rhs) inline
Definition at line 15 of file Clusterer.h.
References CElement< D >::operator=().
                                        : id(0), multiv(0) {
         operator=(rhs);
     }
Member Function Documentation
template<int D> float CElement< D >::dist (const CElement< D > & rhs) const inline
Definition at line 60 of file Clusterer.h.
References CElement< D >::dist2(), and dmutil::sqrt().
{
         return sqrt(dist2(rhs));
     }
template<int D> float CElement< D >::dist2 (const CElement< D > & rhs) const inline
Definition at line 52 of file Clusterer.h.
References CElement< D >::val.
Referenced by Clusterer< D >::classify(), and CElement< D >::dist().
{
         float d=0;
         for(int i=0; i<D; i++) {
             register float cd = val[i]-rhs.val[i];
             d += cd*cd;
         }
         return d;
     }
template<int D> dword CElement< D >::getClassID () const inline
Definition at line 66 of file Clusterer.h.
References CElement< D >::multiv.
 { return multiv; }
template<int D> dword CElement< D >::getNMembers () const inline
Definition at line 64 of file Clusterer.h.
References CElement< D >::multiv.
Referenced by Clusterer< D >::classify().
 { return multiv; }
template<int D> dword& CElement< D >::getNMembers () inline
Definition at line 65 of file Clusterer.h.
References CElement< D >::multiv.
 { return multiv; }
template<int D> CElement<D>& CElement< D >::operator*= (const CElement< D > & rhs) inline
Definition at line 36 of file Clusterer.h.
References CElement< D >::val.
{
         for(int i=0; i<D; i++) val[i]*=rhs.val[i];
         return *this;
     }
template<int D> CElement<D>& CElement< D >::operator*= (float v) inline
Definition at line 40 of file Clusterer.h.
References CElement< D >::val.
{
         for(int i=0; i<D; i++) val[i]*=v;
         return *this;
     }
template<int D> CElement<D>& CElement< D >::operator+= (const CElement< D > & rhs) inline
Definition at line 32 of file Clusterer.h.
References CElement< D >::val.
{
         for(int i=0; i<D; i++) val[i]+=rhs.val[i];
         return *this;
     }
template<int D> CElement<D>& CElement< D >::operator/= (float v) inline
Definition at line 44 of file Clusterer.h.
References CElement< D >::val.
{
         for(int i=0; i<D; i++) val[i]/=v;
         return *this;
     }
template<int D> CElement<D>& CElement< D >::operator= (const vector< float > & rhs) inline
Definition at line 18 of file Clusterer.h.
References CElement< D >::val.
Referenced by CElement< D >::CElement().
{
         for(int i=0; i<D; i++) val[i]=rhs[i];
         return *this;
     }
template<int D> CElement<D>& CElement< D >::operator= (const CElement< D > & rhs) inline
Definition at line 22 of file Clusterer.h.
References CElement< D >::id, CElement< D >::multiv, and CElement< D >::val.
{
         for(int i=0; i<D; i++) val[i]=rhs.val[i];
         id = rhs.id;
         multiv = rhs.multiv;
         return *this;
     }
template<int D> CElement<D>& CElement< D >::operator= (float v) inline
Definition at line 28 of file Clusterer.h.
References CElement< D >::val.
{
         for(int i=0; i<D; i++) val[i]=v;
         return *this;
     }
template<int D> CElement<D>& CElement< D >::randomize (float min = 0, float max = 1) inline
Definition at line 48 of file Clusterer.h.
References frand, and CElement< D >::val.
{
         for(int i=0; i<D; i++) val[i]=frand(max-min)+min;
         return *this;
     }
template<int D> void CElement< D >::setClassID (dword cid) inline
Definition at line 67 of file Clusterer.h.
References CElement< D >::multiv.
Referenced by Clusterer< D >::classify().
 { multiv = cid; }
Friends And Related Function Documentation
template<int D> ostream& operator<< (ostream & os, const CElement< D > & rhs) friend
Definition at line 68 of file Clusterer.h.
{
         for(int i=0; i<D; i++) {
             if(i) os << " ";
             os << rhs.val[i];
         }
         return os;
     }
Member Data Documentation
template<int D> dword CElement< D >::id
Definition at line 78 of file Clusterer.h.
Referenced by CElement< D >::operator=().
template<int D> dword CElement< D >::multiv
Definition at line 79 of file Clusterer.h.
Referenced by CElement< D >::getClassID(), CElement< D >::getNMembers(), CElement< D >::operator=(), and CElement< D >::setClassID().
template<int D> float CElement< D >::val[D]
Definition at line 77 of file Clusterer.h.
Referenced by CElement< D >::dist2(), ImageWindow::onKeyPress(), CElement< D >::operator*=(), CElement< D >::operator+=(), CElement< D >::operator/=(), CElement< D >::operator=(), and CElement< D >::randomize().
The documentation for this class was generated from the following file:
src/Clusterer.h