Structural deformable models: Clusterer< D > Class Template Reference
Clusterer< D > Class Template Reference
#include <Clusterer.h>
Public Types
typedef vector< CElement< D > >::iterator eiterator
typedef vector< CElement< D > >::const_iterator const_eiterator
Public Member Functions
Clusterer (dword nclasses=1, float min=0, float max=1)
void clearAccumulation ()
void initialize (dword nclasses, float min=0, float max=1)
dword classify (CElement< D > &elem)
dword classifyAll ()
void iterateClassification (dword maxit=10)
Public Attributes
vector< CElement< D > > m_Elements
vector< CElement< D > > m_Classes
vector< CElement< D > > m_ElemAcc
Detailed Description
template<int D>
class Clusterer< D >
Definition at line 83 of file Clusterer.h.
Member Typedef Documentation
template<int D> typedef vector< CElement<D> >::const_iterator Clusterer< D >::const_eiterator
Definition at line 86 of file Clusterer.h.
template<int D> typedef vector< CElement<D> >::iterator Clusterer< D >::eiterator
Definition at line 85 of file Clusterer.h.
Constructor & Destructor Documentation
template<int D> Clusterer< D >::Clusterer (dword nclasses = 1, float min = 0, float max = 1) inline
Definition at line 88 of file Clusterer.h.
{
         initialize(nclasses, min, max);
     };
Member Function Documentation
template<int D> dword Clusterer< D >::classify (CElement< D > & elem) inline
Definition at line 118 of file Clusterer.h.
References CElement< D >::dist2(), CElement< D >::getNMembers(), and CElement< D >::setClassID().
{
         float mind=numeric_limits<float>::max();
         dword minid=0;
         dword cid=0;
         for(eiterator cv = m_Classes.begin();
             cv != m_Classes.end(); cv++, cid++)
         {
             float d = elem.dist2(*cv);
             if(d<mind) {
                 mind = d;
                 minid = cid;
             }
         }
         CElement<D> &ae = m_ElemAcc[minid];
         ae += elem;
         ae.getNMembers()++;
         elem.setClassID(minid);
         return minid;
     }
template<int D> dword Clusterer< D >::classifyAll () inline
Definition at line 138 of file Clusterer.h.
{
         dword reclass = 0;
         clearAccumulation();
         for(eiterator e=m_Elements.begin();
             e != m_Elements.end(); e++)
         {
             dword oldclass = e->getClassID();
             if(oldclass != classify(*e))
                 reclass++;
         }
         for(eiterator ci=m_Classes.begin(), ca=m_ElemAcc.begin();
             ci!=m_Classes.end(); ci++, ca++)
         {
             if(ca->getNMembers()) {
                 *ca *= 1.0f/ca->getNMembers();
                 *ci = *ca;
             } else ci->getNMembers() = 0;
             //cout << *ci << " members: " << ci->getNMembers() << endl;
         }
         cout << reclass << " re-classifications" << endl; //DEBUG
         return reclass;
     }
template<int D> void Clusterer< D >::clearAccumulation () inline
Definition at line 92 of file Clusterer.h.
{
         dword cid=0;
         for(eiterator cv = m_ElemAcc.begin();
             cv != m_ElemAcc.end(); cv++, cid++)
         {
             *cv = 0;
             cv->id = cid;
             cv->getNMembers() = 0;
         }
     }
template<int D> void Clusterer< D >::initialize (dword nclasses, float min = 0, float max = 1) inline
Definition at line 103 of file Clusterer.h.
{
         m_Classes.resize(nclasses);
         m_ElemAcc.resize(nclasses);
         dword cid=0;
         for(eiterator cv = m_Classes.begin();
             cv != m_Classes.end(); cv++, cid++)
         {
             cv->id = cid;
             cv->getNMembers() = 0;
             cv->randomize(min,max);
             //cout << *cv << endl;
         }
         clearAccumulation();
     }
template<int D> void Clusterer< D >::iterateClassification (dword maxit = 10) inline
Definition at line 161 of file Clusterer.h.
Referenced by ImageWindow::onKeyPress().
{
         int counter=0; //DEBUG
         while(maxit>0) {
             cout << "iteration " << (++counter) << endl; //DEBUG
             if(classifyAll() == 0) break;
             maxit--;
         }
         int cu=0;
         for(eiterator ci=m_Classes.begin(); ci!=m_Classes.end(); ci++)
             if(ci->getNMembers()) cu++;
         cout << "number of classes used: " << cu << endl;
     }
Member Data Documentation
template<int D> vector< CElement<D> > Clusterer< D >::m_Classes
Definition at line 176 of file Clusterer.h.
Referenced by ImageWindow::onKeyPress().
template<int D> vector< CElement<D> > Clusterer< D >::m_ElemAcc
Definition at line 177 of file Clusterer.h.
template<int D> vector< CElement<D> > Clusterer< D >::m_Elements
Definition at line 175 of file Clusterer.h.
Referenced by ImageWindow::onKeyPress().
The documentation for this class was generated from the following file:
src/Clusterer.h