Structural deformable models: PPSensor Class Reference
PPSensor Class Reference
#include <Sensor.h>
Public Types
enum PPState { PP_DONT =0, PP_DO, PP_FORCE }
Public Types inherited from Sensor
enum UpdateParam {
UPD_NOTHING =0, UPD_DATA =1, UPD_SCALE =2, UPD_CWEIGHTS =4,
UPD_DIR =8, UPD_MINMAX =16, UPD_LAST =32, UPD_ALL =0xffffffff
}
Public Member Functions
PPSensor (const Sensor *_source)
virtual float getValue (int x, int y) const
virtual Point getGradient (int x, int y) const
virtual bool performUpdate ()
Sensor & assign (const Sensor &rhs)
void togglePP (enum PPState state=PP_DO)
dword getPPState () const
Public Member Functions inherited from Sensor
Sensor (const Sensor *_source=NULL)
virtual ~Sensor ()
const Sensor * getSource ()
virtual void changeSource (const Sensor *_source)
void replaceBy (Sensor *target)
bool assignRef (const Sensor *rhs)
float getValue (const Point &p) const
get value at position p using nearest neighbour interpolation
virtual std::vector< float > getMValue (int x, int y) const
get multi-channel value
Point2D getGradient (const Point2D &p) const
get gradient at position p using nearest neighbor interpolation
float getMax () const
float getMin () const
float getMinMaxRange () const
float getWeightedValue (int x, int y) const
get max normalized value at discrete position range [0,1]
Point2D getWeightedGradient (int x, int y) const
get range weighted gradient at discrete position
void setCWeights (const std::vector< float > &weights)
const std::vector< float > & getCWeights () const
void setDirection (const Point &dir)
const Point & getDirection () const
void setScale (float _scale)
float getScale () const
bool isModified (dword mask=UPD_ALL) const
void setModified (dword mask=UPD_ALL)
void unsetModified (dword mask=UPD_ALL)
bool isUpdate (dword udMask) const
void enableUpdate (dword udMask)
void disableUpdate (dword udMask)
virtual int getDim1Size () const
virtual int getDim2Size () const
virtual int getDim3Size () const
virtual int getNChannels () const
virtual int getSkip () const
bool isValid (int x, int y) const
virtual Image< float > createSensorImage () const
const std::string & getID () const
void setID (const std::string &id)
virtual std::ostream & hprint (std::ostream &os, SensorCollection *sc) const
virtual std::ostream & print (std::ostream &os) const
void refSuperSensor (Sensor *super)
void unrefSuperSensor (Sensor *super)
void invalidateSource ()
Protected Member Functions
void fitSheets ()
virtual void calcAllValues ()
virtual void calcAllGradients ()
Protected Member Functions inherited from Sensor
virtual float calcValue (int x, int y) const =0
virtual std::vector< float > calcMValue (int x, int y) const
virtual Point calcGradient (int x, int y) const
virtual void calcMinMax ()
Protected Attributes
Image< float > values
caching sheet for sensed values
Image< Point > gradients
caching sheet for gradients
dword doPP
do preprocessing?
Protected Attributes inherited from Sensor
const Sensor * source
float scale
std::vector< float > cweights
multi-channel weights ('color')
Point dir
direction parameter
float maxval
float minval
overall minimum and maximum
float mean
float stdev
overall mean and stdev
dword toupdate
bitflag for updates
dword updateMask
bitflag to mask unimportant updates
std::string m_ID
int m_Skip
int m_AddSkip
Additional Inherited Members
Static Public Member Functions inherited from Sensor
static dword getStringNumber (const char *sid)
static void getNumberString (char sid[5], dword id)
Detailed Description
Sensor with preprocessing
Definition at line 210 of file Sensor.h.
Member Enumeration Documentation
enum PPSensor::PPState
Enumerator
PP_DONT
PP_DO
PP_FORCE
Definition at line 212 of file Sensor.h.
 { PP_DONT=0, PP_DO, PP_FORCE };
Constructor & Destructor Documentation
PPSensor::PPSensor (const Sensor * _source)
Definition at line 223 of file Sensor.cpp.
     : Sensor(_source),
       values(source->getDim1Size(), source->getDim2Size(), AIR_NAN),
       gradients(source->getDim1Size(), source->getDim2Size(),
                 Point(AIR_NAN,AIR_NAN)),
       doPP(PPSensor::PP_DONT)
 {}
Member Function Documentation
Sensor & PPSensor::assign (const Sensor & rhs) virtual
Reimplemented from Sensor.
Reimplemented in MappingSensor, MahalSensor, and CombiSensor.
Definition at line 306 of file Sensor.cpp.
References Sensor::assign(), and doPP.
Referenced by CombiSensor::assign(), MahalSensor::assign(), and MappingSensor::assign().
 {
     if(&rhs != this) {
         Sensor::assign(rhs);
         if(typeid(&rhs) == typeid(PPSensor*)) {
             const PPSensor& crhs = (const PPSensor&) rhs;
             doPP = crhs.doPP;
         }
     }
     return *this;
 }
void PPSensor::calcAllGradients () protected virtual
Definition at line 260 of file Sensor.cpp.
References calcAllValues(), Sensor::calcGradient(), fitSheets(), Sensor::getDim1Size(), Sensor::getDim2Size(), gradients, Sensor::isModified(), Sensor::performUpdate(), Sensor::setModified(), Sensor::source, Sensor::toupdate, and Sensor::unsetModified().
{
     if(gradients.getSizeX() == source->getDim1Size() &&
        gradients.getSizeY() == source->getDim2Size())
     {
     int i,j;
     Image<Point>::iterator g=gradients.begin();
     for(j=0; j<source->getDim2Size()-1; j++, g++) {
         for(i=0; i<source->getDim1Size()-1; i++, g++) {
         *g = calcGradient(i,j);
         }
     }
     }
 }
void PPSensor::calcAllValues () protected virtual
Reimplemented in SmoothIntensitySensor.
Definition at line 244 of file Sensor.cpp.
References Sensor::calcValue(), Sensor::getDim1Size(), Sensor::getDim2Size(), Image< T >::getSizeX(), Image< T >::getSizeY(), Sensor::source, and values.
Referenced by calcAllGradients(), and SmoothIntensitySensor::calcAllValues().
{
     if(values.getSizeX() == source->getDim1Size() &&
        values.getSizeY() == source->getDim2Size())
     {
     int i,j;
     Image<float>::iterator v=values.begin();
     for(j=0; j<source->getDim2Size(); j++) {
         for(i=0; i<source->getDim1Size(); i++, v++)
         {
         *v = calcValue(i,j);
         assert(!isnan(*v));
         }
     }
     }
 }
void PPSensor::fitSheets () protected
Definition at line 231 of file Sensor.cpp.
References Sensor::getDim1Size(), Sensor::getDim2Size(), Image< T >::getSizeX(), Image< T >::getSizeY(), gradients, Image< T >::setSize(), Sensor::source, and values.
Referenced by calcAllGradients(), and performUpdate().
{
     if(values.getSizeX() != source->getDim1Size() ||
        values.getSizeY() != source->getDim2Size()) {
     values.setSize(source->getDim1Size(), source->getDim2Size());
     gradients.setSize(source->getDim1Size(), source->getDim2Size());
     }
     //this is also done later on by Sensor::performUpdate,
     //but we might need it earlier
     //if(cweights.size() != source->getNChannels()) {
 //  cweights.resize(source->getNChannels());
 //    }
 }
Point PPSensor::getGradient (int x, int y) const inline virtual
Return cached gradient or compute and cache new one.
Reimplemented from Sensor.
Definition at line 266 of file Sensor.h.
References Sensor::calcGradient(), Sensor::isModified(), and Sensor::performUpdate().
{
     if(doPP) {
     if(isModified()) const_cast<PPSensor*>(this)->performUpdate();
     int index = gradients.getBoundedIndex(x,y);
     if(index<0) return Point();
     if(std::isnan(gradients[index].x)) {  // no precalculated value?
 //      if(doPP == PP_FORCE) {
 //      //this should not happen
 //      assert(false);
 //      const_cast<PPSensor*>(this)->performFullUpdate();
 //      return gradients[index];
 //      } else
         return (const_cast<PPSensor*>(this)->gradients[index]
             = calcGradient(x,y));
     } else return gradients[index];
     } else return calcGradient(x,y);
 }
dword PPSensor::getPPState () const inline
Definition at line 226 of file Sensor.h.
Referenced by Node::attachSensor().
 { return doPP; }
float PPSensor::getValue (int x, int y) const inline virtual
Return cached value or compute and cache new one.
Reimplemented from Sensor.
Definition at line 248 of file Sensor.h.
References Sensor::calcValue(), Sensor::isModified(), Sensor::performUpdate(), and PP_FORCE.
{
     if(doPP) {
     if(isModified()) const_cast<PPSensor*>(this)->performUpdate();
     int index = (int)values.getBoundedIndex(x,y);
     if(index==-1) return 0;
     float v;
     if(std::isnan((v = values[index]))) {
         if(doPP == PPSensor::PP_FORCE) {
         assert(false); //no NAN values in forced full update at this point
         const_cast<PPSensor*>(this)->performFullUpdate();
         return values[index];
         } else {
         return (const_cast<PPSensor*>(this)->values[index] = calcValue(x,y));
         }
     } else return v;
     } else return calcValue(x,y);
 }
bool PPSensor::performUpdate () virtual
clear all data sheets
Reimplemented from Sensor.
Reimplemented in MappingSensor, CornerSensor, GradMagSensor, and SmoothIntensitySensor.
Definition at line 288 of file Sensor.cpp.
References AIR_NAN, doPP, fitSheets(), gradients, Sensor::isModified(), Sensor::performUpdate(), PP_FORCE, and values.
Referenced by SmoothIntensitySensor::performUpdate(), GradMagSensor::performUpdate(), CornerSensor::performUpdate(), and MappingSensor::performUpdate().
 {
     if(isModified()) {
     if(doPP == PPSensor::PP_FORCE) return performFullUpdate();
     else {
         fitSheets();
         for(Image<float>::iterator v=values.begin(); v!=values.end(); v++) {
         *v = AIR_NAN;
         }
         for(Image<Point>::iterator g=gradients.begin(); g!=gradients.end(); g++) {
         g->x = AIR_NAN;
         }
         Sensor::performUpdate();
         return true;
     }
     }else return false;
 }
void PPSensor::togglePP (enum PPState state = PP_DO) inline
Tell how strict precomputation will be done. PPState::PP_DO will compute and cache on the fly. PPState::PP_FORCE will compute entire caching sheet.
Definition at line 225 of file Sensor.h.
Referenced by SmoothIntensitySensor::SmoothIntensitySensor().
 { doPP = state; }
Member Data Documentation
dword PPSensor::doPP protected
do preprocessing?
Definition at line 240 of file Sensor.h.
Referenced by assign(), and performUpdate().
Image<Point> PPSensor::gradients protected
caching sheet for gradients
Definition at line 239 of file Sensor.h.
Referenced by calcAllGradients(), fitSheets(), and performUpdate().
Image<float> PPSensor::values protected
caching sheet for sensed values
Definition at line 238 of file Sensor.h.
Referenced by SmoothIntensitySensor::calcAllValues(), calcAllValues(), fitSheets(), and performUpdate().
The documentation for this class was generated from the following files:
src/Sensor.h
src/Sensor.cpp