Structural deformable models: MStructure Class Reference
MStructure Class Reference
#include <MStruct.h>
Public Member Functions
MStructure (const std::string &name="", StructTable *psTable=NULL)
MStructure (const MStructure &rhs)
~MStructure ()
void clear ()
MStructure & operator= (const MStructure &rhs)
void setName (const std::string &name)
const std::string & getName () const
void setSize (float size)
float getSize () const
void setModel (const Model &model)
const Model & getModel () const
Model & getModel ()
void setWeight (float weight)
float getWeight () const
void attachStructTable (StructTable *psTable)
StructTable * getStructTable ()
const Searcher & getSearcher () const
const Winner * getWinner (dword wid) const
bool isFrame () const
operator bool () const
void addSubStruct (const SubStructure &substruct)
const SubStructure & getSubStruct (const std::string sname) const
bool hasSubStruct (const std::string sname) const
const SubStructure & getSupStruct (const std::string sname) const
bool hasSupStruct (const std::string sname) const
bool read (ParseFile &is)
void write (std::ostream &os) const
void showStats (const SubStructure &subs, std::ostream &os=std::cout) const
std::string getInfoFilename (const std::string &suffix) const
bool getRefModel (dword id, Model &model) const
void setRefModel (dword id, const Model &model)
bool getRefProp (dword id, PropVec &prop) const
void setRefProp (dword id, const PropVec &prop)
template<class Iter >
dword getRefModelIDs (Iter iter) const
dword loadRefProp ()
void saveRefProp () const
void buildAllStats ()
bool buildMasterModel (float scscale=1.f)
void rebuildExpMap ()
void verifyWinnerRating ()
const ExpectationMap & getExpMap () const
bool stepSearch (float dt)
Protected Member Functions
void refSubSuper (bool doclear=false)
bool addExpectation (const SubStructure &subs, ExpectationMap &expmap, bool inverse=false) const
Protected Attributes
StructTable * m_PStructTable
std::string m_Name
Model m_Model
float m_Size
stdradius in mm
std::map< std::string, SubStructure > m_SubStructures
std::map< std::string, SubStructure * > m_SupStructures
std::map< dword, PropVec > m_RefProp
Searcher m_Searcher
float m_Weight
Winner m_FrameWinner
Friends
class StructTable
ParseFile & operator>> (ParseFile &is, MStructure &st)
std::ostream & operator<< (std::ostream &os, const MStructure &st)
Detailed Description
Definition at line 52 of file MStruct.h.
Constructor & Destructor Documentation
MStructure::MStructure (const std::string & name = "", StructTable * psTable = NULL)
Definition at line 24 of file MStruct.cpp.
References Model::attachDataset(), StructTable::getDataset(), StructTable::getSensors(), m_Model, m_PStructTable, Model::mergeSensorCollection(), and setName().
     : m_PStructTable(psTable), m_Size(1.0f), m_Weight(1.0f)
 {
     setName(name);
     if(m_PStructTable) {
         m_Model.attachDataset(m_PStructTable->getDataset());
         m_Model.mergeSensorCollection(m_PStructTable->getSensors());
     }
 }
MStructure::MStructure (const MStructure & rhs)
Definition at line 34 of file MStruct.cpp.
References operator=().
 {
     operator=(rhs);
 }
MStructure::~MStructure ()
Definition at line 39 of file MStruct.cpp.
References clear(), m_RefProp, and saveRefProp().
 {
     if(!m_RefProp.empty()) saveRefProp();
     clear();
 }
Member Function Documentation
bool MStructure::addExpectation (const SubStructure & subs, ExpectationMap & expmap, bool inverse = false) const protected
Definition at line 373 of file MStruct.cpp.
References ExpectationMap::add(), DMatrix< T >::at(), dmutil::avg(), ExpectationMap::correctLBUB(), DUMP, SubStructure::generateEMDist(), Model::getDataScale(), StructTable::getDataset(), ExpectationMap::getEDist(), Searcher::getGeneration(), EMDRect::getLB(), SubStructure::getLBUB(), Model::getNode(), Dataset::getPPMM(), Model::getProperties(), getPropScale(), Dataset::getPropVec(), Model::getQualityOfFit(), getSearchPara(), EMDistribution::getShootCount(), EMDRect::getUB(), Searcher::getWinList(), isFrame(), Winner::m_BestRating, m_FrameWinner, SearcherParams::m_MaxShoot, SubStructure::m_Mode, Winner::m_Model, SubStructure::m_Pivot, m_PStructTable, SubStructure::m_RateWeight, m_Searcher, Winner::m_WinnerID, DMatrix< T >::max(), DMatrix< T >::min(), SubStructure::MODE_NOSPAWN, NULL, EMDistribution::setCreator(), EMDistribution::setIntegral(), EMDRect::setLB(), setPropPos(), setPropScale(), EMDistribution::setShootCount(), EMDRect::setUB(), and dmutil::stdev().
Referenced by rebuildExpMap().
 {
 // if inverse look backwards to super structure
 //     MStructure& st = m_PStructTable->getStructs()
 //         [backwards ? subs.m_SupStructName : subs.m_SubStructName];
     if(isFrame()) {
         //cout << "is a frame" << endl;
         float ppmm = (float)m_PStructTable->getDataset()->getPPMM();
         PropVec frameprop(m_PStructTable->getDataset()->getPropVec());
         if(!(subs.m_Mode&SubStructure::MODE_NOSPAWN)) {
             EMDistribution* emdist =
                 subs.generateEMDist(frameprop,ppmm,backwards,
                                     getSearchPara().m_PDist);
             emdist->setCreator(m_FrameWinner);
             EMDistribution* olddist=expmap.getEDist(m_FrameWinner.m_WinnerID);
             if(olddist) emdist->setShootCount(olddist->getShootCount());
             float exhaust =
                 float(emdist->getShootCount()) / getSearchPara().m_MaxShoot;
             if(exhaust>1.f) exhaust = 0.f;
             else exhaust = 1.f-exhaust;
             emdist->setIntegral(exhaust); //1.f was default
             expmap.add(emdist);
         }
         PropVec lb, ub;
         subs.getLBUB(lb, ub, frameprop, ppmm);
         ExpectationMap::correctLBUB(lb, ub);
         expmap.setLB(lb);
         expmap.setUB(ub);
         return true;
     }
 //     list<const Model*> winners;
 //     m_Searcher.getWinners( back_inserter(winners) );
     if(subs.m_Mode&SubStructure::MODE_NOSPAWN) return true;
     const map<dword,Winner>& winners = m_Searcher.getWinList();
     dword nwinners = winners.size();
     if(!nwinners) return false;
     DMatrixf qof(1, nwinners);
     map<dword,Winner>::const_iterator wi = winners.begin();
     for(dword i=0; i<nwinners; i++, wi++)
         qof.at(0,i) = wi->second.m_Model->getQualityOfFit();
     float avgqof = dmutil::avg(qof).at(0,0);
     float stdqof = dmutil::stdev(qof).at(0,0);
     float maxqof = qof.max(), minqof = qof.min();
     if(maxqof<0.0000001) return false; //DEBUG
     const Winner* thebest = NULL;
     float bestrating = 0;
     dword maxshoot = 0;
     for(wi = winners.begin(); wi!= winners.end(); wi++) {
         const Winner& winner = wi->second;
         if(m_Searcher.getGeneration(winner.m_Model) > 2) {
             float wqof = winner.m_Model->getQualityOfFit();
 #ifdef _SPAWN_FROM_BEST_
             float rating = wqof/maxqof + subs.m_RateWeight*winner.m_BestRating;
             if(rating > bestrating) {
                 thebest = &winner;
                 bestrating = rating;
             }
         }
     }
     if(thebest) {
         {
             const Winner& winner = *thebest;
             float wqof = winner.m_Model->getQualityOfFit();
 #endif
             float ppmm = (float)winner.m_Model->getDataScale();
             PropVec wprop = winner.m_Model->getProperties();
             if(subs.m_Pivot>=0) setPropPos(wprop, winner.m_Model
                                            ->getNode(subs.m_Pivot));
             EMDistribution* emdist = subs.generateEMDist
                 (wprop,ppmm,backwards,getSearchPara().m_PDist);
             emdist->setCreator(winner);
             EMDistribution* olddist=expmap.getEDist(winner.m_WinnerID);
             if(olddist) emdist->setShootCount(olddist->getShootCount());
             if(maxshoot < emdist->getShootCount())
                 maxshoot = emdist->getShootCount();
             float exhaust =
                 float(emdist->getShootCount()) / getSearchPara().m_MaxShoot;
             if(exhaust>1.f) exhaust = 0.f;
             else exhaust = 1.f-exhaust;
             emdist->setIntegral((wqof/maxqof)*exhaust);
             expmap.add(emdist);
             PropVec lb, ub;
             subs.getLBUB(lb, ub, wprop, ppmm);
             ExpectationMap::correctLBUB(lb, ub);
             PropVec olb = expmap.getLB(), oub = expmap.getUB();
             setPropScale(lb, getPropScale(olb));
             setPropScale(ub, getPropScale(oub));
             ExpectationMap::correctLBUB(lb, olb);
             ExpectationMap::correctLBUB(oub, ub);
             expmap.setLB(lb);
             expmap.setUB(ub);
         }
     }
     if(thebest && false) {
         PropVec lb, ub;
         float ppmm = (float)thebest->m_Model->getDataScale();
         subs.getLBUB(lb, ub, thebest->m_Model->getProperties(), ppmm);
         ExpectationMap::correctLBUB(lb, ub);
         PropVec olb = expmap.getLB(), oub = expmap.getUB();
         setPropScale(olb, getPropScale(lb));
         setPropScale(oub, getPropScale(ub));
         expmap.setLB(olb);
         expmap.setUB(oub);
     }
     DUMP(maxshoot << " --------------------" );
     return true;
 }
void MStructure::addSubStruct (const SubStructure & substruct)
Definition at line 87 of file MStruct.cpp.
References m_Name, SubStructure::m_SubStructName, and m_SubStructures.
Referenced by read().
 {
     m_SubStructures[substruct.m_SubStructName] = substruct;
     m_SubStructures[substruct.m_SubStructName].m_SupStructName = m_Name;
     //super structure references are updated in connectSubSuper()
 }
void MStructure::attachStructTable (StructTable * psTable) inline
Definition at line 71 of file MStruct.h.
 { m_PStructTable = psTable;}
void MStructure::buildAllStats ()
Definition at line 232 of file MStruct.cpp.
References SubStructure::analyseTF(), VVector< T, D >::begin(), buildMasterModel(), Model::convertPointToMM(), Model::getCenter(), getInfoFilename(), Model::getNNodes(), Model::getNode(), getPropPos(), getPropTF(), getRefModel(), getRefModelIDs(), getRefProp(), StructTable::getStructs(), SubStructure::m_Mode, m_Model, m_Name, SubStructure::m_Pivot, m_PStructTable, SubStructure::m_SubStructName, m_SubStructures, SubStructure::MODE_SHOWSTATS, setPropPos(), DMatrix< T >::setRange(), showStats(), VVector< T, D >::size(), and toString().
Referenced by Brain::doCommand().
 {
     set<dword> refmod;
     getRefModelIDs( insert_iterator<set<dword> >(refmod, refmod.begin()) );
     Model model; // not attached to anything
     //ofstream infile("info.dat");
     for(map<string,SubStructure>::iterator si = m_SubStructures.begin();
         si != m_SubStructures.end(); si++)
     {
         SubStructure& subs = si->second;
         MStructure& st = m_PStructTable->getStructs()[subs.m_SubStructName];
         set<dword> strefmod; st.getRefModelIDs(
             insert_iterator<set<dword> >(strefmod, strefmod.begin()) );
         list<dword> comod;
         set_intersection( refmod.begin(), refmod.end(),
                           strefmod.begin(), strefmod.end(),
                           back_inserter(comod) );
         dword ncomod = comod.size();
         DMatrixf tfmat(PropVec::size(), ncomod);
         dword rowind = 0;
         for(list<dword>::const_iterator idi = comod.begin();
             idi != comod.end(); idi++, rowind++)
         {
             Point2D pivot(0,0); bool usepivot = false;
             if(subs.m_Pivot>=0 && m_Model.getNNodes()>subs.m_Pivot) {
                 if(getRefModel(*idi, model)) {  // find pivot
                     pivot = model.getNode(subs.m_Pivot);
                     pivot -= model.getCenter();
                     model.convertPointToMM(pivot);
                     usepivot = true;
                 } else cout << "error: could not find reference model "
                             << getInfoFilename(toString(*idi)) << endl;
             }
             //compute transformation
             PropVec prop, ssprop;
             if(getRefProp(*idi, prop) && st.getRefProp(*idi, ssprop)) {
                 setPropPos(prop, getPropPos(prop) + pivot);
                 PropTF sstf = getPropTF(prop, ssprop);
                 DMatrixf tfvec(PropVec::size(), 1, sstf.begin());
                 tfmat.setRange(0,rowind,tfvec);
             } else cerr << "error getting propvec for " << m_Name
                         << " or " << st.m_Name << " for species "
                         << *idi << endl;
         }
         subs.analyseTF(tfmat);
         if(subs.m_Mode&SubStructure::MODE_SHOWSTATS)
             showStats(subs);
     }
     buildMasterModel();
 }
bool MStructure::buildMasterModel (float scscale = 1.f)
Definition at line 283 of file MStruct.cpp.
References dmutil::abs(), Model::getDataScale(), Model::getEdge(), Model::getLiveliness(), Model::getNEdges(), getRefModel(), getRefModelIDs(), ParticleParam::global, ParticleParam::imgforce, Edge::lengthRatio(), m_Model, Model::phys, Edge::restlength, Model::scale(), SHAPEADAPTTIMESTEP, ParticleParam::springconst, Edge::springconstant, and Model::updateParticles().
Referenced by buildAllStats().
 {
     if(!m_Model) return false;
     list<dword> refmod;
     dword nrefmod = getRefModelIDs( back_inserter(refmod) );
 //        insert_iterator<list<dword> >(refmod, refmod.begin()) );
     Model model; // not attached to anything
     DMatrixf rlen(1, m_Model.getNEdges(), 0.f);
     DMatrixf lenrat(1, m_Model.getNEdges(), 0.f);
     dword nmod = 0;
     for(list<dword>::const_iterator idi = refmod.begin();
         idi != refmod.end(); idi++)
     {
         if(getRefModel(*idi, model)) {  // get model instance
             if(model.getNEdges() == m_Model.getNEdges()) {
                 for(int i=0;i<model.getNEdges();i++) {
                     const Edge& se = model.getEdge(i);
                     //Edge& me = m_Model.getEdge(i);
                     float rl = se.restlength/model.getDataScale();
                     float lr = se.lengthRatio();
                     if(lr>1) lr = 1/lr;
                     lr = 1-lr;
                     rlen.at(0,i) += rl;
                     lenrat.at(0,i) += lr;
                 }
                 nmod++;
             }
         }
     }
     if(nmod>1) {        // setup spring constants according to statistics
         float scmax = ParticleParam::global.springconst;
         float minlr = 1/scmax;
         int i;
         float refallrl=0, nallrl=0;
         for(int i=0;i<m_Model.getNEdges();i++) {
             Edge& me = m_Model.getEdge(i);
             float rl = rlen.at(0,i) /= nmod;
             lenrat.at(0,i) /= nmod;
             nallrl += rl;
             refallrl += me.restlength;
         }
         nallrl *= m_Model.getDataScale();
         m_Model.scale(nallrl/refallrl,true);
         for(int i=0;i<m_Model.getNEdges();i++) {
             Edge& me = m_Model.getEdge(i);
             float rl = rlen.at(0,i);
             float sc = lenrat.at(0,i);
             sc *= scscale;
             //DUMP(sc);
             if(sc>minlr) sc = 1/sc;
             else sc = scmax;
             //cout << "springconst = " << sc << endl;
             me.restlength = rl*m_Model.getDataScale();
             me.springconstant = sc;
         }
 #define SHAPEADAPTTIMESTEP 0.01
         float imgfscale = m_Model.phys.imgforce;
         m_Model.phys.imgforce = 0;              //disable image influence
         m_Model.updateParticles(SHAPEADAPTTIMESTEP);
         float liveliness = 0;
         dword timeout = 100;
         while(abs(liveliness-m_Model.getLiveliness())>0.01 && timeout--) {
             liveliness = m_Model.getLiveliness();
             m_Model.updateParticles(SHAPEADAPTTIMESTEP);
             m_Model.updateParticles(SHAPEADAPTTIMESTEP);
             m_Model.updateParticles(SHAPEADAPTTIMESTEP);
             m_Model.updateParticles(SHAPEADAPTTIMESTEP);
             m_Model.updateParticles(SHAPEADAPTTIMESTEP);
         }
         m_Model.phys.imgforce = imgfscale;
         if(!timeout) cout << "timeout reached while calming model" << endl;
 #undef SHAPEADAPTTIMESTEP
     }
     return true;
 }
void MStructure::clear ()
Definition at line 61 of file MStruct.cpp.
References Model::clear(), m_FrameWinner, m_Model, m_Name, m_RefProp, m_Size, Winner::m_StructName, m_SubStructures, m_SupStructures, and m_Weight.
Referenced by read(), and ~MStructure().
 {
     m_Name.clear();
     m_Model.clear();
     m_Size = 1.0f;
     m_Weight = 1.0f;
     m_SupStructures.clear();
     m_SubStructures.clear();
     m_FrameWinner.m_StructName.clear();
     m_RefProp.clear();
 }
const ExpectationMap& MStructure::getExpMap () const inline
Definition at line 109 of file MStruct.h.
References dmutil::inverse(), and StructTable::stepSearch().
         { return m_Searcher.getExpectationMap(); }
string MStructure::getInfoFilename (const std::string & suffix) const
Definition at line 157 of file MStruct.cpp.
References StructTable::getFilename(), m_Name, and m_PStructTable.
Referenced by buildAllStats(), Brain::doCommand(), getRefModel(), loadRefProp(), saveRefProp(), setRefModel(), and showStats().
{
     string fn;
     if(m_PStructTable) {
       fn = m_PStructTable->getFilename();
       fn = fn.substr(0, fn.rfind('.'));
     } else fn = "struct";
     fn = fn + "_" + m_Name + "_" + suffix + ".dm";
     return fn;
 }
const Model& MStructure::getModel () const inline
Definition at line 67 of file MStruct.h.
Referenced by Brain::load(), and Brain::triggerTest().
 { return m_Model; }
Model& MStructure::getModel () inline
Definition at line 68 of file MStruct.h.
 { return m_Model; }
const std::string& MStructure::getName () const inline
Definition at line 63 of file MStruct.h.
Referenced by StructPath::getWinner(), Brain::load(), StructTable::read(), and Brain::triggerTest().
 { return m_Name; }
bool MStructure::getRefModel (dword id, Model & model) const
Definition at line 167 of file MStruct.cpp.
References getInfoFilename(), Model::readFile(), and toString().
Referenced by buildAllStats(), buildMasterModel(), Brain::load(), showStats(), and Brain::triggerTest().
 {
     string filename = getInfoFilename(toString(id));
     bool readf = model.readFile(filename.c_str());
     return readf;
 }
template<class Iter > dword MStructure::getRefModelIDs (Iter iter) const
Definition at line 131 of file MStruct.h.
References FFind::findFiles(), and fromString().
Referenced by buildAllStats(), buildMasterModel(), Brain::doCommand(), showStats(), and Brain::triggerTest().
{
     dword count = 0;
     if(!m_Model) {
         for(std::map<dword,PropVec>::const_iterator rp=m_RefProp.begin();
             rp!=m_RefProp.end(); rp++, count++)
             *iter++ = rp->first;
         return count;
     }
     std::string filemask = getInfoFilename("*");
     std::list<std::string> files;
     if(FFind::findFiles(filemask, back_inserter(files)))
     {
         for(std::list<std::string>::iterator cf=files.begin();
             cf != files.end(); cf++) {
             std::string suff = cf->substr(cf->rfind('_')+1);
             suff = suff.substr(0, suff.find('.'));
             dword id=0;
             fromString(suff, id);
             if(id) {
                 *iter++ = id;
                 count++;
             }
         }
     }
     return count;
 }
bool MStructure::getRefProp (dword id, PropVec & prop) const
Definition at line 174 of file MStruct.cpp.
References m_RefProp.
Referenced by buildAllStats(), showStats(), and Brain::triggerTest().
 {
     map<dword,PropVec>::const_iterator rp = m_RefProp.find(id);
     if(rp != m_RefProp.end()) {
         prop = rp->second;
         return true;
     } else return false;
 }
const Searcher& MStructure::getSearcher () const inline
Definition at line 73 of file MStruct.h.
Referenced by StructTable::findBestConnection(), Brain::triggerTest(), and verifyWinnerRating().
 { return m_Searcher; }
float MStructure::getSize () const inline
Definition at line 65 of file MStruct.h.
 { return m_Size; }
StructTable* MStructure::getStructTable () inline
Definition at line 72 of file MStruct.h.
 { return m_PStructTable; }
const SubStructure& MStructure::getSubStruct (const std::string sname) const inline
Definition at line 79 of file MStruct.h.
         { return m_SubStructures.find(sname)->second; }
const SubStructure& MStructure::getSupStruct (const std::string sname) const inline
Definition at line 83 of file MStruct.h.
Referenced by StructPath::print().
         { return *m_SupStructures.find(sname)->second; }
float MStructure::getWeight () const inline
Definition at line 70 of file MStruct.h.
Referenced by StructTable::findBestConnection(), and StructPath::print().
 { return m_Weight; }
const Winner * MStructure::getWinner (dword wid) const
Definition at line 80 of file MStruct.cpp.
References Searcher::getWinner(), isFrame(), m_FrameWinner, m_Searcher, and Winner::WID_FRAME.
Referenced by StructTable::findBestConnection(), StructPath::getWinner(), and StructPath::print().
 {
     if(isFrame() && wid==Winner::WID_FRAME)
         return &m_FrameWinner;
     else return m_Searcher.getWinner(wid);
 }
bool MStructure::hasSubStruct (const std::string sname) const inline
Definition at line 81 of file MStruct.h.
         { return m_SubStructures.find(sname) != m_SubStructures.end(); }
bool MStructure::hasSupStruct (const std::string sname) const inline
Definition at line 85 of file MStruct.h.
References SubStructure::read(), and StructTable::write().
Referenced by StructPath::print().
         { return m_SupStructures.find(sname) != m_SupStructures.end(); }
bool MStructure::isFrame () const inline
Definition at line 75 of file MStruct.h.
Referenced by addExpectation(), getWinner(), stepSearch(), and verifyWinnerRating().
 { return !m_Model; }
dword MStructure::loadRefProp ()
Definition at line 198 of file MStruct.cpp.
References fromString(), getInfoFilename(), ParseFile::getKey(), ParseFile::getNextLine(), ParseFile::getValue(), and m_RefProp.
Referenced by read().
 {
     if(!*this) return 0;
     string filename(getInfoFilename("pvec"));
     ParseFile pf(filename);
     if(pf) {
         m_RefProp.clear();
         while(pf.getNextLine()) {
             dword id=0;
             fromString(pf.getKey(),id);
             if(id) {
                 PropVec prop(0.0);
                 fromString(pf.getValue(), prop);
                 m_RefProp[id] = prop;
             }
         }
         return m_RefProp.size();
     } return 0;
 }
MStructure::operator bool () const inline
Definition at line 76 of file MStruct.h.
 { return !m_Name.empty(); }
MStructure & MStructure::operator= (const MStructure & rhs)
Definition at line 45 of file MStruct.cpp.
References m_FrameWinner, m_Model, m_Name, m_PStructTable, m_RefProp, m_Size, m_SubStructures, m_SupStructures, and m_Weight.
Referenced by MStructure().
 {
     if(this != &rhs) {
         m_Name = rhs.m_Name;
         m_Model = rhs.m_Model;
         m_Size = rhs.m_Size;
         m_PStructTable = rhs.m_PStructTable;
         m_SubStructures = rhs.m_SubStructures;
         m_SupStructures = rhs.m_SupStructures;
         m_RefProp = rhs.m_RefProp;
         m_Weight = rhs.m_Weight;
         m_FrameWinner = rhs.m_FrameWinner;
     }
     return *this;
 }
bool MStructure::read (ParseFile & is)
Definition at line 94 of file MStruct.cpp.
References addSubStruct(), clear(), ParseFile::error(), fromString(), ParseFile::getKey(), ParseFile::getNextLine(), ParseFile::getPath(), ParseFile::getValue(), loadRefProp(), m_Model, m_Name, m_Searcher, m_Size, m_Weight, ParseFile::pushLine(), SubStructure::read(), Model::readFile(), setName(), ParseFile::setParseError(), Searcher::setShapeWeight(), and STRUCT_SHAPEWEIGHT.
Referenced by StructTable::read().
 {
     clear();
     bool readon = true;
     SubStructure substruct;
     while(readon && is.getNextLine()) {
         const string& key = is.getKey();
         const string& value = is.getValue();
         if(key == "struct") {
             if(!m_Name.empty()) is.setParseError(
                 "struct inside struct. (rather use substruct?)");
             else {
                 setName(value.c_str());
                 loadRefProp();
             }
         } else if(m_Name.empty()) {
             is.pushLine(); return false;
         } else if(key == "end") readon = false;
         else if(key == "model") {
             string filename = is.getPath()+is.getValue();
             if(!m_Model.readFile(filename.c_str())) {
                 is.setParseError(string("couldn't load model ")+filename);
             }
         } else if(key == "size") {
             istringstream(value) >> m_Size;
         } else if(key == "weight") {
             fromString(value, m_Weight);
         } else if(key == "shapeweight") {
             float shapeweight=STRUCT_SHAPEWEIGHT;
             fromString(value, shapeweight);
             m_Searcher.setShapeWeight(shapeweight);
         } else if(substruct.read(is)) addSubStruct(substruct);
         else is.setParseError(string("(parsing struct) unknown token ") + key);
     }
     if(is.error()) return false;
     return true;
 }
void MStructure::rebuildExpMap ()
Definition at line 482 of file MStruct.cpp.
References ExpectationMap::add(), addExpectation(), ExpectationMap::clear(), ExpectationMap::correctLBUB(), DUMP, StructTable::getDataset(), Dataset::getDim1Size(), Dataset::getDim2Size(), Searcher::getExpectationMap(), Dataset::getPPMM(), Model::getPropertiesMM(), getPropScale(), ExpectationMap::getRepresentative(), StructTable::getStructs(), EMDistribution::m_Integral, m_Model, m_Name, M_PI, m_PStructTable, m_Searcher, m_SubStructures, m_SupStructures, ExpectationMap::markAllOld(), Searcher::setExpectationMap(), EMDRect::setLB(), Model::setName(), setPropDir(), setPropPos(), setPropScale(), ExpectationMap::setRepresentative(), and EMDRect::setUB().
 {
     if(!m_Model) return;
     //cout << "rebuild expmap for " << m_Name << endl;
     ExpectationMap& expmap = m_Searcher.getExpectationMap();
     expmap.markAllOld();
     expmap.setRepresentative(m_Model);
     expmap.getRepresentative().setName(m_Name);
 //calculate upper and lower bounds from dataset (and avg Model)
     PropVec propl(0.), propu(0.);
     Point2D dims((float)m_PStructTable->getDataset()->getDim1Size(),
                  (float)m_PStructTable->getDataset()->getDim2Size());
     float scale = getPropScale(m_Model.getPropertiesMM());
     scale *= m_PStructTable->getDataset()->getPPMM();
     setPropPos(propu, dims);
     setPropDir(propu, 2*M_PI);
     setPropScale(propu, scale*1.1);  // is that good?
     setPropScale(propl, scale*0.9);
     ExpectationMap::correctLBUB(propl, propu);
     expmap.setLB(propl);
     expmap.setUB(propu);
 #ifdef _USE_BACKGROUND_DIST_
 //add a background distribution over entire allowed search range
     EMDRect* drect = new EMDRect(propl,propu);
     //drect->setIntegral(0.2); keep it 1 (like the winner)
     expmap.add(drect); //DEBUG
 #endif
 //add expectation from connected super structures
     for(map<string,SubStructure*>::iterator si = m_SupStructures.begin();
         si != m_SupStructures.end(); si++)
     {
         MStructure& st = m_PStructTable->getStructs()[si->first];
         // [si->second->m_SupStructName]
         st.addExpectation(*si->second, expmap);
     }
 #if DO_INVERSE_TRANSFORM
 //add expectation backwards from sub structures
     for(map<string,SubStructure>::iterator si = m_SubStructures.begin();
         si != m_SubStructures.end(); si++)
     {
         MStructure& st = m_PStructTable->getStructs()[si->first];
         st.addExpectation(si->second, expmap, true);
     }
 #endif
     expmap.clear(true);         // remove old ones only
     m_Searcher.setExpectationMap(expmap);
     DUMP(m_Name<<" "<<expmap.m_Integral);
 }
void MStructure::refSubSuper (bool doclear = false) protected
Definition at line 359 of file MStruct.cpp.
References StructTable::getStructs(), m_Name, m_PStructTable, m_SubStructures, and m_SupStructures.
 {
     if(doclear) {  // just clear own list
         m_SupStructures.clear();
         return;
     }
     for(map<string,SubStructure>::iterator si = m_SubStructures.begin();
         si != m_SubStructures.end(); si++)
     {
         MStructure& st = m_PStructTable->getStructs()[si->first];
         st.m_SupStructures[m_Name] = &si->second;
     }
 }
void MStructure::saveRefProp () const
Definition at line 218 of file MStruct.cpp.
References getInfoFilename(), and m_RefProp.
Referenced by ~MStructure().
 {
     if(!*this) return;
     string filename = getInfoFilename("pvec");
     ofstream os(filename.c_str());
     if(os)
         for(map<dword,PropVec>::const_iterator rp=m_RefProp.begin();
             rp != m_RefProp.end(); rp++)
         {
             if(rp->first)
                 os << rp->first << " " << rp->second << endl;
         }
 }
void MStructure::setModel (const Model & model) inline
Definition at line 66 of file MStruct.h.
Referenced by Brain::triggerTest().
 { m_Model = model; }
void MStructure::setName (const std::string & name)
Definition at line 73 of file MStruct.cpp.
References m_FrameWinner, m_Name, Winner::m_StructName, Winner::m_WinnerID, and Winner::WID_FRAME.
Referenced by MStructure(), and read().
 {
     m_Name = name;
     m_FrameWinner.m_StructName = name; //just in case it is used
     m_FrameWinner.m_WinnerID = Winner::WID_FRAME;
 }
void MStructure::setRefModel (dword id, const Model & model)
Definition at line 188 of file MStruct.cpp.
References Model::convertPropToMM(), getInfoFilename(), Model::getProperties(), m_RefProp, toString(), and Model::writeFile().
Referenced by Brain::doCommand(), and Brain::triggerTest().
 {
     PropVec pv(model.getProperties());
     model.convertPropToMM(pv);
     m_RefProp[id] = pv;
     //save model file for geometry internal statistics
     string filename = getInfoFilename(toString(id));
     model.writeFile(filename.c_str());
 }
void MStructure::setRefProp (dword id, const PropVec & prop)
Definition at line 183 of file MStruct.cpp.
References m_RefProp.
Referenced by Brain::doCommand(), and Brain::triggerTest().
 {
     m_RefProp[id] = prop;
 }
void MStructure::setSize (float size) inline
Definition at line 64 of file MStruct.h.
 { m_Size = size; }
void MStructure::setWeight (float weight) inline
Definition at line 69 of file MStruct.h.
 { m_Weight = weight; }
void MStructure::showStats (const SubStructure & subs, std::ostream & os = std::cout) const
Definition at line 561 of file MStruct.cpp.
References DMatrix< T >::at(), dmutil::avg(), VVector< T, D >::begin(), Model::convertPointToMM(), DUMP, SubStructure::generateEMDist(), Model::getCenter(), getIdentityPropTF(), getInfoFilename(), Model::getNNodes(), Model::getNode(), getPropPos(), getPropTF(), getRefModel(), getRefModelIDs(), getRefProp(), getSearchPara(), StructTable::getStructs(), SubStructure::m_Mean, m_Model, m_Name, SubStructure::m_Pivot, m_PStructTable, SubStructure::m_Sigma, SubStructure::m_Stdev, SubStructure::m_SubStructName, SubStructure::m_SupStructName, DMatrix< T >::max(), DMatrix< T >::min(), EMDistribution::ratePropVec(), setPropPos(), DMatrix< T >::setRange(), VVector< T, D >::size(), dmutil::stdev(), and toString().
Referenced by buildAllStats().
 {
     os << " stats for ["<<subs.m_SupStructName<<"] --> ["
        <<subs.m_SubStructName<<"]"<<endl;
     set<dword> refmod;
     getRefModelIDs( insert_iterator<set<dword> >(refmod, refmod.begin()) );
     Model model; // not attached to anything
     MStructure& st = m_PStructTable->getStructs()[subs.m_SubStructName];
     set<dword> strefmod; st.getRefModelIDs(
         insert_iterator<set<dword> >(strefmod, strefmod.begin()) );
     list<dword> comod;
     set_intersection( refmod.begin(), refmod.end(),
                       strefmod.begin(), strefmod.end(),
                       back_inserter(comod) );
     dword ncomod = comod.size();
     DMatrixf tfmat(PropVec::size(), ncomod);
     DMatrixf ratings(1,ncomod);
     dword rowind = 0;
     for(list<dword>::const_iterator idi = comod.begin();
         idi != comod.end(); idi++, rowind++)
     {
         Point2D pivot(0,0); bool usepivot = false;
         if(subs.m_Pivot>=0 && m_Model.getNNodes()>subs.m_Pivot) {
             if(getRefModel(*idi, model)) {  // find pivot
                 pivot = model.getNode(subs.m_Pivot);
                 pivot -= model.getCenter();
                 model.convertPointToMM(pivot);
                 usepivot = true;
             } else os << "error: could not find reference model "
                       << getInfoFilename(toString(*idi)) << endl;
         }
         //compute transformation
         PropVec prop, ssprop;
         if(getRefProp(*idi, prop) && st.getRefProp(*idi, ssprop)) {
             setPropPos(prop, getPropPos(prop) + pivot);
             PropTF sstf = getPropTF(prop, ssprop);
             DMatrixf tfvec(PropVec::size(), 1, sstf.begin());
             tfmat.setRange(0,rowind,tfvec);
             //determine rating
             EMDistribution* ed = subs.generateEMDist(prop,1,false,
                                                      getSearchPara().m_PDist);
             if(ed) {
                 ratings.at(0,rowind) = ed->ratePropVec(ssprop);
                 os << *idi << ": " << ratings.at(0,rowind) << "  pv:"
                    << getPropTF(prop,ssprop) << endl;
                 delete ed;
             } else os << "error generating exp.distr. for " << *idi << endl;
         } else os << "error getting propvec for " << m_Name
                   << " or " << st.m_Name << " for species "
                   << *idi << endl;
     }
     EMDistribution* ed = subs.generateEMDist(getIdentityPropTF(),1,false,
                                              getSearchPara().m_PDist);
     if(ed) {
         os << "central rating: " << ed->ratePropVec(subs.m_Mean) << endl;
         DUMP(subs.m_Mean);
         DUMP(subs.m_Stdev);
         delete ed;
     os << "pcomp  : " << PropVec(&subs.m_Sigma.at(0,0)) << endl;
     os << "average: " << dmutil::avg(ratings).at(0,0) << endl;
     os << "stdev  : " << dmutil::stdev(ratings).at(0,0) << endl;
     if(ncomod>0) {
       os << "min    : " << ratings.min() << endl;
       os << "max    : " << ratings.max() << endl;
     }
     } else os << "error generating exp.distr." << endl;
 }
bool MStructure::stepSearch (float dt)
Definition at line 630 of file MStruct.cpp.
References isFrame(), m_Searcher, and Searcher::step().
 {
     return m_Searcher.step(dt) || isFrame();
 }
void MStructure::verifyWinnerRating ()
Definition at line 531 of file MStruct.cpp.
References getSearcher(), StructTable::getStructs(), Searcher::getWinList(), Searcher::getWinner(), isFrame(), m_Name, m_PStructTable, and m_Searcher.
 {
     int okcount = 0;
     map<dword,Winner>& wl = m_Searcher.getWinList();
     for(map<dword,Winner>::iterator wi = wl.begin(); wi!=wl.end(); wi++)
     { // for each Winner wi
         for(Winner::Ratings::iterator refstruct = wi->second.m_Ratings.begin();
             refstruct != wi->second.m_Ratings.end(); refstruct++)
         { // for each rating parent structure
             MStructure& st = m_PStructTable->getStructs()[refstruct->first];
             if(!st.isFrame()) {
                 map<dword,float>::iterator wr= refstruct->second.begin();
                 while(wr != refstruct->second.end())
                 { // for each rating wr
                     map<dword,float>::iterator nextwr = wr; nextwr++;
                     const Winner* refwin=st.getSearcher().getWinner(wr->first);
                     if(refwin) {
                         okcount++;
                     } else {
                         refstruct->second.erase(wr);
                     }
                     wr = nextwr;
                 }
             } else okcount += refstruct->second.size();
         }
         wi->second.updateBestRating();
     }
     cout << okcount << " good connections to struct " << m_Name << endl;
 }
void MStructure::write (std::ostream & os) const
Definition at line 132 of file MStruct.cpp.
References Model::getFilename(), StructTable::getPath(), Searcher::getShapeWeight(), m_Model, m_Name, m_PStructTable, m_Searcher, m_Size, m_SubStructures, m_Weight, and STRUCT_SHAPEWEIGHT.
 {
     if(!(*this)) return;
     os << "struct " << m_Name << endl;
     if(!m_Model.getFilename().empty()) {
         string filename = m_Model.getFilename();
         if(m_PStructTable) {
             if(filename.substr(0,m_PStructTable->getPath().size())
                == m_PStructTable->getPath())
                 filename = filename.substr(m_PStructTable->getPath().size());
         }
         os << "  model " << filename << endl;
     }
     if(m_Weight != 1.f) os << "  weight " << m_Weight << endl;
     if(m_Searcher.getShapeWeight() != STRUCT_SHAPEWEIGHT)
         os << "  shapeweight " << m_Searcher.getShapeWeight() << endl;
     os << "  size " << m_Size << endl;
     for(map<string,SubStructure>::const_iterator si = m_SubStructures.begin();
         si != m_SubStructures.end(); si++)
     {
         os << si->second;
     }
     os << "end    # of struct" << endl << endl;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const MStructure & st) friend
Definition at line 92 of file MStruct.h.
         { st.write(os); return os; }
ParseFile& operator>> (ParseFile & is, MStructure & st) friend
Definition at line 90 of file MStruct.h.
         { st.read(is); return is; }
friend class StructTable friend
Definition at line 54 of file MStruct.h.
Member Data Documentation
Winner MStructure::m_FrameWinner protected
Definition at line 127 of file MStruct.h.
Referenced by addExpectation(), clear(), getWinner(), operator=(), and setName().
Model MStructure::m_Model protected
Definition at line 120 of file MStruct.h.
Referenced by buildAllStats(), buildMasterModel(), clear(), MStructure(), operator=(), read(), rebuildExpMap(), showStats(), and write().
std::string MStructure::m_Name protected
Definition at line 119 of file MStruct.h.
Referenced by addSubStruct(), buildAllStats(), clear(), getInfoFilename(), operator=(), read(), rebuildExpMap(), refSubSuper(), setName(), showStats(), verifyWinnerRating(), and write().
StructTable* MStructure::m_PStructTable protected
Definition at line 118 of file MStruct.h.
Referenced by addExpectation(), buildAllStats(), getInfoFilename(), MStructure(), operator=(), rebuildExpMap(), refSubSuper(), showStats(), verifyWinnerRating(), and write().
std::map<dword,PropVec> MStructure::m_RefProp protected
Definition at line 124 of file MStruct.h.
Referenced by clear(), getRefProp(), loadRefProp(), operator=(), saveRefProp(), setRefModel(), setRefProp(), and ~MStructure().
Searcher MStructure::m_Searcher protected
Definition at line 125 of file MStruct.h.
Referenced by addExpectation(), getWinner(), read(), rebuildExpMap(), stepSearch(), verifyWinnerRating(), and write().
float MStructure::m_Size protected
stdradius in mm
Definition at line 121 of file MStruct.h.
Referenced by clear(), operator=(), read(), and write().
std::map<std::string, SubStructure> MStructure::m_SubStructures protected
Definition at line 122 of file MStruct.h.
Referenced by addSubStruct(), buildAllStats(), clear(), StructTable::findBestConnection(), operator=(), rebuildExpMap(), refSubSuper(), and write().
std::map<std::string, SubStructure*> MStructure::m_SupStructures protected
Definition at line 123 of file MStruct.h.
Referenced by clear(), operator=(), rebuildExpMap(), and refSubSuper().
float MStructure::m_Weight protected
Definition at line 126 of file MStruct.h.
Referenced by clear(), operator=(), read(), and write().
The documentation for this class was generated from the following files:
src/MStruct.h
src/MStruct.cpp