Structural deformable models: SmoothIntensitySensor Class Reference
SmoothIntensitySensor Class Reference
#include <SensorSet.h>
Public Member Functions
SmoothIntensitySensor (float _scale=0)
bool performUpdate ()
std::ostream & print (std::ostream &os) const
Public Member Functions inherited from PPSensor
PPSensor ()
virtual float getValue (int x, int y) const
virtual Point getGradient (int x, int y) const
Sensor & assign (const Sensor &rhs)
void togglePP (enum PPState state=PP_DO)
dword getPPState () const
Public Member Functions inherited from Sensor
virtual ~Sensor ()
sensor_cptr getSource ()
virtual void changeSource (sensor_cptr _source)
void replaceBy (sensor_ptr target)
bool assignRef (sensor_cptr rhs)
float getValue (const Point &p) const
get value at position p using nearest neighbour interpolation
virtual std::vector< float > getMValue (int x, int y) const
get multi-channel value
Point2D getGradient (const Point2D &p) const
get gradient at position p using nearest neighbor interpolation
float getMax () const
float getMin () const
float getMinMaxRange () const
float getWeightedValue (int x, int y) const
get max normalized value at discrete position range [0,1]
Point2D getWeightedGradient (int x, int y) const
get range weighted gradient at discrete position
void setCWeights (const std::vector< float > &weights)
const std::vector< float > & getCWeights () const
void setDirection (const Point &dir)
const Point & getDirection () const
void setScale (float _scale)
float getScale () const
bool isModified (dword mask=UPD_ALL) const
void setModified (dword mask=UPD_ALL)
void unsetModified (dword mask=UPD_ALL)
bool isUpdate (dword udMask) const
void enableUpdate (dword udMask)
void disableUpdate (dword udMask)
virtual int getDim1Size () const
virtual int getDim2Size () const
virtual int getDim3Size () const
virtual int getNChannels () const
virtual int getSkip () const
bool isValid (int x, int y) const
virtual Image< float > createSensorImage () const
const std::string & getID () const
void setID (const std::string &id)
virtual std::ostream & hprint (std::ostream &os, SensorCollection *sc) const
void refSuperSensor (sensor_ptr super)
void unrefSuperSensor (sensor_ptr super)
void invalidateSource ()
template<typename Derived >
std::shared_ptr< Derived > shared_from_base ()
Protected Member Functions
void calcAllValues ()
float calcValue (int x, int y) const
void updateScale ()
Protected Member Functions inherited from PPSensor
void fitSheets ()
virtual void calcAllGradients ()
Protected Member Functions inherited from Sensor
Sensor (dword updateMask)
Sensor ()
virtual std::vector< float > calcMValue (int x, int y) const
virtual Point calcGradient (int x, int y) const
virtual void calcMinMax ()
Protected Attributes
Fourier2D m_FT
Fourier2D m_FTflt
Image< double > m_SData
Image< double > m_SFilter
Image< std::complex< double > > m_FData
Image< std::complex< double > > m_FFilter
Protected Attributes inherited from PPSensor
Image< float > values
caching sheet for sensed values
Image< Point > gradients
caching sheet for gradients
dword doPP
do preprocessing?
Protected Attributes inherited from Sensor
sensor_cptr source
float scale
std::vector< float > cweights
multi-channel weights ('color')
Point dir
direction parameter
float maxval
float minval
overall minimum and maximum
float mean
float stdev
overall mean and stdev
dword toupdate
bitflag for updates
dword updateMask
bitflag to mask unimportant updates
std::string m_ID
int m_Skip
int m_AddSkip
Additional Inherited Members
Public Types inherited from PPSensor
enum PPState { PP_DONT =0, PP_DO, PP_FORCE }
Public Types inherited from Sensor
enum UpdateParam {
UPD_NOTHING =0, UPD_DATA =1, UPD_SCALE =2, UPD_CWEIGHTS =4,
UPD_DIR =8, UPD_MINMAX =16, UPD_LAST =32, UPD_ALL =0xffffffff
}
Static Public Member Functions inherited from Sensor
static dword getStringNumber (const char *sid)
static void getNumberString (char sid[5], dword id)
Detailed Description
Smoothed intensity sensor (using gaussian)
Definition at line 149 of file SensorSet.h.
Constructor & Destructor Documentation
SmoothIntensitySensor::SmoothIntensitySensor (float _scale = 0)
Definition at line 20 of file SensorSet.cpp.
 {
     enableUpdate(UPD_SCALE|UPD_DATA);
     togglePP(PP_FORCE);
     setScale(_scale);
 }
Member Function Documentation
void SmoothIntensitySensor::calcAllValues () protected virtual
Reimplemented from PPSensor.
Definition at line 43 of file SensorSet.cpp.
References PPSensor::calcAllValues().
 {
     PPSensor::calcAllValues();
     if(m_FFilter.initialized() && m_FData.initialized()) {
         m_SData.convertFrom(values);
         m_FT.transform();
         m_FData *= m_FFilter;
         m_FT.transformInv();
         values.convertFrom(m_SData);
         //values = values.convolve(m_SFilter);
     }
 }
float SmoothIntensitySensor::calcValue (int x, int y) const inline protected virtual
Compute a sensed value at position x,y. This function is essential for all derived sensors.
Implements Sensor.
Definition at line 162 of file SensorSet.h.
References Sensor::source.
{
         return source->getValue(x,y);
     }
bool SmoothIntensitySensor::performUpdate () virtual
clear all data sheets
Reimplemented from PPSensor.
Definition at line 27 of file SensorSet.cpp.
References Fourier2D::complexX(), and PPSensor::performUpdate().
{
     if(!isModified()) return false;
     if(source->getDim1Size()>0) {
         if(m_SData.getSizeX() != source->getDim1Size() ||
            m_SData.getSizeY() != source->getDim2Size()) {
             m_SData.setSize(source->getDim1Size(), source->getDim2Size());
             m_FData.setSize(Fourier2D::complexX(source->getDim1Size())/2,
                             source->getDim2Size());
             m_FT.initTransform(m_SData.getSizeX(), m_SData.getSizeY(),
                                m_SData.getData(), (double*)m_FData.getData());
         }
         updateScale();
     }
     return PPSensor::performUpdate();
 }
std::ostream& SmoothIntensitySensor::print (std::ostream & os) const inline virtual
Reimplemented from Sensor.
Definition at line 154 of file SensorSet.h.
References Sensor::getScale(), and Sensor::print().
{
         Sensor::print(os)
             << "g " << getScale();
         return os;
     }
void SmoothIntensitySensor::updateScale () protected
Definition at line 56 of file SensorSet.cpp.
References Fourier2D::complexX(), create2DGaussian(), Image< T >::getSize(), and dmutil::stdev().
{
     assert(source->getDim1Size()>0);
     bool nosizematch = !(m_SFilter.getSizeX() == source->getDim1Size() &&
                          m_SFilter.getSizeY() == source->getDim2Size());
     if(isModified(UPD_SCALE) || nosizematch) {
         unsetModified(UPD_SCALE);
         if(nosizematch) {
             m_SFilter.setSize(source->getDim1Size(), source->getDim2Size());
             m_FFilter.setSize(Fourier2D::complexX(m_SFilter.getSizeX())/2,
                               m_SFilter.getSizeY());
             m_FTflt.initTransform(m_SFilter.getSizeX(), m_SFilter.getSizeY(),
                                   m_SFilter.getData(),
                                   (double*)m_FFilter.getData());
         }
         float ffltsize = pow(2,scale);
         int fltsize = (int)ffltsize;
         if(fltsize<1) fltsize=1;
         m_AddSkip = fltsize/2+1;
         double stdev = ffltsize*0.5*0.2;
         create2DGaussian(m_SFilter, stdev, ffltsize,
                          m_SFilter.getSizeX()/2.0f,m_SFilter.getSizeY()/2.0f);
         m_FTflt.transform();
 //normalize transform and perform shift
         double factor = 1.0/m_SFilter.getSize();
         double nfactor = -factor;
         complex<double>* freq = m_FFilter.getData();
         for(int j=0; j<m_FFilter.getSizeY(); j++) {
             for(int i=0; i<m_FFilter.getSizeX(); i++, freq++) {
                 if((i+j)&0x01) *freq *= nfactor;
                 else *freq *= factor;
             }
         }
         setModified(UPD_DATA);
     }
 }
Member Data Documentation
Image< std::complex<double> > SmoothIntensitySensor::m_FData protected
Definition at line 169 of file SensorSet.h.
Image< std::complex<double> > SmoothIntensitySensor::m_FFilter protected
Definition at line 169 of file SensorSet.h.
Fourier2D SmoothIntensitySensor::m_FT protected
Definition at line 167 of file SensorSet.h.
Fourier2D SmoothIntensitySensor::m_FTflt protected
Definition at line 167 of file SensorSet.h.
Image< double > SmoothIntensitySensor::m_SData protected
Definition at line 168 of file SensorSet.h.
Image< double > SmoothIntensitySensor::m_SFilter protected
Definition at line 168 of file SensorSet.h.
The documentation for this class was generated from the following files:
src/SensorSet.h
src/SensorSet.cpp