Structural deformable models: Model Class Reference
Model Class Reference
#include <Model.h>
Public Types
enum DistType {
DIST_XY, DIST_XYS, DIST_PVEC, DIST_POINTS,
DIST_CPOINTS, DIST_HPOINTS
}
enum ModelState {
ST_WINNER =1, ST_LOOSER =2, ST_OLDSTATE =4, ST_DEL =8,
ST_MEMBER =16, ST_NODEL =32
}
Public Member Functions
Model (dataset_cptr _dataset=NULL, SensorCollection *sensors=NULL)
Default constructor.
Model (const Model &rhs)
Copy constructor.
~Model ()
Destructor.
void clear ()
remove and destroy all geometry information (nodes and edges)
operator bool () const
is initialized?
void reset ()
reset all model information (including geometry)
int addNode (const Node &node)
int addEdge (const Edge &edge)
int addEdge (const Node &from, const Node &to)
int addEdge (int ifrom, int ito)
const Edge & getEdge (int index) const
Edge & getEdge (int index)
const Node & getNode (int index) const
Node & getNode (int index)
int getNNodes () const
int getNEdges () const
float getNodeAngle (const Node &n) const
void setName (const std::string &name)
const std::string & getName () const
dword getCRC () const
dword getID () const
void setID (dword id)
void draw (bool drawPoints=false) const
Draw using OpenGL.
void drawPS (CAMgraphicsProcess &gp, dword mode=0) const
Draw to postscrip output.
bool readEdge (ParseFile &is)
read edge from stream
bool readNode (ParseFile &is)
read node from stream
bool readSensor (ParseFile &is)
read sensor from stream
bool readParameter (ParseFile &is)
read model parameters
Model & operator= (const Model &rhs)
bool readFile (const char *filename, bool fullread=true)
bool writeFile (const char *filename) const
void attachDataset (dataset_cptr dataset)
float getQualityOfFit () const
float getLiveliness () const
void translate (const Point &t)
void addNoise (float r)
void freeze ()
void push (const Point &t)
void rotate (float angle, const Point &c)
void rotate (float angle)
void pushRotate (const Point &c, float angle)
void attract (const Point &c, float factor)
float getFullLength () const
Returns overall sum of edge lengths.
float getStdRadius (const Point &center) const
Returns mean squared distance from centroid.
float getStdRadius () const
float getMaxRadius (const Point &center) const
Returns the maximum radius from the centroid.
float getMaxRadius () const
void scale (float factor, bool movepoints=false)
multiply all rest lengths by factor
void scaleSel (float factor, const DMatrixf &selm)
multiply all rest lengths of selected edges by factor
void adaptRestLength (float ratio)
adapt restlengths towards current lengths by ratio
void adaptRestLengthSel (float ratio, const DMatrixf &selm)
adapt restlengths of selected edges towards current lengths by ratio
void adaptProportion (float ratio)
overall rest lengths sum is adapted to overall edge lengths by ratio
float getLengthRatio () const
relation of overall edge length by overall rest length sum
float getLengthVariation () const
mean squared difference from restlength normalized by restlength sum
float getDeformation () const
normalized length variation to compensate for different sizes
float getSensorFit (dword *npts=NULL) const
get average sensor value
float getEdgeSensorFit (dword *npts=NULL) const
get average fit of sensors along edges
void updateParticles (float dt, int method=0)
void resetForces ()
void calculateForces (float dt)
void calculateDerivatives (std::vector< NodeDerivative > &deriv)
float addImageForces (float dt)
void addTorque (float dt)
void prepareTorque ()
void mergeSensorCollection (SensorCollection *sensors)
SensorCollection * getSensorCollection ()
void reattachSensors ()
get sensors from sensor collection
dword createEdgeSensors (float dist=0.1)
auto-create appropriate edge sensors (dist*stdRadius is distance)
const Point getCenter () const
float getDirection () const
const Node & getDirNode () const
void setDirNode (int id)
void setWinner (bool iswin=true, float ts=0.)
bool isWinner ()
void setLooser (bool isloose=true, float ts=0.)
bool isLooser ()
void setOldState (bool isoldstate=true, float ts=0.)
bool isOldState ()
dword & getFlags ()
bool hasFlags (dword flags) const
dword & setFlags (dword flags)
dword & unsetFlags (dword flags)
dword & switchFlags (dword flags)
void setShapeWeight (float weight)
void adaptDataScale (dword ppmm=0)
dword getDataScale () const
void adaptProperties (const PropVec &prop)
const PropVec & getProperties () const
PropVec getPropertiesMM () const
return property vector using millimeter scale
void adaptPropertiesMM (PropVec prop)
adapt to a property vector using millimeter scale
Point2D & convertPointFromMM (Point2D &pt) const
Point2D & convertPointToMM (Point2D &pt) const
PropVec & convertPropFromMM (PropVec &prop) const
PropVec & convertPropToMM (PropVec &prop) const
int nearestNode (const Point &pos, float &dist=*(float *)(NULL)) const
float distance (const Model &rhs, enum Model::DistType kind=DIST_POINTS) const
void invalidatePC (dword pcflags=PC_ALL)
dword getInstCount () const
void setInstCount (dword ic)
dword mergeModel (Model &mergemod)
const std::string & getFilename () const
void setHLNode (int hlnode)
int getHLNode () const
Returns ID of highlighted node. Value is -1 if none is selected.
dword getSelectedNodesN (dword state=Node::ST_SELECT) const
get number of selected nodes
dword connectNodes ()
Connect selected nodes.
dword removeEdges ()
Remove edges between selected nodes.
void removeNode (int nid)
Removes a node and its adjacent edges.
DMatrixf adjMat () const
compute undirected adjacency matrix
DMatrixf selMaskMat () const
compute mask matrix of selected nodes
Public Attributes
ParticleParam phys
physical parameter set
float m_TimeStamp
time stamps (see. TTimeStamp)
Protected Types
enum PreCompF {
PC_CENTER =0x01, PC_SCALE =0x02, PC_DIR =0x04, PC_QOF =0x08,
PC_LIVE =0x10, PC_NOTHING =0x00, PC_ALL =0x1f, PC_PVEC =PC_CENTER|PC_SCALE|PC_DIR,
PC_STATS =PC_QOF|PC_LIVE
}
Protected Member Functions
dword removeByAdjMat (DMatrixf &adjm)
remove edged not mentioned in (non-directional) adjacency matrix
dword createByAdjMat (const DMatrixf &adjm)
create edges mentioned in adjacency matrix
void rebuildIndexTables ()
rebuild cross indexing between nodes and edges
void attachSensorColl (SensorCollection *sc)
set reference to and from sensor collection for correct updates
Protected Attributes
NodeArray nodes
indexed list of nodes
EdgeArray edges
indexed list of edges
dataset_cptr m_Dataset
SensorCollection * m_Sensors
std::string m_SensorFile
float m_ShapeWeight
dword m_Flags
std::string m_Name
dword m_CRC
dword m_ppmm
int m_DirNodeInd
dword m_PCFlags
PropVec m_PropVec
float m_QOF
float m_Liveliness
float m_Scale
float m_Direction
dword m_InstCount
number of merged instances
std::string m_Filename
int m_HLNode
dword m_ID
Friends
ParseFile & operator>> (ParseFile &is, Model &g)
std::ostream & operator<< (std::ostream &is, const Model &g)
Detailed Description
Definition at line 33 of file Model.h.
Member Enumeration Documentation
enum Model::DistType
Enumerator
DIST_XY
DIST_XYS
DIST_PVEC
DIST_POINTS
DIST_CPOINTS
DIST_HPOINTS
Definition at line 40 of file Model.h.
                   {DIST_XY, DIST_XYS, DIST_PVEC, DIST_POINTS,
                    DIST_CPOINTS, DIST_HPOINTS };
enum Model::ModelState
Enumerator
ST_WINNER
ST_LOOSER
ST_OLDSTATE
ST_DEL
ST_MEMBER
ST_NODEL
Definition at line 43 of file Model.h.
                     { ST_WINNER=1, ST_LOOSER=2, ST_OLDSTATE=4, ST_DEL=8,
                       ST_MEMBER=16, ST_NODEL=32};
enum Model::PreCompF protected
Enumerator
PC_CENTER
PC_SCALE
PC_DIR
PC_QOF
PC_LIVE
PC_NOTHING
PC_ALL
PC_PVEC
PC_STATS
Definition at line 35 of file Model.h.
                   {PC_CENTER=0x01, PC_SCALE=0x02, PC_DIR=0x04, PC_QOF=0x08,
                    PC_LIVE=0x10, PC_NOTHING=0x00, PC_ALL=0x1f,
                    PC_PVEC=PC_CENTER|PC_SCALE|PC_DIR,
                    PC_STATS=PC_QOF|PC_LIVE};
Constructor & Destructor Documentation
Model::Model (dataset_cptr _dataset = NULL, SensorCollection * sensors = NULL)
Default constructor.
Definition at line 26 of file Model.cpp.
References __SHAPEWEIGHT, DEFAULT_PPMM, ParticleParam::gravitational, m_DirNodeInd, m_ppmm, m_Sensors, m_ShapeWeight, phys, SensorCollection::refModel(), setName(), and ParticleParam::viscousdrag.
     : m_TimeStamp(0), m_Dataset(_dataset), m_Sensors(sensors),
       m_Flags(0), m_PCFlags(PC_NOTHING), m_InstCount(1), m_HLNode(-1), m_ID(0)
 {
     phys.gravitational = phys.gravitational;
     phys.viscousdrag = phys.viscousdrag;
     m_ShapeWeight = __SHAPEWEIGHT;
     setName("00");
     m_ppmm = DEFAULT_PPMM;
     m_DirNodeInd=-1;
     if(m_Sensors) m_Sensors->refModel(this);
 }
Model::Model (const Model & rhs)
Copy constructor.
Definition at line 39 of file Model.cpp.
References m_Sensors, NULL, and operator=().
 {
     m_Sensors = NULL;
     operator=(rhs);
 }
Model::~Model ()
Destructor.
Definition at line 45 of file Model.cpp.
References attachSensorColl(), and NULL.
 {
     attachSensorColl(NULL);
 }
Member Function Documentation
void Model::adaptDataScale (dword ppmm = 0)
Definition at line 1240 of file Model.cpp.
References m_Dataset, m_ppmm, and scale().
Referenced by attachDataset(), operator>>(), and setShapeWeight().
{
     if(!ppmm) {
         if(!m_Dataset) return;
         if(!(ppmm = m_Dataset->getPPMM())) return;
     }
     if(m_ppmm) scale(float(ppmm)/m_ppmm, true);
     m_ppmm = ppmm;
 }
void Model::adaptProperties (const PropVec & prop)
Definition at line 1249 of file Model.cpp.
References getCenter(), getDirection(), getPropDir(), getPropPos(), getPropScale(), getStdRadius(), nodes, rotate(), scale(), and translate().
Referenced by adaptPropertiesMM(), ExpectationMap::generateInstance(), getDataScale(), and Searcher::mutate().
{
     if(nodes.empty()) return;
     Point2D nc = getPropPos(prop);
     float ndir = getPropDir(prop);
     float nscale = getPropScale(prop);
     Point center = getCenter();
     float cscale = getStdRadius();
     float cdir = getDirection();
     rotate(ndir-cdir);
     if(nscale>0.001 && cscale>0.0000001)
         scale(nscale/cscale, true);
     translate(nc-center);
 }
void Model::adaptPropertiesMM (PropVec prop)
adapt to a property vector using millimeter scale
Definition at line 1281 of file Model.cpp.
References adaptProperties(), and convertPropFromMM().
Referenced by getDataScale().
 {
     adaptProperties(convertPropFromMM(prop));
 }
void Model::adaptProportion (float ratio)
overall rest lengths sum is adapted to overall edge lengths by ratio
Definition at line 1164 of file Model.cpp.
References edges, and getLengthRatio().
Referenced by getMaxRadius(), Searcher::mutate(), and Brain::triggerTest().
 {
     float corrat = getLengthRatio();
     corrat -= (corrat-1)*(1-ratio);
     for(EdgeArray::iterator e = edges.begin(); e != edges.end(); e++) {
         e->restlength *= corrat;
     }
 }
void Model::adaptRestLength (float ratio)
adapt restlengths towards current lengths by ratio
Definition at line 1126 of file Model.cpp.
References edges.
Referenced by getMaxRadius(), and Brain::triggerTest().
 {
     for(EdgeArray::iterator e = edges.begin(); e != edges.end(); e++) {
         e->adaptRestLength(ratio);
     }
 }
void Model::adaptRestLengthSel (float ratio, const DMatrixf & selm)
adapt restlengths of selected edges towards current lengths by ratio
Definition at line 1133 of file Model.cpp.
References edges.
Referenced by getMaxRadius(), and Brain::triggerTest().
 {
     for(EdgeArray::iterator e = edges.begin(); e != edges.end(); e++) {
         e->adaptRestLength(ratio);
     }
 }
int Model::addEdge (const Edge & edge)
add an Edge to the model
Returns
index in the internal array
Definition at line 138 of file Model.cpp.
References edges, and nodes.
Referenced by addEdge(), createByAdjMat(), operator bool(), readEdge(), and Brain::triggerTest().
 {
     int index = edges.size();
     edges.push_back(edge);
     edges[index].index = index;
     edges[index].setNodesList(nodes);
     edges[index].fromNode().edges.push_back(index+1);
     edges[index].toNode().edges.push_back(-index-1);
     return index;
 }
int Model::addEdge (const Node & from, const Node & to)
create an Edge from two given nodes
Returns
index in the internal array
Definition at line 151 of file Model.cpp.
References addEdge(), addNode(), and nodes.
 {
     int fi = addNode(from);
     int ti = addNode(to);
     return addEdge(Edge(fi,ti,nodes));
 }
int Model::addEdge (int ifrom, int ito)
create an Edge using node indices (from nodes - array)
Returns
index in the internal array
Definition at line 160 of file Model.cpp.
References addEdge(), nodes, and phys.
 {
     assert((dword)ifrom<nodes.size() &&
            (dword)ito<nodes.size() && ifrom>=0 && ito>=0);
     return addEdge( Edge(ifrom, ito, nodes, &phys) );
 }
float Model::addImageForces (float dt)
Definition at line 701 of file Model.cpp.
References m_Dataset, and nodes.
Referenced by calculateForces(), and getMaxRadius().
{
     if(!m_Dataset || !m_Dataset->initialized()) return 0.0f;
     if(m_Dataset) const_cast<vuMutex&>(m_Dataset->writeMutex).lock();
     float allf=0;
     for (NodeArray::iterator p=nodes.begin(); p!=nodes.end();p++) {
         p->addSensorForce();
         allf += p->f.norm();
     }
     if(m_Dataset) const_cast<vuMutex&>(m_Dataset->writeMutex).unlock();
     return allf;
 }
int Model::addNode (const Node & node)
add a Node to the model
Returns
index in the internal array
Definition at line 120 of file Model.cpp.
References Node::index, nodes, and TRACE.
Referenced by addEdge(), operator bool(), readNode(), and Brain::triggerTest().
 {
     if(node.index!=-1 && nodes.size()>(dword)node.index) {
         TRACE(node.index);
         nodes[node.index] = node;
         return node.index;
     }
     int index = nodes.size();
     //nodes[index] = node;
     nodes.push_back(node);
     //nodes.end()->index = index;
     nodes[index].index = index;
     assert(nodes[index].index == index);
     return index;
 }
void Model::addNoise (float r)
Definition at line 901 of file Model.cpp.
References dmutil::abs(), edges, frand, and nodes.
Referenced by Searcher::mutate(), setID(), and Brain::triggerTest().
 {
     /*
       for(NodeArray::iterator n = nodes.begin(); n != nodes.end(); n++) {
       Point d(r-2*frand(r), r-2*frand(r));
       n->ef += d;
       }
     */
     for(NodeArray::iterator n = nodes.begin(); n != nodes.end(); n++) {
         float minlen=-1;
         for(vector<int>::const_iterator edi=n->edges.begin();
             edi!=n->edges.end(); edi++) {
             float elen = edges[abs(*edi)-1].length();
             if(minlen==-1) minlen = elen;
             else if(minlen>elen) minlen=elen;
         }
         float er = r*minlen;
         Point d(er-2*frand(er), er-2*frand(er));
         n->ef += d;
     }
 }
void Model::addTorque (float dt)
Definition at line 719 of file Model.cpp.
References edges, Node::f, Point2D::flipOrtho(), Edge::fromNode(), getNodeAngle(), m_Dataset, mapAnglePI(), nodes, Point2D::normalize(), phys, Edge::toNode(), and ParticleParam::torque.
Referenced by getMaxRadius(), and updateParticles().
{
     //doesn't really work with a node array other than nodes
     //(because of edges.fromNode()...
     if(m_Dataset) const_cast<vuMutex&>(m_Dataset->writeMutex).lock();
     //NodeArray &narr = tp ? *tp : nodes;
     for(NodeArray::iterator p=nodes.begin(); p!=nodes.end();p++) {
         if(!p->edges.empty()) {
             float da = mapAnglePI(getNodeAngle(*p) - p->oangle);
             //TRACE(da << " " << p->oangle << " " << getNodeAngle(*p));
             if(da!=0.0) {
                 int eind = p->edges[0];
                 Edge &e1 = eind<0 ? edges[-eind-1]:edges[eind-1];
                 Node &n1 = eind<0 ? e1.fromNode() : e1.toNode();
                 Point d1(n1-*p);
                 d1.normalize();
                 eind = p->edges[1];
                 Edge &e2 = eind<0 ? edges[-eind-1]:edges[eind-1];
                 Node &n2 = eind<0 ? e2.fromNode() : e2.toNode();
                 Point d2(*p-n2);
                 d2.normalize();
                 Point t1 = d1.flipOrtho()*(da*phys.torque*0.5);
                 n1.f -= t1;
                 p->f += t1;
                 Point t2 = d2.flipOrtho()*(da*phys.torque*0.5);
                 n2.f -= t2;
                 p->f += t2;
             }
         }
     }
     if(m_Dataset) const_cast<vuMutex&>(m_Dataset->writeMutex).unlock();
 }
DMatrixf Model::adjMat () const
compute undirected adjacency matrix
compute directed adjacency matrix
Definition at line 415 of file Model.cpp.
References DMatrix< T >::at(), edges, getNNodes(), DMatrix< T >::setLower(), and DMatrix< T >::transpose().
Referenced by connectNodes(), getHLNode(), and removeEdges().
 {
     DMatrixf adjm(getNNodes(), getNNodes(), 0.0f);
     for(EdgeArray::const_iterator e=edges.begin(); e!=edges.end(); e++)
     {
         assert(e->from < getNNodes() && e->to < getNNodes());
         adjm.at(e->from, e->to)++;
     }
     DMatrixf tri(getNNodes(), getNNodes());
     tri.setLower();
     tri*=adjm; tri.transpose();
     adjm += tri;
     adjm.setLower(0);
     return adjm;
 }
void Model::attachDataset (dataset_cptr dataset)
Definition at line 85 of file Model.cpp.
References adaptDataScale(), SensorCollection::addSensor(), SensorCollection::getSensor(), m_Dataset, and m_Sensors.
Referenced by MStructure::MStructure(), and setID().
{
     if(m_Dataset == dataset) return;
     m_Dataset = dataset;
     if(m_Sensors && m_Sensors->getSensor("d0") != dataset)
         m_Sensors->addSensor("d0",
                              std::dynamic_pointer_cast<Sensor>(
                                  std::const_pointer_cast<Dataset>(dataset)));
     adaptDataScale();
 }
void Model::attachSensorColl (SensorCollection * sc) protected
set reference to and from sensor collection for correct updates
Definition at line 588 of file Model.cpp.
References m_Sensors, SensorCollection::refModel(), and SensorCollection::unrefModel().
Referenced by getHLNode(), operator=(), and ~Model().
 {
     if(m_Sensors == sc) return;
     if(m_Sensors) m_Sensors->unrefModel(this);
     if(sc) sc->refModel(this);
     m_Sensors = sc;
 }
void Model::attract (const Point & c, float factor)
Definition at line 961 of file Model.cpp.
References nodes.
Referenced by rotate().
 {
     for(NodeArray::iterator n = nodes.begin(); n != nodes.end(); n++) {
         n->ef -= (*n-c)*factor;
     }
 }
void Model::calculateDerivatives (std::vector< NodeDerivative > & deriv)
Definition at line 839 of file Model.cpp.
References nodes.
Referenced by getMaxRadius(), and updateParticles().
 {
     deriv.resize(nodes.size());
     vector<NodeDerivative>::iterator d = deriv.begin();
     for (NodeArray::iterator n = nodes.begin();
          d != deriv.end(), n != nodes.end();
          d++, n++) {
         d->dpdt = n->v;
         d->dvdt = n->f;
         d->dvdt *= (1/n->mass);
     }
 }
void Model::calculateForces (float dt)
Definition at line 648 of file Model.cpp.
References addImageForces(), Point2D::dot(), edges, ParticleParam::gravitational, ParticleParam::imgforce, nodes, Point2D::norm(), phys, and ParticleParam::viscousdrag.
Referenced by getMaxRadius(), and updateParticles().
 {
     Point down(0.0f, -1.0f);
     Point f;
     float imgf, ifscale;
     if(phys.imgforce == 0) {
         imgf = 0;
         ifscale = 0;
     } else {
         imgf = addImageForces(dt);
         ifscale=1;
     }
     if(imgf>0.0) ifscale = ((float)phys.imgforce/imgf)*(float)nodes.size();
     //TRACE(imgf<< " scale="<<ifscale);
     for (NodeArray::iterator p=nodes.begin(); p!=nodes.end();p++) {
         //if (p->fixed) continue;
         p->f *= ifscale;
         p->f += p->ef/dt;
         p->ef = 0.;
         /* Gravitation */
         if(phys.gravitational > 0.0f)
             p->f = (down * (phys.gravitational * p->mass));
         /* Viscous drag */
         if(phys.viscousdrag > 0.0f)
             p->f -= (p->v * phys.viscousdrag);
     }
     /* Handle the spring interaction */
     for (EdgeArray::iterator s=edges.begin(); s!=edges.end(); s++)
     {
         Point d = s->fromNode();
         d -= s->toNode();
         float len = d.norm();
         float len1 = 1/len;
         //spring force
         f = (s->springconstant * (len - s->restlength));
         //calc damping force
         Point vd(s->fromNode().v);
         vd -= s->toNode().v;
         d *= len1;                       //spring direction normalized
         //vd.times(d);                     //project velocity difference to spring
         vd = vd.dot(d);                     //project velocity difference to spring
         vd *= s->dampingconstant;
         f += vd;
         f *= (d*-1);
         //if not fixed - maybe
         s->fromNode().f += f;
         s->toNode().f -= f;
     }
 }
void Model::clear ()
remove and destroy all geometry information (nodes and edges)
Definition at line 95 of file Model.cpp.
References edges, m_DirNodeInd, and nodes.
Referenced by Searcher::clear(), MStructure::clear(), and reset().
 {
     nodes.clear();
     edges.clear();
     //m_Deriv.clear();
     m_DirNodeInd=-1;
 }
dword Model::connectNodes ()
Connect selected nodes.
Definition at line 483 of file Model.cpp.
References adjMat(), createByAdjMat(), DMatrix< T >::min(), prepareTorque(), selMaskMat(), and DMatrix< T >::setLower().
Referenced by getHLNode(), and Brain::triggerTest().
 {
     DMatrixf selm = selMaskMat();
     selm.setLower(0);
     DMatrixf adjm = adjMat();
     adjm.min(1);
     DMatrixf crem(selm);
     adjm *= selm;
     crem -= adjm;
     dword nc = createByAdjMat(crem);
     if(nc) prepareTorque();
     return nc;
 }
Point2D & Model::convertPointFromMM (Point2D & pt) const
Definition at line 1285 of file Model.cpp.
References m_Dataset, and m_ppmm.
Referenced by convertPropFromMM(), and getDataScale().
 {
     if(m_ppmm) pt *= (float)m_ppmm;
     if(m_Dataset) pt += m_Dataset->getOrigin();
     return pt;
 }
Point2D & Model::convertPointToMM (Point2D & pt) const
Definition at line 1291 of file Model.cpp.
References m_Dataset, and m_ppmm.
Referenced by MStructure::buildAllStats(), convertPropToMM(), getDataScale(), and MStructure::showStats().
 {
     if(m_Dataset) pt -= m_Dataset->getOrigin();
     if(m_ppmm) pt /= (float)m_ppmm;
     return pt;
 }
PropVec & Model::convertPropFromMM (PropVec & prop) const
Definition at line 1297 of file Model.cpp.
References convertPointFromMM(), getPropPos(), getPropScale(), m_ppmm, setPropPos(), and setPropScale().
Referenced by adaptPropertiesMM(), and getDataScale().
 {
     Point2D pos(getPropPos(prop));
     setPropPos(prop, convertPointFromMM(pos));
     if(m_ppmm) setPropScale(prop, getPropScale(prop)*m_ppmm);
     return prop;
 }
PropVec & Model::convertPropToMM (PropVec & prop) const
Definition at line 1304 of file Model.cpp.
References convertPointToMM(), getPropPos(), getPropScale(), m_ppmm, setPropPos(), and setPropScale().
Referenced by getDataScale(), getPropertiesMM(), and MStructure::setRefModel().
 {
     Point2D pos(getPropPos(prop));
     setPropPos(prop, convertPointToMM(pos));
     if(m_ppmm) setPropScale(prop, getPropScale(prop)/m_ppmm);
     return prop;
 }
dword Model::createByAdjMat (const DMatrixf & adjm) protected
create edges mentioned in adjacency matrix
Definition at line 468 of file Model.cpp.
References addEdge(), DMatrix< T >::at(), getNNodes(), DMatrix< T >::sizeX(), and DMatrix< T >::sizeY().
Referenced by connectNodes(), and getHLNode().
 {
     assert(adjm.sizeX() == adjm.sizeY() && adjm.sizeX() == (dword)getNNodes());
     dword count=0;
     for(dword j=0; j<adjm.sizeY(); j++)
         for(dword i=0; i<adjm.sizeX(); i++) {
             if(adjm.at(i,j)>0.0001) {
                 addEdge(i,j);
                 count++;
             }
         }
     return count;
 }
dword Model::createEdgeSensors (float dist = 0.1)
auto-create appropriate edge sensors (dist*stdRadius is distance)
Definition at line 622 of file Model.cpp.
References edges, and getStdRadius().
Referenced by getSensorCollection(), and Brain::triggerTest().
 {
     float smpdist = getStdRadius()*dist;
     if(smpdist < 0.000001) return 0;
     dword nsens=0;
     for(EdgeArray::iterator e=edges.begin(); e!=edges.end(); e++)
     {
         if(e->fromNode().sensor == e->toNode().sensor && e->fromNode().sensor)
         {                       // positive means from-node
             nsens += (e->edgesensor = (int)(e->length()/smpdist));
         }
     }
     return nsens;
 }
float Model::distance (const Model & rhs, enum Model::DistType kind = DIST_POINTS) const
Definition at line 1043 of file Model.cpp.
References DIST_CPOINTS, DIST_HPOINTS, DIST_POINTS, DIST_PVEC, DIST_XY, DIST_XYS, getCenter(), getNNodes(), getProperties(), getPropSDir(), getStdRadius(), nodes, dmutil::sqrt(), Point2D::x, and Point2D::y.
Referenced by getDataScale(), and NMerge::operator()().
 {
     switch(kind) {
     case DIST_XY:
         return (getCenter() - rhs.getCenter()).norm();
         break;
     case DIST_XYS:
     {
         float scaledist = getStdRadius() - rhs.getStdRadius();
         return sqrt((getCenter() - rhs.getCenter()).norm2()
                     + scaledist*scaledist);
     }
     break;
     case DIST_PVEC:
     {
         PropVec prop = getProperties();
         PropVec rhsprop = rhs.getProperties();
         Point2D sd = getPropSDir(prop);
         Point2D rhssd = getPropSDir(rhsprop);
         prop[2] = sd.x; prop[3] = sd.y;
         rhsprop[2] = rhssd.x; rhsprop[3] = rhssd.y;
         return (prop - rhsprop).norm();
     }
     break;
     case DIST_POINTS:
         if(getNNodes() != rhs.getNNodes())
             return std::numeric_limits<float>::max();
         else {
             float dist=0;
             for(NodeArray::const_iterator thisn = nodes.begin(),
                     rhsn = rhs.nodes.begin();
                 thisn != nodes.end(); thisn++, rhsn++)
             {
                 dist += (*thisn-*rhsn).norm2();
             }
             return sqrt(dist);
         }
         break;
     case DIST_HPOINTS:      // Chamfer distance
     case DIST_CPOINTS:      // Hausdorff distance
     {
         if(getNNodes()==0 || rhs.getNNodes()==0)
             return std::numeric_limits<float>::max();
         double dist=0;
         for(NodeArray::const_iterator thisn = nodes.begin();
             thisn != nodes.end(); thisn++)
         {
             float mindist = std::numeric_limits<float>::max();
             for(NodeArray::const_iterator rhsn = rhs.nodes.begin();
                 rhsn != rhs.nodes.end(); rhsn++)
             {
                 register float d = (*thisn-*rhsn).norm2();
                 if(d<mindist) mindist = d;
             }
             if(kind == DIST_HPOINTS && mindist>dist) dist=(double)mindist;
             if(kind == DIST_CPOINTS ) dist += sqrt((double)mindist);
         }
         if(kind == DIST_HPOINTS) dist = sqrt(dist);
         if(kind == DIST_CPOINTS) dist /= getNNodes();
         return float(dist);
     }
     }
     return 0;
 }
void Model::draw (bool drawPoints = false) const
Draw using OpenGL.
Definition at line 542 of file Model.cpp.
References edges, and nodes.
Referenced by Searcher::draw(), StructTable::draw(), Brain::drawAllModels(), and setID().
{
     if(!edges.empty()) {
         glBegin(GL_LINES);
         for(EdgeArray::const_iterator e=edges.begin(); e!=edges.end(); e++)
         {
             e->fromNode().glVertex();
             e->toNode().glVertex();
         }
         glEnd();
     }
     if(drawPoints &&  !nodes.empty()) {
         glPointSize(3.0f);
         glEnable(GL_POINT_SMOOTH);
         glColor3f(0,0,1);
         glBegin(GL_POINTS);
         for(NodeArray::const_iterator n=nodes.begin(); n!=nodes.end(); n++)
         {
             n->glVertex();
         }
         glEnd();
         glDisable(GL_POINT_SMOOTH);
         glPointSize(1.0f);
         for(NodeArray::const_iterator n=nodes.begin(); n!=nodes.end(); n++)
         {
             if(n->hasState()) n->draw();
         }
     }
 }
void Model::drawPS (CAMgraphicsProcess & gp, dword mode = 0) const
Draw to postscrip output.
Referenced by setID().
void Model::freeze ()
Definition at line 938 of file Model.cpp.
References edges, and prepareTorque().
Referenced by setID().
 {
     for(EdgeArray::iterator e = edges.begin(); e != edges.end(); e++) {
         e->adaptRestLength();
     }
     prepareTorque();
 }
const Point Model::getCenter () const
Definition at line 852 of file Model.cpp.
References getPropPos(), m_PCFlags, m_PropVec, nodes, PC_CENTER, and setPropPos().
Referenced by adaptProperties(), MStructure::buildAllStats(), distance(), Brain::distributeModel(), Brain::evolve(), Searcher::getBindex(), getDirection(), getDirNode(), getLiveliness(), getMaxRadius(), getProperties(), getSensorCollection(), getStdRadius(), rotate(), scale(), MStructure::showStats(), and Brain::triggerTest().
{
     if(!(m_PCFlags&PC_CENTER)) {
         Point c(0,0);
         if(!nodes.empty()) {
             for (NodeArray::const_iterator n = nodes.begin();
                  n != nodes.end();
                  n++)
             {
                 c+=*n;
             }
             c *= (1.0f/nodes.size());
         }
         setPropPos(m_PropVec, c);
         m_PCFlags|=PC_CENTER;
     }
     return getPropPos(m_PropVec);
 }
dword Model::getCRC () const inline
Definition at line 82 of file Model.h.
References m_CRC.
 { return m_CRC; }
dword Model::getDataScale () const inline
Definition at line 204 of file Model.h.
References adaptProperties(), adaptPropertiesMM(), convertPointFromMM(), convertPointToMM(), convertPropFromMM(), convertPropToMM(), DIST_POINTS, distance(), getProperties(), getPropertiesMM(), m_ppmm, nearestNode(), and NULL.
Referenced by MStructure::addExpectation(), Searcher::buildClusters(), and MStructure::buildMasterModel().
 { return m_ppmm; }
float Model::getDeformation () const
normalized length variation to compensate for different sizes
Definition at line 995 of file Model.cpp.
References edges, getLengthRatio(), scale(), ParticleParam::springconst, and dmutil::sqrt().
Referenced by getMaxRadius(), getQualityOfFit(), and Brain::triggerTest().
{
     if(edges.empty()) return 0.0;
     float vlengths=0,restlengths=0;
     float scale = 1/getLengthRatio();
     float scscale = 1/ParticleParam::global.springconst;
     for(EdgeArray::const_iterator e = edges.begin(); e != edges.end(); e++) {
         register float dl = e->restlength-e->length()*scale;
         //dl *= e->springconstant*scscale; // weight by relative springconst
         vlengths+=dl*dl;
         restlengths+=e->restlength;
     }
     register float n = edges.size();
     return sqrt(vlengths*n)/(restlengths);
 }
float Model::getDirection () const
Definition at line 890 of file Model.cpp.
References getCenter(), getDirNode(), getPropDir(), m_PCFlags, m_PropVec, mapAngle2PI(), nodes, PC_DIR, and setPropDir().
Referenced by adaptProperties(), getProperties(), and getSensorCollection().
{
     if(!(m_PCFlags&PC_DIR)) {
         setPropDir(m_PropVec, nodes.empty() ? 0 :
                    mapAngle2PI((getDirNode()-getCenter()).angle()) );
         m_PCFlags|=PC_DIR;
     }
     return getPropDir(m_PropVec);
 }
const Node & Model::getDirNode () const
Definition at line 870 of file Model.cpp.
References getCenter(), getNNodes(), getNode(), m_DirNodeInd, and nodes.
Referenced by Brain::doCommand(), getDirection(), and getSensorCollection().
{
     static const Node dummy;
     if(!getNNodes()) return dummy;
     if(m_DirNodeInd < 0) {
         Point c = getCenter();
         float cdist = -1.;
         dword cind = 0;
         for(NodeArray::const_iterator n=nodes.begin();
             n!=nodes.end(); n++, cind++)
         {
             float dist = (*n-c).norm2();
             if(cdist < dist) {
                 cdist = dist;
                 m_DirNodeInd = cind;
             }
         }
     }
     return getNode(m_DirNodeInd);
 }
const Edge& Model::getEdge (int index) const inline
Definition at line 71 of file Model.h.
References edges.
Referenced by MStructure::buildMasterModel(), and Brain::triggerTest().
 { return edges[index]; }
Edge& Model::getEdge (int index) inline
Definition at line 72 of file Model.h.
References edges.
 { return edges[index]; }
float Model::getEdgeSensorFit (dword * npts = NULL) const
get average fit of sensors along edges
Definition at line 1191 of file Model.cpp.
References edges.
Referenced by getMaxRadius(), getQualityOfFit(), and Brain::triggerTest().
 {
     if(edges.empty()) { if(npts) *npts = 0; return 0.0; }
     float fit = 0;
     dword npoints = 0;
     for(EdgeArray::const_iterator e = edges.begin(); e != edges.end(); e++) {
         float i=e->getSensorValue(fit, npoints);
     }
     if(npoints) fit /= (float)npoints;
     if(npts) *npts = npoints;
     return fit;
 }
const std::string& Model::getFilename () const inline
Definition at line 225 of file Model.h.
References m_Filename, and setHLNode().
Referenced by Brain::triggerTest(), and MStructure::write().
 { return m_Filename; }
dword& Model::getFlags () inline
Definition at line 196 of file Model.h.
References m_Flags.
Referenced by Searcher::add(), and Brain::triggerTest().
 { return m_Flags; }
float Model::getFullLength () const
Returns overall sum of edge lengths.
Definition at line 1010 of file Model.cpp.
References edges.
Referenced by rotate().
{
     float length=0;
     for(EdgeArray::const_iterator e = edges.begin(); e != edges.end(); e++) {
         length += e->length();
     }
     return length;
 }
int Model::getHLNode () const inline
Returns ID of highlighted node. Value is -1 if none is selected.
Definition at line 231 of file Model.h.
References adjMat(), attachSensorColl(), connectNodes(), createByAdjMat(), getSelectedNodesN(), m_HLNode, rebuildIndexTables(), removeByAdjMat(), removeEdges(), removeNode(), selMaskMat(), and Node::ST_SELECT.
Referenced by Brain::triggerTest().
 { return m_HLNode; }
dword Model::getID () const inline
Definition at line 83 of file Model.h.
References m_ID.
Referenced by Winner::setModel().
 { return m_ID; }
dword Model::getInstCount () const inline
Definition at line 222 of file Model.h.
References m_InstCount.
 { return m_InstCount; }
float Model::getLengthRatio () const
relation of overall edge length by overall rest length sum
Definition at line 968 of file Model.cpp.
References edges.
Referenced by adaptProportion(), getDeformation(), and getMaxRadius().
{
     float lengths=0,restlengths=0;
     for(EdgeArray::const_iterator e = edges.begin(); e != edges.end(); e++) {
         lengths+=e->length();
         restlengths+=e->restlength;
     }
     return lengths/restlengths;
 #ifdef NOTLENGTHWEIGHTED
     float lenrat=0;
     for(EdgeArray::const_iterator e = edges.begin(); e != edges.end(); e++) {
         lenrat += e->lengthRatio();
     }
     return lenrat/(float)edges.size();
 #endif
 }
float Model::getLengthVariation () const
mean squared difference from restlength normalized by restlength sum
Definition at line 984 of file Model.cpp.
References edges, and dmutil::sqrt().
Referenced by getMaxRadius().
{
     float vlengths=0,restlengths=0;
     for(EdgeArray::const_iterator e = edges.begin(); e != edges.end(); e++) {
         register float dl = e->restlength-e->length();
         vlengths+=dl*dl;
         restlengths+=e->restlength;
     }
     register float n = edges.size();
     return sqrt(vlengths*n)/(restlengths);
 }
float Model::getLiveliness () const
Definition at line 1222 of file Model.cpp.
References edges, getCenter(), m_Liveliness, m_PCFlags, nodes, PC_LIVE, and dmutil::sqrt().
Referenced by MStructure::buildMasterModel(), and setID().
 {
     if(m_PCFlags&PC_LIVE) return m_Liveliness;
     m_Liveliness = 0;
     if(!nodes.empty() && !edges.empty()) {
         float dist= 0;
         Point c = getCenter();
         for(NodeArray::const_iterator n = nodes.begin(); n != nodes.end(); n++)
         {
             m_Liveliness += n->v.norm();
             dist += (c-*n).norm2();
         }
         if(dist > 0.00001) m_Liveliness /= sqrt(dist);
     }
     m_PCFlags|=PC_LIVE;
     return m_Liveliness;
 }
float Model::getMaxRadius (const Point & center) const
Returns the maximum radius from the centroid.
Definition at line 1032 of file Model.cpp.
References nodes, and dmutil::sqrt().
{
     if(nodes.empty()) return 0;
     float dist = 0;
     for(NodeArray::const_iterator n = nodes.begin(); n != nodes.end(); n++) {
         register float td = (*n-center).norm2();
         if(dist<td) dist=td;
     }
     return sqrt(dist);
     //return (center-getDirNode()).norm();
 }
float Model::getMaxRadius () const inline
Definition at line 135 of file Model.h.
References adaptProportion(), adaptRestLength(), adaptRestLengthSel(), addImageForces(), addTorque(), calculateDerivatives(), calculateForces(), getCenter(), getDeformation(), getEdgeSensorFit(), getLengthRatio(), getLengthVariation(), getMaxRadius(), getSensorFit(), mergeSensorCollection(), NULL, prepareTorque(), resetForces(), scale(), scaleSel(), and updateParticles().
Referenced by getMaxRadius(), and getStdRadius().
 { return getMaxRadius(getCenter());}
const std::string& Model::getName () const inline
Definition at line 81 of file Model.h.
References m_Name.
Referenced by Brain::Brain(), Searcher::evolve(), Winner::setModel(), Searcher::triggerTest(), and Brain::triggerTest().
 { return m_Name; }
int Model::getNEdges () const inline
Definition at line 78 of file Model.h.
References edges, getNodeAngle(), and setName().
Referenced by MStructure::buildMasterModel(), and Brain::triggerTest().
 { return edges.size(); }
int Model::getNNodes () const inline
Definition at line 77 of file Model.h.
References nodes.
Referenced by adjMat(), MStructure::buildAllStats(), Searcher::buildBins(), createByAdjMat(), distance(), Searcher::distribute(), getDirNode(), removeByAdjMat(), removeNode(), selMaskMat(), setHLNode(), MStructure::showStats(), Brain::triggerTest(), and updateParticles().
 { return nodes.size(); }
const Node& Model::getNode (int index) const inline
Definition at line 74 of file Model.h.
References nodes.
Referenced by MStructure::addExpectation(), MStructure::buildAllStats(), getDirNode(), setHLNode(), MStructure::showStats(), and Brain::triggerTest().
 { return nodes[index]; }
Node& Model::getNode (int index) inline
Definition at line 75 of file Model.h.
References nodes.
 { return nodes[index]; }
float Model::getNodeAngle (const Node & n) const
Definition at line 605 of file Model.cpp.
References Point2D::angle(), Node::edges, and edges.
Referenced by addTorque(), getNEdges(), and prepareTorque().
{
     if(n.edges.size()>=2) {
         int eind1 = n.edges[0];
         Point e1 = eind1<0 ? edges[-eind1-1].idir() : edges[eind1-1].dir();
         int eind2 = n.edges[1];
         Point e2 = eind2<0 ? edges[-eind2-1].idir() : edges[eind2-1].dir();
         //TRACE(e1<<" "<<e2<<" "<<e1.angle(e2));
         return e1.angle(e2);
     } return 0.0;
 }
const PropVec & Model::getProperties () const
Definition at line 1263 of file Model.cpp.
References getCenter(), getDirection(), getStdRadius(), m_PCFlags, m_PropVec, PC_CENTER, PC_DIR, PC_PVEC, and PC_SCALE.
Referenced by MStructure::addExpectation(), Searcher::buildBins(), Searcher::cleanFlags(), distance(), Searcher::distribute(), Brain::doCommand(), getDataScale(), getPropertiesMM(), main(), Searcher::mutate(), MStructure::setRefModel(), and Brain::triggerTest().
 {
     if((m_PCFlags&PC_PVEC) != PC_PVEC) {
         if((m_PCFlags&PC_CENTER) == 0) getCenter(); //setPropPos(m_PropVec,..
         if((m_PCFlags&PC_SCALE) == 0)  getStdRadius();
         if((m_PCFlags&PC_DIR) == 0)    getDirection();
     }
     return m_PropVec;
 }
PropVec Model::getPropertiesMM () const
return property vector using millimeter scale
Definition at line 1274 of file Model.cpp.
References convertPropToMM(), and getProperties().
Referenced by getDataScale(), and MStructure::rebuildExpMap().
 {
     PropVec prop(getProperties());
     convertPropToMM(prop);
     return prop;
 }
float Model::getQualityOfFit () const
Definition at line 1204 of file Model.cpp.
References dmutil::abs(), edges, getDeformation(), getEdgeSensorFit(), getSensorFit(), m_Dataset, m_PCFlags, m_QOF, m_ShapeWeight, nodes, and PC_QOF.
Referenced by MStructure::addExpectation(), Searcher::cleanFlags(), Searcher::distribute(), Brain::distributeModel(), Brain::drawAllModels(), Searcher::evolve(), Brain::evolve(), StructTable::findBestConnection(), std::greater< Model * >::operator()(), StructPath::print(), setID(), and Brain::triggerTest().
 {
     if(m_PCFlags&PC_QOF) return m_QOF;
     if(nodes.empty() || edges.empty()
        || !m_Dataset || !m_Dataset->initialized()) m_QOF=0;
     else {
         dword nns=0, nes=0;
         float ns = getSensorFit(&nns);           // node sensors
         float es = getEdgeSensorFit(&nes);       // edge sensors
         m_QOF = (es*nes+ns*nns)/float(nns+nes);
         //DEBUG: use deformation*10?
         register float lv = getDeformation(); //getLengthVariation();
         m_QOF = (1-m_ShapeWeight)*m_QOF + (m_ShapeWeight)*exp(-5*abs(lv));
     }
     m_PCFlags|=PC_QOF;
     return m_QOF;
 }
dword Model::getSelectedNodesN (dword state = Node::ST_SELECT) const
get number of selected nodes
Definition at line 1334 of file Model.cpp.
References nodes.
Referenced by getHLNode(), and Brain::triggerTest().
 {
     dword count=0;
     for(NodeArray::const_iterator n = nodes.begin(); n != nodes.end(); n++)
         if(n->hasState(state)) count++;
     return count;
 }
SensorCollection* Model::getSensorCollection () inline
Definition at line 168 of file Model.h.
References createEdgeSensors(), getCenter(), getDirection(), getDirNode(), m_Sensors, and reattachSensors().
Referenced by Brain::triggerTest().
 { return m_Sensors; }
float Model::getSensorFit (dword * npts = NULL) const
get average sensor value
Definition at line 1173 of file Model.cpp.
References nodes.
Referenced by getMaxRadius(), getQualityOfFit(), and Brain::triggerTest().
 {
     if(nodes.empty()) { if(npts) *npts = 0; return 0.0; }
     float fit = 0;
     dword nsns = 0;
     for(NodeArray::const_iterator n = nodes.begin(); n != nodes.end(); n++)
         if(n->sensor) {
             float i=n->sensor->getWeightedValue((int)n->x,(int)n->y);
             //float gm = n->sensor->getGradient(*n).norm();
             //float vel = n->v.norm();
             fit += i;
             nsns++;
         }
     if(nsns) fit /= (float)nsns;
     if(npts) *npts = nsns;
     return fit;
 }
float Model::getStdRadius (const Point & center) const
Returns mean squared distance from centroid.
Definition at line 1018 of file Model.cpp.
References getPropScale(), m_PCFlags, m_PropVec, nodes, PC_SCALE, setPropScale(), and dmutil::sqrt().
Referenced by distance(), Brain::distributeModel(), Brain::evolve(), Searcher::mutate(), and Brain::setupSearch().
{
     if(m_PCFlags&PC_SCALE) return getPropScale(m_PropVec);
     float dist = 0;
     if(!nodes.empty()) {
         for(NodeArray::const_iterator n = nodes.begin(); n != nodes.end(); n++)
             dist += (*n-center).norm2();
         dist /= (float)nodes.size();
         dist = sqrt(dist);
     }
     setPropScale(m_PropVec, dist);
     m_PCFlags|=PC_SCALE;
     return dist;
 }
float Model::getStdRadius () const inline
Definition at line 132 of file Model.h.
References getCenter(), getMaxRadius(), and getStdRadius().
Referenced by adaptProperties(), createEdgeSensors(), distance(), getProperties(), getStdRadius(), and rotate().
 { return getStdRadius(getCenter());}
bool Model::hasFlags (dword flags) const inline
Definition at line 197 of file Model.h.
References m_Flags.
Referenced by mergeModel().
 { return m_Flags & flags; }
void Model::invalidatePC (dword pcflags = PC_ALL) inline
Definition at line 220 of file Model.h.
References m_PCFlags.
Referenced by rotate(), scale(), setDirNode(), setShapeWeight(), translate(), and updateParticles().
 { m_PCFlags &= ~pcflags; }
bool Model::isLooser () inline
Definition at line 190 of file Model.h.
References m_Flags, and ST_LOOSER.
 { return m_Flags&ST_LOOSER; }
bool Model::isOldState () inline
Definition at line 195 of file Model.h.
References m_Flags, and ST_OLDSTATE.
 { return m_Flags&ST_OLDSTATE; }
bool Model::isWinner () inline
Definition at line 184 of file Model.h.
References m_Flags, and ST_WINNER.
 { return m_Flags&ST_WINNER; }
dword Model::mergeModel (Model & mergemod)
Definition at line 1312 of file Model.cpp.
References hasFlags(), m_ID, m_InstCount, m_TimeStamp, setFlags(), ST_DEL, and ST_NODEL.
Referenced by setInstCount().
 {
     if(&mergemod != this && !mergemod.hasFlags(Model::ST_DEL)) {
         m_InstCount += mergemod.m_InstCount;
         mergemod.m_InstCount=0;
         bool mergeID = false;
         if(m_TimeStamp > mergemod.m_TimeStamp) {
             m_TimeStamp = mergemod.m_TimeStamp;
             mergeID = mergemod.m_ID != 0;
         } else mergeID = (m_ID==0 && mergemod.m_ID != 0);
         if(mergeID) {
             m_ID = mergemod.m_ID;
             mergemod.m_ID = 0;
             if(mergemod.hasFlags(Model::ST_NODEL)) {
                 setFlags(Model::ST_NODEL);
             }
         }
         mergemod.setFlags(Model::ST_DEL);
     }
     return m_InstCount;
 }
void Model::mergeSensorCollection (SensorCollection * sensors)
Definition at line 596 of file Model.cpp.
References m_Sensors, SensorCollection::merge(), and NULL.
Referenced by getMaxRadius(), and MStructure::MStructure().
 {
     if(!sensors) return;
     if(m_Sensors != NULL) {
         sensors->merge(*m_Sensors);
     }
     m_Sensors = sensors;
 }
int Model::nearestNode (const Point & pos, float & dist = *(float*)(NULL)) const
Definition at line 1108 of file Model.cpp.
References nodes, and dmutil::sqrt().
Referenced by getDataScale(), and Brain::triggerTest().
 {
     if(nodes.empty()) return -1;
     int rid=0, cid=0;
     float tdist;
     float& mindist = &dist ? dist : tdist;
     rid = 0;
     mindist = std::numeric_limits<float>::max();
     for(NodeArray::const_iterator ni = nodes.begin();
         ni != nodes.end(); ni++, cid++)
     {
         register float d = (pos-*ni).norm2();
         if(d<mindist) { mindist = d; rid = cid; }
     }
     mindist = sqrt(mindist);
     return rid;
 }
Model::operator bool () const inline
is initialized?
Definition at line 55 of file Model.h.
References addEdge(), addNode(), nodes, and reset().
 { return !nodes.empty(); }
Model & Model::operator= (const Model & rhs)
Definition at line 50 of file Model.cpp.
References attachSensorColl(), edges, m_CRC, m_Dataset, m_DirNodeInd, m_Filename, m_Flags, m_HLNode, m_ID, m_InstCount, m_Liveliness, m_Name, m_PCFlags, m_ppmm, m_PropVec, m_QOF, m_SensorFile, m_Sensors, m_ShapeWeight, m_TimeStamp, nodes, and phys.
Referenced by Model(), and setID().
 {
     if(&rhs == this) return *this;
     m_Dataset = rhs.m_Dataset;
     attachSensorColl(rhs.m_Sensors);
     m_SensorFile = rhs.m_SensorFile;
     nodes = rhs.nodes;
     edges = rhs.edges;
     for(EdgeArray::iterator e=edges.begin(); e!=edges.end(); e++)
     {
         e->setNodesList(nodes);
     }
     m_Flags = rhs.m_Flags;
 //     phys.gravitational = rhs.phys.gravitational;
 //     phys.viscousdrag = rhs.phys.viscousdrag;
     phys = rhs.phys;
     m_Name = rhs.m_Name;
     m_CRC = rhs.m_CRC;
     m_ppmm = rhs.m_ppmm;
     m_TimeStamp = rhs.m_TimeStamp;
     m_DirNodeInd = rhs.m_DirNodeInd;
     m_PCFlags = rhs.m_PCFlags;
     m_PropVec = rhs.m_PropVec;
     m_Liveliness = rhs.m_Liveliness;
     m_ShapeWeight = rhs.m_ShapeWeight;
     m_QOF = rhs.m_QOF;
     m_InstCount = rhs.m_InstCount;
     m_Filename = rhs.m_Filename;
     m_HLNode = rhs.m_HLNode;
     //m_Deriv = rhs.m_Deriv;
     //m_LastDT = rhs.m_LastDT;
     m_ID = rhs.m_ID;
     return *this;
 }
void Model::prepareTorque ()
Definition at line 713 of file Model.cpp.
References getNodeAngle(), and nodes.
Referenced by connectNodes(), freeze(), getMaxRadius(), operator>>(), removeEdges(), removeNode(), and Brain::triggerTest().
{
     for(NodeArray::iterator p=nodes.begin(); p!=nodes.end();p++) {
         p->oangle = getNodeAngle(*p);
     }
 }
void Model::push (const Point & t)
Definition at line 931 of file Model.cpp.
References nodes.
Referenced by Searcher::mutate(), and setID().
 {
     for(NodeArray::iterator n = nodes.begin(); n != nodes.end(); n++) {
         n->f += t;
     }
 }
void Model::pushRotate (const Point & c, float angle)
Definition at line 954 of file Model.cpp.
References nodes.
Referenced by Searcher::mutate(), and rotate().
 {
     for(NodeArray::iterator n = nodes.begin(); n != nodes.end(); n++) {
         n->ef += (*n-c).flipOrtho().copyNormalized()*angle;
     }
 }
bool Model::readEdge (ParseFile & is)
read edge from stream
Definition at line 167 of file Model.cpp.
References addEdge(), Edge::dampingconstant, edges, Edge::edgesensor, ParseFile::getKey(), ParseFile::getNextLine(), ParseFile::getValue(), nodes, ParseFile::pushLine(), Edge::restlength, ParseFile::setParseError(), and Edge::springconstant.
Referenced by operator>>(), and setID().
 {
     if(!is.getNextLine()) return false;
     if(is.getKey() != "e") {
         is.pushLine();
         return false;
     }
     istringstream vs(is.getValue());
     vs >> ws;
     int from, to;
     vs >> from;
     from--;
     int size = nodes.size();
     if(from<0 || from>size-1) throw new IOException("Edge is made of node indices that don't exist.");
     vs >> to;
     to--;
     if(to<0 || to>size-1) throw new IOException("Edge is made of node indices that don't exist.");
     Edge &ed = edges[addEdge(from, to)];
     string param;
     while(vs >> param) {
         if(param == "sc")
             vs >> ed.springconstant;
         else if(param == "dc")
             vs >> ed.dampingconstant;
         else if(param == "rl")
             vs >> ed.restlength;
         else if(param == "es") {
             char ft = 0;
             vs >> ft;
             if(ft == 'f') vs >> ed.edgesensor;
             else if(ft == 't') { vs >> ed.edgesensor; ed.edgesensor *= -1; }
             else {
                 is.setParseError("error reading edge parameter [es]");
                 throw new IOException("error reading edge parameter [es]");
             }
         } else {
             is.setParseError("error reading edge parameters");
             throw new IOException("error reading edge parameters");
         }
     }
     return true;
 }
bool Model::readFile (const char * filename, bool fullread = true)
Read geometry from file. See operator>>() for further details.
Definition at line 365 of file Model.cpp.
References IOException::getMessage(), and reset().
Referenced by Brain::doCommand(), MStructure::getRefModel(), Brain::loadModel(), main(), MStructure::read(), and setID().
 {
     ParseFile is(filename);
     if(is) {
         try {
             is >> *this;
         } catch (const IOException *e) {
             cerr << "IOException: " << e->getMessage() << endl
                  << "reading file " << filename << endl;
             reset();
             return false;
         }
         return true;
     } else return false;
 }
bool Model::readNode (ParseFile & is)
read node from stream
Definition at line 210 of file Model.cpp.
References addNode(), Node::attachSensor(), ParseFile::getKey(), ParseFile::getNextLine(), SensorCollection::getSensor(), ParseFile::getValue(), getZeroSensor(), m_Sensors, Node::mass, phys, ParseFile::pushLine(), ParseFile::setParseError(), Point2D::x, and Point2D::y.
Referenced by operator>>(), and setID().
 {
     if(!is.getNextLine()) return false;
     if(is.getKey() != "v") {
         is.pushLine();
         return false;
     }
     istringstream vs(is.getValue());
     vs >> ws;
     Node n(&phys);
     vs >> n.x;
     vs >> n.y;
     n.attachSensor(getZeroSensor());
     string param;
     while(vs >> param) {
         if(param == "s") {
             vs >> param;
             if(m_Sensors) n.attachSensor(m_Sensors->getSensor(param));
             else {
                 is.setParseError("tried to load undefined sensor");
                 throw new IOException("tried to load undefined sensor");
             }
         } else if(param == "m")
             vs >> n.mass;
         else {
             is.setParseError("error reading node parameters");
             throw new IOException("error reading node parameters");
         }
     }
     addNode(n);
     //debugline: cout << addNode(n) << " - " << n << endl;
     return true;
 }
bool Model::readParameter (ParseFile & is)
read model parameters
Definition at line 263 of file Model.cpp.
References ParticleParam::damping, ParseFile::getKey(), ParseFile::getNextLine(), ParseFile::getValue(), ParticleParam::gravitational, ParticleParam::imgforce, m_DirNodeInd, m_ppmm, ParticleParam::mass, phys, ParseFile::pushLine(), setName(), ParticleParam::springconst, ParticleParam::torque, and ParticleParam::viscousdrag.
Referenced by operator>>(), and setID().
 {
     if(!is.getNextLine()) return false;
     if(is.getKey() != "p") {
         is.pushLine();
         return false;
     }
     istringstream vs(is.getValue());
     string pname;
     vs >> pname;
     if(pname == "mass") {
         vs >> phys.mass;
     } else if(pname == "springconst") {
         vs >> phys.springconst;
     } else if(pname == "grav") {
         vs >> phys.gravitational;
     } else if(pname == "viscousdrag") {
         vs >> phys.viscousdrag;
     } else if(pname == "damping") {
         vs >> phys.damping;
     } else if(pname == "imageforce") {
         vs >> phys.imgforce;
     } else if(pname == "torque") {
         vs >> phys.torque;
     } else if(pname == "name") {
         string name;
         vs >> name;
         setName(name);
     } else if(pname == "ppmm") {
         vs >> m_ppmm;
     } else if(pname == "dirnode") {
         vs >> m_DirNodeInd;
     }
     return true;
 }
bool Model::readSensor (ParseFile & is)
read sensor from stream
Definition at line 244 of file Model.cpp.
References SensorCollection::addSensor(), ParseFile::getKey(), ParseFile::getNextLine(), ParseFile::getPath(), ParseFile::getValue(), m_SensorFile, m_Sensors, ParseFile::pushLine(), and SensorCollection::readSensor().
Referenced by operator>>(), and setID().
 {
     if(!is.getNextLine()) return false;
     if(is.getKey() == "sensors") {
         ParseFile sf(is.getPath()+is.getValue());
         if(sf) {
             m_SensorFile = is.getValue();
             while(sf) readSensor(sf);
         } else cerr << "couldn't load sensor file "
                     << is.getPath()+is.getValue() << endl;
     } else is.pushLine();
     if(!m_Sensors) m_Sensors = new SensorCollection();
     sensor_ptr s = m_Sensors->readSensor(is);
     if(!s) return false;
     m_Sensors->addSensor(s);
     //s->enableUpdate(Sensor::UPD_MINMAX); done in Node::attachSensor
     return true;
 }
void Model::reattachSensors ()
get sensors from sensor collection
Definition at line 616 of file Model.cpp.
References SensorCollection::getSensor(), m_Sensors, and nodes.
Referenced by getSensorCollection(), Searcher::reattachSensors(), and Brain::triggerTest().
{
     for (NodeArray::iterator p=nodes.begin(); p!=nodes.end();p++) {
         p->attachSensor(m_Sensors->getSensor(p->sensorID));
     }
 }
void Model::rebuildIndexTables () protected
rebuild cross indexing between nodes and edges
Definition at line 527 of file Model.cpp.
References edges, and nodes.
Referenced by getHLNode(), removeByAdjMat(), and removeNode().
 {
     dword idx=0;
     for(NodeArray::iterator n=nodes.begin(); n!=nodes.end(); n++,idx++) {
         n->index = idx;
         n->edges.clear();
     }
     idx=0;
     for(EdgeArray::iterator e=edges.begin(); e!=edges.end(); e++, idx++) {
         e->index = idx;
         e->fromNode().edges.push_back(e->index+1);
         e->toNode().edges.push_back(-e->index-1);
     }
 }
dword Model::removeByAdjMat (DMatrixf & adjm) protected
remove edged not mentioned in (non-directional) adjacency matrix
remove edged mentioned in (non-directional) adjacency matrix
Definition at line 447 of file Model.cpp.
References DMatrix< T >::at(), edges, getNNodes(), rebuildIndexTables(), DMatrix< T >::sizeX(), and DMatrix< T >::sizeY().
Referenced by getHLNode(), and removeEdges().
 {
     assert(adjm.sizeX() == adjm.sizeY() && adjm.sizeX() == (dword)getNNodes());
     dword count=0;
     EdgeArray::iterator e=edges.begin();
     while(e!=edges.end()) {
         int from,to;
         if(e->from > e->to) { from = e->from; to = e->to; }
         else { from = e->to; to = e->from; }
         assert(e->to < getNNodes());
         if(adjm.at(from, to)>0.0001) {
             edges.erase(e);
             adjm.at(from, to)--;
             count++;
         } else e++;
     }
     if(count) rebuildIndexTables();
     return count;
 }
dword Model::removeEdges ()
Remove edges between selected nodes.
Definition at line 498 of file Model.cpp.
References adjMat(), prepareTorque(), removeByAdjMat(), and selMaskMat().
Referenced by getHLNode(), and Brain::triggerTest().
 {
     DMatrixf selm = selMaskMat();
     selm *= adjMat();
     dword nc = removeByAdjMat(selm);
     if(nc) prepareTorque();
     return nc;
 }
void Model::removeNode (int nid)
Removes a node and its adjacent edges.
Definition at line 508 of file Model.cpp.
References edges, getNNodes(), m_DirNodeInd, m_HLNode, nodes, prepareTorque(), and rebuildIndexTables().
Referenced by getHLNode(), and Brain::triggerTest().
 {
     if(!(nid>=0 && nid<getNNodes())) return;
     EdgeArray::iterator e=edges.begin();
     while(e!=edges.end()) {
         if(e->to == nid || e->from == nid) edges.erase(e);
         else {
             if(e->to > nid) e->to--;
             if(e->from > nid) e->from--;
             e++;
         }
     }
     m_DirNodeInd = -1;
     m_HLNode = -1;
     nodes.erase(nodes.begin()+nid);
     rebuildIndexTables();
     prepareTorque();
 }
void Model::reset ()
reset all model information (including geometry)
Definition at line 103 of file Model.cpp.
References __SHAPEWEIGHT, clear(), ParticleParam::gravitational, m_Filename, m_Flags, m_InstCount, m_PCFlags, m_ShapeWeight, m_TimeStamp, PC_NOTHING, phys, setName(), and ParticleParam::viscousdrag.
Referenced by operator bool(), operator>>(), and readFile().
 {
     clear();
     m_TimeStamp = 0; //vector<float>(TS_LAST, 0);
     m_Flags=0;
     m_PCFlags=PC_NOTHING;
     m_InstCount=1;
     phys.gravitational = phys.gravitational;
     phys.viscousdrag = phys.viscousdrag;
     m_ShapeWeight = __SHAPEWEIGHT;
     setName("00");
     //m_ppmm = DEFAULT_PPMM;
     m_Filename.clear();
 }
void Model::resetForces ()
Definition at line 640 of file Model.cpp.
References nodes.
Referenced by getMaxRadius(), and updateParticles().
 {
     Point zero;
     for (NodeArray::iterator p=nodes.begin(); p!=nodes.end();p++) {
         p->f = zero;
     }
 }
void Model::rotate (float angle, const Point & c)
Definition at line 946 of file Model.cpp.
References invalidatePC(), nodes, PC_CENTER, PC_DIR, PC_STATS, and Point2D::rotate().
Referenced by adaptProperties(), Brain::distributeModel(), rotate(), setID(), and Brain::triggerTest().
 {
     for(NodeArray::iterator n = nodes.begin(); n != nodes.end(); n++) {
         (Point2D&)*n = c+(*n-c).rotate(angle);
     }
     invalidatePC(PC_DIR|PC_CENTER|PC_STATS);
 }
void Model::rotate (float angle) inline
Definition at line 124 of file Model.h.
References attract(), getCenter(), getFullLength(), getStdRadius(), m_PCFlags, PC_CENTER, pushRotate(), and rotate().
{
         dword cf=m_PCFlags&PC_CENTER;rotate(angle,getCenter());m_PCFlags|=cf;}
void Model::scale (float factor, bool movepoints = false)
multiply all rest lengths by factor
Definition at line 1140 of file Model.cpp.
References edges, getCenter(), invalidatePC(), nodes, PC_SCALE, and PC_STATS.
Referenced by adaptDataScale(), adaptProperties(), MStructure::buildMasterModel(), Brain::distributeModel(), getDeformation(), getMaxRadius(), and Brain::triggerTest().
 {
     for(EdgeArray::iterator e = edges.begin(); e != edges.end(); e++) {
         e->restlength*=factor;
     }
     if(movepoints) {
         Point center = getCenter();
         for(NodeArray::iterator n = nodes.begin();
             n != nodes.end(); n++)
         {
             n->setPos(center + ((*n-center)*factor));
         }
         invalidatePC(PC_SCALE|PC_STATS);
     }
 }
void Model::scaleSel (float factor, const DMatrixf & selm)
multiply all rest lengths of selected edges by factor
Definition at line 1156 of file Model.cpp.
References DMatrix< T >::at(), and edges.
Referenced by getMaxRadius(), and Brain::triggerTest().
 {
     for(EdgeArray::iterator e = edges.begin(); e != edges.end(); e++) {
         if(selm.at(e->from, e->to) > 0.001)
             e->restlength*=factor;
     }
 }
DMatrixf Model::selMaskMat () const
compute mask matrix of selected nodes
Definition at line 431 of file Model.cpp.
References getNNodes(), DMatrix< T >::min(), nodes, DMatrix< T >::setCol(), DMatrix< T >::setRow(), and Node::ST_SELECT.
Referenced by connectNodes(), getHLNode(), removeEdges(), and Brain::triggerTest().
 {
     DMatrixf selmc(getNNodes(), getNNodes());
     DMatrixf selmr(getNNodes(), getNNodes());
     for(NodeArray::const_iterator n = nodes.begin(); n != nodes.end(); n++)
         if(n->hasState(Node::ST_SELECT)) {
             selmr.setRow(n->getIndex());
             selmc.setCol(n->getIndex());
         }
     selmr+=selmc;
     selmc=selmr;
     selmr.min(1);
     return selmc-=selmr;
 }
void Model::setDirNode (int id) inline
Definition at line 177 of file Model.h.
References invalidatePC(), m_DirNodeInd, and PC_DIR.
Referenced by Brain::doCommand().
 { m_DirNodeInd = id; invalidatePC(PC_DIR); }
dword& Model::setFlags (dword flags) inline
Definition at line 198 of file Model.h.
References m_Flags.
Referenced by mergeModel(), and StructPath::protectWinners().
 { return m_Flags|=flags; }
void Model::setHLNode (int hlnode)
Set ID of highlighted node. Pass invalid node id (e.g. -1) to have none highlighted.
Definition at line 405 of file Model.cpp.
References Node::disableState(), Node::enableState(), getNNodes(), getNode(), m_HLNode, and Node::ST_HIGHLIGHT.
Referenced by getFilename(), and Brain::triggerTest().
{
     if(m_HLNode>=0 && m_HLNode<getNNodes())
         getNode(m_HLNode).disableState(Node::ST_HIGHLIGHT);
     m_HLNode = hlnode;
     if(m_HLNode>=0 && m_HLNode<getNNodes())
         getNode(m_HLNode).enableState(Node::ST_HIGHLIGHT);
     else m_HLNode = -1;
 }
void Model::setID (dword id) inline
Definition at line 84 of file Model.h.
References addNoise(), attachDataset(), draw(), drawPS(), freeze(), getLiveliness(), getQualityOfFit(), m_ID, operator<<, operator=(), operator>>, push(), readEdge(), readFile(), readNode(), readParameter(), readSensor(), rotate(), translate(), and writeFile().
Referenced by Searcher::add().
 { m_ID = id; }
void Model::setInstCount (dword ic) inline
Definition at line 223 of file Model.h.
References m_InstCount, and mergeModel().
Referenced by Searcher::add().
 { m_InstCount=ic; }
void Model::setLooser (bool isloose = true, float ts = 0.) inline
Definition at line 185 of file Model.h.
References m_Flags, and ST_LOOSER.
{
         if(isloose) m_Flags |= ST_LOOSER;
         else m_Flags &= ~ST_LOOSER;
         //if(ts!=0.) m_TimeStamp[TS_LOOSE]=ts;
     }
void Model::setName (const std::string & name)
Definition at line 399 of file Model.cpp.
References CRC(), m_CRC, and m_Name.
Referenced by getNEdges(), Model(), operator>>(), readParameter(), MStructure::rebuildExpMap(), and reset().
 {
     m_Name = name;
     m_CRC = (dword)CRC((unsigned char*)m_Name.c_str(), m_Name.size());
 }
void Model::setOldState (bool isoldstate = true, float ts = 0.) inline
Definition at line 191 of file Model.h.
References m_Flags, and ST_OLDSTATE.
{
         if(isoldstate) m_Flags |= ST_OLDSTATE;
         else m_Flags &= ~ST_OLDSTATE;
     }
void Model::setShapeWeight (float weight) inline
Definition at line 201 of file Model.h.
References adaptDataScale(), invalidatePC(), m_ShapeWeight, and PC_QOF.
Referenced by Brain::distributeModel(), and Brain::triggerTest().
{
         m_ShapeWeight = weight; invalidatePC(PC_QOF); }
void Model::setWinner (bool iswin = true, float ts = 0.) inline
Definition at line 179 of file Model.h.
References m_Flags, and ST_WINNER.
{
         if(iswin) m_Flags |= ST_WINNER;
         else m_Flags &= ~ST_WINNER;
         //if(ts!=0.) m_TimeStamp[TS_WIN]=ts;
     }
dword& Model::switchFlags (dword flags) inline
Definition at line 200 of file Model.h.
References m_Flags.
 { return m_Flags^=flags; }
void Model::translate (const Point & t)
Definition at line 923 of file Model.cpp.
References invalidatePC(), nodes, PC_CENTER, and PC_STATS.
Referenced by adaptProperties(), Brain::distributeModel(), Brain::evolve(), setID(), and Brain::triggerTest().
 {
     for(NodeArray::iterator n = nodes.begin(); n != nodes.end(); n++) {
         *n += t;
     }
     invalidatePC(PC_CENTER|PC_STATS);
 }
dword& Model::unsetFlags (dword flags) inline
Definition at line 199 of file Model.h.
References m_Flags.
Referenced by StructPath::unprotectWinners().
 { return m_Flags&=~flags; }
void Model::updateParticles (float dt, int method = 0)
Definition at line 752 of file Model.cpp.
References addTorque(), calculateDerivatives(), calculateForces(), getNNodes(), getSearchPara(), invalidatePC(), SearcherParams::m_ParaSolver, nodes, and resetForces().
Referenced by MStructure::buildMasterModel(), and getMaxRadius().
 {
     method = getSearchPara().m_ParaSolver;
     if(nodes.empty()) return;
     switch (method) {
     case 0:                                   // Euler
     {
         std::vector<NodeDerivative> m_Deriv(getNNodes());
         resetForces();
         calculateForces(dt);
         addTorque(dt);
         calculateDerivatives(m_Deriv);
         vector<NodeDerivative>::iterator d=m_Deriv.begin();
         for (NodeArray::iterator n=nodes.begin();
              n != nodes.end(), d != m_Deriv.end(); n++, d++) {
             *n += (d->dpdt*dt);
             n->v += (d->dvdt*dt);
         }
     }
     break;
     case 1:                                   // Midpoint
     {
         int i;
         std::vector<NodeDerivative> m_Deriv(getNNodes());
         resetForces();
         calculateForces(dt);
         addTorque(dt);
         calculateDerivatives(m_Deriv);
         NodeArray ptmp(nodes);
         for (i=0;i<(int)nodes.size();i++) {
             nodes[i] += (m_Deriv[i].dpdt * (dt * 0.5));
             nodes[i].v += (m_Deriv[i].dvdt * (dt * 0.5));
         }
         vector<NodeDerivative> deriv2(getNNodes());
         resetForces();
         calculateForces(dt);
         addTorque(dt);
         calculateDerivatives(deriv2);
         for (i=0;i<(int)nodes.size();i++) {
             nodes[i].setPos(ptmp[i]+
                             ((m_Deriv[i].dpdt+deriv2[i].dpdt)* (0.5*dt)));
             nodes[i].v = ptmp[i].v+
                 ((m_Deriv[i].dvdt+deriv2[i].dvdt)*(0.5*dt));
         }
     }
     break;
     case 2:                                   // latent midpoint
     {
         // the goal of this approach is to use information about
         // the last derivative to get more stable results if step
         // size is increasing. actually, there is no point in using
         // a derivative of a long past position to correct the
         // current derivative for further steps. incorporating the
         // old one makes the method even more instable...
         // in the original implementation this is preserved from last time
         std::vector<NodeDerivative> m_Deriv(getNNodes());
         float m_LastDT = 0;
         vector<NodeDerivative> deriv(getNNodes());
         resetForces();
         calculateForces(dt);
         addTorque(dt);
         calculateDerivatives(deriv);
         if(m_LastDT == 0 || deriv.size() != m_Deriv.size()) {
             m_Deriv = deriv;
             m_LastDT = 0;
         }
         //float wnow = dt*m_LastDT / (dt+m_LastDT);
         //float wlast =  dt*dt / (dt+m_LastDT);
         float wnow = 0.9*dt;
         float wlast = dt - wnow;
         int i;
         for (i=0;i<(int)nodes.size();i++) {
             nodes[i] += (m_Deriv[i].dpdt*wlast+deriv[i].dpdt*wnow);
             nodes[i].v += (m_Deriv[i].dvdt*wlast+deriv[i].dvdt*wnow);
         }
         m_Deriv = deriv;
         m_LastDT = dt;
     }
     break;
     }
     invalidatePC();
 }
bool Model::writeFile (const char * filename) const
Write geometry to file.
Definition at line 381 of file Model.cpp.
References IOException::getMessage(), and phys.
Referenced by setID(), MStructure::setRefModel(), and Brain::triggerTest().
 {
     ofstream os(filename);
     if(os) {
         try {
             os << "# file '" << filename << "' "<<endl;
             ParticleParam::global = phys;
             os << *this;
         } catch (const IOException *e) {
             cerr << "IOException: " << e->getMessage() << endl
                  << "writing file " << filename << endl;
             return false;
         }
         os.close();
         return true;
     } else return false;
 }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & is, const Model & g) friend
Read geometry from stream.
Definition at line 338 of file Model.cpp.
Referenced by setID().
 {
     os << "p name " << g.m_Name << endl;
     if(g.m_ppmm != DEFAULT_PPMM)
         os << "p ppmm " << g.m_ppmm << endl;
     os << "p dirnode " << g.m_DirNodeInd << endl;
     os << g.phys;
     os << endl;
     if(!g.m_SensorFile.empty()) {
         ofstream sf((ParseFile::getPath(g.m_Filename)+g.m_SensorFile).c_str());
         sf << *g.m_Sensors;
         os << "sensors " << g.m_SensorFile << endl;
     } else {
         g.m_Sensors->clearPrintList();
         for(NodeArray::const_iterator n = g.nodes.begin(); n != g.nodes.end();
             n++)
             n->sensor->hprint(os, (SensorCollection*)g.m_Sensors);
     }
     os << endl;
     for(NodeArray::const_iterator n = g.nodes.begin(); n != g.nodes.end(); n++)
         os << *n;
     os << endl;
     for(EdgeArray::const_iterator e = g.edges.begin(); e != g.edges.end(); e++)
         os << *e;
     return os;
 }
ParseFile& operator>> (ParseFile & is, Model & g) friend
Read complete geometry from input stream.
is comment character, v introduces a point (vertex), e an edge:
#example v 1 1 v 2 2 e 1 2
Definition at line 299 of file Model.cpp.
Referenced by setID().
 {
     g.reset();
     g.m_Filename = is.getFilename();
     g.phys = ParticleParam::global;
     g.setName("<noname>");
     g.m_ppmm = DEFAULT_PPMM;
     try{
         int phase=0;
         while(is) {
             if(phase == 0) {
                 if(!g.readSensor(is) && !g.readParameter(is))
                     phase++;
             }
             if(phase == 1) {
                 if(!g.readNode(is))
                     phase++;
             }
             if(phase == 2) {
                 if(!g.readEdge(is))
                     phase++;
             }
             if(phase == 3 && !is.eof()) {
                 g.reset();
                 throw new IOException("Error reading model file.");
             }
         }
     } catch(const IOException *e) {
         const char* omsg = e->getMessage();
         int l=strlen(omsg);
         char msg[l+256];
         sprintf(msg,"%s (interpreted line %i)", omsg, is.getLineNumber());
         throw new IOException(msg);
     }
     g.adaptDataScale();
     g.prepareTorque();
     return is;
 }
Member Data Documentation
EdgeArray Model::edges protected
indexed list of edges
Definition at line 263 of file Model.h.
Referenced by adaptProportion(), adaptRestLength(), adaptRestLengthSel(), addEdge(), addNoise(), addTorque(), adjMat(), calculateForces(), clear(), createEdgeSensors(), draw(), freeze(), getDeformation(), getEdge(), getEdgeSensorFit(), getFullLength(), getLengthRatio(), getLengthVariation(), getLiveliness(), getNEdges(), getNodeAngle(), getQualityOfFit(), operator<<(), operator=(), readEdge(), rebuildIndexTables(), removeByAdjMat(), removeNode(), scale(), and scaleSel().
dword Model::m_CRC protected
Definition at line 271 of file Model.h.
Referenced by getCRC(), operator=(), and setName().
dataset_cptr Model::m_Dataset protected
Definition at line 265 of file Model.h.
Referenced by adaptDataScale(), addImageForces(), addTorque(), attachDataset(), convertPointFromMM(), convertPointToMM(), getQualityOfFit(), and operator=().
float Model::m_Direction mutable protected
Definition at line 279 of file Model.h.
int Model::m_DirNodeInd mutable protected
Definition at line 273 of file Model.h.
Referenced by clear(), getDirNode(), Model(), operator<<(), operator=(), readParameter(), removeNode(), and setDirNode().
std::string Model::m_Filename protected
Definition at line 281 of file Model.h.
Referenced by getFilename(), operator<<(), operator=(), operator>>(), and reset().
dword Model::m_Flags protected
Definition at line 269 of file Model.h.
Referenced by getFlags(), hasFlags(), isLooser(), isOldState(), isWinner(), operator=(), reset(), setFlags(), setLooser(), setOldState(), setWinner(), switchFlags(), and unsetFlags().
int Model::m_HLNode mutable protected
Definition at line 283 of file Model.h.
Referenced by getHLNode(), operator=(), removeNode(), and setHLNode().
dword Model::m_ID mutable protected
Definition at line 284 of file Model.h.
Referenced by getID(), mergeModel(), operator=(), and setID().
dword Model::m_InstCount protected
number of merged instances
Definition at line 280 of file Model.h.
Referenced by getInstCount(), mergeModel(), operator=(), reset(), and setInstCount().
float Model::m_Liveliness mutable protected
Definition at line 277 of file Model.h.
Referenced by getLiveliness(), and operator=().
std::string Model::m_Name protected
Definition at line 270 of file Model.h.
Referenced by getName(), operator<<(), operator=(), and setName().
dword Model::m_PCFlags mutable protected
Definition at line 274 of file Model.h.
Referenced by getCenter(), getDirection(), getLiveliness(), getProperties(), getQualityOfFit(), getStdRadius(), invalidatePC(), operator=(), reset(), and rotate().
dword Model::m_ppmm protected
Definition at line 272 of file Model.h.
Referenced by adaptDataScale(), convertPointFromMM(), convertPointToMM(), convertPropFromMM(), convertPropToMM(), getDataScale(), Model(), operator<<(), operator=(), operator>>(), and readParameter().
PropVec Model::m_PropVec mutable protected
Definition at line 275 of file Model.h.
Referenced by getCenter(), getDirection(), getProperties(), getStdRadius(), and operator=().
float Model::m_QOF mutable protected
Definition at line 276 of file Model.h.
Referenced by getQualityOfFit(), and operator=().
float Model::m_Scale mutable protected
Definition at line 278 of file Model.h.
std::string Model::m_SensorFile protected
Definition at line 267 of file Model.h.
Referenced by operator<<(), operator=(), and readSensor().
SensorCollection* Model::m_Sensors protected
Definition at line 266 of file Model.h.
Referenced by attachDataset(), attachSensorColl(), getSensorCollection(), mergeSensorCollection(), Model(), operator<<(), operator=(), readNode(), readSensor(), and reattachSensors().
float Model::m_ShapeWeight protected
Definition at line 268 of file Model.h.
Referenced by getQualityOfFit(), Model(), operator=(), reset(), and setShapeWeight().
float Model::m_TimeStamp
time stamps (see. TTimeStamp)
Definition at line 259 of file Model.h.
Referenced by Searcher::add(), Searcher::cleanFlags(), Searcher::getGeneration(), mergeModel(), operator=(), and reset().
NodeArray Model::nodes protected
indexed list of nodes
Definition at line 262 of file Model.h.
Referenced by adaptProperties(), addEdge(), addImageForces(), addNode(), addNoise(), addTorque(), attract(), calculateDerivatives(), calculateForces(), clear(), distance(), draw(), getCenter(), getDirection(), getDirNode(), getLiveliness(), getMaxRadius(), getNNodes(), getNode(), getQualityOfFit(), getSelectedNodesN(), getSensorFit(), getStdRadius(), nearestNode(), operator bool(), operator<<(), operator=(), prepareTorque(), push(), pushRotate(), readEdge(), reattachSensors(), rebuildIndexTables(), removeNode(), resetForces(), rotate(), scale(), selMaskMat(), translate(), and updateParticles().
ParticleParam Model::phys
physical parameter set
Definition at line 257 of file Model.h.
Referenced by addEdge(), addTorque(), MStructure::buildMasterModel(), calculateForces(), Edge::Edge(), Model(), Node::Node(), operator<<(), operator=(), operator>>(), readNode(), readParameter(), reset(), Brain::triggerTest(), and writeFile().
The documentation for this class was generated from the following files:
src/Model.h
src/Model.cpp