Structural deformable models: src/Data.cpp File Reference
Data.cpp File Reference
#include <fstream>
#include <sstream>
#include <math.h>
#include <GL/gl.h>
#include "Data.h"
#include "fxconfig.h"
#include <fx.h>
#include <FXPNGImage.h>
#include <FXJPGImage.h>
#include <FXTIFImage.h>
#include <FXICOImage.h>
#include <FXTGAImage.h>
#include <FXRGBImage.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <signal.h>
#include <unistd.h>
Functions
static void copyFXImage2Image (vector< Image< byte > > &dimg, const FXImage &img)
static void copyFXImage2Image (Image< byte > &dimg, const FXImage &img)
static void copyImage2FXImage (FXImage &img, const vector< Image< byte > > &dimg)
template<class T >
Image< T > & makeNoiseImage (Image< T > &nimg, T mean, T sigma)
byte * interleave (const vector< Image< byte > > &img)
static void copyImage2FXImage (FXImage &img, const Image< byte > &dimg)
Function Documentation
static void copyFXImage2Image (vector< Image< byte > > & dimg, const FXImage & img) static
Definition at line 280 of file Data.cpp.
Referenced by Dataset::loadImage().
 {
     //FXImage *img=imgv->getImage();
     // copy to image buffer
     int height = img.getHeight();
     int width = img.getWidth();
     int size = width*height;
     byte *imgdat = (byte*)img.getData();
     const int nchan = 4;
     dimg.clear();
     dimg.resize(nchan);//, Image<byte>(width,height));
     for(vector< Image<byte> >::iterator ii = dimg.begin();
         ii!=dimg.end(); ii++)
         ii->setSize(width, height);
     //dimg.setSize(width,height);
     int sind = 0;
     for(int i=size;i>0;i--,imgdat+=nchan,sind++)
     {
         for(int c=0; c<nchan; c++) {
             dimg[c][sind] = imgdat[c];
         }
     }
 }
static void copyFXImage2Image (Image< byte > & dimg, const FXImage & img) static
Definition at line 304 of file Data.cpp.
References Image< T >::getData(), and Image< T >::setSize().
 {
     //FXImage *img=imgv->getImage();
     // copy to image buffer
     int height = img.getHeight();
     int width = img.getWidth();
     int size = width*height;
     byte *imgdat = (byte*)img.getData();
     dimg.setSize(width,height);
     byte *htimg = dimg.getData();
     int nchan = 4;
     for(int i=size;i>0;i--,imgdat+=nchan,htimg++)
     {
         //int val = int(0.299f*imgdat[0]+0.587f*imgdat[1]+0.114f*imgdat[2]);
         //int val = (int(imgdat[0])+imgdat[1]+imgdat[2])/3;
         int val = imgdat[0];
         //*htimg = val > 255 ? 255 : val;
         *htimg = byte(val);
     }
 }
static void copyImage2FXImage (FXImage & img, const vector< Image< byte > > & dimg) static
static void copyImage2FXImage (FXImage & img, const Image< byte > & dimg) static
Definition at line 326 of file Data.cpp.
References Image< T >::getData(), Image< T >::getSizeX(), and Image< T >::getSizeY().
 {
     int height = img.getHeight();
     int width = img.getWidth();
     img.resize(dimg.getSizeX(), dimg.getSizeY());
     int size = width*height;
     byte *imgdat = (byte*)img.getData();
     const byte *htimg = dimg.getData();
     int nchan = 4;
     for(int i=size;i>0;i--,imgdat+=nchan,htimg++)
     {
         imgdat[0] = *htimg;
         imgdat[1] = *htimg;
         imgdat[2] = *htimg;
     }
     img.create();
 }
byte* interleave (const vector< Image< byte > > & img)
Definition at line 241 of file Data.cpp.
Referenced by Dataset::drawImage().
{
     const int comp = img.size()>3 ? 3 : img.size();
     int size = img[0].size();
     byte *b = new byte[size*3];
     if(comp<3) {
         Image<byte>::const_iterator bi = img[0].begin();
         byte *cv = b;
         for(int i=0; i!=size; i++, cv++, bi++)
             *cv = *bi;
     } else { // comp == 3
         Image<byte>::const_iterator bi[comp];
         for(int a=0; a<comp; a++) bi[a] = img[a].begin();
         byte *cv = b;
         for(int i=0; i<size; i++) {
             *(cv++) = *bi[0]; bi[0]++;
             *(cv++) = *bi[1]; bi[1]++;
             *(cv++) = *bi[2]; bi[2]++;
         }
     }
     return b;
 }
template<class T > Image< T > & makeNoiseImage (Image< T > & nimg, T mean, T sigma)
Definition at line 346 of file Data.cpp.
References Dataset::data, fgauss01(), Image< T >::getData(), Image< T >::getSizeX(), Image< T >::getSizeY(), and Sensor::mean.
 {
     T* data = nimg.getData();
     for(int j=0; j<nimg.getSizeY(); j++)
         for(int i=0; i<nimg.getSizeX(); i++, data++)
         {
             *data = (T)(fgauss01()*sigma+mean);
         }
     return nimg;
 }