Structural deformable models: src/deform.h File Reference
deform.h File Reference
#include "fxconfig.h"
#include <fx.h>
#include <FXApp.h>
#include <string>
#include "glImage.h"
#include "sensordlg.h"
#include "Brain.h"
Classes
class ImageWindow
Functions
bool setTitle (const std::string &title)
bool setStatusText (const std::string &stext)
Function Documentation
bool setStatusText (const std::string & stext)
Definition at line 77 of file deform.cpp.
References ImageWindow::create(), ImageWindow::drawScene(), ImageWindow::ImageWindow(), NULL, ImageWindow::onCanvasRepaint(), ImageWindow::onCmdOpenGL(), ImageWindow::onConfigure(), ImageWindow::onExpose(), setStatusText(), ImageWindow::setStatusText(), TIMER_INTERVAL, and ImageWindow::~ImageWindow().
Referenced by ImageWindow::onToggleSensorDlg(), ImageWindow::selectSensor(), and setStatusText().
{
     ImageWindow *mw = dynamic_cast<ImageWindow*>
         (FXApp::instance()->getRootWindow());
     if(mw) {
         mw->setStatusText(stext.c_str());
         return true;
     } else return false;
 }
bool setTitle (const std::string & title)
Definition at line 68 of file deform.cpp.
{
     ImageWindow *mw = dynamic_cast<ImageWindow*>
         (FXApp::instance()->getRootWindow());
     if(mw) {
         mw->setTitle(title.c_str());
         return true;
     } else return false;
 }