Structural deformable models: src/deform.cpp File Reference
deform.cpp File Reference
#include "deform.h"
#include <fx3d.h>
#include <fxkeys.h>
#include <string.h>
#include <iostream>
#include <time.h>
#include "glutils.h"
Macros
#define STATUSTXTLEN 2048
Functions
FXDEFMAP (ImageWindow) ImageWindowMap[]
bool setTitle (const std::string &title)
bool setStatusText (const std::string &stext)
int main (int argc, char *argv[])
int gethostname (char *, int)
Variables
const FXuint TIMER_INTERVAL = 50
const FXString patterns
Macro Definition Documentation
#define STATUSTXTLEN 2048
Definition at line 21 of file deform.cpp.
Function Documentation
FXDEFMAP (ImageWindow)
int gethostname (char * , int)
Definition at line 505 of file deform.cpp.
 {
     return 0;
 }
int main (int argc, char * argv[])
Definition at line 479 of file deform.cpp.
References ImageWindow::cmdline().
{
 //#define REDIRECT_STDOUT
 #ifdef REDIRECT_STDOUT
     ofstream logfile("output.log");
     cout.rdbuf(logfile.rdbuf());
     cerr.rdbuf(logfile.rdbuf());
 #endif
   // Make application
   FXApp application("Deformable Model Segmentation","FoxText");
   // Start app
   application.init(argc,argv);
   // Make window
   ImageWindow *iw = new ImageWindow(&application);
   iw->cmdline(argc,argv);
   glutInit(&argc,argv);
   // Create the application's windows
   application.create();
   // Run the application
   return application.run();
 }
bool setStatusText (const std::string & stext)
Definition at line 77 of file deform.cpp.
References ImageWindow::create(), ImageWindow::drawScene(), ImageWindow::ImageWindow(), NULL, ImageWindow::onCanvasRepaint(), ImageWindow::onCmdOpenGL(), ImageWindow::onConfigure(), ImageWindow::onExpose(), setStatusText(), ImageWindow::setStatusText(), TIMER_INTERVAL, and ImageWindow::~ImageWindow().
Referenced by ImageWindow::onToggleSensorDlg(), ImageWindow::selectSensor(), and setStatusText().
{
     ImageWindow *mw = dynamic_cast<ImageWindow*>
         (FXApp::instance()->getRootWindow());
     if(mw) {
         mw->setStatusText(stext.c_str());
         return true;
     } else return false;
 }
bool setTitle (const std::string & title)
Definition at line 68 of file deform.cpp.
{
     ImageWindow *mw = dynamic_cast<ImageWindow*>
         (FXApp::instance()->getRootWindow());
     if(mw) {
         mw->setTitle(title.c_str());
         return true;
     } else return false;
 }
Variable Documentation
const FXString patterns
Initial value:
=
  "All Files (*)\n"
  "GIF Image (*.gif)\n"
  "BMP Image (*.bmp)\n"
  "XPM Image (*.xpm)\n"
  "PCX Image (*.pcx)\n"
  "RGB Image (*.rgb)\n"
  "PNG Image (*.png)\n"
  "JPEG Image (*.jpg)\n"
  "TARGA Image (*.tga)\n"
  "TIFF Image (*.tif)\n"
Definition at line 25 of file deform.cpp.
Referenced by ImageWindow::onToggleSensorDlg().
const FXuint TIMER_INTERVAL = 50
Definition at line 22 of file deform.cpp.
Referenced by ImageWindow::onTimeout(), and setStatusText().