Structural deformable models: src/ExpMap.h File Reference
ExpMap.h File Reference
#include <list>
#include <map>
#include "Model.h"
#include "VVector.h"
#include "DMatrix.h"
#include "common.h"
Classes
class Winner
class EMDistribution
class EMDRect
class EMDGauss
class EMDXformer
class ExpectationMap
Functions
PropVec & hgPropTF (const DMatrixf &tfmat, PropVec &prop)
Function Documentation
PropVec& hgPropTF (const DMatrixf & tfmat, PropVec & prop) inline
Definition at line 182 of file ExpMap.h.
References VVector< T, D >::begin(), DMatrix< T >::empty(), DMatrix< T >::mulLeft(), DMatrix< T >::setRange(), VVector< T, D >::size(), DMatrix< T >::sizeX(), and DMatrix< T >::sizeY().
Referenced by EMDXformer::getPropVec(), and EMDXformer::ratePropVec().
 {
     if(!tfmat.empty() && tfmat.sizeX() == tfmat.sizeY()) {
         DMatrixf propDM(1,PropVec::size(), prop.begin());
         if(tfmat.sizeX() == propDM.sizeY()) { // linear
             propDM = propDM.mulLeft(tfmat);
             prop = &*propDM.getData().begin();
         } else if(tfmat.sizeX() == propDM.sizeY()+1) {//affine (homogeneous)
             DMatrixf propDMH(1,propDM.sizeY()+1, 1.f);
             propDMH.setRange(0,0,propDM);
             propDMH = propDMH.mulLeft(tfmat);
             prop = &*propDMH.getData().begin();
         }
     }
     return prop;
 }