Structural deformable models: src/ffind.cpp File Reference
ffind.cpp File Reference
#include <iostream>
#include <string>
#include <list>
#include <libgen.h>
#include <dirent.h>
#include <fnmatch.h>
Classes
class FFind
Functions
int __fixed_fnmatch (const struct dirent *dent)
void perror (const char *errmsg)
int main ()
Variables
char __fnmatchpattern [2048]
Function Documentation
int __fixed_fnmatch (const struct dirent * dent)
Definition at line 12 of file ffind.cpp.
Referenced by FFind::find(), and FFind::findFiles().
{
     return !fnmatch(__fnmatchpattern, dent->d_name,0);
 }
int main ()
Definition at line 61 of file ffind.cpp.
           {
     struct dirent **namelist;
     int n;
     FFind ff("./*.cpp");
     ff.findAll();
     return 0;
 }
void perror (const char * errmsg)
Definition at line 57 of file ffind.cpp.
Referenced by FFind::findFiles().
{
     cerr << errmsg << endl;
 }
Variable Documentation
char __fnmatchpattern[2048]
Definition at line 11 of file ffind.cpp.
Referenced by __fixed_fnmatch(), and FFind::findFiles().