Structural deformable models: src/glutils.h File Reference
glutils.h File Reference
#include <GL/glut.h>
Macros
#define GLUT_DISABLE_ATEXIT_HACK
Functions
int sglBitmapString (const char *msg, int x, int y, void *font=(void *) GLUT_BITMAP_8_BY_13)
int sglBitmapStringOutlined (const char *msg, int x, int y, void *font=(void *) GLUT_BITMAP_8_BY_13)
Macro Definition Documentation
#define GLUT_DISABLE_ATEXIT_HACK
Definition at line 4 of file glutils.h.
Function Documentation
int sglBitmapString (const char * msg, int x, int y, void * font = (void*)GLUT_BITMAP_8_BY_13) inline
Definition at line 7 of file glutils.h.
Referenced by Brain::drawAllModels(), and sglBitmapStringOutlined().
 {
     int width = 0;
     const char *c = msg;
     while(*c != 0) {
         glRasterPos2i(x+width,y);
         glutBitmapCharacter(font, (int)*c);
         int w = glutBitmapWidth(font, (int)*c);
         width += w;
         c++;
     }
     return width;
 }
int sglBitmapStringOutlined (const char * msg, int x, int y, void * font = (void*)GLUT_BITMAP_8_BY_13) inline
Definition at line 22 of file glutils.h.
References sglBitmapString().
Referenced by Node::draw(), and Brain::drawAllModels().
 {
     glColor3f(0,0,0);
     sglBitmapString(msg,x-1,y-1);
     sglBitmapString(msg,x-1,y+1);
     sglBitmapString(msg,x+1,y-1);
     sglBitmapString(msg,x+1,y+1);
     glColor3f(1,1,1);
     return sglBitmapString(msg, x, y, font);
 }