Structural deformable models: src/mathutil.h File Reference
mathutil.h File Reference
#include <math.h>
#include "simpletypes.h"
#include <stdlib.h>
Macros
#define M_PI 3.14159265359
#define M_1_PI (1/M_PI)
#define M_E 2.718281828
#define M_SQRT2PI 2.5066283
#define frand(max) (((float)rand())*(max)/RAND_MAX)
#define FRAND1 (((float)rand())/RAND_MAX)
Functions
int absint (int v)
template<class T >
bool clamp (T &x, T &y, const T x0, const T y0, const T x1, const T y1)
float fgauss01 ()
float gauss (float x, float stdev)
float gauss2 (float x2, float stdev)
double gaussd (float x, double stdev)
float gaussd2 (float x2, double stdev)
float mapAngle360 (float a)
float mapAngle360 (float a, float mina)
float mapAngle180 (float a)
float mapAngle2PI (float a)
float mapAngle2PI (float a, float mina)
float mapAnglePI (float a)
float mapAnglePI (float a, float cnta)
dword power2 (dword x)
Macro Definition Documentation
#define frand (max) (((float)rand())*(max)/RAND_MAX)
Definition at line 48 of file mathutil.h.
Referenced by Model::addNoise(), Brain::distributeModel(), Brain::evolve(), fgauss01(), EMDRect::getPropVec(), ExpectationMap::getPropVec(), Searcher::mutate(), and CElement< D >::randomize().
#define FRAND1 (((float)rand())/RAND_MAX)
Definition at line 49 of file mathutil.h.
Referenced by Searcher::mutate().
#define M_1_PI (1/M_PI)
Definition at line 12 of file mathutil.h.
Referenced by Point2D::angle(), VVector< float, 4 >::angle(), and mapAngle2PI().
#define M_E 2.718281828
Definition at line 15 of file mathutil.h.
#define M_PI 3.14159265359
Definition at line 9 of file mathutil.h.
Referenced by Point2D::angle(), VVector< float, 4 >::angle(), Searcher::buildClusters(), ExpectationMap::correctLBUB(), Brain::distributeModel(), SubStructure::getLBUB(), main(), mapAngle2PI(), mapAnglePI(), Searcher::mutate(), MStructure::rebuildExpMap(), Brain::setupSearch(), and Brain::triggerTest().
#define M_SQRT2PI 2.5066283
Definition at line 18 of file mathutil.h.
Referenced by gauss(), gauss2(), gaussd(), gaussd2(), and EMDGauss::ratePropVec().
Function Documentation
int absint (int v) inline
Definition at line 21 of file mathutil.h.
Referenced by Image< T >::addLine().
 { return v<0 ? -v : v;}
template<class T > bool clamp (T & x, T & y, const T x0, const T y0, const T x1, const T y1)
Definition at line 24 of file mathutil.h.
Referenced by Point2D::clamp().
 {
     bool ret=false;
     if(x<x0) { ret = true; x = x0;}
     if(x>x1) { ret = true; x = x1;}
     if(y<y0) { ret = true; y = y0;}
     if(y>y1) { ret = true; y = y1;}
     return ret;
 }
float fgauss01 () inline
Definition at line 53 of file mathutil.h.
References frand, and dmutil::sqrt().
Referenced by Dataset::addNoise(), Brain::distributeModel(), EMDGauss::getPropVec(), and makeNoiseImage().
 {
     float x, y, r2;
     do
     {
         /* choose x,y in uniform square (-1,-1) to (+1,+1) */
         x = -1 + frand(2);
         y = -1 + frand(2);
         /* see if it is in the unit circle */
         r2 = x * x + y * y;
     } while (r2 > 1.0 || r2 == 0);
     /* Box-Mueller transform */
     return y * sqrt (-2.0 * log (r2) / r2);
 }
float gauss (float x, float stdev) inline
Definition at line 68 of file mathutil.h.
References M_SQRT2PI.
{
     return exp(-x*x/(2*stdev*stdev)) / (stdev*M_SQRT2PI);
 }
float gauss2 (float x2, float stdev) inline
Definition at line 71 of file mathutil.h.
References M_SQRT2PI.
Referenced by EMDGauss::ratePropVec().
{
     return exp(-x2/(2*stdev*stdev)) / (stdev*M_SQRT2PI);
 }
double gaussd (float x, double stdev) inline
Definition at line 74 of file mathutil.h.
References M_SQRT2PI.
{
     return exp(-x*x/(2*stdev*stdev)) / (stdev*M_SQRT2PI);
 }
float gaussd2 (float x2, double stdev) inline
Definition at line 77 of file mathutil.h.
References M_SQRT2PI.
Referenced by create2DGaussian().
{
     return exp(-x2/(2*stdev*stdev)) / (stdev*M_SQRT2PI);
 }
float mapAngle180 (float a) inline
Definition at line 92 of file mathutil.h.
References mapAngle360().
{
     a = mapAngle360(a);
     return a<=180 ? a : a-360;
 }
float mapAngle2PI (float a) inline
Definition at line 97 of file mathutil.h.
References M_1_PI, and M_PI.
Referenced by ExpectationMap::correctLBUB(), Model::getDirection(), ExpectationMap::getPropVec(), mapAnglePI(), and ExpectationMap::ratePropVec().
{
     float turns=floor(a*(0.5*M_1_PI));
     return a-(2*M_PI)*turns;
 }
float mapAngle2PI (float a, float mina) inline
Definition at line 102 of file mathutil.h.
References M_1_PI, and M_PI.
{
     float turns=floor((a-mina)*(0.5*M_1_PI));
     return a-(2*M_PI)*turns;
 }
float mapAngle360 (float a) inline
Definition at line 81 of file mathutil.h.
Referenced by mapAngle180().
{
     int d=(int)a/360 - (int)(a<0);
     return a-360*(float)d;
 }
float mapAngle360 (float a, float mina) inline
Definition at line 86 of file mathutil.h.
{
     float ashift = a-mina;
     int d=(int)ashift/360 - (int)(ashift<0);
     return a-360*(float)d;
 }
float mapAnglePI (float a) inline
Definition at line 107 of file mathutil.h.
References M_PI, and mapAngle2PI().
Referenced by Model::addTorque(), StructTable::adjustByAvgDir(), Searcher::buildClusters(), and EMDXformer::ratePropVec().
{
     a = mapAngle2PI(a);
     return (a>M_PI) ? a-(2*M_PI) : a;
 }
float mapAnglePI (float a, float cnta) inline
Definition at line 112 of file mathutil.h.
References M_PI, and mapAngle2PI().
{
     a = mapAngle2PI(a, cnta);
     return (a-cnta>M_PI) ? a-(2*M_PI) : a;
 }
dword power2 (dword x) inline
Definition at line 117 of file mathutil.h.
Referenced by GLImage::setImage().
 {
     return 1<< int(ceil(log(float(x))/log(2.f)));
 }