Structural deformable models: src/Model.cpp File Reference
Model.cpp File Reference
#include <stdlib.h>
#include <iostream>
#include <fstream>
#include <sstream>
#include <ctype.h>
#include "Model.h"
#include "SensorSet.h"
#include "SensorColl.h"
#include "Data.h"
#include "PartParam.h"
#include "Searcher.h"
#include "crc.h"
#include "mathutil.h"
Functions
ParseFile & operator>> (ParseFile &is, Model &g)
ostream & operator<< (ostream &os, const Model &g)
Function Documentation
ostream& operator<< (std::ostream & os, const Model & g)
Read geometry from stream.
Definition at line 338 of file Model.cpp.
References SensorCollection::clearPrintList(), DEFAULT_PPMM, Model::edges, ParseFile::getPath(), Model::m_DirNodeInd, Model::m_Filename, Model::m_Name, Model::m_ppmm, Model::m_SensorFile, Model::m_Sensors, Model::nodes, and Model::phys.
 {
     os << "p name " << g.m_Name << endl;
     if(g.m_ppmm != DEFAULT_PPMM)
         os << "p ppmm " << g.m_ppmm << endl;
     os << "p dirnode " << g.m_DirNodeInd << endl;
     os << g.phys;
     os << endl;
     if(!g.m_SensorFile.empty()) {
         ofstream sf((ParseFile::getPath(g.m_Filename)+g.m_SensorFile).c_str());
         sf << *g.m_Sensors;
         os << "sensors " << g.m_SensorFile << endl;
     } else {
         g.m_Sensors->clearPrintList();
         for(NodeArray::const_iterator n = g.nodes.begin(); n != g.nodes.end();
             n++)
             n->sensor->hprint(os, (SensorCollection*)g.m_Sensors);
     }
     os << endl;
     for(NodeArray::const_iterator n = g.nodes.begin(); n != g.nodes.end(); n++)
         os << *n;
     os << endl;
     for(EdgeArray::const_iterator e = g.edges.begin(); e != g.edges.end(); e++)
         os << *e;
     return os;
 }
ParseFile& operator>> (ParseFile & is, Model & g)
Read complete geometry from input stream.
is comment character, v introduces a point (vertex), e an edge:
#example v 1 1 v 2 2 e 1 2
Definition at line 299 of file Model.cpp.
References Model::adaptDataScale(), DEFAULT_PPMM, ParseFile::eof(), ParseFile::getFilename(), ParseFile::getLineNumber(), IOException::getMessage(), ParticleParam::global, Model::m_Filename, Model::m_ppmm, Model::phys, Model::prepareTorque(), Model::readEdge(), Model::readNode(), Model::readParameter(), Model::readSensor(), Model::reset(), and Model::setName().
 {
     g.reset();
     g.m_Filename = is.getFilename();
     g.phys = ParticleParam::global;
     g.setName("<noname>");
     g.m_ppmm = DEFAULT_PPMM;
     try{
         int phase=0;
         while(is) {
             if(phase == 0) {
                 if(!g.readSensor(is) && !g.readParameter(is))
                     phase++;
             }
             if(phase == 1) {
                 if(!g.readNode(is))
                     phase++;
             }
             if(phase == 2) {
                 if(!g.readEdge(is))
                     phase++;
             }
             if(phase == 3 && !is.eof()) {
                 g.reset();
                 throw new IOException("Error reading model file.");
             }
         }
     } catch(const IOException *e) {
         const char* omsg = e->getMessage();
         int l=strlen(omsg);
         char msg[l+256];
         sprintf(msg,"%s (interpreted line %i)", omsg, is.getLineNumber());
         throw new IOException(msg);
     }
     g.adaptDataScale();
     g.prepareTorque();
     return is;
 }