Structural deformable models: dmutil Namespace Reference
dmutil Namespace Reference
Functions
template<class T >
linalg::Matrix convert (const DMatrix< T > &dmat)
template<class T >
DMatrix< T > convert (const linalg::Matrix &mat)
template<class T >
DMatrix< T > & invert (DMatrix< T > &dmat)
template<class T >
DMatrix< T > inverse (const DMatrix< T > &dmat)
template<class T >
bool SVD (const DMatrix< T > &dmat, DMatrix< T > &mU, DMatrix< T > &mS, DMatrix< T > &mV)
template<class T >
DMatrix< T > pseudoInv (const DMatrix< T > &dmat)
template<class T >
DMatrix< T > makeDiag (const DMatrix< T > &diag)
template<class T >
DMatrix< T > makeIdentity (dword sxy, const T &diag=1)
template<class T >
DMatrix< T > makeUpper (dword sxy, bool filldiag=true, const T &val=1)
template<class T >
DMatrix< T > makeLower (dword sxy, bool filldiag=true, const T &val=1)
template<class T >
DMatrix< T > makeRotMat2D (const float &angle)
template<class T >
DMatrix< T > horizCat (const DMatrix< T > &lm, const DMatrix< T > &rm)
template<class T >
DMatrix< T > vertCat (const DMatrix< T > &um, const DMatrix< T > &lm)
template<class T >
DMatrix< T > sum (const DMatrix< T > &mat)
template<class T >
DMatrix< T > & sqr (DMatrix< T > &mat)
template<class T >
DMatrix< T > & sqrt (DMatrix< T > &mat)
template<class T >
DMatrix< T > avg (const DMatrix< T > &mat)
template<class T >
DMatrix< T > var (const DMatrix< T > &mat)
template<class T >
DMatrix< T > stdev (const DMatrix< T > &mat)
template<class T >
DMatrix< T > expand (const DMatrix< T > &mat, dword mx, dword my)
template<class T >
DMatrix< T > & threshold (DMatrix< T > &mat, const T &th, const T &repl=T(0))
template<class T >
DMatrix< T > & abs (DMatrix< T > &mat)
Function Documentation
template<class T > DMatrix<T>& dmutil::abs (DMatrix< T > & mat)
Definition at line 131 of file DMatrixUtil.h.
References DMatrix< T >::getData().
Referenced by Model::addNoise(), MStructure::buildMasterModel(), Brain::doCommand(), Model::getQualityOfFit(), VVector< float, 4 >::majorComponent(), ImageWindow::onKeyPress(), ImageWindow::onRightMouseClick(), and Brain::triggerTest().
         {
             for(typename DMatrix<T>::iterator mi = mat.getData().begin();
                 mi != mat.getData().end(); mi++)
                 if(*mi<T(0)) *mi = -*mi;
             return mat;
         }
template<class T > DMatrix<T> dmutil::avg (const DMatrix< T > & mat)
Definition at line 89 of file DMatrixUtil.h.
References DMatrix< T >::sizeY(), and sum().
Referenced by MStructure::addExpectation(), SubStructure::analyseTF(), Sensor::calcMinMax(), EMDGauss::setAvg(), MStructure::showStats(), var(), and VVector< float, 4 >::var().
         {
             DMatrix<T> res(sum(mat));
             return res/=T(mat.sizeY());
         }
template<class T > linalg::Matrix dmutil::convert (const DMatrix< T > & dmat)
Definition at line 19 of file DMatrixLinAlg.h.
References DMatrix< T >::sizeX(), and DMatrix< T >::sizeY().
     {
         Eigen::MatrixXf mat((int)dmat.sizeY(), (int)dmat.sizeX());
         linalg::Matrix eth(mat);
         //typename DMatrix<T>::const_iterator dat = dmat.getData().begin();
     // TODO: translate this code from LinAlg to Eigen
         //for(register int i=eth.q_row_lwb(); i<=eth.q_row_upb(); i++)
         //    for(register int j=eth.q_col_lwb(); j<=eth.q_col_upb(); j++)
         //        eth(i,j) = dmat.at(j-1,i-1);
         return mat;
     }
template<class T > DMatrix<T> dmutil::convert (const linalg::Matrix & mat)
Definition at line 32 of file DMatrixLinAlg.h.
     {
         linalg::Matrix cmat(mat);
         linalg::Matrix eth(cmat);
         DMatrix<T> dmat; // (eth.q_col_upb()-eth.q_col_lwb()+1, // TODO
                          // eth.q_row_upb()-eth.q_row_lwb()+1);
         //typename DMatrix<T>::iterator dat = dmat.getData().begin();
         //for(register int i=eth.q_row_lwb(); i<=eth.q_row_upb(); i++)
         //    for(register int j=eth.q_col_lwb(); j<=eth.q_col_upb(); j++)
         //        dmat.at(j-1,i-1) = eth(i,j);
         return dmat;
     }
template<class T > DMatrix<T> dmutil::expand (const DMatrix< T > & mat, dword mx, dword my)
Definition at line 112 of file DMatrixUtil.h.
References DMatrix< T >::setRange(), DMatrix< T >::sizeX(), and DMatrix< T >::sizeY().
Referenced by SubStructure::analyseTF().
         {
             DMatrix<T> res(mat.sizeX()*mx, mat.sizeY()*my);
             for(dword y=0; y<my; y++)
                 for(dword x=0; x<mx; x++)
                     res.setRange(mat.sizeX()*x, mat.sizeY()*y, mat);
             return res;
         }
template<class T > DMatrix<T> dmutil::horizCat (const DMatrix< T > & lm, const DMatrix< T > & rm)
Definition at line 38 of file DMatrixUtil.h.
References DMatrix< T >::setRange(), DMatrix< T >::sizeX(), and DMatrix< T >::sizeY().
         {
             assert(lm.sizeY() == rm.sizeY());
             DMatrix<T> res(lm.sizeX()+rm.sizeX(), lm.sizeY());
             res.setRange(0,0, lm);
             res.setRange(lm.sizeX(),0, rm);
             return res;
         }
template<class T > DMatrix<T> dmutil::inverse (const DMatrix< T > & dmat)
Definition at line 62 of file DMatrixLinAlg.h.
References invert().
Referenced by SubStructure::analyseTF(), MStructure::getExpMap(), and EMDXformer::setTFMat().
     {
         DMatrix<T> imat(dmat);
         return invert(imat);
     }
template<class T > DMatrix<T>& dmutil::invert (DMatrix< T > & dmat)
Definition at line 46 of file DMatrixLinAlg.h.
Referenced by inverse().
     {
         bool m_Verbose = false;
         try {
             //if(!m_Verbose) freopen("/dev/null","a+",stderr);
             linalg::Matrix mat = convert<T>(dmat);
             //dmat = convert<T>(linalg::inverse(mat)); // TODO
         } catch(void*)
         {
             //if(!m_Verbose) freopen("/dev/stdout","a+",stderr);
         }
         //if(!m_Verbose) freopen("/dev/stdout","a+",stderr);
         return dmat;
     }
template<class T > DMatrix<T> dmutil::makeDiag (const DMatrix< T > & diag)
Definition at line 6 of file DMatrixUtil.h.
References DMatrix< T >::at(), DMatrix< T >::getData(), and DMatrix< T >::size().
{
         dword sxy = diag.size();
         DMatrix<T> mat(sxy, sxy, T(0));
         typename DMatrix<T>::const_iterator di = diag.getData().begin();
         for(dword i = 0; i < sxy; i++, di++) mat.at(i,i) = *di;
         return mat;
     }
template<class T > DMatrix<T> dmutil::makeIdentity (dword sxy, const T & diag = 1)
Definition at line 15 of file DMatrixUtil.h.
{
         return DMatrix<T>(sxy, sxy, T(0)).setDiag(diag);
     }
template<class T > DMatrix<T> dmutil::makeLower (dword sxy, bool filldiag = true, const T & val = 1)
Definition at line 25 of file DMatrixUtil.h.
{
         return DMatrix<T>(sxy, sxy).setLower(val);
     }
template<class T > DMatrix<T> dmutil::makeRotMat2D (const float & angle)
Definition at line 30 of file DMatrixUtil.h.
References DMatrix< T >::at().
{
         DMatrix<T> mat(2,2);
         mat.at(0,0) = (T)cos(angle); mat.at(1,0) = (T)-sin(angle);
         mat.at(0,1) = (T)sin(angle); mat.at(1,1) = (T)cos(angle);
         return mat;
     }
template<class T > DMatrix<T> dmutil::makeUpper (dword sxy, bool filldiag = true, const T & val = 1)
Definition at line 20 of file DMatrixUtil.h.
{
         return DMatrix<T>(sxy, sxy).setUpper(1, val);
     }
template<class T > DMatrix<T> dmutil::pseudoInv (const DMatrix< T > & dmat)
Definition at line 126 of file DMatrixLinAlg.h.
References DMatrix< T >::at(), DMLA_TAU, DMatrix< T >::mulRight(), DMatrix< T >::sizeX(), DMatrix< T >::sizeY(), SVD(), and DMatrix< T >::transpose().
     {
         DMatrix<T> U,S,V;
         if(dmutil::SVD(dmat, U,S,V)) {
             //create an inverted S and skip the nearly-zero elements
             //on the diagonal
             dword sxy = std::min(S.sizeX(),S.sizeY());
             for(dword i=0; i<sxy; i++)
                 if(S.at(i,i)>T(DMLA_TAU)) S.at(i,i) = T(1)/S.at(i,i);
                 else S.at(i,i) = 0;
              S.transpose();
              U.transpose();
             DMatrix<T> P = V.mulRight(S.mulRight(U));  // actually V * S(+)*Ut
             return P;
         }
         return dmat;
     }
template<class T > DMatrix<T>& dmutil::sqr (DMatrix< T > & mat)
Definition at line 71 of file DMatrixUtil.h.
References DMatrix< T >::getData().
Referenced by var().
         {
             for(typename DMatrix<T>::iterator mi = mat.getData().begin();
                 mi != mat.getData().end(); mi++)
                 *mi = *mi**mi;
             return mat;
         }
template<class T > DMatrix<T>& dmutil::sqrt (DMatrix< T > & mat)
Definition at line 80 of file DMatrixUtil.h.
References DMatrix< T >::getData().
Referenced by SubStructure::analyseTF(), MCGSensor::calcGradient(), Sensor::calcMinMax(), CRSensor::calcValue(), CElement< D >::dist(), Model::distance(), fgauss01(), SubStructure::generateEMDist(), Model::getDeformation(), Model::getLengthVariation(), Model::getLiveliness(), Model::getMaxRadius(), Model::getStdRadius(), Edge::length(), Model::nearestNode(), Image< T >::norm(), Point2D::norm(), VVector< float, 4 >::norm(), MappingSensor::performUpdate(), Point2D::sinAngle(), VVector< float, 4 >::sqrtEach(), stdev(), and VVector< float, 4 >::stdev().
         {
             for(typename DMatrix<T>::iterator mi = mat.getData().begin();
                 mi != mat.getData().end(); mi++)
                 *mi = (T)sqrtf((double)*mi);
             return mat;
         }
template<class T > DMatrix<T> dmutil::stdev (const DMatrix< T > & mat)
Definition at line 105 of file DMatrixUtil.h.
References sqrt(), and var().
Referenced by MStructure::addExpectation(), SubStructure::analyseTF(), EMDGauss::EMDGauss(), EMDGauss::setAvg(), EMDGauss::setStdev(), EMDXformer::setStdev(), and MStructure::showStats().
         {
             DMatrix<T> sd(var(mat));
             return dmutil::sqrt(sd);
         }
template<class T > DMatrix<T> dmutil::sum (const DMatrix< T > & mat)
Definition at line 58 of file DMatrixUtil.h.
References DMatrix< T >::getData(), DMatrix< T >::sizeX(), and DMatrix< T >::sizeY().
Referenced by avg(), VVector< float, 4 >::avg(), create2DGaussian(), and Edge::toNode().
         {
             DMatrix<T> res(mat.sizeX(), 1);
             typename DMatrix<T>::const_iterator mi = mat.getData().begin();
             for(dword y=0; y<mat.sizeY(); y++) {
                 typename DMatrix<T>::iterator ri = res.getData().begin();
                 for(dword x=0; x<mat.sizeX(); x++, ri++, mi++)
                     *ri += *mi;
             }
             return res;
         }
template<class T > bool dmutil::SVD (const DMatrix< T > & dmat, DMatrix< T > & mU, DMatrix< T > & mS, DMatrix< T > & mV)
Definition at line 69 of file DMatrixLinAlg.h.
References DMatrix< T >::at(), DMatrix< T >::getRange(), DMatrix< T >::resize(), DMatrix< T >::setCol(), DMatrix< T >::sizeX(), and DMatrix< T >::sizeY().
Referenced by pseudoInv().
     {
         using namespace Eigen;
         bool m_Verbose = false;
         try {
             //if(!m_Verbose) freopen("/dev/null","a+",stderr);
             // zeropad matrix to make enough rows
             // (rank doesn't matter for the algorithm)
             int d = dmat.sizeX() - dmat.sizeY();
             if(d<0) d=0;
             linalg::Matrix mat =
                 convert<T>(DMatrix<T>(dmat.sizeX(), dmat.sizeY()+d,0.0f)
                            .setRange(0,0,dmat));
         JacobiSVD<MatrixXd> svd( mat, ComputeThinU | ComputeThinV);
             //linalg::SVD svd(mat); // TODO
             //if(m_Verbose) cout << "condition number of matrix A " <<
             //                  svd.q_cond_number() << endl;
             //if(m_Verbose) cout << svd.q_U().q_nrows() << " rows" << endl;
             DMatrix<T> U = dmutil::convert<T>(svd.matrixU());
             DMatrix<T> V = dmutil::convert<T>(svd.matrixV());
             VectorXf sig(svd.singularValues());
             DMatrix<T> S;
             S.resize(V.sizeY(),U.sizeX(),T(0));
             dword sxy = min(S.sizeX(),S.sizeY());
         std::vector< std::pair<T,dword> > sdiag(sxy);
             for(dword i=0; i<sxy; i++) {
                 S.at(i,i) = sig(i+1);
                 sdiag[i].first = sig(i+1);
                 sdiag[i].second = i;
             }
             mS = S; mU = U; mV = V;
             //sort by diagonal of S
             sort(sdiag.begin(), sdiag.end(), std::greater< std::pair<float,T> >());
             DMatrix<T> colu(1,U.sizeY());
             DMatrix<T> colv(1,V.sizeY());
             for(dword i=0; i<sxy; i++) {
                 dword permi = sdiag[i].second;
                 if(permi != i) {
                     U.getRange(permi,0,colu);
                     mU.setCol(i, colu);
                     V.getRange(permi,0,colv);
                     mV.setCol(i, colv);
                     mS.at(i,i) = S.at(permi,permi);
                 }
             }
         } catch(void*)
         {
             //if(!m_Verbose) freopen("/dev/stdout","a+",stderr);
             return false;
         }
         //if(!m_Verbose) freopen("/dev/stdout","a+",stderr);
         return true;
     }
template<class T > DMatrix<T>& dmutil::threshold (DMatrix< T > & mat, const T & th, const T & repl = T(0))
Definition at line 122 of file DMatrixUtil.h.
References DMatrix< T >::getData().
         {
             for(typename DMatrix<T>::iterator mi = mat.getData().begin();
                 mi != mat.getData().end(); mi++)
                 if(*mi<th) *mi = repl;
             return mat;
         }
template<class T > DMatrix<T> dmutil::var (const DMatrix< T > & mat)
Definition at line 96 of file DMatrixUtil.h.
References avg(), and sqr().
Referenced by stdev(), and VVector< float, 4 >::stdev().
         {
             DMatrix<T> e(avg(mat));
             DMatrix<T> x2(mat); sqr(x2);
             DMatrix<T> e2(avg(x2));
             return e2-=sqr(e);
         }
template<class T > DMatrix<T> dmutil::vertCat (const DMatrix< T > & um, const DMatrix< T > & lm)
Definition at line 48 of file DMatrixUtil.h.
References DMatrix< T >::setRange(), DMatrix< T >::sizeX(), and DMatrix< T >::sizeY().
         {
             assert(um.sizeX() == lm.sizeX());
             DMatrix<T> res(um.sizeX(), lm.sizeY() + um.sizeY());
             res.setRange(0,0, um);
             res.setRange(0,um.sizeY(), lm);
             return res;
         }