Structural deformable models: src/PropVec.h File Reference
PropVec.h File Reference
#include "VVector.h"
#include "Point.h"
Macros
#define _PROPTF_NORMALIZE_SCALE_
Typedefs
typedef VVector< float, 4 > PropVec
typedef PropVec PropTF
Enumerations
enum PropVecOffsets {
PVEC_POS =0, PVEC_POSX =0, PVEC_POSY, PVEC_SCALE,
PVEC_DIR
}
Functions
Point2D getPropPos (const PropVec &prop)
PropVec & setPropPos (PropVec &prop, const Point2D &p)
float getPropScale (const PropVec &prop)
PropVec & setPropScale (PropVec &prop, float pscale)
float getPropDir (const PropVec &prop)
PropVec & setPropDir (PropVec &prop, float dir)
Point2D getPropSDir (const PropVec &prop)
PropVec & setPropSDir (PropVec &prop, const Point2D &sdir)
PropTF getPropTF (const PropVec &from, const PropVec &to)
PropVec & fwdPropTF (PropVec &from, const PropTF &tf)
PropVec & invPropTF (PropVec &to, const PropTF &tf)
PropTF getIdentityPropTF ()
PropVec & scalePropVec (PropVec &prop, float scale)
Macro Definition Documentation
#define _PROPTF_NORMALIZE_SCALE_
Definition at line 6 of file PropVec.h.
Typedef Documentation
typedef PropVec PropTF
Definition at line 9 of file PropVec.h.
typedef VVector<float,4> PropVec
Definition at line 8 of file PropVec.h.
Enumeration Type Documentation
enum PropVecOffsets
Enumerator
PVEC_POS
PVEC_POSX
PVEC_POSY
PVEC_SCALE
PVEC_DIR
Definition at line 11 of file PropVec.h.
 {PVEC_POS=0,PVEC_POSX=0, PVEC_POSY, PVEC_SCALE, PVEC_DIR};
Function Documentation
PropVec& fwdPropTF (PropVec & from, const PropTF & tf) inline
Definition at line 51 of file PropVec.h.
References getPropDir(), getPropPos(), getPropScale(), setPropDir(), setPropPos(), and setPropScale().
Referenced by SubStructure::generateEMDist(), SubStructure::getLBUB(), and EMDXformer::getPropVec().
 {
 #ifdef _PROPTF_NORMALIZE_SCALE_
     setPropPos(from, getPropPos(from)+(getPropPos(tf).rotate(getPropDir(from))
                                        *getPropScale(from)));
 #else
     setPropPos(from, getPropPos(from)+getPropPos(tf).rotate(getPropDir(from)));
 #endif
     setPropDir(from, getPropDir(from)+getPropDir(tf));
     setPropScale(from, getPropScale(from)*getPropScale(tf));
 //     from[0] += tf[0]; from[1] += tf[1];
 //     from[2] *= tf[2]; from[3] += tf[3];
     return from;
 }
PropTF getIdentityPropTF () inline
Definition at line 81 of file PropVec.h.
References setPropScale().
Referenced by SubStructure::generateEMDist(), ExpectationMap::getPropVec(), and MStructure::showStats().
{
     PropVec ie(0.f); setPropScale(ie, 1); return ie;
 }
float getPropDir (const PropVec & prop) inline
Definition at line 25 of file PropVec.h.
References PVEC_DIR.
Referenced by Model::adaptProperties(), Searcher::buildClusters(), ExpectationMap::correctLBUB(), fwdPropTF(), Model::getDirection(), getPropSDir(), getPropTF(), ExpectationMap::getPropVec(), invPropTF(), EMDXformer::ratePropVec(), and ExpectationMap::ratePropVec().
 { return prop[PVEC_DIR]; }
Point2D getPropPos (const PropVec & prop) inline
Definition at line 13 of file PropVec.h.
References PVEC_POS.
Referenced by Model::adaptProperties(), MStructure::buildAllStats(), Searcher::buildClusters(), Model::convertPropFromMM(), Model::convertPropToMM(), fwdPropTF(), SubStructure::generateEMDist(), Model::getCenter(), SubStructure::getLBUB(), getPropTF(), invPropTF(), scalePropVec(), Searcher::setExpectationMap(), and MStructure::showStats().
 { return Point2D(&prop[PVEC_POS]); }
float getPropScale (const PropVec & prop) inline
Definition at line 19 of file PropVec.h.
References PVEC_SCALE.
Referenced by Model::adaptProperties(), MStructure::addExpectation(), Searcher::buildBins(), Searcher::buildClusters(), Model::convertPropFromMM(), Model::convertPropToMM(), ExpectationMap::correctLBUB(), fwdPropTF(), SubStructure::getLBUB(), getPropSDir(), getPropTF(), Model::getStdRadius(), invPropTF(), MStructure::rebuildExpMap(), scalePropVec(), and Brain::setupSearch().
 { return prop[PVEC_SCALE]; }
Point2D getPropSDir (const PropVec & prop) inline
Definition at line 31 of file PropVec.h.
References getPropDir(), getPropScale(), and Point2D::rotate().
Referenced by Model::distance().
 { return Point2D(getPropScale(prop),0).rotate(getPropDir(prop)); }
PropTF getPropTF (const PropVec & from, const PropVec & to) inline
Definition at line 37 of file PropVec.h.
References getPropDir(), getPropPos(), getPropScale(), setPropDir(), setPropPos(), and setPropScale().
Referenced by MStructure::buildAllStats(), EMDXformer::ratePropVec(), and MStructure::showStats().
 {
     PropTF tf;
 #ifdef _PROPTF_NORMALIZE_SCALE_
     setPropPos(tf,(getPropPos(to)-getPropPos(from)).rotate(-getPropDir(from))
                /getPropScale(from));
 #else
     setPropPos(tf,(getPropPos(to)-getPropPos(from)).rotate(-getPropDir(from)));
 #endif
     setPropScale(tf,getPropScale(to)/getPropScale(from));
     setPropDir(tf,getPropDir(to)-getPropDir(from));
     return tf;
 }
PropVec& invPropTF (PropVec & to, const PropTF & tf) inline
Definition at line 66 of file PropVec.h.
References getPropDir(), getPropPos(), getPropScale(), setPropDir(), setPropPos(), and setPropScale().
Referenced by SubStructure::generateEMDist().
 {
     setPropScale(to, getPropScale(to)/getPropScale(tf));
     setPropDir(to, getPropDir(to)-getPropDir(tf));
 #ifdef _PROPTF_NORMALIZE_SCALE_
     setPropPos(to, getPropPos(to)-(getPropPos(tf).rotate(getPropDir(to))
                                    *getPropScale(to)));
 #else
     setPropPos(to, getPropPos(to)-getPropPos(tf).rotate(getPropDir(to)));
 #endif
 //     to[0] -= tf[0]; to[1] -= tf[1];
 //     to[2] /= tf[2]; to[3] -= tf[3];
     return to;
 }
PropVec& scalePropVec (PropVec & prop, float scale) inline
Definition at line 85 of file PropVec.h.
References getPropPos(), getPropScale(), setPropPos(), and setPropScale().
Referenced by Dataset::getPropVecMM().
{
     setPropPos(prop, getPropPos(prop)*scale);
     setPropScale(prop, getPropScale(prop)*scale);
     return prop;
 }
PropVec& setPropDir (PropVec & prop, float dir) inline
Definition at line 28 of file PropVec.h.
References PVEC_DIR.
Referenced by ExpectationMap::correctLBUB(), fwdPropTF(), Model::getDirection(), SubStructure::getLBUB(), getPropTF(), ExpectationMap::getPropVec(), invPropTF(), main(), Searcher::mutate(), EMDXformer::ratePropVec(), ExpectationMap::ratePropVec(), MStructure::rebuildExpMap(), setPropSDir(), and Brain::setupSearch().
 { prop[PVEC_DIR] = dir; return prop; }
PropVec& setPropPos (PropVec & prop, const Point2D & p) inline
Definition at line 16 of file PropVec.h.
References PVEC_POSX, PVEC_POSY, Point2D::x, and Point2D::y.
Referenced by MStructure::addExpectation(), MStructure::buildAllStats(), Model::convertPropFromMM(), Model::convertPropToMM(), fwdPropTF(), SubStructure::generateEMDist(), Searcher::getBindex(), Model::getCenter(), SubStructure::getLBUB(), getPropTF(), invPropTF(), main(), Searcher::mutate(), MStructure::rebuildExpMap(), scalePropVec(), Brain::setupSearch(), and MStructure::showStats().
 {   prop[PVEC_POSX]=p.x; prop[PVEC_POSY]=p.y; return prop; }
PropVec& setPropScale (PropVec & prop, float pscale) inline
Definition at line 22 of file PropVec.h.
References PVEC_SCALE.
Referenced by MStructure::addExpectation(), Model::convertPropFromMM(), Model::convertPropToMM(), ExpectationMap::correctLBUB(), fwdPropTF(), getIdentityPropTF(), SubStructure::getLBUB(), getPropTF(), Dataset::getPropVec(), Model::getStdRadius(), invPropTF(), main(), MStructure::rebuildExpMap(), scalePropVec(), setPropSDir(), and Brain::setupSearch().
 { prop[PVEC_SCALE] = pscale; return prop; }
PropVec& setPropSDir (PropVec & prop, const Point2D & sdir) inline
Definition at line 34 of file PropVec.h.
References Point2D::angle(), Point2D::norm(), setPropDir(), and setPropScale().
 { return setPropScale(setPropDir(prop, sdir.angle()), sdir.norm()); }