Structural deformable models: src/Searcher.h File Reference
Searcher.h File Reference
#include <iostream>
#include <vector>
#include <list>
#include <map>
#include <functional>
#include <algorithm>
#include "ExpMap.h"
#include "Model.h"
Classes
class Searcher
class SearcherParams
Functions
SearcherParams & getSearchPara ()
Function Documentation
SearcherParams& getSearchPara () inline
Definition at line 194 of file Searcher.h.
References SearcherParams::global.
Referenced by MStructure::addExpectation(), SubStructure::analyseTF(), Searcher::buildBins(), Searcher::buildClusters(), Brain::doCommand(), Searcher::evolve(), Brain::evolve(), SubStructure::generateEMDist(), Searcher::getGeneration(), Brain::load(), Searcher::mutate(), Searcher::Searcher(), MStructure::showStats(), StructTable::stepSearch(), and Model::updateParticles().
 { return SearcherParams::global; }