Structural deformable models: src/Sensor.cpp File Reference
Sensor.cpp File Reference
#include <typeinfo>
#include <math.h>
#include "Sensor.h"
#include "SensorColl.h"
#include "airnan.h"
#include <string.h>
Functions
sensor_ptr getZeroSensor ()
Function Documentation
sensor_ptr getZeroSensor ()
Definition at line 234 of file Sensor.cpp.
Referenced by Sensor::changeSource(), Sensor::hprint(), Sensor::invalidateSource(), Sensor::print(), Model::readNode(), SensorCollection::readSensor(), Sensor::refSuperSensor(), SensorCollection::SensorCollection(), CombiSensor::setNSources(), CombiSensor::setSource(), Sensor::unrefSuperSensor(), and Sensor::~Sensor().
 {
     static sensor_ptr zeros = std::make_shared<ZeroSensor>();
     return zeros;
 }