Structural deformable models: src/Sensor.h File Reference
Sensor.h File Reference
#include <math.h>
#include <cmath>
#include <vector>
#include <set>
#include "common.h"
#include "Point.h"
#include "Image.h"
Classes
class Sensor
class ZeroSensor
class PPSensor
Macros
#define SENSOR_GAUSS_NORMALIZATION_RANGE 2
#define _USE_MINMAX_NORMALIZATION_
Functions
sensor_ptr getZeroSensor ()
template<typename SensorType , typename FirstArgType , typename... Args>
std::shared_ptr< SensorType > makeSensor (FirstArgType source, Args...args)
template<typename SensorType >
std::shared_ptr< SensorType > makeSensor ()
Macro Definition Documentation
#define _USE_MINMAX_NORMALIZATION_
#define SENSOR_GAUSS_NORMALIZATION_RANGE 2
Definition at line 13 of file Sensor.h.
Referenced by Sensor::getWeightedValue().
Function Documentation
sensor_ptr getZeroSensor ()
Definition at line 234 of file Sensor.cpp.
Referenced by Sensor::changeSource(), Sensor::hprint(), Sensor::invalidateSource(), Sensor::print(), Model::readNode(), SensorCollection::readSensor(), Sensor::refSuperSensor(), SensorCollection::SensorCollection(), CombiSensor::setNSources(), CombiSensor::setSource(), Sensor::unrefSuperSensor(), and Sensor::~Sensor().
 {
     static sensor_ptr zeros = std::make_shared<ZeroSensor>();
     return zeros;
 }
template<typename SensorType , typename FirstArgType , typename... Args> std::shared_ptr<SensorType> makeSensor (FirstArgType source, Args... args)
Definition at line 189 of file Sensor.h.
 {
     std::shared_ptr<SensorType> s = std::make_shared<SensorType>(args...);
     s->changeSource(source);
     return s;
 }
template<typename SensorType > std::shared_ptr<SensorType> makeSensor ()
Definition at line 197 of file Sensor.h.
 {
     return std::make_shared<SensorType>();
 }