Structural deformable models: src/SensorSet.cpp File Reference
SensorSet.cpp File Reference
#include <iostream>
#include <fstream>
#include <typeinfo>
#include "SensorSet.h"
#include "SensorColl.h"
#include "mathutil.h"
#include "Fourier.h"
#include "DMatrixUtil.h"
Functions
static Image< double > & create2DGaussian (Image< double > &flt, double stdev, float clampd, float cx, float cy)
Function Documentation
static Image< double > & create2DGaussian (Image< double > & flt, double stdev, float clampd, float cx, float cy) static
Definition at line 419 of file SensorSet.cpp.
References gaussd2(), Image< T >::getData(), Image< T >::getSizeX(), Image< T >::getSizeY(), dmutil::sum(), and TRACE.
Referenced by SmoothIntensitySensor::updateScale().
 {
     clampd = clampd*clampd;
     int i,j;
     double sum=0;
     double* pixel = flt.getData();
     int xsize=flt.getSizeX(), ysize=flt.getSizeY();
     TRACE("creating filter " << xsize << " " << ysize);
     for(j=0; j<ysize; j++)
         for(i=0; i<xsize; i++, pixel++) {
             float ii = (float)i-cx;
             float jj = (float)j-cy;
             float d2 = ii*ii+jj*jj;
             if(d2<clampd) {
                 double value = gaussd2(d2, stdev);
                 *pixel = value;
                 sum += value;
             }
         }
     flt *= (1.f/sum);
     return flt;
 }