Structural deformable models: src/SpeciesDB.cpp File Reference
SpeciesDB.cpp File Reference
#include <sstream>
#include "SpeciesDB.h"
#include "Errors.h"
Macros
#define _SP_DEFINE_
Functions
ParseFile & operator>> (ParseFile &is, SpeciesDB &sp)
ostream & operator<< (ostream &os, const SpeciesDB &sp)
ParseFile & operator>> (ParseFile &is, Species &sp)
ostream & operator<< (ostream &os, const Species &sp)
Macro Definition Documentation
#define _SP_DEFINE_
Definition at line 5 of file SpeciesDB.cpp.
Function Documentation
ostream& operator<< (std::ostream & os, const SpeciesDB & sp)
Definition at line 118 of file SpeciesDB.cpp.
 {
     for(map<dword,Species>::const_iterator s=sp.begin(); s!=sp.end(); s++)
         os << s->second << endl;
     return os;
 }
ostream& operator<< (std::ostream & os, const Species & sp)
Definition at line 149 of file SpeciesDB.cpp.
References Species::getFlagString(), Species::m_Flags, NULL, and Species::SFIELDS.
 {
     int entry=0;
     while(Species::SFIELDS[entry] != NULL) {
         const string fields(Species::SFIELDS[entry]);
         map<string,string>::const_iterator s=sp.find(fields);
         if(sp.m_Flags && fields == "flags")
             os << fields << " " << sp.getFlagString() << endl;
         else if(s != sp.end()) os << s->first << " " << s->second << endl;
         entry++;
     }
     return os;
 }
ParseFile& operator>> (ParseFile & is, SpeciesDB & sp)
Definition at line 108 of file SpeciesDB.cpp.
Referenced by SpeciesDB::load().
 {
     Species s;
     while(is) {
         is >> s;
         if(s.id) sp[s.id] = s;
     }
     return is;
 }
ParseFile& operator>> (ParseFile & is, Species & sp)
Definition at line 128 of file SpeciesDB.cpp.
References ParseFile::getKey(), ParseFile::getNextLine(), ParseFile::getValue(), Species::id, Species::m_Flags, ParseFile::pushLine(), and Species::readFlagString().
 {
     sp.clear();
     sp.id = 0;
     sp.m_Flags = 0;
     while(is.getNextLine()) {
         const string& token = is.getKey();
         const string& value = is.getValue();
         //cout << "token: " << token << " value: " << value << endl;
         if(token == "species_id") {
             if(sp.id != 0) { is.pushLine(); return is; }
             istringstream(value) >> sp.id;
         } else if(sp.id == 0) {
             throw new IOException("record didn't start with 'species_id'");
         } else if(token == "flags")
             sp.readFlagString(value);
         sp[token] = value;
     }
     return is;
 }