Structural deformable models: src/utils.cpp File Reference
utils.cpp File Reference
#include <stdlib.h>
#include <fstream>
#include <string>
#include "utils.h"
Functions
const string & __set_fnmatchpattern (const string &pattern)
int __fixed_fnmatch (const struct dirent *dent)
const char * getTemp ()
string & replaceAll (string &txt, char src, char tar)
int matlabCall (const std::string &cmd)
Variables
static string matlabprog = "matlab -nojvw -nosplash -nodesktop -r "
static string matpath = "./"
static string __fnmatchpattern
Function Documentation
int __fixed_fnmatch (const struct dirent * dent)
Definition at line 21 of file utils.cpp.
References __fnmatchpattern.
Referenced by __set_fnmatchpattern(), and fromString().
 { return 0; }
const string& __set_fnmatchpattern (const string & pattern)
Definition at line 15 of file utils.cpp.
References __fixed_fnmatch(), and __fnmatchpattern.
Referenced by FFind::find(), and fromString().
 { return __fnmatchpattern = pattern; }
const char* getTemp ()
Definition at line 25 of file utils.cpp.
Referenced by fromString().
 {
     const char* tc = getenv("TEMP");
     if(!tc) tc = getenv("TMP");
     return tc;
 }
int matlabCall (const std::string & cmd)
Definition at line 41 of file utils.cpp.
References matlabprog.
Referenced by fromString().
 {
     return system((matlabprog+"\""+cmd+", exit\"").c_str());
 }
string& replaceAll (string & txt, char src, char tar)
Definition at line 32 of file utils.cpp.
Referenced by fromString().
 {
     int pos = 0;
     while((pos = txt.find(src,pos)) != (int)txt.npos) {
         txt[pos++] = tar;
     }
     return txt;
 }
Variable Documentation
string __fnmatchpattern static
Definition at line 14 of file utils.cpp.
Referenced by __set_fnmatchpattern().
string matlabprog = "matlab -nojvw -nosplash -nodesktop -r " static
Definition at line 11 of file utils.cpp.
Referenced by matlabCall().
string matpath = "./" static
Definition at line 12 of file utils.cpp.