Structural deformable models: src/utils.h File Reference
utils.h File Reference
#include <iostream>
#include <sstream>
#include <string>
#include <ctype.h>
#include <assert.h>
#include <sys/time.h>
#include "common.h"
Macros
#define MAKE_STRING(msg) (((std::ostringstream&)(std::ostringstream() << msg)).str())
#define MAKE_CSTRING(msg) (((std::ostringstream&)(std::ostringstream() << msg)).str().c_str())
#define COMMENT_CHAR '#'
Functions
std::istream & comment (std::istream &s)
unsigned long getMilliSeconds ()
template<class T >
std::string toString (T v)
template<class T >
T & fromString (const std::string &str, T &v)
std::string & replaceAll (std::string &txt, char src, char tar)
int matlabCall (const std::string &cmd)
const char * getTemp ()
const std::string & __set_fnmatchpattern (const std::string &pattern)
int __fixed_fnmatch (const struct dirent *dent)
template<class T >
int findFiles (const std::string &fmask, T iter)
Macro Definition Documentation
#define COMMENT_CHAR '#'
Definition at line 23 of file utils.h.
Referenced by comment().
#define MAKE_CSTRING (msg) (((std::ostringstream&)(std::ostringstream() << msg)).str().c_str())
Definition at line 20 of file utils.h.
#define MAKE_STRING (msg) (((std::ostringstream&)(std::ostringstream() << msg)).str())
Definition at line 18 of file utils.h.
Function Documentation
int __fixed_fnmatch (const struct dirent * dent)
Definition at line 12 of file ffind.cpp.
References __fnmatchpattern.
Referenced by __set_fnmatchpattern(), FFind::find(), FFind::findFiles(), and fromString().
{
     return !fnmatch(__fnmatchpattern, dent->d_name,0);
 }
const std::string& __set_fnmatchpattern (const std::string & pattern)
Definition at line 15 of file utils.cpp.
References __fixed_fnmatch(), and __fnmatchpattern.
Referenced by FFind::find(), and fromString().
 { return __fnmatchpattern = pattern; }
std::istream& comment (std::istream & s) inline
Definition at line 25 of file utils.h.
References COMMENT_CHAR.
 {
     char c;
     while (s.get(c)) {
         if (!isspace(c)) {
             if (c == COMMENT_CHAR) {
                 while (s.get(c) && c != '\n');
             } else {
                 s.putback(c);
                 break;
             }
         }
     }
     return s;
 }
template<class T > int findFiles (const std::string & fmask, T iter)
Definition at line 88 of file utils.h.
Referenced by fromString().
{
     struct _finddata_t ff;
     int ffhandle;
     int ffcount=0;
     if((ffhandle = _findfirst(fmask.c_str(), &ff)) != -1) {
         do {
             *iter++ = ff.name;
             ffcount++;
         } while(_findnext(ffhandle, &ff) == 0);
     }
     return ffcount;
 }
template<class T > T& fromString (const std::string & str, T & v)
Definition at line 67 of file utils.h.
References __fixed_fnmatch(), __set_fnmatchpattern(), findFiles(), getTemp(), matlabCall(), and replaceAll().
Referenced by Brain::doCommand(), MStructure::getRefModelIDs(), MStructure::loadRefProp(), SubStructure::read(), MStructure::read(), and SearcherParams::read().
{
     std::istringstream ss(str);
     ss >> v;
     return v;
 }
unsigned long getMilliSeconds () inline
Definition at line 41 of file utils.h.
Referenced by Brain::run().
{
 #ifdef WIN32
 //     typedef unsigned long LONGLONG;
 //     typedef long LARGE_INTEGER;
     static LONGLONG frequency=0;
     if(!frequency)
         QueryPerformanceFrequency((LARGE_INTEGER*)&frequency);
     LONGLONG counter;
     QueryPerformanceCounter((LARGE_INTEGER*)&counter);
     return (unsigned long) (counter*1000 / frequency);
 #else
     static struct timeval time;
     gettimeofday(&time, 0);
     return (unsigned long)time.tv_sec*1000 + (unsigned long)time.tv_usec/1000;
 #endif
 }
const char* getTemp ()
Definition at line 25 of file utils.cpp.
Referenced by fromString().
 {
     const char* tc = getenv("TEMP");
     if(!tc) tc = getenv("TMP");
     return tc;
 }
int matlabCall (const std::string & cmd)
Definition at line 7 of file matlab.cpp.
References matlabprog.
Referenced by fromString().
 {
     return system((matlabprog+cmd+", exit").c_str());
 }
std::string& replaceAll (std::string & txt, char src, char tar)
Definition at line 32 of file utils.cpp.
Referenced by fromString().
 {
     int pos = 0;
     while((pos = txt.find(src,pos)) != (int)txt.npos) {
         txt[pos++] = tar;
     }
     return txt;
 }
template<class T > std::string toString (T v)
Definition at line 60 of file utils.h.
Referenced by MStructure::buildAllStats(), Brain::doCommand(), MStructure::getRefModel(), MStructure::setRefModel(), MStructure::showStats(), and Brain::triggerTest().
{
     std::stringstream ss;
     ss << v;
     return ss.str();
 }