Structural deformable models: src/vuThread.cpp File Reference
vuThread.cpp File Reference
#include "vuThread.h"
#include <stdlib.h>
#include <iostream>
#include <errno.h>
#include <string.h>
#include <fstream>
#include <sys/time.h>
#include <pthread.h>
#include <unistd.h>
Functions
vuMutex & getLogMut ()
void * _kickoff (void *ptr)
Variables
vuMutex logmut
Function Documentation
void* _kickoff (void * ptr)
Definition at line 20 of file vuThread.cpp.
References NULL, vuThread::run(), vuThread::stopThread(), and vuMutex::unlock().
Referenced by vuThread::startThread(), vuMutex::unlock(), and vuThread::~vuThread().
 {
     vuThread *th = (vuThread*)ptr;
     int   whatsup = th->m_Whatsup;
     void* data    = th->m_AdditionalData;
     th->m_WhatsupMutex.unlock();
     th->run(whatsup, data);
     th->stopThread();
     return NULL;
 }
vuMutex& getLogMut ()
Definition at line 12 of file vuThread.cpp.
References logmut.
 {return logmut;}
Variable Documentation
vuMutex logmut
Definition at line 10 of file vuThread.cpp.
Referenced by getLogMut().